### ISSUE TITLE
Fingerprinting 2.0: WebGL2

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9189]
This is a sub-issue of the larger fingerprint defense reorganization issue: #8787

Previous implementation blocked all WebGL-specific parameters, at max level only, and did nothing at default level.

New implementation:

At max level, block these WebGL2-specific parameters:
- version
- shading language version
- read buffer binding
- write buffer binding
- framebuffer binding
- max vertex uniform components
- max vertex uniform blocks
- max vertex output components
- max varying components
- max transform feedback interleaved components
- max fragment uniform components
- max fragment uniform blocks
- max fragment input components
- max uniform buffer bindings
- max combined uniform blocks
- max combined vertex uniform components
- max combined fragment uniform components

At default level, farble these WebGL2-specific parameters:
- max vertex uniform components
- max vertex uniform blocks
- max vertex output components
- max varying components
- max transform feedback interleaved components
- max fragment uniform components
- max fragment uniform blocks
- max fragment input components
- max uniform buffer bindings
- max combined uniform blocks
- max combined vertex uniform components
- max combined fragment uniform components

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave could one of you confirm the test plan? I don't see anything for `WebGL2` on https://dev-pages.bravesoftware.com/farbling.html / https://dev-pages.brave.software/farbling.html. Is there something different we should do to check this one?

**Comment by pes10k** [comment]
Test plan is to review the "WebGL2 Params" row on https://dev-pages.brave.software/farbling.html and make sure they match on the same page, but differ across pages CC @pilgrim-brave 

@LaurenWags if that looks good to you, i think we're good to go!

**Comment by LaurenWags** [comment]
@pes10k thanks for getting that added! I do have a question about your setup on the test pages, looks like you've got 1.18 listed but this issue in 1.17.x:

<img width="520" alt="Screen Shot 2020-11-05 at 7 38 20 AM" src="https://user-images.githubusercontent.com/28145373/98242176-0a853b80-1f3a-11eb-8e65-3107689b3065.png">

Can this issue be tested with 1.17.x or should I log a placeholder for it to be tested with 1.18.x?

**Comment by pes10k** [comment]
ah good point @LaurenWags , i tagged it as current nightly, not as the release when the code landed… d'oh.  Fixed!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.17.62 Chromium: 86.0.4240.185 (Official Build) dev (x86_64)
-- | --
Revision | 37e6f852ed18086458552039ad26421aa9fc7acc-refs/branch-heads/4240@{#1377}
OS | macOS Version 10.14.6 (Build 18G6032)
```

Verified test plan from https://github.com/brave/brave-browser/issues/9189#issuecomment-721987277. Note, confirmed with @pes10k that when FP=strict, `WebGL2` values "should be the same over all domains, since we’re just blocking each request in strict mode (so the same value is just the “blocked” value)".  As you will see in screenshots below, the "strict" value differs from "shields down" and "standard" values as expected.

<details>
<summary>Shields Down</summary>

<img width="1202" alt="shields down" src="https://user-images.githubusercontent.com/28145373/98402553-7c8e7b00-2035-11eb-9703-e3815301c66b.png">

</details>

<details>
<summary>Fingerprinting = standard</summary>

<img width="1192" alt="FP=std" src="https://user-images.githubusercontent.com/28145373/98402557-7e583e80-2035-11eb-9829-9caa57289e45.png">

</details>

<details>
<summary>Fingerprinting = strict</summary>

<img width="1196" alt="FP=strict" src="https://user-images.githubusercontent.com/28145373/98402559-80220200-2035-11eb-93e8-ee8ff7c54192.png">

</details>

------------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.17.66 x64 build
- Verified test plan from https://github.com/brave/brave-browser/issues/9189#issuecomment-721987277
<details>
<summary>Shields Down</summary>

dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98936649-2447f500-24dd-11eb-8b1b-6bb0d0673266.png) | ![image](https://user-images.githubusercontent.com/17010094/98936634-1f834100-24dd-11eb-8c12-9b74aba48d04.png)

</details>
<details>
<summary>Fingerprinting Blocked(Standard)</summary>

https://dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98936665-2ad66c80-24dd-11eb-9719-fbdbd1814e70.png) | ![image](https://user-images.githubusercontent.com/17010094/98936677-2f9b2080-24dd-11eb-8942-b25087687500.png)

</details>
<details>
<summary>Fingerprinting Blocked(Strict)</summary>

https://dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98936707-39bd1f00-24dd-11eb-83a3-213e102b5c2d.png) | ![image](https://user-images.githubusercontent.com/17010094/98936695-34f86b00-24dd-11eb-9397-3ea8d1644607.png)

</details>

------------

Verification passed on Samsung Tab A with Android 10 running 1.17.66 x64 beta build
<details>
<summary>Shields Down</summary>

https://dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98936937-9d474c80-24dd-11eb-8fdf-3b4139944f3d.png) | ![image](https://user-images.githubusercontent.com/17010094/98936815-6a04bd80-24dd-11eb-9dd1-57fe4b9b7f05.png)

</details>
<details>
<summary>Fingerprinting Blocked(Standard)</summary>

https://dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98936975-a9cba500-24dd-11eb-8841-cc19540ffe9e.png) | ![image](https://user-images.githubusercontent.com/17010094/98936850-7ab53380-24dd-11eb-82bd-592276fcd9cb.png)

</details>
<details>
<summary>Fingerprinting Blocked(Strict)</summary>

https://dev-page.bravesoftware.com/farbling.html | https://dev-pages.brave.software/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/98937031-be0fa200-24dd-11eb-98e8-1265b28729cc.png) | ![image](https://user-images.githubusercontent.com/17010094/98936902-8dc80380-24dd-11eb-929a-33550ee9f647.png)

</details>
