### ISSUE TITLE
Add tipping (likes)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#919]
Add tipping feature for rewards

When working on this one, please revert this PR https://github.com/brave/brave-core/pull/799

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/1221

**Comment by mandar-brave** [comment]
@NejcZdovc this is critical functionality so tagging it as P2. However, merge when ready only.

**Comment by NejcZdovc** [comment]
closing as this was implemented with twitter tips
