### ISSUE TITLE
Feature Request: Disable certain ads

### ISSUE THREAD

**Issue by SephReed** [brave/brave-browser#9191]
Twice I've gotten an ad for Walmart.  As a result, I've disabled brave rewards.  If it was possible to disable ads from Walmart, I would choose that instead.

I'm probably the only one.

**Comment by rebron** [comment]
Hi @SephReed. 

If you go to brave://rewards/ and select 7-days ad history 
<img width="614" alt="Screen Shot 2020-04-17 at 9 14 47 PM" src="https://user-images.githubusercontent.com/5951041/79627828-8c259100-80f0-11ea-9ff0-a2777257ea40.png">

Should be able to thumbs down the Walmart ad and it shouldn't show up again.
<img width="876" alt="Screen Shot 2020-04-17 at 9 14 29 PM" src="https://user-images.githubusercontent.com/5951041/79627847-b0816d80-80f0-11ea-9691-c45ed9aa9c89.png">

**Comment by SephReed** [comment]
Amazing!  Great job you guys.  Might be worth giving that UI a bit more discoverability, you could collect some pretty good feedback.
