### ISSUE TITLE
[Desktop] Mega.nz buttons on prompts not displayed in Brave Beta/Dev/Nightly with Shield enabled

### ISSUE THREAD

**Issue by bafforosso** [brave/brave-browser#9192]
## Description 
When using mega.nz in Brave Beta, Dev and Nightly with Brave Shield enabled "No" and "Yes" buttons are not displayed at least on the "Move to Rubbish Bin" prompt. Disabling Brave Shield solves the issue, they are also perfectly visible and usable in Brave current channel with Shield enabled, or in Chrome and Firefox.
There is no indication on the Brave Shield panel that it blocked anything. Neither disabling any toggle in Shield advanced panel or allowing cookies or fingerprints, nor any combination of all that appears to solve the issue, only fully disabling Shield does.

## Steps to Reproduce

   1. In mega.nz, right-click any file in your storage and choose either "Remove" or "Move > Rubbish Bin"
   2. When the confirmation prompt appears you cannot accept it (or cancel it the "No" button way) because buttons are simply not there

## Actual result:
In Brave Beta, Dev and Nightly with Brave Shield enabled :
![Brave Meganz bin confirmation](https://user-images.githubusercontent.com/45972132/79172234-69dffa80-7df4-11ea-9f4f-1b66faaa8c35.JPG)

## Expected result:
In Chrome, Firefox and Brave current channel or any with Shield disabled:
![Chrome-Firefox Meganz bin confirmation](https://user-images.githubusercontent.com/45972132/79172248-77958000-7df4-11ea-9528-1cc6d4442cbb.JPG)

## Reproduces how often: 
Constant with Brave Shield enabled on Beta, Dev and Nightly in Windows 10 and OSX

## Brave version (brave://version info)
**Brave Beta - Windows 10 :**
Brave | 1.8.70 Chromium: 81.0.4044.83 (Official Build) beta (64-bit)
-- | --
Revision | 5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS | Windows 10 OS Version 1903 (Build 18362.720)
JavaScript | V8 8.1.307.25
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.83 Safari/537.36

**Brave Beta - OSX 10.14.6:**
Brave	1.8.70 Chromium: 81.0.4044.83 (Official Build) beta (64-bit)
Revision	5718ca617723806b9aacfb41108a0d911d1bde74-refs/branch-heads/4044@{#853}
OS	macOS Version 10.14.6 (Build 18G3020)
JavaScript	V8 8.1.307.25
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.83 Safari/537.36

**Brave Dev - Windows 10 :**
Brave | 1.8.73 Chromium: 81.0.4044.92 (Official Build) dev (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1903 (Build 18362.720)
JavaScript | V8 8.1.307.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

**Brave Nightly - Windows 10 :**
Brave | 1.9.15 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1903 (Build 18362.720)
JavaScript | V8 8.1.307.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release?
No, it works in current release, at least on Windows 10
- Can you reproduce this issue with the beta channel?
Yes, constantly on the Beta channel on Windows 10 and OSX
- Can you reproduce this issue with the dev channel?
Yes, constantly on the Dev channel on Windows 10
- Can you reproduce this issue with the nightly channel?
Yes, constantly on the Nightly channel on Windows 10

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes, turning off Brave Shield resolves the issue. Only fully disabling Shield does though, not any granular settings.
- Does the issue resolve itself when disabling Brave Rewards?
No, it doesn't
- Is the issue reproducible on the latest version of Chrome? 
No, it works on the latest version of Chrome (Version 81.0.4044.92 (Official Build) (64-bit))

## Miscellaneous Information:

**Comment by lyrad87** [comment]
Is there an update on this issue? It still occurs with


Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
OS | macOS Catalina 10.15.4
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

It does not occur with the latest version of Safari (v13.1 (15609.1.20.111.8)).

**Comment by rebron** [comment]
cc: @ryanbr Can you take a look?

**Comment by ryanbr** [comment]
@lyrad87 @bafforosso should be resolved, if you can confirm?
