### ISSUE TITLE
Fingerprinting 2.0: UX / Shields Integration

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9194]
This is a sub-issue of the larger font defense reorganization #8787

## Designs

**Shields panel**
New fingerprinting dropdown menu should show:

![Group 7](https://user-images.githubusercontent.com/2388823/80769914-8c1b8d00-8b03-11ea-97e4-cc8f30607bde.jpg)

Panel shows:
![farbling](https://user-images.githubusercontent.com/2388823/82255650-e2613c00-9909-11ea-890f-b6c5c7c1a8b7.png)

**brave://settings**
![shields settings4](https://user-images.githubusercontent.com/2388823/83061988-be40e180-a012-11ea-9f41-cfc2461c8b4c.png)

- Fingerprinting blocked (label: `Strict, may break sites`): The strongest set of protections, that disables or otherwise modifies page functionality to prevent sites from accessing or learning the underlying data needed for fingerprinting attacks. Carries larger, non-trivial web-compat risks.
- Fingerprinting blocked (default setting and label: `Standard`): A useful set of protections that may not fundamentally prevent fingerprinting attacks, but re practical against real world fingerprinting attacks. Carries a small but non-zero chance of breaking sites.
- Allow all fingerprinting (label: `Disabled`): Don’t apply any fingerprinting protections

**Comment by karenkliu** [comment]
brave://settings designs added.

**Comment by rebron** [comment]
Related backend controls: https://github.com/brave/brave-core/pull/5220

**Comment by simonhong** [comment]
@rebron @pes10k This UX should be only applied when fingerprint v2 feature is enabled? Or using from now on?

**Comment by pes10k** [comment]
@simonhong At this point in nightly, I think we're well past the half way mark migrating from v1 to v2 fingerprinting defenses, and both are enabled, so I think enabling / surfacing as soon as possible in nightly would be ideal

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
-- | --
Revision | e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified design from description and https://github.com/brave/brave-core/pull/5684 as they apply to Fingerprinting. Note, there was additional testing done with https://github.com/brave/brave-browser/issues/9975
* Logged #10670 and #10671 as follow ups

<img width="719" alt="Screen Shot 2020-07-09 at 8 52 27 AM" src="https://user-images.githubusercontent.com/28145373/87042373-9754fe00-c1c1-11ea-81ad-f449d4378e3e.png">
<img width="403" alt="Screen Shot 2020-07-09 at 8 52 48 AM" src="https://user-images.githubusercontent.com/28145373/87042380-98862b00-c1c1-11ea-8ff0-9b5301f16555.png">
<img width="720" alt="Screen Shot 2020-07-09 at 8 53 35 AM" src="https://user-images.githubusercontent.com/28145373/87042481-b81d5380-c1c1-11ea-8d94-eb3ec9df67d3.png">
<img width="396" alt="Screen Shot 2020-07-09 at 8 53 47 AM" src="https://user-images.githubusercontent.com/28145373/87042485-b94e8080-c1c1-11ea-8610-e9edd6e930bd.png">
