### ISSUE TITLE
Update keyword lists for purchase intent trial Japan

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#9195]
Update keyword lists for purchase intent trial Japan. See keywords and sites here https://docs.google.com/spreadsheets/d/1GiIV1qa7XTiyJgQ6Syz0nSFSIgfdNIanulOaNM6jCSQ/edit#gid=0

TBD: work out if ad region targeting settings are enough to constrain trial to Japan region or if additional locale based settings have to be introduced.

**Comment by tmancey** [comment]
Discussed with @moritzhaller and this issue is superseded by https://github.com/brave/brave-browser/issues/8396
