### ISSUE TITLE
"Bat Ads Service" should only be running if Brave Ads is enabled

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9196]
![image](https://user-images.githubusercontent.com/1188719/68126807-822a2000-ff0c-11e9-876f-d7c7fb0a695d.png)

We should only start ads process when ads are enabled

**Comment by rebron** [comment]
@jsecretan should this have higher priority?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5824

Clean profile - Rewards never enabled, confirmed `BAT Ads Service` is not running:
<img width="1194" alt="9196 - clean profile" src="https://user-images.githubusercontent.com/28145373/89038272-0b407d00-d30e-11ea-964b-13605e15d87a.png">

Rewards enabled, ads enabled, confirmed `BAT Ads Service` is running:
<img width="1195" alt="9196 - Rewards enabled, ads enabled" src="https://user-images.githubusercontent.com/28145373/89038279-0ed40400-d30e-11ea-9b81-7ae2d12a84c6.png">

Rewards enabled, ads disabled, confirmed `BAT Ads Service` is not running:
<img width="1192" alt="9196 - Rewards enabled, ads disabled" src="https://user-images.githubusercontent.com/28145373/89038284-11365e00-d30e-11ea-8d58-6b8cb13d1740.png">

Rewards enabled, then disabled, confirmed `BAT Ads Service` is not running:
<img width="1195" alt="9196 - Rewards enabled then disabled" src="https://user-images.githubusercontent.com/28145373/89038289-14314e80-d30e-11ea-925f-7c411c39dc53.png">

------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.109 x64 build
- Verified no ads are shown when ads is turned off
- Verified no ads are shown when rewards is turned off
