### ISSUE TITLE
[Android] Allow top sites to be disabled on Android like it can be on the desktop

### ISSUE THREAD

**Issue by dunk** [brave/brave-browser#9197]
## Description

On Android you can't disable the top sites feature - no matter what you do it is shoved in your face every time you open a new tab. It would be excellent if, like with the desktop version (see #4510), this feature could be disabled.

## Steps to reproduce

   1. Open a new tab
   2. There it is

## Actual result
A bunch of irritating websites that you might not want there all the time.

## Expected result
A blank page, or a page that you have chosen other things for like a background image, but definitely not the top sites.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/hide-frequent-startup-sites/129485?u=eljuno

**Comment by anthonypkeane** [comment]
Disabling the Bookmark widget would solve this one for you. Thanks
