### ISSUE TITLE
Add rewards panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#920]
Add rewards panel that is opened when you click on BAT logo in url bar

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified the welcome note is shown on rewards panel when rewards isn't enabled
* Verified wallet info is shown on rewards panel when rewards is enabled 
* Verified the publisher name is shown on the rewards panel when on a site
* Verified no publisher name is shown on the rewards panel when on a media site like YouTube
