### ISSUE TITLE
State level ads delivery

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9200]
## Description 
Some advertisers need to run their campaigns in specific states/provinces, either because what they are advertising is of regional interest, or because they are not allowed to sell items in specific states.  After some extensive privacy analysis, we have determined we can run campaigns at state level in the United States, for most states (excluding Wyoming and territories for now) while keeping a very high anonymity set (k=1000).

### Determining Location
Upon sign up for Brave Ads, and on exponentially random 24 hour time periods thereafter, the browser should call out to https://ads-serve.brave.com/v5/getstate and store the state and country code provided in its local store, example

`
{
	“country_code”: “US”,
	“state_province_code”: “FL”
}
`

Values will only be returned for either if it is in the given list provided in the above section.  Otherwise, the value will be an empty string “”.

### Ad Catalog Changes
The browser will read the new version of the catalog at /v5/catalog.  This new version of the catalog will allow additional state levels in certain cases.  If multiple targets are listed, the catalog will be eligible for any of the given geo-targets.  Campaigns with specific geo-targeting defined will only be eligible to serve if the client has successfully defined a value for state and it matches.

`"geoTargets": [
        {
          "code": "US-FL",
          "name": "United States-Florida"
        }

  ]
`

### New Settings
For browsers in the US, Brave Ads settings should have the ability to choose state, including the full list of 50 states.  There should also be a setting for “Do not use state to determine ads”, which would result in no state level campaigns.  Once a state is specifically set, it should not be updated by state endpoint.

**Comment by cwmke** [comment]
Would it be possible to set at the city or county level as well? I occasionally get some ads for Chicago Cubs gear despite living in a different city. This is most likely caused by my use of a VPN.

**Comment by jsecretan** [comment]
Not just yet @cwmke, we did a privacy analysis and right now, state is all we are comfortable with to keep large anonymity sets.  But hopefully in the not too distant future as Brave grows.

**Comment by LaurenWags** [comment]
Verified passed using

```
Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5602
* Confirmed if locale is not US (ex. Canada), I see the below in logs:
```
[13069:775:0805/104020.477595:VERBOSE1:subdivision_targeting.cc(73)] Ads subdivision targeting is not supported for en-CA locale
```
* Confirmed in UI that state selection is not possible if locale is not US
<img width="1194" alt="Screen Shot 2020-08-05 at 10 43 05 AM" src="https://user-images.githubusercontent.com/28145373/89426744-78865080-d708-11ea-9fe2-e12a799b4700.png">

* Confirmed when locale is US, I see below in the logs:
```
[13142:775:0805/104354.180029:VERBOSE1:subdivision_targeting.cc(94)] Automatically detecting ads subdivision
[13142:775:0805/104354.180093:VERBOSE1:subdivision_targeting.cc(144)] Fetch ads subdivision
[13142:775:0805/104354.180176:VERBOSE2:subdivision_targeting.cc(145)] GET /v5/getstate
[13142:775:0805/104354.180351:VERBOSE5:subdivision_targeting.cc(150)] URL Request:
  URL: https://ads-serve.bravesoftware.com/v5/getstate
  Method: GET
```
```
[13142:775:0805/104354.593619:VERBOSE6:subdivision_targeting.cc(160)] URL Response:
  URL: https://ads-serve.bravesoftware.com/v5/getstate
  Response Status Code: 200
```

* Confirmed able to select state manually or opt out in UI. Note, logged issue for drop list https://github.com/brave/brave-browser/issues/11095

* Confirmed subdivision fetch is scheduled (non-debug mode):
```
[13142:775:0805/104354.595259:VERBOSE1:subdivision_targeting.cc(247)] Fetch ads subdivision in 13 hours, 30 minutes, 53 seconds at 12:14 AM
```

* Confirmed subdivision fetch is scheduled (debug mode):
```
[13394:775:0805/111434.358035:VERBOSE1:subdivision_targeting.cc(247)] Fetch ads subdivision in 0 hours, 2 minutes, 20 seconds at 11:16 AM
```

* Confirmed if I select `Disable` in the drop down, logs reflect this. Confirmed this selection is retained on restart and not updated automatically.
```
[13142:775:0805/110556.374165:VERBOSE1:subdivision_targeting.cc(80)] Ads subdivision targeting is disabled
```

* Confirmed if I manually select a state in the drop down, logs reflect this. Confirmed this selection is retained on restart and not updated automatically.
```
[13142:775:0805/110647.258933:VERBOSE1:subdivision_targeting.cc(89)] Ads subdivision targeting is enabled for US-AR
```

* Confirmed subdivision fetch retry. Initial attempt:
```
[13436:775:0805/113201.081991:VERBOSE1:subdivision_targeting.cc(176)] Failed to fetch ads subdivision
[13436:775:0805/113201.082480:VERBOSE1:subdivision_targeting.cc(237)] Retry fetching ads subdivision in 0 hours, 0 minutes, 42 seconds at 11:32 AM
```

Second attempt:
```
[13436:775:0805/113243.113186:VERBOSE1:subdivision_targeting.cc(176)] Failed to fetch ads subdivision
[13436:775:0805/113243.113501:VERBOSE1:subdivision_targeting.cc(237)] Retry fetching ads subdivision in 0 hours, 2 minutes, 21 seconds at 11:35 AM
```

Third attempt:
```
[13436:775:0805/113504.144310:VERBOSE1:subdivision_targeting.cc(176)] Failed to fetch ads subdivision
[13436:775:0805/113504.144522:VERBOSE1:subdivision_targeting.cc(237)] Retry fetching ads subdivision in 0 hours, 8 minutes, 48 seconds at 11:43 AM
```

* Confirmed subdivision targeting is auto-detected by default on a fresh install
* Confirmed subdivision targeting is auto-detected by default on upgrade (when ads enabled) from 1.11.x as well.
* Confirmed subdivision targeting messages do not appear in the logs if ads were disabled on 1.11.x prior to upgrade. Confirmed enabling Ads does fetch subdivision after upgrade.

* Additional test plan provided by @jsecretan was confirmed. See me for details.

-----------------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build

- Verified test plan from https://github.com/brave/brave-core/pull/5602
- Verified for non-US locale logs shows not supported message
![image](https://user-images.githubusercontent.com/17010094/90109066-23b78b00-dd43-11ea-9072-2d7116e5f828.png)

- Verified for non-US locale there is no dropdown list for states
  <img width="300" src=https://user-images.githubusercontent.com/17010094/90109186-5c576480-dd43-11ea-83cf-e3e7d84a46cd.png>

- Verified when locale is set to US the following logs are shown
![image](https://user-images.githubusercontent.com/17010094/90109442-beb06500-dd43-11ea-8af3-186b39c259f2.png)
![image](https://user-images.githubusercontent.com/17010094/90109521-da1b7000-dd43-11ea-9c20-e1ede5e9fe86.png)


- Verified able to manually select state via UI from the dropdown list.
  <img width="300" src=https://user-images.githubusercontent.com/17010094/90109851-4a29f600-dd44-11ea-927e-49fdda814dea.png>

- Verified scheduled subdivision fetch is caputed in logs (non-debug mode):
![image](https://user-images.githubusercontent.com/17010094/90110008-81000c00-dd44-11ea-9cbc-9653ae48c6d0.png)

- Scheduled subdivision fetch in debug mode: **Not verified**

- Verified when state selection is set to  `Disable` logs reflect this. Verified restarting browser doesn't reset it to automatic automatically.
![image](https://user-images.githubusercontent.com/17010094/90110426-1c917c80-dd45-11ea-8703-7846209a73a5.png)

- Verified selecting a state manually from UI logs capture it correctly. Verified restarting browser doesn't reset it to automatic
![image](https://user-images.githubusercontent.com/17010094/90110543-4f3b7500-dd45-11ea-8de6-ea48bff4a788.png)

- Verified subdivision fetch retry is logged: 
  - First attempt
![image](https://user-images.githubusercontent.com/17010094/90110683-83af3100-dd45-11ea-875b-121764bf39c6.png)

   - Second attempt:
![image](https://user-images.githubusercontent.com/17010094/90110770-a6d9e080-dd45-11ea-9fff-0dcdcfa81e18.png)

- Verified subdivision targeting is auto-detected by default on a fresh install
![image](https://user-images.githubusercontent.com/17010094/90110939-dab50600-dd45-11ea-926b-cd7399d023f5.png)

- Verified subdivision targeting is auto-detected on upgrade from 1.11.105
- Verified when ads disabled on 1.11.105 and upgrading to 1.12.x, subdivision targeting messages do not appear in the logs. Verified enabling ads automatically starts logging the info
