### ISSUE TITLE
Greaselion: rewards-enabled state is always false on startup

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#9202]
If you create a Greaselion script with the following precondition it won't load when you first launch the browser (even when Rewards is enabled), as Greaselion always thinks Rewards is disabled on startup:

```
"preconditions": {
  "rewards-enabled": true
}
```

If you toggle the Brave Rewards switch on/off while running and reload the page with the Greaselion script, it will begin to work. The problem only occurs on browser startup, from what I've seen.

**Comment by bsclifton** [comment]
Added label for `QA/No`; please update to `QA/Yes` and add steps if manual testing required

Also added to milestone 1.10 👍
