### ISSUE TITLE
Blank Tab on Upgrade after connecting the Binance Widget

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9206]
This due to attempting to access balance values that have not yet been fetched from the API.

Test Plan:
1. Upgrade from an existing profile to version with advanced Binance Widget.
2. Connect via the Oauth flow.
3. Ensure that the current tab/subsequent tabs do not blank out or show errors in the console.
4. Ensure that until balances are fetched, display shows zero values and not `undefined` or other non-numeric data.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified upgrading from `1.8.24` to `1.9.37` and connecting to widget doesn't show blank tab
- Verified that the current tab/subsequent tabs don't blank on open or console logs any errors
- Verified that until balances are fetched, summary shows zero not undefined or other non-numeric data
--------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified upgrading from `1.8.24` to `1.9.37` and connecting to widget doesn't show blank tab
- Verified that the current tab/subsequent tabs don't blank on open or console logs any errors
- Verified that until balances are fetched, summary shows zero not undefined or other non-numeric data
--------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified upgrading from `1.8.24` to `1.9.37` and connecting to widget doesn't show blank tab
- Verified that the current tab/subsequent tabs don't blank on open or console logs any errors
- Verified that until balances are fetched, summary shows zero not undefined or other non-numeric data
