### ISSUE TITLE
No ads when fullscreen (MacOS)

### ISSUE THREAD

**Issue by jaredready** [brave/brave-browser#9209]
## Description 

No ads are displayed when Brave is fullscreen

## Steps to Reproduce

   1. Enter fullscreen
   2. Observe no ads are ever shown
   3. Verify no ads were shown in chrome://rewards/

## Actual result:

No ads

## Expected result:

Ads

## Reproduces how often: 

Whenever Brave is in fullscreen

## Brave version (brave://version info)

Brave | 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **N/A**
- Can you reproduce this issue with the dev channel? **N/A**
- Can you reproduce this issue with the nightly channel? **N/A**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **N/A (need Rewards to see ads)**
- Is the issue reproducible on the latest version of Chrome? **N/A**

## Miscellaneous Information:

**Comment by tmancey** [comment]
@jaredready This is as expected as when full-screen users are normally watching video or working on spreadsheets etc. Thanks

**Comment by jaredready** [comment]
For Windows I agree with you, though on Mac people fullscreen their applications all the time. It's not just for watching videos or working on spreadsheets.

**Comment by jsecretan** [comment]
Very interesting point @jaredready.  Because I think at one time we had exceptions just for video playback and things like that, but for instance, we also want to make sure we avoid the case of having a presentation full screened.  Any sense on where to draw the line?

**Comment by jaredready** [comment]
Yeah that's a good point I don't think there's any technical difference to point at between a fullscreened browser just doing normal browsing vs a fullscreen video.

I'm not knowledgeable enough about the inner workings of chromium but I'm guessing there's no line to draw here. Is it possible this can be a toggle so we can enable to disable ads during fullscreen on demand?

**Comment by andrewmattie** [comment]
I do remember at one point ads would come in while in fullscreen as that's how I primarily use Brave and used to get ads while doing so.

Having Brave fullscreen helps immensely with window management as quick switching cycles through your open apps on macOS compared to cycling through all open windows on Windows.

+1 on a focus mode toggle for fullscreen ads. It would give users the choice to use Brave however they want to. Users also have the option of using the do not disturb settings built into macOS and Windows in critical situations like screen sharing.

**Comment by andrewmattie** [comment]
Preliminary testing seems to indicate that the exceptions for a video being played are still in place. Giving the user some control over seeing ads in fullscreen, whether it be a toggle, chrome flag, or something else, would allow greater flexibility for the users to use Brave how they see fit.

**Comment by jsecretan** [comment]
Thanks for the feedback, made a follow up issue in #9264 and we'll see if it gets a lot of positive community feedback to triage.
