### ISSUE TITLE
[Desktop] Do not show 0.0 BAT for monthly ad earnings in the Monthly Contribution Statements for verified wallets

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#9211]
If the Brave Rewards wallet is verified, then earnings for each month where the wallet is verified will display 0.0 BAT (since ads earnings are sent directly to the user's Uphold account, rather than being accounted for within the browser). Instead of displaying 0.0 BAT, the interface should display an informative message about this case or, e.g., link to the user's Uphold transactions page.

![image](https://user-images.githubusercontent.com/11497541/79264438-93d00600-7e62-11ea-994d-0f86d47f2eb2.png)

Displaying 0.0 BAT for "Earnings from Ads" may be confusing to users. For example, in the above screenshot, the user did have ad earnings for that month, but the statement still displays 0.0 BAT.

**Possible Solution:**

Make some conditional logic such that if the wallet is verified for some month, then replace "0.0 BAT" with a link to the user's Uphold account, or some other message.

**Update:** Hyperlink text == "View deposit history" 

~Add correct accounting in the verified case.~

Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit) MacOS

**Comment by LaurenWags** [comment]
cc @mandar-brave @jenn-rhim also

**Comment by cryptojennie** [comment]
+1: https://www.reddit.com/r/BATProject/comments/hfwqyn/brave_wallet_is_showing_no_activity_00_bat_all_of/

**Comment by cryptojennie** [comment]
+1: https://www.reddit.com/r/brave_browser/comments/hm5fd6/bat_rewards_system_as_now_become_a_joke/fx4t6qm?utm_source=share&utm_medium=web2x

**Comment by kasramp** [comment]
I also have the same issue. Running `Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)` on `Linux Mint 19.3 Tricia`. I  also noticed a visual bug. If from the drop down I change the month it doesn't reflect and only the check mark is shown if I open the drop down,
![bug](https://user-images.githubusercontent.com/4501120/92529072-3762ee00-f22a-11ea-9346-de58d010f66d.jpg)
Notice how in the highlight it's showing `September` even when `May` is selected.

**Comment by LaurenWags** [comment]
@kasramp thanks for reporting, the bug with the drop down selection is being tracked with https://github.com/brave/brave-browser/issues/11613

**Comment by Miyayes** [comment]
`0.0` can be replaced with a link to a user's Uphold transaction history page (e.g. “See your earnings history on Uphold”). According to Uphold, it's currently not possible to filter by month, so a link to the general transaction page will do for now!

**Comment by Miyayes** [comment]
Confirmation by Uphold. Stick with simple solution for now. Do not download and parse .csv: 

>In the page there's no option to filter the activity by month. Still, you can download the Activity report and work the CSV file to filter by dates.

**Comment by jenn-rhim** [comment]
The earning should be indicated here regardless of where the tokens are stored/managed, just as the total balance. This seems to have gotten off the rail somewhere.

**Comment by Miyayes** [comment]
@jenn-rhim Unfortunately, the issue (I was told by Nejc back in the day, and I think is probably still true) is that because they're direct deposits to Uphold, we don't have easy access to the accounting, so we can't fetch this information easily :(. 

I think this would just be a temporary solution until we fix these issues from the bottom up (for instance, with pure virtual wallets).

**Comment by Miyayes** [comment]
This will be resolved properly (not with a stopgap solution) once this is implemented: https://github.com/brave/brave-browser/issues/15320

**Comment by Miyayes** [comment]
I think we should just go with the stopgap solution for now as initially proposed (link out to the custodians' transaction page). It's an easier win and will end confusion now. Waiting for https://github.com/brave/brave-browser/issues/15320 may take too long, and https://github.com/brave/brave-browser/issues/15320 might become obsolete if/when we move away from direct deposits.

**Comment by Miyayes** [comment]
Going with `View deposit history` for the hyperlink text. cc: @zenparsing @codybanxs

**Comment by Miyayes** [comment]
+1 https://community.brave.com/t/faulty-monthly-statement/245787

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/p0e75x/my_bat_rewards_are_significantly_less_than/

**Comment by Miyayes** [comment]
Related: https://github.com/brave/brave-browser/issues/18159
