### ISSUE TITLE
All creators showing as "not yet configured"

### ISSUE THREAD

**Issue by J-Reis** [brave/brave-browser#9215]
## Description 

Since 2nd to last (most recent) update (I waited through an update cycle to see if the issue would resolve), even verified creators to whom I'd previously been able to send tips are marked with:

> This creator has not yet signed up to receive contributions from Brave users. Any tips you send will remain in your wallet until they verify.

These same creators _**can**_ be tipped from the Android app.

## Steps to Reproduce

   1. Navigate to arstechnica.com or npr.org
   2. open Brave Rewards dialogue, observe indication of creator "status"
   3. attempt to tip using 'Send Tip' button

## Actual result:

tip does not go through
amount is under 'Pending Contributions
wallet amount not changed

## Expected result:
tip should be processed
contribution should be shown under 'Total tips this month'
tip amount should be deducted from wallet

## Reproduces how often: 

always

## Brave version (brave://version info)

Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Debian Stable (Buster 10.3)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **yes**
- Can you reproduce this issue with the beta channel? **not attempted**
- Can you reproduce this issue with the dev channel? **not attempted**
- Can you reproduce this issue with the nightly channel? **not attempted**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **no**
- Does the issue resolve itself when disabling Brave Rewards? **N/A**
- Is the issue reproducible on the latest version of Chrome? **N/A
![Android_20200414-164439_Brave](https://user-images.githubusercontent.com/23666144/79279164-09dc6900-7e73-11ea-9114-673efd4c33a2.jpg)
![Android_20200414-164526_Brave](https://user-images.githubusercontent.com/23666144/79279166-0a74ff80-7e73-11ea-9386-9c2a97e41526.jpg)
![Desktop_2020-04-14_04-46-32pm](https://user-images.githubusercontent.com/23666144/79279167-0a74ff80-7e73-11ea-9881-ec460bc14d2c.png)
![Desktop_2020-04-14_04-47-37pm](https://user-images.githubusercontent.com/23666144/79279169-0b0d9600-7e73-11ea-9ba1-7eaaa946bc06.png)
![Desktop_2020-04-14_04-48-02pm](https://user-images.githubusercontent.com/23666144/79279172-0b0d9600-7e73-11ea-9f6c-b59dfe233c85.png)

**

**Comment by NejcZdovc** [comment]
What you are seeing is correct. On mobile we don't have support for uphold wallet, meaning even publishers that are just connected (meaning that they are in our system, but are not KYC) can receive contributions. When you add uphold wallet for contribution to be successful publisher need to be fully KYC.

**Comment by J-Reis** [comment]
Lol, so does this mean that the vast majority of the tips I've given on mobile have been useless and aren't likely to actually have been collected by the creators I was trying to support?

… or just that the implementation on desktop is such that I can't actually use it to do the exact same basic thing that I can do on mobile?

**Comment by NejcZdovc** [comment]
@J-Reis no no, what you sent on mobile went through. 

Thing is that when you have uphold wallet connected (same will be on mobile when we add support for uphold) receiving publisher need to be KYC. 

When you are doing contributions without uphold wallet, contributions are going through our system and then we do payouts. When you have uphold wallet you are doing contribution directly via uphold (brave is not involved in the transaction). And because you are doing it directly uphold requires for you and publisher to be KYC.

**Comment by J-Reis** [comment]
I see. Thank you very much for taking the time to clarify. Much appreciated!
