### ISSUE TITLE
Did brave somehow change my wall paper ? I feel invasive. Any option to set my own ?

### ISSUE THREAD

**Issue by Xyncgas** [brave/brave-browser#9219]

**Comment by bsclifton** [comment]
Hi @Xyncgas 

There is a background shown on the new tab page. At the moment, this is not very customizable. You can disable the image and if there is a sponsored image you can disable this. But there is no way (yet) to provide a custom picture. We do have that issue captured with https://github.com/brave/brave-browser/issues/5838

There are some other feature requests you might like to see here: https://github.com/brave/brave-browser/issues/353
