### ISSUE TITLE
[Android] Link opened in a new tab does't use Desktop mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9224]
## Description 
 Link opened in a new tab does't use Desktop mode

## Steps to reproduce 

1. set all pages to load using desktop view in the general website settings of Brave
2. open any page in a new tab
3. open a link from that page in a new tab
4. Second tab opened is using mobile view instead of desktop view

## Actual result 
Link opened in a new tab does't use Desktop mode

## Expected result
Link opened in a new tab should use Desktop mode

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86):All
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: All
   
## Brave version
1.5.120 onwards

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

Issue reported on community https://community.brave.com/t/1-5-120-does-not-open-new-tabs-in-desktop-mode/116586/13

**Comment by bsclifton** [comment]
Not a problem in Chrome because Chrome only has a per-site Desktop mode

**Comment by Brave-Matt** [comment]
@bsclifton @anthonypkeane can we get some eyes on this? It's been around for a long time and I'm sure is fairly annoying for any users encountering it. 

+1 here: https://community.brave.com/t/new-tabs-still-open-in-mobile-view-related-gesture-bug/247483

**Comment by Brave-Matt** [comment]
Another +1 from Community:
https://community.brave.com/t/option-to-force-all-sites-to-be-desktop-view-on-android/381793/4

**Comment by 4ekki** [comment]
Extremely annoying issue. Do you have any update regarding it?

**Comment by deeppandya** [comment]
@srirambv this issue seems to be working with latest nightly. would you be able to verify ?

**Comment by srirambv** [comment]
Seems to be fixed. Don't see any issue with desktop site setting with new tabs. Closing for now can reopen if required
