### ISSUE TITLE
Google search engine is enabled by default. Brave should ask which search engine to use on first run / installation

### ISSUE THREAD

**Issue by AlexzAK** [brave/brave-browser#9228]
Subj.

Brave should ask which search engine to use on first run / installation
In an competitive manner to give no advantage to an "default" search engine

**Comment by bsclifton** [comment]
@AlexzAK which platform are you on?

The Desktop version has a welcome onboard wizard (viewable at brave://welcome/) which has this question. User is not forced to answer this though:
![Screen Shot 2020-04-15 at 12 45 45 AM](https://user-images.githubusercontent.com/4733304/79311650-9d815a00-7eb2-11ea-8d2d-59a90274954a.png)

**Comment by AlexzAK** [comment]
I did not seen it. Also I have old installation of Brave | 0.26.0 on my machine
But duckduckgo were selected there as a search engine...

Now it seems like an minor / non important bug as for me

@bsclifton 
You can reject/close it if you want

**Comment by bsclifton** [comment]
@AlexzAK oh wow - you're definitely going to want to uninstall that version and grab the latest via the instructions at https://brave.com/download/ (download page links to instructions for Linux)

You can remove the old key and install this new one. The executable is now called `brave-browser` versus the older `brave` (the version based on Electron/Muon)
