### ISSUE TITLE
build issue regarding rust

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [brave/brave-browser#9230]
## Description 
I am trying to build the latest version v1.9.19, a rust dependency giving an error. Upon looking into it, it may be due to the rust version. Details are provided below. I did not try to manually change the version of rust as I don't know the supported version or it may break the build process further.

## Steps to Reproduce

   1. On windows simply run npm run build.

## Actual result:
<img width="856" alt="tes" src="https://user-images.githubusercontent.com/46624268/79326958-1cb37400-7f2d-11ea-8d93-1c3c73d96c30.PNG">

## Brave version (brave://version info)

- v1.9.19

## Other Additional Information:
- So I went in the rustup folder to check the version of rust available. The path is `D:\brave-browser\src\brave\build\rustup\0.1.3\bin` for me. The Output is
![image](https://user-images.githubusercontent.com/46624268/79327391-ce52a500-7f2d-11ea-885f-d98b3fc226c4.png)
May be due to the rust version.

**Comment by bsclifton** [comment]
Closing as stale - @muhammad-usman-anwar if you're still interested, please give things a shot again 😄 Wiki with setup steps is available https://github.com/brave/brave-browser/wiki/Windows-Development-Environment
