### ISSUE TITLE
Asset address text is not legible

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9236]
## Description 

Asset address text is not legible

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/79364145-88660300-7f66-11ea-9912-6e1e15cdb3a3.png)

## Expected result:
Should have more contrast so that its legible 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.9.21 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? Na
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Na
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

## Miscellaneous Information:

cc: @jamesmudgett

**Comment by jamesmudgett** [comment]
Use #7d7d7d

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified text is using #7D7D7D for text colour
![image](https://user-images.githubusercontent.com/17010094/79848328-92f92000-83de-11ea-9441-e40cfe23e93d.png)
-------------------

Verification passed on 
Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified text is using #7D7D7D for text colour
![image](https://user-images.githubusercontent.com/17010094/79848998-7f9a8480-83df-11ea-93d8-6f9dae4db164.png)
-------------------

Verification passed on 
Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified text is using #7D7D7D for text colour
![image](https://user-images.githubusercontent.com/17010094/79849378-018aad80-83e0-11ea-8f3b-666101722788.png)
