### ISSUE TITLE
Balance view state is retained when widget is disabled and re-enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9238]
## Description 

Balance view state is retained when widget is disabled and re-enabled

## Steps to Reproduce

   1. Connect to Binance account on the widget
   2. Balance view is hidden by default
   3. Enable balance view to show
   4. Hide Binance widget 
   5. Re-enable Binance widget, balance view state is retained

## Actual result:

Hide balance view when widget is disabled and re-enabled

## Expected result:
Balance view state should be reset when widget is disabled/enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.9.21 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @ryanml @bbondy @jamesmudgett

**Comment by ryanml** [comment]
Closing this one as we are going to reset the widget on hide: https://github.com/brave/brave-browser/issues/9244

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state
----------
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state
----------
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state
----------
