### ISSUE TITLE
BraveAutocompleteProviderClientForClassifier is leaking OTR profile data.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#9239]
## Test plan
- Follow steps in https://github.com/brave/brave-browser/issues/1758
- Ensure it still works as expected

## Description
This is a follow-up issue for brave/brave-core#5221.
See https://github.com/brave/brave-core/pull/5221#discussion_r408989332

When using a Private window, BraveAutocompleteProviderClientForClassifier is likely leaking OTR autocomplete data into the regular profile.

STR: See https://github.com/brave/brave-browser/issues/1758

cc: @simonhong

**Comment by simonhong** [comment]
`BraveAutocompleteProviderClientForClassifier` is introduced to fix https://github.com/brave/brave-browser/issues/1037. Original PR is https://github.com/brave/brave-core/pull/757. Need to find another way to fix original issue.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from https://github.com/brave/brave-browser/issues/1758
* Confirmed using context menu item `Search DuckDuckGo for...` on a Tor window does use DDG for the search

-----
