### ISSUE TITLE
Site banner

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#924]
Implement site banner which is triggered via donate now button in panel.

Related issue https://github.com/brave/brave-browser/issues/920

**Comment by NejcZdovc** [comment]
blocked on #920 and #921

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.16 Chromium: 70.0.3538.54 (Official Build) (64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified steps from issue
* Logged #1658 for visual bug
