### ISSUE TITLE
Suppress Brave ad notifications when WebRTC is active

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9243]
## Description 
Feature Request: Allow users to optionally disable ad notifications while camera and/or microphone are in use. This feature could inadvertently distract the conference participant, or cause audio to bleed into the call.

## Miscellaneous Information:
Suggested by [a user on Twitter](https://twitter.com/techloreistaken/status/1250522266628091904).

![image](https://user-images.githubusercontent.com/815158/79387288-05768580-7f31-11ea-9fb5-1cae63bf0f84.png)

**Comment by tmancey** [comment]
We should investigate suppressing ad notifications if there is any active WebRTC

**Comment by tmancey** [comment]
Discussed and it was agreed we should not show ads based on the above for both native and custom push notifications

**Comment by tmancey** [comment]
Closing issue as will be investigated as part of https://github.com/brave/brave-browser/issues/33874
