### ISSUE TITLE
Binance Widget should be disconnected after hiding

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9244]
# Description 
When hiding the Binance Widget via settings/widget menu, we should revoke the access token and reset the widget.

## Steps to Reproduce

   1. Connect via Oauth on the Binance widget.
   2. Using the ellipsis menu, click "hide"
   3. Unhide the widget via footer dashboard settings

## Actual result:
Widget State is retained

## Expected result:
User should be disconnected with state reset.

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state
----------
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state
----------
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified hiding the widget disconnects state and reset 
- Verified hiding via dashboard or via widget menu resets the connected state

**Comment by jonathansampson** [comment]
We should not make a network request unless there is a token to be revoked. For users who just installed Brave, hiding these widgets (without ever having used them) results in a _token revocation_ request being made. These requests do not contain a token, since the user never actually used the widget.
