### ISSUE TITLE
Unhiding a crypto widget should bring it in to the foreground

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9245]
## Description 
Toggling on a crypto widget should bring it to the front of the stack

## Steps to Reproduce

   1. Clean profile, hide Binance while it is in the background
   2. Unhide Binance from the footer settings

## Actual result:
Binance is still behind the Rewards widget

## Expected result:
Binance should be in the foreground. The same behavior goes for Rewards.

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified toggling widget when in the background brings it in front
![9245](https://user-images.githubusercontent.com/17010094/79862026-09078200-83f3-11ea-946d-225edf14081f.gif)
