### ISSUE TITLE
NTP UI/UE fixes to ellipsis icon

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9247]
## Description 
Follow-up to: #8883 

Need the following UI fixes - 
- [x] widget shadow should show as long as ellipsis icon is visible (currently it goes away if you hover over the ellipsis icon) (Steps to Reproduce #1)
- [x] ellipsis menu should not show again on hover; the user should click on the ellipsis icon again to show it (Steps to Reproduce #2)
- [ ] ellipsis icon needs more padding on stats, top sites, and clock (see Design)

## Design

![ellipsis icon needs more padding on stats, top sites, and clock](https://user-images.githubusercontent.com/2388823/79400430-0d3b2780-7f3b-11ea-81f5-18652b2f6f50.jpg)

## Steps to Reproduce

   1. Using nightly 1.9.x, hover over Brave Rewards(or front most widget) and move mouse over ellipsis icon and notice shadow (it's a faint shadow) disappears. Expected result is that shadow is still there on mouse over.
<img width="481" alt="widget shadow should show as long as ellipsis icon is visible" src="https://user-images.githubusercontent.com/2388823/79399417-25f60e00-7f38-11ea-8a25-572e989161fe.png">

   2. Click on an ellipsis icon, select and open menu. Move mouse away from widget area and hover back into the widget area (or near ellipsis icon) and notice that the menu is still open. Expected result is that the menu is closed and a user needs to reselect the ellipsis icon to open. 

![ellipsis menu should not show again on hover 2020-04-15 16_50_11](https://user-images.githubusercontent.com/2388823/79399830-3d81c680-7f39-11ea-944d-a8e7d8e55207.gif)

## Reproduces how often: 
Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
https://bravesoftware.slack.com/archives/CQUHQ0PM3/p1586549021178800

**Comment by rebron** [comment]
cc: @ryanml

**Comment by karenkliu** [comment]
@rebron @ryanml The first 2 items are fixed; all that's needed to close this issue is to adjust the ellipses icon padding.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Linux

- Verified test plan from issue description
![image](https://user-images.githubusercontent.com/17010094/96969934-cee67c80-150a-11eb-8c1c-a07ca14e8366.png)
---------------
Verification passed on 

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | Windows 10 OS Version 1809 (Build 17763.1518)

- Verified test plan from issue description
![image](https://user-images.githubusercontent.com/17010094/96970732-04d83080-150c-11eb-8109-5ac4da621167.png)

----------
Verification passed on

Brave | 1.16.67 Chromium: 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | `b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}`
OS | macOS Version 10.15.7 (Build 19H2)

- Verified test plan from issue description
![image](https://user-images.githubusercontent.com/17010094/96970101-166d0880-150b-11eb-9fc0-9325e43436fb.png)
