### ISSUE TITLE
make widget card stack padding and title size consistent 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9249]
## Description 
Widget card stack padding and title sizes need to be made consistent for all widgets in the stack

## Design:
![widget_card_stack_padding_and_title_sizes_need_to_be_made_consistent_for_all_widgets_in_the_stack](https://user-images.githubusercontent.com/5951041/79399735-fd224880-7f38-11ea-904b-e8079f1df800.jpg)

## Brave version (brave://version info)

Brave | 1.9.21 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)
-- | --
Revision | 32921c79b6f01a0fb2deef0e1d45b42f96581051-refs/branch-heads/4044@{#883}
OS | macOS Version 10.15.5 (Build 19F53f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified widget title uses `18px Poppins` font
![image](https://user-images.githubusercontent.com/17010094/79974417-ef2f7300-84b6-11ea-8762-5e0f06c1877a.png)
- Verified cards use rounded corners
![image](https://user-images.githubusercontent.com/17010094/79974719-74b32300-84b7-11ea-9031-4e1b187eed8a.png)
- Logged issue for gap between card stack #9385 
----------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified widget title uses `18px Poppins` font
- Verified cards use rounded corners
-------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified widget title uses `18px Poppins` font
- Verified cards use rounded corners
