### ISSUE TITLE
"Safe Browsing" changes made in #8002 regressed with C81

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9266]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/9000

Issue #8002 made changes to Safe Browsing setting label for 1.7.x. When C81 was applied to 1.7.x, this issue regressed.

Setting was also moved farther down the list, but maybe this is expected, I'm unsure about that.

## Steps to Reproduce

   1. Go to brave://settings/privacy
   2. Find Safe Browsing setting

## Actual result:

<img width="940" alt="Screen Shot 2020-04-16 at 11 41 20 AM" src="https://user-images.githubusercontent.com/28145373/79476712-55a82300-7fd7-11ea-95c0-3884822efb98.png">

## Expected result:
<img width="1195" alt="Screen Shot 2020-04-16 at 11 35 26 AM" src="https://user-images.githubusercontent.com/28145373/79476720-593baa00-7fd7-11ea-8a5d-49e4d3d5b7d3.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.7.95 Chromium: 81.0.4044.92 (Official Build) (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron @bsclifton

**Comment by kjozwiak** [comment]
Moving this out of the milestone. We'll get this fixed in `1.8.x` as we need to release C81 ASAP.

**Comment by rebron** [comment]
Current location of Google Safe Browsing setting is fine. Let's update the label though #8002
We'll be updating/reorganizing this whole Privacy and security section shortly.

**Comment by simonhong** [comment]
Assigned to me. I can fix this quickly.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` using the following build:

```
Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
```

<img width="1118" alt="Screen Shot 2020-05-04 at 1 00 31 AM" src="https://user-images.githubusercontent.com/2602313/80937371-ca82a780-8da2-11ea-90f3-032411d95d2c.png">
