### ISSUE TITLE
Widget context menu on NTP is behind top sites

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#9267]
See screenshot

<img width="364" alt="Screen Shot 2020-04-16 at 12 44 57" src="https://user-images.githubusercontent.com/4672033/79477252-6315db00-7fe0-11ea-9f17-921c9a301a80.png">

## Test Plan
1. Launch Brave
2. Accumulate some top sites
3. Click the ellipsis menu in the top right corner of the top sites widget
4. Ensure that widget menu lays over the top site tiles, and does not clip behind.

cc @ryanml

**Comment by cezaraugusto** [comment]
Set as p3 since it's a regression

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.8.84 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from description.
* Confirmed for varying window sizes:
<img width="1341" alt="Screen Shot 2020-04-27 at 7 39 14 AM" src="https://user-images.githubusercontent.com/28145373/80368193-51db9280-885a-11ea-8ae2-6907793bf482.png">
<img width="780" alt="Screen Shot 2020-04-27 at 7 38 48 AM" src="https://user-images.githubusercontent.com/28145373/80368202-556f1980-885a-11ea-84fe-1d7ed928bcb7.png">
<img width="497" alt="Screen Shot 2020-04-27 at 7 39 00 AM" src="https://user-images.githubusercontent.com/28145373/80368211-586a0a00-885a-11ea-9751-d5e602d22bb7.png">
