### ISSUE TITLE
Saved passwords not imported from chrome browser to brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9269]
## Description 

Saved passwords not imported from chrome browser to brave

## Steps to Reproduce

   1. Clean profile 1.7.x
   2. Import bookmarks and settings from the welcome screen or `chrome://settings/importData`
   3. Import bookmarks and saved passwords from chrome
   4. Passwords are not imported from chrome to brave

## Actual result:

Saved passwords not imported from chrome browser to brave
## Expected result:
Passwords should be imported from chrome to brave

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.7.95 Chromium: 81.0.4044.92 (Official Build) (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa

**Comment by LaurenWags** [comment]
Could not reproduce on macOS:

Brave | 1.7.95 Chromium: 81.0.4044.92 (Official Build) (64-bit)
-- | --
Revision | e98e6f21168a55e7ba57202f56323911cd9d31d1-refs/branch-heads/4044@{#883}
OS | macOS Version 10.14.6 (Build 18G3020)

**Comment by rebron** [comment]
cc: @kjozwiak to try and reproduce on Windows

**Comment by btlechowski** [comment]
Not reproducible on Linux

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Ubuntu 18.04 LTS

Brave | 1.9.30 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Ubuntu 18.04 LTS

**Comment by GeetaSarvadnya** [comment]
@rebron Issue is reproducible for @kjozwiak and for me, whereas the issue is not reproducible for @LaurenWags. I am not sure what is the cause. I am trying to downgrade a few older versions of chrome and check which version is causing the issue as per as I know it was working for me always, from the last two releases it stopped working maybe 1.6.x onwards. Anyways I am closing this issue as dup as this issue is covered and fixed in https://github.com/brave/brave-browser/issues/3674
