### ISSUE TITLE
[Desktop] [Webcompat] Ads / Broken site on https://www.idnes.cz/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9271]
## Description 
Viewing `https://www.idnes.cz/zpravy/domaci/koronavirus-bilance-pocet-nakazenych-testu.A200416_082629_domaci_knn` shows up ads.

## Steps to Reproduce

   1. Go to `brave://adblock`
   2. Enable `CZE, SVK: EasyList Czech and Slovak`
   3. Visit: `https://www.idnes.cz/zpravy/domaci/koronavirus-bilance-pocet-nakazenych-testu.A200416_082629_domaci_knn`

## Actual result:
Ads show/Site a broken

## Expected result:
Site being rendered correctly

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.9.26 Chromium: 81.0.4044.92 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

## Miscellaneous Information:

Related (from `CZE, SVK: EasyList Czech and Slovak) Not being applied:

`idnes.cz##+js(acis, String.prototype.indexOf, atob)`
`idnes.cz##+js(aeld, beforeunload)`
`idnes.cz##+js(cookie-remover, /^_?adb/)`

Works fine with uBO enabled with the above subscription.

**Comment by antonok-edm** [comment]
@ryanbr I'm not seeing any ads on that site (renders the same for me as in Firefox w/ uBO). But it does look like some cosmetic filters might help the layout slightly.

**Comment by ryanbr** [comment]
Hmm looking into this looks like uBO combines 2 lists
`https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters_ublock.txt` and `https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt`   Whats an easy way to combine these 2 lists?  filters_ublock.txt  has fixes on `idnes.cz`  @antonok-edm
