### ISSUE TITLE
[webcompat] Display issues on https://www.costco.com/.product.100518269.html

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9275]
## Description 
Viewing `https://www.costco.com/.product.100518269.html`  Doesn't show the image viewer correctly

## Steps to Reproduce

   1. Visit `https://www.costco.com/.product.100518269.html`
   2. Expect zoom controls to work correctly.
   3. 

## Actual result:
Zoom controls not working

## Expected result:
Expect site to work with picture zooms.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/3e6a376a5c60b600b270943eddfcc6c110a805e8

**Comment by bsclifton** [comment]
@ryanbr looks like it's still happening

**Comment by ryanbr** [comment]
Okay, thanks!

https://github.com/easylist/easylist/commit/c18a1688c328d19cc35db25f738cd0f7d469051f

Let see how this goes

**Comment by ryanbr** [comment]
Seems this had more scripts affecting this, this should resolve it. Leaving open to confirm when Shields updates.

**Comment by ryanbr** [comment]
Confirmed, Costco images are now working. closing report.
