### ISSUE TITLE
[Webcompat] Video not showing on https://video.repubblica.it/home

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9278]
## Description 
Viewing `https://video.repubblica.it/home` Video not showing up

## Steps to Reproduce

   1. Visit `https://video.repubblica.it/home`
   2. Video doesn't show
   3. 

## Actual result:
No embedded video.

## Expected result:
Expect Video to play

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/217b6c87377a801d16e69c1888e69cf1c0078e16


Should fix it

**Comment by bsclifton** [comment]
@ryanbr looks like it's still happening

**Comment by ryanbr** [comment]
Okay, re-looking.

**Comment by ryanbr** [comment]
Filters being blocked:

`https://oasjs.kataweb.it/adsetup.js`
`https://www.repstatic.it/cless/common/chartbeat/chartbeat_notlh.js?ver=3a`
`https://www.repstatic.it/cless/main/nazionale/2013-v1/js/script/taboola.js`
`https://cdn-gl.imrworldwide.com/conf/P88CDD34A-1ED6-4C87-8E6F-65B3E240E07E.js#name=GEDI_nielsen_video&ns=NOLBUNDLE`
`https://sb.scorecardresearch.com/beacon.js`
`https://bee.imrworldwide.com/v1/clients/match?client_id=kataweb-it&url=https://video.repubblica.it/home`
`https://ssl.google-analytics.com/ga.js`
`https://secure-it.imrworldwide.com/storageframe.html`
`https://cdn-gl.imrworldwide.com/conf/config250.js#name=v60Bsdk__1588586702863&ns=NOLBUNDLE`

**Comment by ryanbr** [comment]
Okay, seems to be affecting other sites.

https://github.com/easylist/easylist/commit/e3314cd494943117b83ae13f4bc909deffecc707

Should help, will leave Issue report open to confirm

**Comment by ryanbr** [comment]
Confirmed to be working now @bsclifton 

(on 4 sites)

```
video.ilsecoloxix.it
video.lanuovasardegna.it
video.lastampa.it
video.repubblica.it
```

Closing.
