### ISSUE TITLE
Captcha image

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#928]
Captcha image that we currently use in rewards is from browser laptop, which is of course wrong. We need new api call that will return adjusted image for brave-core. This will live in `/v3/captchas/{paymentId}`

Current
![image](https://user-images.githubusercontent.com/9574457/44955056-41202100-aead-11e8-956f-748d3f7fd110.png)

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

<img width="1041" alt="screen shot 2018-10-03 at 5 18 57 pm" src="https://user-images.githubusercontent.com/2602313/46441653-2c95a980-c735-11e8-8708-9f7c56070bf8.png">
