### ISSUE TITLE
Vertical height of the Binance Widget should increase by ~30% when logged in

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9283]
The height of the widget after connecting should increase to 360px tall. The initial Buy view before connecting should remain unchanged.

<img width="307" alt="Screen Shot 2020-04-16 at 5 26 39 PM" src="https://user-images.githubusercontent.com/8732757/79519475-d9c6ce80-8008-11ea-9cfe-98ecdb6c5d10.png">
<img width="311" alt="Screen Shot 2020-04-16 at 5 26 31 PM" src="https://user-images.githubusercontent.com/8732757/79519477-daf7fb80-8008-11ea-873c-caaf831da6a3.png">

<img width="314" alt="Screen Shot 2020-04-16 at 5 26 25 PM" src="https://user-images.githubusercontent.com/8732757/79519482-db909200-8008-11ea-97c8-b38c31537d49.png">
<img width="307" alt="Screen Shot 2020-04-16 at 5 26 16 PM" src="https://user-images.githubusercontent.com/8732757/79519483-dc292880-8008-11ea-913f-39f48a086de2.png">/

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

![image](https://user-images.githubusercontent.com/17010094/79932191-8ae6c200-846a-11ea-95db-68d744178f31.png)
![image](https://user-images.githubusercontent.com/17010094/79932399-106a7200-846b-11ea-8694-0b9dced3c28b.png)
![image](https://user-images.githubusercontent.com/17010094/79932379-08aacd80-846b-11ea-8cc3-ec31589b64c3.png)
-------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

![image](https://user-images.githubusercontent.com/17010094/79941162-3ef34780-8481-11ea-9a00-4a4479535383.png)
![image](https://user-images.githubusercontent.com/17010094/79941268-8a0d5a80-8481-11ea-9841-d47b6ed1bf7b.png)
![image](https://user-images.githubusercontent.com/17010094/79941412-d789c780-8481-11ea-8719-fcf21e9fbb6e.png)
-------
