### ISSUE TITLE
Binance Widget Nav Menu should be present on all four screens.

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9284]
To confirm:

1. The nav menu containing the `Deposit Summary Convert Buy` nav items should be present in each view.
2. For the Connect view, the "Connect label" should be done away with. With the available balance left-aligned.
3. For the Connect and Buy View, the Convert/Buy buttons should be moved down further in to the negative space. The `Cancel` prompt underneath each of those buttons should go away. As we now have the nav.

<img width="311" alt="Screen Shot 2020-04-16 at 5 26 31 PM" src="https://user-images.githubusercontent.com/8732757/79519630-3de99280-8009-11ea-9bc2-38a7f6003883.png">
<img width="307" alt="Screen Shot 2020-04-16 at 5 26 39 PM" src="https://user-images.githubusercontent.com/8732757/79519643-4346dd00-8009-11ea-9796-a84e60e45eac.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified navigation menu is shown on all four screen
------------------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified navigation menu is shown on all four screen
------------------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified navigation menu is shown on all four screen
