### ISSUE TITLE
Implement Copy/Print/Save as File actions under "Backup your wallet"

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#929]
Implement copy, print and save as File in Backup/Restore dialog.

![image](https://user-images.githubusercontent.com/9574457/44955096-dcb19180-aead-11e8-99cd-ab9691682d43.png)

**Comment by bbondy** [comment]
maybe we could move this to 1.0 considering a user can copy and paste the codes?

**Comment by NejcZdovc** [comment]
agree

**Comment by garrettr** [comment]
> maybe we could move this to 1.0 considering a user can copy and paste the codes using cmd+c or the right click menu.

Could we hide the nonfunctional buttons in the meantime? I just encountered this and was briefly perplexed. Might frustrate/unnerve some end users.

Also, might consider adding some copy saying "you can select and copy the recovery key with the Cmd-C copy keyboard shortcut." I figured that out via trial and error but it's not exactly obvious.

**Comment by srirambv** [comment]
@NejcZdovc  the implemented design is different from the original spec screenshot mentioned in the issue? Can you confirm which one is to be verified?
![image](https://user-images.githubusercontent.com/17010094/49791838-4cf66b80-fd57-11e8-8ce7-9156bf96a3af.png)

**Comment by NejcZdovc** [comment]
@srirambv yes we changed design, what you have on the screenshoot is correct

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

- Verified Save/Print/Save options for recover backup key
