### ISSUE TITLE
[Android] Fix crash on private tab

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#9293]
## Description 
There is crash on version 1.7.x when on opening of private tab. Needs to be fixed.

## Steps to reproduce 

   1. In description

## Expected result
No crash

## Issue reproduces how often 
Easy on version 1.7.x

## Issue happens on 
   - Current Play Store version? no
   - Beta build? only on version 1.7.x

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.7.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@samartnik assuming this only affected `1.7.x` and not `1.5.x` correct? Going to apply the `release-notes/exclude` label as this never made it into `1.5.x`. Please correct me if that's not the case.

Regarding the STR/Test Case for QA, is it basically making sure that you can use PB without crashing?

**Comment by samartnik** [comment]
Yes, it is only on 1.7.x and just make sure there is no crash when open private tab

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.100 x64 stable build
- Verified opening a private tab via hamburger menu doesn't crash the browser
- Verified loading a site on a private tab opened via hamburger menu doesn't crash
- Verified opening a private tab via hamburger menu via tab tray doesn't crash the browser
- Verified loading a site on a private tab opened via hamburger menu in tab tray doesn't crash the browser
- Verified opening a bookmark in a private tab doesn't crash the browser
- Verified opening a private tab via app context menu on homescreen doesn't crash the browser 
-------
Verification passed on Samsung Tab A with Android 9 running 1.7.100 x64 stable build
- Verified opening a private tab via hamburger menu doesn't crash the browser
- Verified loading a site on a private tab opened via hamburger menu doesn't crash
- Verified opening a bookmark in a private tab doesn't crash the browser
- Verified opening a private tab via app context menu on homescreen doesn't crash the browser 
-------
Logged #9444 for missing context menu.
