### ISSUE TITLE
More fine-grained fingerprinting control

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#93]
@snyderp suggested in https://github.com/brave/antimuon/pull/44 about having possibilities to do more complex fingerprinting protection policies, such as blocking a specific feature.
Open this issue to track and host discussions for this.

**Comment by jumde** [comment]
From the discussion: https://bravesoftware.slack.com/archives/C8MP8ME4C/p1522451094000033

```
`First party` fingerprinting protection breaks a lot of sites. 

1. Instead of 1st party and third party fingerprinting protection what if we have `default` and `enhanced` fingerprinting protection where `default` is `3rd Party + 1st party protections (that don't break a lot of sites)` and `enhanced` is `3rd Party + 1st Party` fingerprinting protection

2. For advanced users Brave can can have granular control over which fingerprinting protection techniques can be enabled or disabled.
```

**Comment by pes10k** [comment]
Closing this in favor of https://github.com/brave/brave-browser/issues/8787, which will address at least some of this.  And if we need even further grained controls, this FP protections revamp adds some under the hood machinery that will make this easier too
