### ISSUE TITLE
Wallet activity - Monthly Statement

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#930]
Implement wallet activity dialog that is triggered on rewards page in wallet section.

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/918

**Comment by mandar-brave** [comment]
Please fix https://github.com/brave/brave-browser/issues/1298; closing #1298 as redundant

**Comment by LaurenWags** [comment]
@NejcZdovc is this for the monthly statement for Brave Rewards?

**Comment by NejcZdovc** [comment]
@LaurenWags yes

**Comment by LaurenWags** [comment]
+1s from community:
https://community.brave.com/t/is-there-any-way-to-view-total-tips-from-last-month/38847
https://community.brave.com/t/is-there-any-way-to-view-total-tips-from-last-month/38847/2

**Comment by kjozwiak** [comment]
@davidtemkin @mandar-brave @rebron is there any updates re: monthly statements? What's the current schedule for this? We really need to get this into the product. Right now, once you a-c, there's no way of knowing where exactly your BAT went as an end user. Getting several +1 from the community well. CCing @LaurenWags.

**Comment by mandar-brave** [comment]
@jenn-rhim  please add the final design for the monthly statements

**Comment by jenn-rhim** [comment]
Monthly statement update:
1. For the statements dated prior to us keeping track of opening and closing balances: indicate NA
2. Pending contribution list for unverified creators
3. A case where no auto-contribute has gone out

![statement-pendinglist](https://user-images.githubusercontent.com/4369856/52257373-7226d680-28cf-11e9-91ba-5dd2b39964ae.png)


![statement-noac](https://user-images.githubusercontent.com/4369856/52257379-7652f400-28cf-11e9-9381-4fb3f8914ca4.png)


@NejcZdovc @mandar-brave

**Comment by eljuno** [comment]
+1 fron community https://community.brave.com/t/where-is-my-contributor-statement-history/45592?u=eljuno

**Comment by LaurenWags** [comment]
+1 from community - worked with a user via DM who funded their wallet and then it was used in Auto Contribute shortly thereafter (about 20 minutes), and without this feature it just looked like the BAT never made it to their wallet.

**Comment by Miyayes** [comment]
+1 from Reddit: https://www.reddit.com/r/BATProject/comments/c98plf/where_can_i_see_all_of_my_rewards_earnings/

**Comment by rossmoody** [comment]
For QA, this is the latest design mockup I can find for this initiative. 

![7 7 2019 - Statement Modal](https://user-images.githubusercontent.com/29072694/61004039-f87d9380-a319-11e9-97a3-8b0441a4546c.png)

**Comment by kjozwiak** [comment]
@mandar-brave @jenn-rhim is the above mockup that @rossmoody mentioned in https://github.com/brave/brave-browser/issues/930#issuecomment-510224549 the latest design that will be used? Or is there something newer?

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/cgbxzv/balance/

**Comment by mandar-brave** [comment]
@kjozwiak i missed the tag on this. 
I think it is in the ballpark with changes due to changes in product since design was agreed upon. @alexwykoff you probably are the best bet in terms of final final.

**Comment by kjozwiak** [comment]
Thanks @mandar-brave 👍@alexwykoff if the above isn't the current design/spec, do we have an up to date one that we can add into the issue so once QA starts going through it, there's no discrepancies in what we see in the product vs the design documents?

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/cyg21b/history_for_previous_months_tips/

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/5815

**Comment by cryptojennie** [comment]
+1 https://www.reddit.com/r/BATProject/comments/ezvygr/view_historical_monthbymonth_rewards/

**Comment by LaurenWags** [comment]
marking as `QA/Blocked` until https://github.com/brave/brave-browser/issues/8828 is uplifted to 1.7.x

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.7.79 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/4279
* General cases executed:
1. Clean profile 1.7.x (funded via UGP & Ad grants) - **PASS**
   - claim Ad grant
   - claim UGP grant
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
---> Monthly statement contains all expected information

2. Clean profile 1.7.x (funded via KYC'd wallet) - **PASS** 
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
---> Monthly statement contains all expected information

3. Clean profile 1.7.x (funded via restored wallet with user funds) - **PASS**
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
---> Monthly statement contains all expected information 

4. Upgrade - install 1.5.x (funded via UGP & Ad grants) - **PASS**
   - claim Ad grant
   - claim UGP grant
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
   - upgrade to 1.7.x
   - view monthly statement
---> Monthly statement contains all expected information 

5. Upgrade - install 1.5.x (funded via KYC'd wallet) - **PASS**
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
   - upgrade to 1.7.x
   - view monthly statement
---> Monthly statement contains all expected information

6. Upgrade - install 1.5.x (funded via restored wallet with user funds) - **PASS**
   - set up & perform AC
   - set up & perform recurring tips
   - set up 1 time tips
   - upgrade to 1.7.x
   - view monthly statement
---> Monthly statement contains all expected information

<img width="951" alt="Screen Shot 2020-03-31 at 1 49 24 PM" src="https://user-images.githubusercontent.com/28145373/78069980-01f7d180-7369-11ea-95bb-dd74f4e8c588.png">
<img width="953" alt="Screen Shot 2020-03-31 at 1 49 33 PM" src="https://user-images.githubusercontent.com/28145373/78069988-04f2c200-7369-11ea-87b9-f84cf20c497a.png">
<img width="948" alt="Screen Shot 2020-03-31 at 1 49 41 PM" src="https://user-images.githubusercontent.com/28145373/78069992-07551c00-7369-11ea-94ea-f0eeae474c66.png">
<img width="955" alt="Screen Shot 2020-03-31 at 1 49 49 PM" src="https://user-images.githubusercontent.com/28145373/78070000-09b77600-7369-11ea-80e2-c6db1fc6e156.png">
