### ISSUE TITLE
[Desktop] Brave has no option to prevent "Set default browser" notification appearing repeatedly

### ISSUE THREAD

**Issue by matthewbal** [brave/brave-browser#9306]
## Description 
On Linux, each time Brave is launched, it asks to be the default browser. If I click the x, it goes away and asks on the next Brave startup. If I select "Make default browser", it goes away and then also appears on the next startup.

## Steps to Reproduce

   1. Install Brave on KDE Plasma (Ubuntu 18.04.4 LTS)
   2. Launch Brave
   3. Dismiss Notification
   4. Exit Brave
   5. Launch Brave
   6. Notification Appears again

## Actual result:
The notification cannot be removed permanently and appears every time. To fix this, you need to manually edit files as a workaround.

## Expected result:
The notification should only appear once, and there **should be an option in settings to never display the notification.** Other modern browsers offer such functionality from the settings menu.

## Reproduces how often: 
Happens every time on my machine. The same issue has happened to many other Linux users: See below from the first page of google

https://github.com/brave/brave-browser/issues/1274
https://github.com/brave/brave-browser/issues/6860
https://community.brave.com/t/cannot-set-brave-as-default-browser/34661
https://www.reddit.com/r/brave_browser/comments/9yy7e0/disable_make_default_browser_prompt_at_launch/
https://forum.mxlinux.org/viewtopic.php?f=108&t=57348

## Brave version (brave://version info)
Brave	1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision	e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS	Linux
JavaScript	V8 8.0.426.30
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/arkady/.config/BraveSoftware/Brave-Browser/Default

## Linux Version
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I acknowledge this issue appears elsewhere in the repo, but they are dead from 2018, and don't address that we could add a setting to have the browser never ask - this would resolve all edge cases and prevent people having to do workarounds to stop brave asking on every launch

**Comment by landshrk** [comment]
Same issue on Arch 5.4.32-1-lts. Same issue previously on Manjaro whateverversionitwas. 

`[nova@novarch ~]$ pacman -Qi brave-bin
Name            : brave-bin
Version         : 1:1.7.92-1
Description     : Web browser that blocks ads and trackers by default (binary release).
Architecture    : x86_64
URL             : https://brave.com/download
Licenses        : MPL2  BSD  custom:chromium
Groups          : None
Provides        : brave  brave-browser
Depends On      : gtk3  nss  alsa-lib  libxss  ttf-font
Optional Deps   : cups: Printer support
                  pepper-flash: Adobe Flash support
                  libgnome-keyring: Enable GNOME keyring support
Required By     : None
Optional For    : None
Conflicts With  : brave
Replaces        : None
Installed Size  : 235.56 MiB
Packager        : Unknown Packager
Build Date      : Sun Apr 19 01:14:08 2020
Install Date    : Sun Apr 19 01:18:36 2020
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None`

`[nova@novarch ~]$ ls -l /usr/share/applications | grep brave
-rw-r--r-- 1 root root  4972 Apr 19 01:14 brave-browser.desktop`

brave://version output:

`Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) unknown (64-bit)
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Linux
JavaScript | V8 8.0.426.30
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,DnsOverHttps,SimplifyHttpsIndicator,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/nova/.config/BraveSoftware/Brave-Browser/Default`

None of the "fixes" that have been posted from a couple years ago have had any effect. And again, this has existed across a couple of Linux distros for me.

**Comment by XavierCLL** [comment]
Hi, I not only confirm the notification error but also confirm the button to "Make default" browser not work, not changes the settings in Plasma 5.19.5 (on Archlinux) using Brave version 1.13.82

![Screenshot_20200901_110212](https://user-images.githubusercontent.com/11801453/91889661-09d2df00-ec43-11ea-9906-3f567900333b.png)

**Comment by fmarier** [comment]
For Arch users, we are aware of the issue and are tracking it separately here: #2377 (see the issue for a possible work-around).

For Ubuntu, here are a few things you could check to make sure that Brave is set as default correctly: https://feeding.cloud.geek.nz/posts/set-default-web-browser-debian-ubuntu/

**Comment by karenkliu** [comment]
Does https://github.com/brave/brave-browser/issues/12203 fix this issue?

cc @simonhong

**Comment by simonhong** [comment]
@karenkliu Infobar will not be visible anymore with #12203 
Instead, our modal dialog will be shown repeatedly only for 2nd,3rd, 4th, 8th, and 20th launch.

**Comment by karenkliu** [comment]
@rebron Can we close this issue since Simon's work should have removed the infobar?

**Comment by rebron** [comment]
Closing per fix in #12203
