### ISSUE TITLE
Brave is using an old, insecure version of chromium

### ISSUE THREAD

**Issue by corecontingency** [brave/brave-browser#9311]
On Arch Linux, installed latest version of Brave (version 1.7.92) from [AUR](https://aur.archlinux.org/packages/brave-bin/).

Here is what `brave://settings/help` reports:

![brave_version](https://user-images.githubusercontent.com/54042889/79631880-bc7d2780-8110-11ea-9f51-561e031f0e87.png)

As you can see, Brave reports it is using chromium version 80.0.3987.163, which was released April 2, and has 33 security bugs that had CVEs assigned.

I sincerely hope that this is just a display bug.

**Comment by eljuno** [comment]
Uplifted here #9286

**Comment by bsclifton** [comment]
Thanks for sharing the link @eljuno - the build is in progress now and we'll be working to release as soon as we can 😄 

Apologies for being a bit behind on this one. We had a lot of work packed into the 1.7 release and also migrated Android over to using the same code-base, which took up a lot of resources. We should have an update in the next day or two 😄
