### ISSUE TITLE
Feature Request: Fix StartupWMClass for .desktop file on Linux

### ISSUE THREAD

**Issue by BachoSeven** [brave/brave-browser#9313]
## Description 

On the latest nightly build, when using the provided brave-browser-nightly.desktop file, the StartupWMClass string (from `xprop`) is `' "WM_CLASS(STRING) = "brave-browser", "Brave-browser" '`; however, when adding the .desktop file to a dock or similar interfaces and starting Brave from there, a different icon is created and shown as the launched app on the launcher.

I found an easy workaround (see below) that I have to apply on every update of the app, however it would be easy to implement it. This issue is not limited to Ubuntu, as WMClass is a property of X.

## Steps to Reproduce

   1. Install Brave Nightly on Ubuntu (18.04 or later)
   2. Add the .desktop file as a favourite application on the dock
   3. Launch the application from the dock

## Actual result:

Creates a different icon in the dock:

![image](https://user-images.githubusercontent.com/55460785/79644333-9014ea00-81a8-11ea-899a-c3ceaaf5890d.png)

## Expected result:
Respect WMClass of the launcher's icon in the dock (obtained using the workaround described below):

![image](https://user-images.githubusercontent.com/55460785/79644330-89867280-81a8-11ea-902e-85ad2a2e1d92.png)

## Reproduces how often:

N/A

## Brave version (brave://version info)

Brave: 1.9.32 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
Revision: cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS: Linux

## Version/Channel Information:

- Can you reproduce this issue with the nightly channel? YES

## Miscellaneous Information:

An easy workaround for this is just to add the line `StartupWMClass="Brave-browser"` under the `[Desktop Entry]` section of `brave-browser-nightly.desktop`.

I also checked it out the other channels releases, and the issue seems to be independent of the channel.

**Comment by fmarier** [comment]
Let's discuss that fix on #1746.
