### ISSUE TITLE
noopener should be in use for opening Binance auth and referral URLs

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9317]
Per sec review comments here: https://github.com/brave/brave-core/pull/5160#pullrequestreview-395813568 we should be using `noopener` for the Binance referral and authorization URLs. Also, some validation should be performed before setting the clientUrl.

For QA, there should be no change in functionality, rather a regression test should be performed for the auth process and the buy links.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified able to connect to widget successfully
- Verified hide/unhide functionality works fine
- Verified asset address/QR code shows correctly 
- Verified convert functionality works fine 
- Verified hiding widget via menu or dashboard successfully disconnects the widget
- Verified ref code correctly auto-populated on the buy landing page
------------------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified able to connect to widget successfully
- Verified hide/unhide functionality works fine
- Verified asset address/QR code shows correctly 
- Verified convert functionality works fine 
- Verified hiding widget via menu or dashboard successfully disconnects the widget
- Verified ref code correctly auto-populated on the buy landing page
------------------
Verification passed on 

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Linux

- Verified able to connect to widget successfully
- Verified hide/unhide functionality works fine
- Verified asset address/QR code shows correctly 
- Verified convert functionality works fine 
- Verified hiding widget via menu or dashboard successfully disconnects the widget
- Verified ref code correctly auto-populated on the buy landing page
