### ISSUE TITLE
GitHub icon not showing in Top Sites

### ISSUE THREAD

**Issue by ilan274** [brave/brave-browser#9319]
**Description:**
My Top Sites is not showing the GitHub icon.
I have tried cleaning the total cached images and files, reinstalling (purge/install) Brave, but nothing helped.

**Actual result:**
https://i.imgur.com/jlj7v72.jpg

**Expected result:**
Expect to see the GitHub icon.

**Brave version:**
Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
OS: Linux (Xubuntu)

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by simonhong** [comment]
In dark mode, github's favicon color is white and our toptiles bg is white.
This is why github favicon is not visible in NTP.

duplicated issue with https://github.com/brave/brave-browser/issues/9030

**Comment by ilan274** [comment]
After changing back to light mode nothing changed (even after restarting my notebook).

The solution was go into `/home/USERNAME/.config/BraveSoftware/Brave-Browser/Default/`, delete both `Favicons` and `Favicons-journal` and restart Brave.

Thanks for the replay, @rebron and @simonhong :+1:  :)
