### ISSUE TITLE
Importing Cookies/Passwords from Brave installed on another Windows computer

### ISSUE THREAD

**Issue by afirmware** [brave/brave-browser#9320]
## Description 

I have brave installed installed on another Windows computer, but recently it can't boot. I tried everything but can't fix it, so I'm trying to copy and restore the brave profiles from that hard disk to the current one. I followed this guide (https://www.reddit.com/r/vivaldibrowser/comments/65qrlb/importing_cookiespasswords_from_vivaldichrome/) to migrating my DPAPI keys, and then copied Chrome profile from that computer and the Chrome profile works with no problem, everything (github, gmail) is kept signed in. However, when I'm doing the same thing on brave, all my signed in websites are not signed in anymore.

So how to import brave profile and keep everything as they were there?

## Steps to Reproduce

The steps are the same as this guide, just replace chrome with brave: (https://www.reddit.com/r/vivaldibrowser/comments/65qrlb/importing_cookiespasswords_from_vivaldichrome/) 
   1. copy %APPDATA%\Microsoft\Protect\ from old computer to the new one
   2. download https://sourceforge.net/p/keepass/wiki/Recover%20Windows%20User%20Account%20Credentials/attachment/DPAPI%20migration.reg.txt
   3. edit DPAPI%20migration.reg.txt replacing <sid> with directory name in old %APPDATA%\Microsoft\Protect\ (S-1-5-...), <username> with old username, I also replaced "computer-1" with my current computer name(maybe not important)
   4. ename DPAPI%20migration.reg.txt to DPAPI%20migration.reg
   5. click on reg file so Regedit can copy keys.
   6. open administrator command prompt (Win-X key in Win10) and execute c:\windows\system32\dpapimig.exe. I had to do it twice for some reason. It will ask you for password from the old computer. (That OP said it will ask for password, but it did not ask me possibly because I use the same password for the old computer and this computer)
   7. bacon time/profit! at this very moment your non working %APPDATA%\Local\Google file magically starts working.
(I use this method and copied everything in %APPDATA%\Local\Google folder and chrome works. I also copied everything in %APPDATA%\Local\BraveSoftware, but it did not work.)
   

## Actual result:
The result is the Brave's history and bookmarks are copied, but all the signed in website are not signed in.

## Expected result:
I hope all the signed in websites are kept signed in like the latest Chrome does.
Also, I hope to have an option to completely turn off the cookies encryption with DPAPI since we have full disk encryption like veracrypt, there is no need another layer of encryption. Just like firefox's profile have no encryption at all and it makes easier to backup and restore.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not tested, but possibly yes
- Can you reproduce this issue with the dev channel? not tested, but possibly yes
- Can you reproduce this issue with the nightly channel? not tested, but possibly yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rebron** [comment]
@afirmware The article you're linking to is from 3 years ago or 50 Chromium versions ago.
We're working on Sync v2 that will let you import cookies and passwords from one computer to the next. 

Marking this one as wontfix and we'll resolve this via Sync v2. I don't believe those instructions you pointed to will work as workaround for now.
