### ISSUE TITLE
Don't show branded wallpaper notification in NTP for Super Referral

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#9329]
## Description
Notification for guiding about how to hide SI is only valid for Sponsored Images.
See https://bravesoftware.slack.com/archives/CT7JC4KBM/p1587357584128900

## Test plan
1. Do an install that uses Super Referral (put `promoCode` file in directory for `TECHNIK`; see https://github.com/brave/brave-core/pull/4866 for more steps)
2. Launch into brave
3. Enable rewards
4. Pull up new tab until it shows super referral page
5. Verify the rewards widget on NTP does NOT look like this:
![Screen Shot 2020-04-20 at 10 52 07 AM](https://user-images.githubusercontent.com/4733304/79783128-0888c180-82f5-11ea-96be-28ce703da316.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64` using the following build:

```
Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)
```

Went through the STR outlined under https://github.com/brave/brave-browser/issues/9329 and ensured that the `You're getting paid to view this background image` message wasn't being displayed in the Rewards modal under the NTP:

<img width="1074" alt="Screen Shot 2020-04-28 at 2 48 44 AM" src="https://user-images.githubusercontent.com/2602313/80456164-1fce3d00-88fb-11ea-984e-cfe68ddc5e71.png">

<img width="1081" alt="Screen Shot 2020-04-28 at 2 48 53 AM" src="https://user-images.githubusercontent.com/2602313/80456168-22c92d80-88fb-11ea-8477-9fb182f0029f.png">

<img width="1076" alt="Screen Shot 2020-04-28 at 2 49 04 AM" src="https://user-images.githubusercontent.com/2602313/80456173-25c41e00-88fb-11ea-97f4-2a724eae2108.png">

Also ensured that the `You're getting paid to view this background image` was still being displayed when a user enabled Rewards that's going through the normal NTP SI flow:

<img width="1081" alt="Screen Shot 2020-04-28 at 2 49 56 AM" src="https://user-images.githubusercontent.com/2602313/80456199-2f4d8600-88fb-11ea-9c3d-32293b3f5544.png">

**Comment by btlechowski** [comment]
Setting as `OS/Windows` and `OS/macOS` because referrals are unavailable on Linux
