### ISSUE TITLE
Can't load Twitter with 3rd party cookies blocked

### ISSUE THREAD

**Issue by eljuno** [brave/brave-browser#9337]
## Description 
Reported here https://community.brave.com/t/twitter-mobile-site-not-accessible/119865?u=eljuno

User unable to load Twitter.com if 3rd party cookies is blocked. Twitter showing "Something went wrong, Try again!” error message.

Loaded properly if 3rd party cookies blocker is disabled.

## Steps to reproduce 

   1. Visit Twitter with default shield -- 3rd party cookies blocked
   2. Twitter unable to load. "Something went wrong" error message
   3. Disable 3rd party cookies blocker. Reload. Twitter loaded properly.

## Actual result 

https://drive.google.com/file/d/1OY6oAAIeRWdZYNjG6vTgV2xBGaJ4k_I3/view

## Expected result

Twitter loaded properly with 3rd party cookies blocked

## Issue reproduces how often 

Easy on my end.

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? NDA

## Device details
   - Install type (ARM, x86): NDA
   - Device (Phone, Tablet, Phablet): Redmi Note 5
   - Android version: 9.0
   
## Brave version

V.1.5.131

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  Yes. 3rd party cookies blocker disabled
- Does the issue resolve itself when disabling Brave Rewards? NDA
- Is the issue reproducible on the latest version of Chrome?  NDA

### Additional information

cc @SergeyZhukovsky @srirambv @samartnik

**Comment by samartnik** [comment]
Issue related to all OSes. To reproduce ob desktop just set allow cookies for twitter first, then set cross-site cookies blocked.

**Comment by bridiver** [comment]
The default block 3rd-party cookies setting allows subdomains, but the site setting does not. The site settings should match the default setting and a PR will be ready soon

**Comment by kjozwiak** [comment]
Removed the `OS/Android` label as this still seems broken on `Android` as per https://github.com/brave/brave-core/pull/5318#issuecomment-619679544, https://github.com/brave/brave-core/pull/5318#issuecomment-619711110 and https://github.com/brave/brave-core/pull/5318#issuecomment-619899524.

@jumde is taking a look on why it's still reproducible on Android and will create a follow up issue.

**Comment by btlechowski** [comment]
We need a new build for this one

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Ubuntu 18.04 LTS

Reproduced the issue on 1.7.98
![image](https://user-images.githubusercontent.com/34715963/80560667-22f02880-89e2-11ea-9cd4-8576fdec6b37.png)

Verified fixed after upgrade to 1.8.86
![image](https://user-images.githubusercontent.com/34715963/80560715-55018a80-89e2-11ea-9b51-f1d5a8c15e9d.png)

Also verified on clean profile
