### ISSUE TITLE
Allow user to turn off location access globally in Setting

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#934]
Carried over from https://github.com/brave/browser-laptop/issues/9033

Basically, allow a user to completely disable the location access feature of the browser (they shouldn't get prompted for it anymore)

Related https://github.com/brave/brave-browser/issues/751, https://github.com/brave/brave-browser/issues/937

**Comment by tomlowenthal** [comment]
This is an option in the location portion of site-specific settings at `chrome://settings/content/location`.
