### ISSUE TITLE
[Webcompat] Broken login for https://www.nintendo.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9347]
## Description 
Logging into `https://www.nintendo.com/` Fails

## Steps to Reproduce

   1. Open `https://www.nintendo.com/` 
   2. Click on `Login` (Top RIght), will open a another page.
   3. Main site will not show login in top right. 

## Actual result:
**No login at top right:**

![nintendo-error](https://user-images.githubusercontent.com/1659004/79851686-c311e480-8419-11ea-8ead-95fb6e974fd4.png)

## Expected result:
**My login at top right:**
![nintendo-ok](https://user-images.githubusercontent.com/1659004/79851700-c7d69880-8419-11ea-9d61-e894a44ce772.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes

## Miscellaneous Information:
`Allow all Cookies` is needed, looks like cookies for `nintendo.net` are being rejected

**Comment by rebron** [comment]
@ryanbr ok to close this one out? It looks like the login button on the homepage and login page are working now.
![Screen Shot 2021-05-18 at 10 41 51 AM](https://user-images.githubusercontent.com/5951041/118698810-b18a4000-b7c5-11eb-9ac2-bda8f36703f3.png)

**Comment by ryanbr** [comment]
Looks good now, not seeing the same issues. Thanks for the heads up @rebron
