### ISSUE TITLE
Ad Conversions on staging server fail due to 301 response code 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9352]
On staging pretty much all ads with conversions are converted using `https://travala.com/booking?check_in=*` link. The server responds with 301 code and conversion is never triggered

IMPORTANT: This issue is reproducible on Brave 1.5.111 and conversions on staging were working on it https://github.com/brave/brave-browser/issues/6536

## Steps to Reproduce

   1. Connect to us
   2. See an ad
   3. Check if the ad shown can be converted with `https://travala.com/booking?check_in=*`
   4. Convert the ad using `https://travala.com/booking?check_in=*`

## Actual result:

Ad is not converted due to 301 response code from the server
![image](https://user-images.githubusercontent.com/34715963/79871263-647e4380-83e4-11ea-94f8-2e351848dd16.png)
The page is redirected to `https://www.travala.coom/booking?check_in=*`
We don't handle redirects: https://github.com/brave/brave-browser/issues/8663

## Expected result:
Ads are converted on staging

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.5.111 Chromium: 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Ubuntu 18.04 LTS

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}

Brave | 1.9.30 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}

cc @brave/legacy_qa @rebron @jsecretan @tmancey

**Comment by tmancey** [comment]
@btlechowski For ad conversions, the URL pattern must match the visited page and where that can be differences the patter must contain wildcards

**Comment by btlechowski** [comment]
@tmancey on staging catalog conversion patterns will not work, because the page started to redirect.
catalog:
`"urlPattern":"https://travala.com/booking?check_in=*"`
using this pattern will not work, because the page redirects to a different page `"urlPattern":"https://www.travala.com/booking?check_in=*"`.
Therefor it is impossible to convert ads on staging.

Were you able to convert ads on staging US catalog?

**Comment by btlechowski** [comment]
@tmancey has updated catalog with new `urlPattern` and ad conversions started to work on staging
New `urlPattern` is `https://www.travala.com/booking?check_in=*`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Ubuntu 18.04 LTS

The ad was converted using `https://www.travala.com/booking?check_in=*` pattern

```
[2991:1:0505/191230.522112:INFO:ad_conversions.cc(131)] Ad conversion for c7f96341-726f-4e5d-9494-5686db89664b creative set id for postview
[2991:1:0505/191230.527352:INFO:ad_conversions.cc(300)] Saving ad conversions state
[2991:1:0505/191230.527534:INFO:ad_conversions.cc(289)] Started ad conversion timer for creative_instance_id 7e798d96-3ab9-4469-862d-f04d3d8b9506 with creative set id c7f96341-726f-4e5d-9494-5686db89664b which will trigger on 2020-05-05 17:22:26.000 UTC
```
