### ISSUE TITLE
Background images and sponsored images settings are Not hidden in brave://settings/newTab for SR profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9353]
## Description 

Background images and sponsored images settings are Not hidden in brave://settings/newTab for SR profile   

## Steps to Reproduce

   1. Launch Browser with clean profile with `promoCode`
   2. After SR is ready, load settings page
   3. Change to `Brave default images` and check background images and sponsored images settings are hidden

## Actual result:

Background images and sponsored images settings are Not hidden in brave://settings/newTab for SR profile   

## Expected result:
Background images and sponsored images settings should be hidden in brave://settings/newTab for SR profile   

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @simonhong

**Comment by simonhong** [comment]
Currently, it's hidden only for newly opened settings page.

**Comment by simonhong** [comment]
loadTimeData is not refreshed for reloading..

**Comment by LaurenWags** [comment]
@simonhong or @GeetaSarvadnya  to confirm, the `promoCode` needs to be for a super referral, not a normal promo code, correct?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Yup, that's correct.

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.82 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5311
- Verified that `Background images` and `Sponsored images` settings are hidden from `brave://settings/newTab` when Super Referral profile is launched.
![image](https://user-images.githubusercontent.com/38657976/83647766-e3b18a80-a5d2-11ea-872a-6bcd02921216.png)
- Verified that `Background images` and `Sponsored images` settings are hidden from `Dashboard settings` in NTP when the Super Referral profile is launched.
- Verified that SR images are shown in all the tabs when SR profile is launched and `Rush Gaming` SR option is selected in Theme
- Verified that when `Brave default images` radio button is selected in `Theme`,  the `Background images` and `Sponsored images` settings should be shown in both `brave://settings/newTab` and `Dashboard` settings
- Verified that normal bg images are shown in NTP's when `Brave default images` option is selected
- Verified Sponsored images are shown in every 4th NTP
