### ISSUE TITLE
Disable `Sponsored images` in brave://settings/newTab will not disable `Sponsored images` settings  in NTP dashboard

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9354]
## Description 

Disable `Sponsored images` in brave://settings/newTab will not disable `Sponsored images` settings  in NTP dashboard

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

Disable `Sponsored images` in brave://settings/newTab will not disable `Sponsored images` settings  in NTP dashboard

## Expected result:

Disable `Sponsored images` in brave://settings/newTab should disable `Sponsored images`settings in NTP dashboard

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.9.36 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @cezaraugusto

**Comment by simonhong** [comment]
@cezaraugusto I think using `toggleBrandedBackgroundOption_()` seems not working as expected.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from https://github.com/brave/brave-core/pull/5310#issuecomment-622331329
