### ISSUE TITLE
Restore deleted sites

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#936]
User can delete sites and recover them in the panel. In this issue we will implement button to restore all publishers, that will be shown in see all sites for auto contribute.

Button text: `Restore <X> manually excluded sites`

**Comment by NejcZdovc** [comment]
blocked on https://github.com/brave/brave-browser/issues/967

**Comment by jenn-rhim** [comment]
Button text should be 'Restore All Excluded Sites': no need to mention 'manually' as we don't allow auto-excluded sites to be restored nor has the user been exposed to the notion of 'auto-exclusion'. Hence unnecessary cognitive noise. 

If we could, adding this in front of the button would be nice:
Total Excluded Sites:  xx

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified excluded sites can be restored back by clicking on `Restore all` button
