### ISSUE TITLE
Allow user to turn off web notifications globally in Setting

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#937]
Carried over from https://github.com/brave/browser-laptop/issues/13624
> This is for parity with other browsers:
> http://www.thewindowsclub.com/disable-web-notifications-chrome-firefox-edge

**Comment by daviddahl** [comment]
Related to this, with no allowed origins in the notifications settings, I still receive notifications from some  domains. I do not see an issue like that here. Is that a known issue? Otherwise I will file one. This global disable feature is needed.

**Comment by daviddahl** [comment]
Actually, Now that I understand the *label* in both chrome and brave, this seems as though it is implemented and this issue should be closed, no?

![image](https://user-images.githubusercontent.com/23880/63204964-a1cb4e00-c06b-11e9-865d-c92f2555064f.png)
