### ISSUE TITLE
Newly updated Brave freezes after launch - Windows 10

### ISSUE THREAD

**Issue by onmyouji** [brave/brave-browser#9372]
## Description 

Few hours ago Brave just released new update on release channel. Got the notification on Help-About menu, so I relaunch to proceed with the update. After that I'm not able to use the browser anymore.

Every time I open the browser, it just freezes there with URL bar and blank page. I can't click anything and Windows 10 Task Manager shows high CPU usage from Brave Browser.

The browser was working just fine before the update. I’ve tried uninstalling and reinstalling (without deleting my browsing data), tried using the --disable-brave-sync and --disable-extensions flag, but it doesn’t solve the problem. I know deleting my user data will probably fix this, but I don't want to lose my extension, history, etc.

I'm running Windows 10 Home 64-bit 1809 (Build 17763.1098) 

Link to other user with similar problem:
https://community.brave.com/t/newly-updated-brave-1-7-98-chromium-81-0-4044-113-unresponsive-for-3-min-after-launch/120351

## Brave version (brave://version info)

I can't open brave://version since the browser is basically unusable and doesn't respond to any input, but I believe the latest release channel is v1.7.98

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
I can't test it because the browser freezes and doesn't respond to any input.
- Does the issue resolve itself when disabling Brave Rewards? 
I can't test it because the browser freezes and doesn't respond to any input.
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
@onmyouji Can you take a screenshot of your task manager and post here? Wondering if it's a specific page that's causing this or just on startup?

**Comment by onmyouji** [comment]
![Image 1](https://user-images.githubusercontent.com/8424198/79944806-a962b280-8496-11ea-8666-83fc0cf11e73.png)


![Image 2](https://user-images.githubusercontent.com/8424198/79944818-b089c080-8496-11ea-9ca6-091b17ef158e.png)

**Comment by bsclifton** [comment]
Thanks for the quick response @onmyouji - how about if you open the browser's task manager?

It's under the hamburger menu (top right, 3 lines) under the area "More Tools" => "Task Manager"

This should help us determine where in Brave is taking all the CPU

**Comment by onmyouji** [comment]
Can't open the menu, it just freezes.

Is there any way to launch Brave without loading Brave Rewards? Something like --disable-brave-sync ?

**Comment by bsclifton** [comment]
@onmyouji I don't think that's possible actually... but if it's freezing the UI thread, it's probably not rewards (I shared with @NejcZdovc just in case). Can you try launching Brave from the CLI using `--disable-gpu` to see if that makes a difference?

**Comment by onmyouji** [comment]
Okay, now I can at least open the hamburger menu, but after that it still freezes, I can't do anything. 

And it's not consistent. I tried to launch Brave a few times with --disable-gpu, sometimes I can open the hamburger menu, but most of the time I can't open it.

![Image 4](https://user-images.githubusercontent.com/8424198/79946946-28f28080-849b-11ea-9a0d-616fcd812310.png)

**Comment by onmyouji** [comment]
Another user with similar problem:

https://community.brave.com/t/brave-not-respoding-after-pc-restart/120375

**Comment by onmyouji** [comment]
Report from another user:

https://community.brave.com/t/browser-does-not-open-does-not-do-anything/120436

**Comment by pawadski** [comment]
Having exactly the same problem in latest version, no issues before the update.

**Comment by RiskyFire** [comment]
I'm having this same problem too.

> Brave Browser has been working great until today.
> [Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)]
> Windows 10
> 
> Now when I open the browser, the initial page opens but it hangs for about 30 seconds. I can see the address bar and my bookmarks toolbar but I can’t type or select anything. The sponsored background image doesn’t load either. Then after 30 seconds it loads, background now shows and it all works normally.
> 
> From this point onwards it works fine, just very slow on initial opening.
> 
> Any ideas ?

https://community.brave.com/t/brave-browser-slow-on-initial-opening/120505

**Comment by ViSTiE** [comment]
I'm also facing this problem! My Brave browser (v1.7.98; Chromium: 81.0.4044.113 (Official Build) (64-bit)) freezes for over 20 seconds after starting it. It hasn't done this before (as far as I remember).

I already closed all my open tabs and deleted the browser's data and cache, but every time I close and reopen Brave, it doesn't respond for at least 20 seconds.

**Comment by talisto** [comment]
> I'm also facing this problem! My Brave browser (v1.7.98; Chromium: 81.0.4044.113 (Official Build) (64-bit)) freezes for over 20 seconds after starting it. It hasn't done this before (as far as I remember).

I'm having the same issue on MacOS 10.14.6, using Brave v1.7.98, except the freeze lasts about 90 seconds.  It recovers and works fine after the initial lag time.  I've disabled all my extensions and have cleared my cache.

**Comment by bsclifton** [comment]
@ViSTiE does Brave respond after the 20 seconds of freezing?

@NejcZdovc can this be hang be when fetching the publisher list?

**Comment by jsecretan** [comment]
@onmyouji would you be available for a screen share some time soon.  We might be able to diagnose if we could interactively look at some of the standard profile files.

**Comment by NejcZdovc** [comment]
@onmyouji @pawadski @RiskyFire @ViSTiE @talisto do you have rewards on?

**Comment by pawadski** [comment]
@NejcZdovc I don't think so. I haven't started the rewards function. I also have the new music library addition disabled, along with sponsored images.

**Comment by ViSTiE** [comment]
@bsclifton Yes, it responds after 'bout 20 seconds of freezing. 

@NejcZdovc No, Rewards are off.

**Comment by NejcZdovc** [comment]
@ViSTiE and this is every time that you start a browser you get 20s freeze and then is ok?

**Comment by ViSTiE** [comment]
@NejcZdovc Exactly. It freezes for like 20-25 seconds after starting it, and then it works normally/ as usual.

**Comment by iefremov** [comment]
Hey @onmyouji @ViSTiE and other people - do you mind sharing minidumps of hanging processes with us? Minidump can be captured using ProcDump tool, see https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

we would need something like this `C:\>procdump -h brave.exe bravehung.dmp`

**Comment by pawadski** [comment]
@iefremov Sure, though it sounds like I will need different command:

`[11:48:39] Multiple processes match the specified name.`

**Comment by iefremov** [comment]
yeah, sorrty
`C:\>procdump -h <PID> bravehung.dmp`

we need do determine PID of the main process - e.g. via process explorer (you would  need to enable advanced view, and add "Process ID" and "Command line" columns by right clicking on any column). The main process is the one launched without any command-line arguments

**Comment by pawadski** [comment]
@iefremov Do I need to terminate procdump manually? I've waited a couple seconds after Brave unfroze and hit CTRL+C but received `[11:59:32] Dump count not reached.`

**Comment by iefremov** [comment]
well actually it should have been triggered by the fact of hanging...
So we can manually trigger the crashdump by just `procdump <PID>` when you see it the browser frozen

**Comment by pawadski** [comment]
It does not hang in the sense that Windows tells me that the program is not responding. It feels like Brave is trying to do something, and the CPU usage percentage fluctuates in Task Manager, but the window does not open anything and is not responsive to input. Tabs that were previously open are open again but do not load (the animated loading icon where the tab icon is is not moving as well).

**Comment by onmyouji** [comment]
I got the same thing, dump count not reached. Is there other parameter besides -h that we can try?

**Comment by iefremov** [comment]
@onmyouji 
1) it is possible just to manually trigger the dump by `procdump <PID>` at any time
2) E.g. `procdump -c 70 -s 2 -n 1 PID` - write the dump when the process CPU consumption exceeds 70% for two seconds

**Comment by pawadski** [comment]
@iefremov With your latest command, here are 4 dmp files while it's not responding. Does quantity matter?

[Procdump.zip](https://github.com/brave/brave-browser/files/4528276/Procdump.zip)

**Comment by ViSTiE** [comment]
I've a problem creating the dumb. I executed procdump64.exe with Administrator rights, but cannot create the dump:
![procdump](https://user-images.githubusercontent.com/25864484/80203936-4143d600-8628-11ea-99e5-86490b74ad44.JPG)

**Comment by onmyouji** [comment]
@iefremov ok, it works now.

[brave1.zip](https://github.com/brave/brave-browser/files/4528331/brave1.zip)

**Comment by onmyouji** [comment]
> I've a problem creating the dumb. I executed procdump64.exe with Administrator rights, but cannot create the dump:
> ![procdump](https://user-images.githubusercontent.com/25864484/80203936-4143d600-8628-11ea-99e5-86490b74ad44.JPG)

Lower the CPU threshold based on your system. For example, on my system Brave takes about 15% CPU when it freezes, so I use -c 10 instead of -c 70

**Comment by iefremov** [comment]
many thanks @onmyouji @pawadski

**Comment by ViSTiE** [comment]
Now, it worked :) Created several dumps:
[procdump64 dumps.zip](https://github.com/brave/brave-browser/files/4528408/procdump64.dumps.zip)

**Comment by RiskyFire** [comment]
> do you have rewards on?

I have tried with rewards off, I thought the sponsored screen could be the problem. But it still shows and the delay is the same.

**Comment by arashsayadi** [comment]
I'm having similar issues with the Brave browser on a Win10 x64.  

The browser eats up too many resources, runs out of memory and slows all processes on the computer.  The issue just started with the latest update.  

I don't have rewards on and the only way I can get a semblance of control for the computer is to restart it. 

I'm switching to another browser until this is resolved.

**Comment by bsclifton** [comment]
Thanks for the reports and the hang dumps, folks 😄 I've created a new tracking issue here:
https://github.com/brave/brave-browser/issues/9481

Please subscribe there for updates. Going to try to link all known reports of this and see if that helps characterize the problem

**Comment by Scott-5Litre** [comment]
I'm experiencing this very same issue. I'm also on Win 10 (64bit). has there been a resolve yet? I have to keep a brave tab loaded at all times otherwise it freezes up solid for appx 30 seconds. then it loads just as others have mentioned.

**Comment by bsclifton** [comment]
@Scott-5Litre no fix yet - we're troubleshooting in https://github.com/brave/brave-browser/issues/9481 in case you wanted to subscribe to that issue or join the discussion
