### ISSUE TITLE
Unable to display preview pictures on this site

### ISSUE THREAD

**Issue by GitGuuuud** [brave/brave-browser#9373]
## Description 
After installed latest release, the preview pictures unable to show. You can see the preview pictures change from "broken image icon", then gone/ hide by brave

## Steps to Reproduce
   1. Load the site

## Actual result:
https://i.imgur.com/2MFWe1Y.jpg

## Expected result:
https://i.imgur.com/gNG2VVU.jpg

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
v1.7.92

## Version/Channel Information:

- Can you reproduce this issue with the current release?
yes
- Can you reproduce this issue with the beta channel?
yes
- Can you reproduce this issue with the dev channel?
yes
- Can you reproduce this issue with the nightly channel?
yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
I loaded up https://tieba.baidu.com/f?kw=steam&ie=utf-8, as shown in your picture

Many of the thumbnails load 👍 Those which don't seem to be http (not https). We are trying to upgrade mixed content, so it will try to load those over https or it ends up not loading them

cc: @fmarier @diracdeltas should insecure resources still be loading? I tried with shields down and they are not loading

**Comment by fmarier** [comment]
It looks like it's coming from the following chrome flag we enabled in brave/brave-core#4537:
![Screenshot from 2020-05-05 14-23-40](https://user-images.githubusercontent.com/167821/81117500-0d946600-8edc-11ea-9fdc-bba4ee079341.png)

If I go into the site settings and enable insecure content for this site, the images come back:
![Screenshot from 2020-05-05 14-22-22](https://user-images.githubusercontent.com/167821/81117459-f81f3c00-8edb-11ea-970e-1ee0bd0d6724.png)

**Comment by bsclifton** [comment]
Awesome, thanks @fmarier 😄 

@GitGuuuud I would recommend the above- changing `Insecure content` specific site setting to `Allow` for that site to see the content
