### ISSUE TITLE
The link URL preview box is is white with dark theme applied

### ISSUE THREAD

**Issue by Mhowser** [brave/brave-browser#9374]
## Description 

the URL preview box that appears does not match the browser's dark theme

## Steps to Reproduce

   1. open the browser - set the theme to dark
   2. hover over a clickable link
   3. look at the bottom left corner of the browser

## Actual result:

![image](https://user-images.githubusercontent.com/24195572/79944758-3703bb00-8421-11ea-9164-2680ea287892.png)

## Expected result:
Same thing but it matches the dark theme

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave	1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
Revision	e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS	Linux
## Version/Channel Information:

Release channel
- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Not tested
- Can you reproduce this issue with the dev channel?
Not tested
- Can you reproduce this issue with the nightly channel?
Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome? 
Not tested

**Comment by bsclifton** [comment]
I'm able to reproduce, but only if I pick `Use GTK+`. @Mhowser if you go under brave://settings/appearance, can you please try switching to Classic (if that's available)?

**Comment by Mhowser** [comment]
This bug is fixed as of version 1.8.86.
