### ISSUE TITLE
Improve publisher list insert time/memory/cpu

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9376]
We have a big performance problem on iOS when we are inserting publisher list into db (we need to insert over 600k publishers). We need to review code and fix memory and CPU problems for this process.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64` using the following build:

```
Brave | 1.8.84 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)
```

* Went through the cases outlined via https://github.com/brave/brave-core/pull/5301#issue-406702052 and https://github.com/brave/brave-core/pull/5301#issuecomment-618020352.

Verified that the `Publisher List` was being downloaded without any issues once `brave://rewards` was enabled:

```
[ RESPONSE - OnDownload ]
> time: 1588029200
> result: Success
> http code: 200
> response: Publisher list
> headers accept-ranges: bytes
> headers access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
> headers access-control-allow-methods: GET
> headers access-control-allow-origin: https://rewards.bravesoftware.com
> headers access-control-request-method: GET
> headers age: 564
> headers cache-control: max-age=3600, public
> headers content-encoding: gzip
> headers content-length: 19006799
> headers content-type: application/json; charset=utf-8
> headers date: Mon, 27 Apr 2020 22:57:51 GMT
> headers etag: W/"4b8454a1c57a8bdf4f924f70507b812c"
> headers server: Cowboy
> headers status: 200
> headers vary: Accept-Encoding
> headers via: 1.1 varnish
> headers x-cache: HIT
> headers x-cache-hits: 0
> headers x-frame-options: deny
> headers x-request-id: 79bb2085-eaf8-4293-adc2-6cbbf83afd2c
> headers x-runtime: 2.669314
> headers x-served-by: cache-yyz4545-YYZ
[ END RESPONSE ]
```

Ensured that `brave.com`, `chess.com` and `kjozwiak.github.com` appeared as `verified` and displayed the custom banners without any issues.

**`brave.com example:`**

<img width="439" alt="Screen Shot 2020-04-27 at 7 14 08 PM" src="https://user-images.githubusercontent.com/2602313/80429966-4e2c2800-88bb-11ea-8495-e9d2fc9d3664.png">

<img width="1216" alt="Screen Shot 2020-04-27 at 7 14 15 PM" src="https://user-images.githubusercontent.com/2602313/80429968-508e8200-88bb-11ea-9251-a4419cb231ac.png">

**`chess.com example:`**

<img width="420" alt="Screen Shot 2020-04-27 at 7 14 45 PM" src="https://user-images.githubusercontent.com/2602313/80430005-62702500-88bb-11ea-8fc1-a762947cb5e9.png">

<img width="1236" alt="Screen Shot 2020-04-27 at 7 14 52 PM" src="https://user-images.githubusercontent.com/2602313/80430011-656b1580-88bb-11ea-8777-1162e954e09d.png">

**`kjozwiak.github.io example:`**

<img width="409" alt="Screen Shot 2020-04-27 at 7 15 32 PM" src="https://user-images.githubusercontent.com/2602313/80430049-7fa4f380-88bb-11ea-9adf-57258b1eb744.png">

<img width="1227" alt="Screen Shot 2020-04-27 at 7 15 42 PM" src="https://user-images.githubusercontent.com/2602313/80430057-83387a80-88bb-11ea-8821-917151ca4a1f.png">

Also checked and ensured that the `server_publisher_info` database was populated as per the following:

<img width="553" alt="Screen Shot 2020-04-27 at 7 22 16 PM" src="https://user-images.githubusercontent.com/2602313/80430376-6ea8b200-88bc-11ea-9145-02211d02d64e.png">

Ensured that `publisher_info` was populated whenever you visited a website:

<img width="804" alt="Screen Shot 2020-04-27 at 7 22 59 PM" src="https://user-images.githubusercontent.com/2602313/80430403-85e79f80-88bc-11ea-8469-d95f3c442f04.png">
