### ISSUE TITLE
Remove "What's New" in developer console

### ISSUE THREAD

**Issue by xanzhu** [brave/brave-browser#9378]
## Description 
Remove "What's New" tab in the developer console as its showing the latest updates for chrome.

## Steps to Reproduce
Open developer console

## Actual result:

![Screen Shot 2020-04-22 at 18 56 17](https://user-images.githubusercontent.com/34955679/79951035-1cd2e700-84cc-11ea-9db3-bcaa35cf0bb4.png)

## Expected result:
When opening developer console or simply inspecting something not to see this tab. 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:

Applies to all channels. 

## Other Additional Information:
This could be used in the future for a custom tab based on Braves Changes/Features, but until then remove it!

**Comment by bsclifton** [comment]
Thanks for the suggestion 😄 - this has came up before. There is some useful information in there for users when new developer tool features are released

Closing as a `wontfix`. But cc: @rebron in case we did want to tweak this in any way to have Brave specific content
