### ISSUE TITLE
Favorite disappear after last update

### ISSUE THREAD

**Issue by etiennebonnafoux** [brave/brave-browser#9383]
Hello,

## Description 
After updating to Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit) (I don't the previous version I had), I lost all my favorites I saved.

## Steps to Reproduce

   1.  Have some favorite
   2.  Update to Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

## Brave version (brave://version info)
Now Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

## Miscellaneous Information:
It didn't update a natural way, it was written "Brave can't update, please download it again." (translate badly from french).

Just do you if I could still find them somwhere? Thank you for your help!

**Comment by bsclifton** [comment]
Hi @etiennebonnafoux - sorry for the delayed response

Can you check to see if you have multiple profiles? If you check the top right, you may see something like this:
![Screen Shot 2020-05-05 at 2 00 40 PM](https://user-images.githubusercontent.com/4733304/81115604-d5d7ef00-8ed8-11ea-99da-52b51e061b1b.png)

If a new profile is created on accident, it can definitely seem like everything was lost 😄 Please let us know!

**Comment by etiennebonnafoux** [comment]
Hello,

It seem that I have only "Profile 1" and "Invité/Guest" which are the default profile. 

![Capture](https://user-images.githubusercontent.com/23340020/81160147-0461d280-8f8a-11ea-8e1b-b98b0f7e591c.PNG)

But I am not sur that I created a profile on the previous version. So maybe the new version just create a blank profile.
Thank you for your help.

**Comment by rebron** [comment]
Closing per last comment https://github.com/brave/brave-browser/issues/9383#issuecomment-624532888.

@etiennebonnafoux Sounds like it was a new profile that was created and it seemed like you lost your bookmarks?

**Comment by etiennebonnafoux** [comment]
Yes, you are right. But now the question is how can we avoid that the user profile are delete when updating.
