### ISSUE TITLE
Gap behind card stack 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9385]
## Description 

Gap behind card stack 

## Actual result:

No hover
![image](https://user-images.githubusercontent.com/17010094/79974817-91e7f180-84b7-11ea-85c9-dc1aba86e756.png)
On card hover
![image](https://user-images.githubusercontent.com/17010094/79974977-d3789c80-84b7-11ea-8767-01e1ea0f560c.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/79974831-990eff80-84b7-11ea-9c3b-ab13ba6d4813.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.9.37 Chromium: 81.0.4044.113 (Official Build) nightly (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

## Miscellaneous Information:

Related to #9249
cc: @jamesmudgett @karenkliu @ryanml

**Comment by rebron** [comment]
cc: @karenkliu and @ryanml note priority on this one.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.103 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | macOS Version 10.15.5 (Build 19F101)

- Verified no gap behind the cards stack
   <img width=300 src="https://user-images.githubusercontent.com/17010094/88659778-3ac76d80-d0f3-11ea-80ae-7285493e8b22.png">

------

Verification passed on 

Brave | 1.12.103 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Windows 10 OS Version 1809 (Build 17763.1339)

- Verified no gap behind the cards stack
   <img width=300 src="https://user-images.githubusercontent.com/17010094/88659848-5763a580-d0f3-11ea-8a3b-3218818d983c.png">

-------

Verification passed on 

Verification passed on 

Brave | 1.12.103 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Linux

- Verified no gap behind card stack
   <img width=300 src="https://user-images.githubusercontent.com/17010094/88660124-c80ac200-d0f3-11ea-9e09-c98108477865.png">
