### ISSUE TITLE
[Android] Decrease ANR rate 

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#9388]
## Description 
It is required to decrease ANR rate.
Some of ANR, maybe the most of them are fixed by https://github.com/brave/brave-core/pull/5087 . 

## Steps to reproduce 

   1. Run debug build
   2. Go through messages like `StrictMode policy violation` in device monitor

Points to check for QA team:
1. Install referrers
2. Default browser settings behavior

**Comment by AlexeyBarabash** [comment]
Marked QA/yes because related PR touches install referrers and default browser behavior, so it needs to be re-tested.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk 1.8.93`
- Verified that all the default settings are working as expected
- Verified toggle default settings are working as expected
