### ISSUE TITLE
clock widget menu goes off the screen on certain window widths

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9389]
## Description 

On certain window widths (approx 950-1140px, unsure of exact widths), the clock widget menu goes off screen when opened.

## Steps to Reproduce

   1. Set window width to somewhere within approximately 950-1140 px width.
   2. Click on clock widget menu.

## Actual result:

~950px:
<img width="975" alt="Screen Shot 2020-04-22 at 9 59 06 AM" src="https://user-images.githubusercontent.com/28145373/79992235-37cc3980-8481-11ea-9a4b-2a621f71a0ea.png">

~1140px:
<img width="1164" alt="Screen Shot 2020-04-22 at 9 58 22 AM" src="https://user-images.githubusercontent.com/28145373/79992217-33a01c00-8481-11ea-9343-f906f0429195.png">

## Expected result:
Widget menu should not be going off screen. 
This is 1.8.x on other window widths:
<img width="1349" alt="Screen Shot 2020-04-22 at 10 10 41 AM" src="https://user-images.githubusercontent.com/28145373/79992482-8a0d5a80-8481-11ea-9986-24cff655bd6c.png">

<img width="769" alt="Screen Shot 2020-04-22 at 10 11 15 AM" src="https://user-images.githubusercontent.com/28145373/79992538-9e515780-8481-11ea-9693-51b85e3d2e59.png">

On 1.7.x the widget is on the other side of the clock:
<img width="1079" alt="Screen Shot 2020-04-22 at 10 03 42 AM" src="https://user-images.githubusercontent.com/28145373/79992324-55010800-8481-11ea-8fe3-7b7e99e00bc8.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce on 1.7.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by LaurenWags** [comment]
cc @bsclifton @cezaraugusto - not sure if related to refactor done with https://github.com/brave/brave-browser/issues/2971?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Reproduced the issue on 1.9.x
![image](https://user-images.githubusercontent.com/34715963/83102239-517e2380-a0b4-11ea-88ab-d12f350e4a31.png)

Verified test plan from https://github.com/brave/brave-core/pull/5319 and the description
![image](https://user-images.githubusercontent.com/34715963/83102304-72467900-a0b4-11ea-9fe0-44e1270420d3.png)

Also verified other resolutions for regressions.
