### ISSUE TITLE
rewards & binance widget menus go off screen on certain window widths

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9390]
## Description 

Similar to https://github.com/brave/brave-browser/issues/9389

On certain window widths, the widget menu for Rewards and Binance widgets goes off screen. Seems to happen on approximately 950-1140px window width as #9389 does.

## Steps to Reproduce

   1. Set window width to somewhere within approx 950-1140px width
   2. Open Rewards or Binance widget menu

## Actual result:

Off screen:
<img width="1153" alt="Screen Shot 2020-04-22 at 11 29 18 AM" src="https://user-images.githubusercontent.com/28145373/80001699-acf13c00-848c-11ea-838f-98619ffd8fd8.png">

## Expected result:
widget menu should not be off screen, this is how it behaves on other window widths:
<img width="1410" alt="Screen Shot 2020-04-22 at 11 37 28 AM" src="https://user-images.githubusercontent.com/28145373/80002506-bcbd5000-848d-11ea-9408-0259ac2b6b3a.png">

<img width="852" alt="Screen Shot 2020-04-22 at 11 38 00 AM" src="https://user-images.githubusercontent.com/28145373/80002523-bf1faa00-848d-11ea-949d-186bea870628.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, not on 1.7.x
- Can you reproduce this issue with the beta channel? yes (1.8.x)
- Can you reproduce this issue with the dev channel? yes (1.9.x)
- Can you reproduce this issue with the nightly channel? yes (1.10.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa @bsclifton

**Comment by LaurenWags** [comment]
Possibly related to https://github.com/brave/brave-browser/issues/8883

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Reproduced the issue on 1.9.x
![image](https://user-images.githubusercontent.com/34715963/83102522-fbf64680-a0b4-11ea-8cfe-273ea0ab1ce1.png)


Verified test plan from https://github.com/brave/brave-core/pull/5319 and the description
![image](https://user-images.githubusercontent.com/34715963/83102621-3233c600-a0b5-11ea-9376-9a45f955c6bb.png)
![image](https://user-images.githubusercontent.com/34715963/83102635-3b249780-a0b5-11ea-8041-c070f8f66eef.png)


Also verified other resolutions for regressions.
