### ISSUE TITLE
[Android] do not implement custom home page on x86 Android devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9394]
## Description 
Per discussion with @anthonypkeane and @deeppandya - no custom home page on x86 Android devices.

## Steps to reproduce 

   1. Confirm no custom home page on x86 Android devices. 

cc @srirambv

**Comment by deeppandya** [comment]
@LaurenWags can we close this issue ? i think it's an old issue.

**Comment by LaurenWags** [comment]
@deeppandya yeah, probably. This should have been closed with whatever build CHP went out with. Guess it got missed.
