### ISSUE TITLE
T2tea.com address field on checkout form is broken with Shields down

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9396]
## Description 

Address field auto-suggest list doesn't show up when typing in a shipping address on https://www.t2tea.com/en/us/shipping

## Steps to Reproduce

   1. Go to https://www.t2tea.com/
   2. Select some products, add to cart, and go to checkout
   3. Go to shipping step https://www.t2tea.com/en/us/shipping and try to enter a shipping address
   4. See that no results show up; website won't let you proceed unless a valid address picked from results is entered

## Actual result:

![image](https://user-images.githubusercontent.com/2388823/80020435-e37b8680-848d-11ea-8ae0-476a620ed592.png)

## Expected result:
![image](https://user-images.githubusercontent.com/2388823/80020426-deb6d280-848d-11ea-834b-c4188cfe2b45.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Release Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
@karenkliu hey does `Allow all Cookies` in Shields help?

**Comment by karenkliu** [comment]
@ryanbr Yes it works if I select that!

**Comment by ryanbr** [comment]
@karenkliu fix being rolled out, in the next 48hrs. which will resolve this without needing to change Shield settings.

**Comment by karenkliu** [comment]
Awesome, thanks! Gotta support those Brave tea aficionados :laughing:
