### ISSUE TITLE
change Fingerprinting option wording on shields panel - follow up to 7949

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9399]
## Description 

Follow up to #7949 

Per https://github.com/brave/brave-browser/issues/7949#issuecomment-617945489 from @karenkliu, the wording for the fingerprinting options on the shields panel needs to be updated. The panel options should match those in brave://settings/shields.

## Steps to Reproduce

   1. Navigate to a site
   2. Open shields panel
   3. Expand fingerprinting options

## Actual result:

<img width="359" alt="Screen Shot 2020-04-22 at 3 05 09 PM" src="https://user-images.githubusercontent.com/28145373/80023159-2009ab00-84ab-11ea-8916-51a7da2a5d0c.png">

## Expected result:
should see these options
<img width="709" alt="Screen Shot 2020-04-22 at 3 04 39 PM" src="https://user-images.githubusercontent.com/28145373/80023180-26982280-84ab-11ea-86f5-1f24862c7597.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron as original issue was slated for 1.8.x, unsure if this needs to be in 1.8.x as well.

**Comment by rebron** [comment]
Closing. Fixed with https://github.com/brave/brave-browser/issues/9194
