### ISSUE TITLE
Crypto Widget title alignment is off

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9403]
## Description 
Widget titles aren't aligned when Binance is in the foreground

## Steps to Reproduce
   1. Put the Binance widget in the foreground on NTP

## Actual result:
Titles are not aligned
<img width="420" alt="Screen Shot 2020-04-22 at 2 24 37 PM" src="https://user-images.githubusercontent.com/8732757/80035644-37459a00-84a5-11ea-9d08-e013c4086a17.png">

## Expected result:
<img width="415" alt="Screen Shot 2020-04-22 at 2 07 13 PM" src="https://user-images.githubusercontent.com/8732757/80035658-3d3b7b00-84a5-11ea-97e6-679988b01909.png">

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Verified alignment issue looks good to match expected result above.
Brave | 1.10.9 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.5 (Build 19F62f)

<img width="647" alt="Screen Shot 2020-04-24 at 3 43 23 PM" src="https://user-images.githubusercontent.com/5951041/80263717-5c254300-8646-11ea-8629-dd95ab4184fb.png">

**Comment by rebron** [comment]
Verified alignment issue looks good to match expected result above.

Brave | 1.10.9 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1903 (Build 18362.720)

![alignment](https://user-images.githubusercontent.com/5951041/80263960-482e1100-8647-11ea-883c-8d8679d530e8.PNG)

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.8.84 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the test plan from the description

![image](https://user-images.githubusercontent.com/38657976/80369047-46fd1e00-88ab-11ea-95b7-d642007ba6a5.png)
