### ISSUE TITLE
[Feature Request] Develop a Github/Gitlab product where 'Report a Broken Site' automatically produces issue

### ISSUE THREAD

**Issue by NumDeP** [brave/brave-browser#9404]
Have you searched for similar issues? No. 
 
## Description 
The title pretty much speak for itself I think and I'm pretty sure you understand why I'm stating such a method. So I'll just skip to why it would be really nice for the team do so.

There are just so many web compatibility issues and literally for years I/we've had to put up with it. As users we don't really know whether you've received a 'Report a Broken Site' issue and what is being done about it, furthermore, it's really frustrating when the same site still has the same issue several months down the line.

Ad guard and I'm sure others have a dedicated section for issues like theses (obviously because they're product is more simple and specific) and I think these issue need to be pinned until they're fixed because I/we really can't have constant issues like this and I'm sorry to say (certainly not a harsh tone) but issues like these demand a p1 label with a separate category and a separate team.

## How the feature would work in my example:

   1. User finds imdb.com broken, user selects on 'Report a Broken Site'.
   2. The same box that appears to clarify issue has been sent has a small comment box attached where a user can either briefly comment on issue such as **Step to Reproduce** or just send without commenting.
   3. Issue automatically appears in Github/Gitlab as '**[RBS] https:// imdb.com/ #XXXX'**
   4. **## Description** & **## Steps to Reproduce** would be joined in these cases and will state what was included in the small comment box if a user commented. If not, the title from the issue is also pasted, if site shields was up or down and brave://version info like the typical stuff sent with Report a Broken Site currently.
 
## Miscellaneous Information:
I would have just left this issue but I remember having a conversation with a Tor developer a couple of years ago and I couldn't understand why they didn't bother implementing an ad block and he discussed it with me at length and I remember him saying 'Filter-based solutions in general can also introduce strange breakage and cause usability nightmares.' and thought, a few issues here and there would be okay. Fast forward a couple of years, not such much.

It's strange, like the 'would you rather' game, I'm questioning having put up with it for years now whether the preservation of ones privacy worth a constant annoyance where the browser in many cases is not productivity friendly.  

## Addition to the above statement
Rather than fixing these issues on a case by cases basis, has brave issued a plan not yet published to mitigate issues like web compatibility and shields config issues completely?

**Comment by bsclifton** [comment]
cc: @alexwykoff

**Comment by rebron** [comment]
@NumDeP Thanks for the feature suggestion. At this time, I don't think we'll be able to build something like this, the number of sites and issues would flood github. We do have a separate tool that helps us with broken sites.

**Comment by NumDeP** [comment]
What are we to do then in the mean time? Honestly, this is such a P*** take. I read a lengthy discussion about how not sending/selecting a 'Do Not Track' response is more privacy friendly and remember thinking in reference to the dialogue because I never thought about it, wow, look how finicky they are about something so little. However, having to switch to another browser because simple websites cause a problem with Brave is and has been a constant issue and something tells me the team knows that it will continue to be an issue for a long time.

I selected two notifications ads that showed and Brave with Shields On didn't work on either of them. One of them was the Lenovo site and I can't remember what the other was, It must have been a freelancing site where it asks you to confirm you're a real person after opening several tabs and after completing that it just becomes stuck and doesn't direct you again to the link you selected and you can't obviously go back.

I'm really starting to get terribly annoyed by all things crypto in Brave with the exception of giving BAT away to certain channels and creators because it seems crypto is the teams favourite part of Brave and I take a huge issue with that.

I'm not annoyed by the fact that you closed and won't bother with the feature I requested but the fact that you're aware of this and have been for a long time.
