### ISSUE TITLE
[Android] 1.7.x beta crashes on Settings->Privacy->Clear browsing data

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#9406]
## Description 
There is a crash

## Steps to reproduce 

   1. Go to Settings->Privacy->Clear browsing data

## Actual result 
browser crashes

## Expected result
no crash

## Issue reproduces how often 
always

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Resolved by uplift https://github.com/brave/brave-core/pull/5340

**Comment by srirambv** [comment]
Waiting on uplift of brave/brave-core#5340

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
- Verified clearing data from Privacy settings don't crash the browser
- Verified clearing data from history page don't crash the browser
- Verified clearing individual items don't crash the browser
---------
Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
- Verified clearing data from Privacy settings don't crash the browser
- Verified clearing data from history page don't crash the browser
- Verified clearing individual items don't crash the browser
