### ISSUE TITLE
Enforce licenses in third_party code added to brave-core

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#9408]
The `licenses.py` currently throws three `LicenseError` in `src/brave/` (and then [ignores them all](https://source.chromium.org/chromium/chromium/src/+/master:tools/licenses.py;l=670-672;drc=f4fa98d2aebf027fde33fdb2164966a87c728994?originalUrl=https:%2F%2Fcs.chromium.org%2F)):
- `brave/vendor/extension-whitelist`
- `brave/vendor/speedreader_rust_ffi`
- `brave/ui/webui/resources/fonts/third_party/crypto`

The first one is a known issue and I added the missing license in https://github.com/brave/extension-whitelist/pull/20 already but it was never updated in brave-core. The second was introduced in https://github.com/brave/brave-core/pull/4496 and the third in https://github.com/brave/brave-core/pull/5160. Only the last one is a true third-party component and needs to be fixed (tracked in #9407).

We should treat errors as fatal when they're triggered in `src/brave/`. Eventually, [all errors will be fatal](https://bugs.chromium.org/p/chromium/issues/detail?id=39240).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5333

Verified that following entries have a license and a working link:

`Brave background images`
![image](https://user-images.githubusercontent.com/34715963/82853997-7aad8100-9f07-11ea-9cd1-7bd6bac225d3.png)
`extension-whitelist`
![image](https://user-images.githubusercontent.com/34715963/82854119-c7915780-9f07-11ea-8ddb-70ee955a0a0b.png)


`speedreader-rust-ffi` has no entry in `brave://credits`. Logged  https://github.com/brave/brave-browser/issues/9939
