### ISSUE TITLE
Wallet summary grant

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#941]
When you a claim a grant, grant is not shown in the wallet summary

**Comment by NejcZdovc** [comment]
done in https://github.com/brave/brave-core/pull/241

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) (64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/46892553-20fd5d80-ce6e-11e8-995a-df0d6fad5cc4.png)
