### ISSUE TITLE
Multiple landed confirmations for the same ad view

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9412]
Found when testing: https://github.com/brave/brave-browser/issues/8634. 
New landed confirmation is created every time landing page is opened

IMPORTANT: This is a regression. This issue is not reproducible in 1.7.x

## Steps to Reproduce

1. Overwrite the catalog with Charles
Catalog: [one ad, no conversion.txt](https://github.com/brave/brave-browser/files/4520817/one.ad.no.conversion.txt)
2. Run Brave with command line: `/usr/bin/brave-browser-dev --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true`
3. Enable Rewards
4. Open `brave.com` and trigger an ad
5. Click on the ad
6. Wait for `landed` confirmation
7. Open `https://www.youtube.com/` in a new tab
8. Wait for `landed` confirmation

## Actual result:

Second `landed` confirmation is triggered for the same ad view

Log 
[multi_landed_log.txt](https://github.com/brave/brave-browser/files/4520856/multi_landed_log.txt)

## Expected result:
Only one `landed` confirmation is possible for the ad viewed

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproduced on

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Ubuntu 18.04 LTS

Not reproducible on

Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Ubuntu 18.04 LTS

cc @jsecretan @tmancey @brave/legacy_qa @rebron

**Comment by btlechowski** [comment]
It seems we had similar issue before https://github.com/brave/brave-browser/issues/7249 (Thanks @LaurenWags for providing the link)

**Comment by LaurenWags** [comment]
Reproduced with 

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

Used STR from description. Also confirmed this happens if I refresh the page from the issue noted by @btlechowski in https://github.com/brave/brave-browser/issues/9412#issuecomment-618576694

**Comment by tmancey** [comment]
Regression caused by https://github.com/brave/brave-browser/issues/8634

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5406
Verified test plan from the description. Verified getting only 1 `landed` confirmation.
Verified `Already sustained ad notification interaction for visited URL` is shown in the logs when attempt is made to land same URL again
[9412_1.txt](https://github.com/brave/brave-browser/files/4679469/9412_1.txt)

Verified test plan from https://github.com/brave/brave-browser/issues/8634#issuecomment-618218538
Verified that  `Already sustained ad notification interaction for visited URL` message is not shown in the logs when trying to convert the set again
Verified that creative set cannot exceed frequency capping for conversions:
```
[16180:1:0526/033938.035373:INFO:ads_impl.cc(1130)] creativeSetId de5a82e1-17d6-47e0-a368-17f8f56dfeb3 has exceeded the frequency capping for conversions
```
