### ISSUE TITLE
Changelog URL is incorrect

### ISSUE THREAD

**Issue by leonschmidlin** [brave/brave-browser#9415]
## Description 

The Brave Software Update prompt shows the old changelog URL "https://github.com/brave/brave-browser/blob/master/CHANGELOG.md" instead of the new "CHANGELOG_DESKTOP.md" or "CHANGELOG_ANDROID.md".

## Steps to Reproduce
Get a Brave Software update prompt on update and try to open the link, "CHANGELOG.md" does not exist.
Try to open the URL of changelog_url in brave-core/script/lib/omaha.py.

## Actual result:
<img width="987" alt="Screenshot 2020-04-23 at 14 03 06" src="https://user-images.githubusercontent.com/27723630/80097296-5b6bae80-856b-11ea-82c5-54a02af6a94e.png">

## Expected result:
Adjusted URL to the respective changelog.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:
Current release

**Comment by Waldbaer88** [comment]
Just wanted to say that this problem is really obvious because of the apps frequent updates. I'm using it on MacOS and there, the (false) link is not even rendered but just shown as plain HTML code.
<img width="732" alt="Bildschirmfoto 2020-05-08 um 12 42 35" src="https://user-images.githubusercontent.com/50910368/81398551-b257b300-9129-11ea-8916-333eda5d06e0.png">
Should be quite easy to fix, isn't it?

**Comment by mbacchi** [comment]
We'll update the URL shortly, and hopefully get the link rendered too while we're at it. Thanks for the report!

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.13.6 High Sierra x64` using the following build:

```
Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.13.6 (Build 17G11023)
```

* ensured that https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md was being used

<img width="686" alt="Screen Shot 2020-06-02 at 5 56 18 PM" src="https://user-images.githubusercontent.com/2602313/83574024-8cd88200-a4fa-11ea-8244-68ae653936d7.png">

Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)

```

* ensured that https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md was being used

<img width="662" alt="Screen Shot 2020-06-02 at 10 33 25 PM" src="https://user-images.githubusercontent.com/2602313/83589941-bad1bc80-a522-11ea-89ac-30befee33108.png">
