### ISSUE TITLE
[Feature request] Tab Groups

### ISSUE THREAD

**Issue by jaredready** [brave/brave-browser#9419]
The latest release of Chrome and Chromium supports tab groups. Is this something that Brave is planning on supporting?

https://gizmodo[dot]com/tab-groups-is-chromes-best-new-feature-in-years-and-he-1842944249

**Comment by rebron** [comment]
@jaredready You can try it in Brave here: brave://flags/#tab-groups

**Comment by jaredready** [comment]
Oh thanks! I've got this enabled now.

**Comment by rodrigoswz** [comment]
> @jaredready You can try it in Brave here: brave://flags/#tab-groups
> 

Yeah, activating this flag works, but consequently breaks handy menu when long press the tab icon on bottom bar.

**Comment by Brave-Matt** [comment]
This is a dupe of #7142:
https://github.com/brave/brave-browser/issues/7142
