### ISSUE TITLE
[Android] Use defined center for Sponsored images

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#9426]
https://bravesoftware.slack.com/archives/CQGTGBNH1/p1587658271168500?thread_ts=1587615215.165300&cid=CQGTGBNH1

## Description 
Andriod appears to be ignoring the defined center and using actual center instead.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
Sponsored image appears to be using actual center.

## Expected result
Sponsored image should use the defined center.
## Issue happens on 
   - Current Play Store version? yes
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
- Verified focal point for SI is centred as per spec
![image](https://user-images.githubusercontent.com/17010094/80336677-96285c00-8875-11ea-984e-ac1bd5239175.png)
![image](https://user-images.githubusercontent.com/17010094/80336670-90327b00-8875-11ea-94f9-ed911f4c4f3e.png)
![image](https://user-images.githubusercontent.com/17010094/80336696-9d4f6a00-8875-11ea-8de9-dc04d6b6c3d7.png)
![image](https://user-images.githubusercontent.com/17010094/80336686-9aed1000-8875-11ea-94b5-48e57500bcc9.png)
![image](https://user-images.githubusercontent.com/17010094/80336673-932d6b80-8875-11ea-9d54-969b0ea7322d.png)
![image](https://user-images.githubusercontent.com/17010094/80336703-a17b8780-8875-11ea-84aa-6b45cae7c44d.png)
------------------------------------------------
Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
- Verified focal point for SI is centred as per spec
![image](https://user-images.githubusercontent.com/17010094/80337232-fff53580-8876-11ea-8d7a-267db00b39aa.png)
![image](https://user-images.githubusercontent.com/17010094/80337226-fc61ae80-8876-11ea-912e-d7d1126b3a5b.png)
![image](https://user-images.githubusercontent.com/17010094/80337220-f966be00-8876-11ea-96c2-cc3ba86e36bf.png)
![image](https://user-images.githubusercontent.com/17010094/80337249-0d122480-8877-11ea-9895-2c9673612079.png)
![image](https://user-images.githubusercontent.com/17010094/80337233-02f02600-8877-11ea-8af0-dfc30752b10a.png)
![image](https://user-images.githubusercontent.com/17010094/80337240-071c4380-8877-11ea-8a5d-aab26be3169d.png)
