### ISSUE TITLE
[Android] Replace chrome:// with brave:// to follow desktop

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#9427]
## Description 
Internal pages on Android use chrome:// (i.e. chrome://flags vs brave://flags)

Please update the internals to use brave:// 

## Description

On Android, pages like `rewards-internals` are under `chrome://` and not under `brave://`. In order to reach parity with desktop, `brave://` should resolve as expected.

Message from @Miyayes via  #10117

**Why should this be considered a priority?**

1. **Optics:** Given the high number of requests we make to users (in public) to send us their `rewards-internals` or check other settings (e.g., relating to ad block, browser version info, etc.), `chrome://` pages are more visible to end-users than one might expect. 

2. **User disorientation:** Navigating to `chrome://` pages is very disorienting to users, as they don't understand why their **Brave Browser** uses/asks for `chrome://` pages. This is especially the case for users who emphatically quit Google Chrome for Brave.

3. **Support duplication:** Because of the inconsistency between desktop and Android, support docs must always written to cover both `brave://` and `chrome://` cases, which adds unnecessary complexity to support instructions.

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-browser/issues/8886

**Comment by srirambv** [comment]
+1 from @mhatvan for `chrome://rewards` via #12760

**Comment by Miyayes** [comment]
+1 This user was confused by chrome:// https://www.reddit.com/r/BATProject/comments/rk0s7c/weekly_bat_discussion_thread/hpbnwog/?context=3

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 11 running 1.35.87 x64 Beta Build
- Verified visiting `brave://rewards` loads rewards page
- Verified visiting `brave://rewards-internals` loads rewards internals page
- Verified visiting any of the chrome pages with `brave://` loads correctly
- Verified reloading the page with `brave://` retains its and doesn't redirect or reload it in `chrome://`
- Verified clicking on the settings button on rewards panel loads rewards page using `brave://`
- Verified loading Brave Rewards option on menu loads the rewards page using `brave://`
---------
Verification passed on Samsung Tab A with Android 10 running 1.35.87 x64 Beta Build
- Verified visiting `brave://rewards` loads rewards page
- Verified visiting `brave://rewards-internals` loads rewards internals page
- Verified visiting any of the chrome pages with `brave://` loads correctly
- Verified reloading the page with `brave://` retains its and doesn't redirect or reload it in `chrome://`
- Verified clicking on the settings button on rewards panel loads rewards page using `brave://`
- Verified loading Brave Rewards option on menu loads the rewards page using `brave://`
