### ISSUE TITLE
Browser crashes when clicking on Autoplay notification 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#943]
## Description 

Browser crashes when clicking on Autoplay notification 

## Steps to Reproduce

   1. Launch a new profile
   2. Open a new tab and visit cnn.com
   3. Click back button when site is loaded and go back to new tab
   4. Shows Autoplay notification on new tab for cnn.com
   5. Click on Allow, browser crashes

## Actual result:

![autoplay1](https://user-images.githubusercontent.com/17010094/45031632-6338b100-b01d-11e8-93c0-43346e8bc734.gif)
Crash ID: 4952a5c9ccb51091 

## Expected result:
Should not show the autoplay notification on new tab and should not crash if clicked on the notification

## Reproduces how often: 

Easy 

## Brave version (about:brave info) 

Brave | 0.54.4 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy @brave/legacy_qa

**Comment by LaurenWags** [comment]
@srirambv does not reproduce on MacOS with `0.55.3` with the following Steps:
1. Launch a new profile
2. Open a new tab and visit cnn.com
3. Click back button when site is loaded and go back to new tab
4. New tab does not show Autoplay notification for cnn.com (Once I go back to the new tab page, the autoplay notification goes away)

**Comment by srirambv** [comment]
Still happens on Windows. CrashID eef6d4b66c791d58 
![943](https://user-images.githubusercontent.com/17010094/45510930-a99eb600-b769-11e8-855c-7b901049cef1.gif)

**Comment by kjozwiak** [comment]
@srirambv can you still reproduce this on Win? I tried following the `gif` and STR but got the same [results](https://github.com/brave/brave-browser/issues/943#issuecomment-421117204) as @LaurenWags. I'm not receiving the `Autoplay notification` that I'm seeing in the `gif`. Was using `0.55.10 Chromium: 70.0.3538.22`.

**Comment by kjozwiak** [comment]
Thanks for the updated STR @srirambv! Added `OS/Linux` as this is also reproducible under Linux. Couldn't reproduce under macOS 10.13.6 after several attempts.

**Comment by srirambv** [comment]
This issue is not valid anymore as the autoplay bubble prompt is now replaced with autoplay notification inside URL bar. Also tried the steps on 0.59.31 and doesn't reproduce hence closing the issue
