### ISSUE TITLE
Fingerprinting 2.0: Plugins

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9435]
This is a sub-issue of the larger fingerprinting defense reorganization #8787

### Plugins interfaces
`NavigatorPlugins.plugins`
`navigator.plugins`

Currently Brave reports two plugins,  "Chrome PDF Plugin" and "Chrome PDF Viewer"

**Word replacements:**
- Chrome: ["Chrome", "Chromium", "Brave", "Web", "Browser", "" (empty string), "OpenSource", "Online", "JavaScript"]
- PDF: ["PDF", "Portable Document Format", "portable-document-format", "document", "doc", "PDF and PS", "com.adobe.pdf"]
- Plugin: ["Viewer", "Renderer", "Display", "Plugin", "plug-in", "plug in", "extension", "" (empty string)]
- Viewer: ["Viewer", "Renderer", "Display", "Plugin", "plug-in", "plug in", "extension", "" (empty string)] 

**Random plugin**
(see https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/plugins/dom_plugin.cc)
- description: any 3 random words, possibly taken from `chrome/browser/spellchecker/spellcheck_hunspell_dictionary.h`
- filename: 32 random characters, from [a-z]
- name: any 3 random words, possibly taken from `chrome/browser/spellchecker/spellcheck_hunspell_dictionary.h`
- length: 0 (needed for web compat reasons)
- namedItem(): always null (again needed for web compat)

**default protection:** 
 - Randomize both descriptions of plugins, under eTLD+1 seed, using random selections from the above word replacements
 - Randomize both filename to be 32 random characters, under eTLD+1 seed, from [a-z]
 - Include two randomly generated plugins, using the above schema
 - Randomize return order

**max protection:**
 - Include two randomly generated plugins, using the above schema
 - Randomize return order
 - Include no other plugin information

**Comment by Madis0** [comment]
I don't see how the randomization of names could help. 

The issue is bigger than Brave - if the UA, rendering engine and other stuff already tell the world it's Chromium, plugin randomization would only make the user more distinct, _because it is unlike any other Chromium_. 
So keeping it 1:1 with latest Chrome (which I think also has Native Client) would be the best bet.

Another option could be emulating Firefox/Tor browser by simply keeping it an empty array, but again, that needs more precautions overall.

**Comment by pes10k** [comment]
https://brave.com/whats-brave-done-for-my-privacy-lately-episode3/ gives some background why randomization is superior to fixed response, when you can do it w/o breaking things

**Comment by pes10k** [comment]
For QA, I've added a plugins test to https://dev-pages.brave.software/farbling.html

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.73 Chromium: 84.0.4147.125 (Official Build) dev (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Verified using https://dev-pages.bravesoftware.com/farbling.html and https://dev-pages.brave.software/farbling.html

<details>
<summary>Confirmed with shields up, FP values are the same for "Plugins" per page, but the values are different between the two pages above</summary>

Note - logged https://github.com/brave/brave-browser/issues/11278 as a follow-up for the `Local Frame` value being different from `This Page` and `Remote Frame` value

Default Shields (FP = Standard):
<img width="1198" alt="1 13 x - initial check - default shields" src="https://user-images.githubusercontent.com/28145373/90434786-01ec3a00-e09c-11ea-95cc-e3726ec0aeb8.png">

Modified Shields (FP = Strict):
<img width="1196" alt="1 13 x strict shields" src="https://user-images.githubusercontent.com/28145373/90434987-5099d400-e09c-11ea-9f55-f3c95badb75b.png">

</details>

<details>
<summary>Confirmed with shields up, if you close and relaunch the browser, and visit the pages again the values for "Plugins" are different (they are not retained between sessions)</summary>

See note about logged issue in above

Default Shields (FP = Standard):
<img width="1197" alt="1 13 x relaunch check - default shields" src="https://user-images.githubusercontent.com/28145373/90434979-4c6db680-e09c-11ea-8656-778872199330.png">

Modified Shields (FP = Strict):
<img width="1197" alt="1 13 x strict shields relaunch" src="https://user-images.githubusercontent.com/28145373/90435078-77580a80-e09c-11ea-9a7b-2c950c04fc04.png">

</details>

<details>
<summary>Confirmed with shields down, FP values for "Plugins" are the same for each individual item on a given page and are the same for both pages</summary>

Shields Down:
<img width="1197" alt="1 13 x shields down" src="https://user-images.githubusercontent.com/28145373/90435234-b8501f00-e09c-11ea-8fab-88076a653570.png">

</details>

<details>
<summary>Confirmed with shields down, if you close and relaunch the browser, and visit the pages again, the values for "Plugins: are the same (they are retained between sessions)</summary>

Shields Down:
<img width="1195" alt="1 13 x shields down - relaunch" src="https://user-images.githubusercontent.com/28145373/90435365-e46ba000-e09c-11ea-86c6-3704bd00c86b.png">

</details>

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.81 x64 build

Verified using `https://dev-pages.bravesoftware.com/farbling.html` and `https://dev-pages.brave.software/farbling.html`

<details>
<summary>Verified with shields up, FP values are same for "Plugins" on the same page but values are different on each page</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91414335-5170f980-e844-11ea-8b01-917a4e4458a0.png) | ![image](https://user-images.githubusercontent.com/17010094/91414365-5a61cb00-e844-11ea-9057-7c78e27a3edb.png)

</details>

<details>
<summary>Verified with shields up closing and relaunching the browser values for "Plugins" are not retained between sessions</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91414406-6d749b00-e844-11ea-880f-10ae1b7c451a.png) | ![image](https://user-images.githubusercontent.com/17010094/91414433-76656c80-e844-11ea-9108-7988bbac3682.png)

</details>

<details>
<summary>Verified with shields down, FP values for "Plugins" are set to `00000000` as plugin list is empty </summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91414487-88dfa600-e844-11ea-9f7b-191bd0484069.png) | ![image](https://user-images.githubusercontent.com/17010094/91414499-8d0bc380-e844-11ea-8522-2c1a040ca09b.png)

<li>Logged https://github.com/brave/brave-browser/issues/11460 for investigating no plugins when shields is disabled</li>
</details>

<details>
<summary>Verified with shields down, FP values for "Plugins" value of "00000000" is retained between sessions</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91414487-88dfa600-e844-11ea-9f7b-191bd0484069.png) | ![image](https://user-images.githubusercontent.com/17010094/91414499-8d0bc380-e844-11ea-8522-2c1a040ca09b.png)

</details>

----------------------------
Verification passed on Samsung Tab A with Android 10 running 1.13.81 x64 build

Verified using `https://dev-pages.bravesoftware.com/farbling.html` and `https://dev-pages.brave.software/farbling.html`

<details>
<summary>Verified with shields up, FP values are same for "Plugins" on the same page but values are different on each page</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91416959-00fb9b00-e848-11ea-8da8-dd8955461d81.png) | ![image](https://user-images.githubusercontent.com/17010094/91416975-0658e580-e848-11ea-9eda-321cd3b1b289.png)

</details>

<details>
<summary>Verified with shields up closing and relaunching the browser values for "Plugins" are not retained between sessions</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91417005-11ac1100-e848-11ea-96b5-6ce446d98d85.png) | ![image](https://user-images.githubusercontent.com/17010094/91416991-0bb63000-e848-11ea-9267-9431d28f5dfa.png)

</details>

<details>
<summary>Verified with shields down, FP values for "Plugins" are set to `00000000` as plugin list is empty </summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91417020-1670c500-e848-11ea-9bc5-84662578f27f.png) | ![image](https://user-images.githubusercontent.com/17010094/91417031-1a9ce280-e848-11ea-9317-3cb02f02dbe5.png)

<li>Logged https://github.com/brave/brave-browser/issues/11460 for investigating no plugins when shields is disabled</li>
</details>

<details>
<summary>Verified with shields down, FP values for "Plugins" value of "00000000" is retained between sessions</summary>

https://dev-pages.brave.software/farbling.html | https://dev-pages.bravesoftware.com/farbling.html
-- | --
![image](https://user-images.githubusercontent.com/17010094/91417020-1670c500-e848-11ea-9bc5-84662578f27f.png) | ![image](https://user-images.githubusercontent.com/17010094/91417031-1a9ce280-e848-11ea-9317-3cb02f02dbe5.png)

</details>
