### ISSUE TITLE
Sign widevine 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#944]
Equivalent to this:
https://github.com/brave/browser-laptop/blob/master/tools/buildInstaller.js#L74

To QA:
Make sure Netflix still works.

**Comment by bsclifton** [comment]
**_NOTE_**: when reviewing a fix for this, please note that you'll have to revert https://github.com/brave/brave-core/commit/21aea586beb497ca8965b315e2e8c9dfbed4c7cb from the `0.55.x` branch (`master` and `0.56.x` are both OK)

**Comment by mihaiplesa** [comment]
Adding changes needed for pipeline in https://github.com/brave/brave-browser/pull/3981

**Comment by bsclifton** [comment]
Partially fixed with https://github.com/brave/brave-browser/pull/3903 and https://github.com/brave/brave-core/pull/2023 ; we'll need https://github.com/brave/brave-browser/pull/3981 too, as @mihaiplesa called above (then we can close this)

**Comment by simonhong** [comment]
@bsclifton @mihaiplesa Yay! 👍

**Comment by simonhong** [comment]
VMP related PRs are reverted because Windows PR builders failed for signing.
https://github.com/brave/brave-core/pull/2157
https://github.com/brave/brave-browser/pull/3993
https://github.com/brave/brave-browser/pull/3994

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.68.116 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Mac OS X

* Verified test plan from description. 
cc @kjozwiak to check on Mojave

**Comment by kjozwiak** [comment]
@bbondy just a quick double check regarding the case under https://github.com/brave/brave-browser/issues/944#issue-356800725. When you rename `Brave Browser Nightly Framework.sig`, you need to restart the browser or the content will keep playing even though the file was renamed. Assuming this is expected as the `Brave Browser Nightly Framework.sig` was already being used when initially launching the browser before renaming.
