### ISSUE TITLE
Optimize timers for publisher lists

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9441]
When users disable rewards we don't clear the interval. This means that publisher list will be downloaded next time even if rewards are off. This is because we don't check if rewards enabled on timers. This is not a problem for users that never enabled rewards/clean profiles.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64` using the following build:

```
Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)
```

* enabled rewards via the rewards panel and ensured that the `publisher list` was downloaded.
* disabled rewards via `brave://rewards` and closed Brave
* edited `server_publisher_list_stamp` under `preferences` and moved it back ~3 days
* restarted the browser several times and ensured that the `publisher list` isn't being downloaded
* enabled rewards and ensured that the `publisher list` was downloaded without any issues

Example of `publisher list` being downloaded after enabling rewards:

```
[ RESPONSE - OnDownload ]
> time: 1588040094
> result: Success
> http code: 200
> response: Publisher list
> headers accept-ranges: bytes
> headers access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
> headers access-control-allow-methods: GET
> headers access-control-allow-origin: https://rewards.bravesoftware.com
> headers access-control-request-method: GET
> headers age: 1561
> headers cache-control: max-age=3600, public
> headers content-encoding: gzip
> headers content-length: 19006799
> headers content-type: application/json; charset=utf-8
> headers date: Tue, 28 Apr 2020 02:14:53 GMT
> headers etag: W/"cd3c678094a8b205d71bd20eb1477483"
> headers server: Cowboy
> headers status: 200
> headers strict-transport-security: max-age=31536000; includeSubDomains
> headers vary: Accept-Encoding
> headers via: 1.1 varnish
> headers x-cache: HIT
> headers x-cache-hits: 0
> headers x-frame-options: deny
> headers x-request-id: 0b9c3bc2-ee67-401d-8e80-d96ae1f129c8
> headers x-runtime: 2.940268
> headers x-served-by: cache-yyz4527-YYZ
[ END RESPONSE ]
```
