### ISSUE TITLE
[Android] Missing context menu on long press on New tab button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9444]
## Description 
Missing context menu on long press on New tab button

## Steps to reproduce 

   1. Clean install 1.7.100
   2. Disable home button from settings
   3. VIsit a page on new tab
   4. Long press on the new tab + button, no context menu to open tabs is shown
   5. Open tab tray and long press on + button, no context menu to open tabs is shown 

## Actual result 
Missing context menu on long press on New tab button

## Expected result
Should show context menu to open normal and private tabs 

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.7.100

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Found while testing #9293

**Comment by srirambv** [comment]
Need to retest #9293 for context menu once this is fixed

**Comment by samartnik** [comment]
They removed it in chromium. You may see the same behavior in Chrome when Duet is on with new tab option.

**Comment by srirambv** [comment]
moving out of 1.7.x release. @jamesmudgett thoughts on re-adding the option back later ?

**Comment by bsclifton** [comment]
Not valid after move from android-tabs repo to here
