### ISSUE TITLE
[Android] Manual test run on Android x86 for 1.7.x Release 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9447]
## Installer

- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Visual look

- [x] Make sure thereafter every merge
  - [x] No Chrome/Chromium words appear on normal or private tabs
  - [x] No Chrome/Chromium icons are shown in normal or private tabs

## Data
Pre-Requisite: Put previous build shortcut on the home screen. Also, have several sites 'Added to home screen' (from 3 dots menu) and then upgrade to new build
- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify shortcut is still available on the home screen after upgrade
- [x] Verify sites added to home screen are still visible and able to be used after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify settings changes done in the previous version are still retained on upgrade

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)

## Settings and Bottom bar

- [x] Verify changing default settings are retained and don't cause the browser to crash
- [x] Verify bottom bar buttons (Home/Bookmark/Search/Tabs) work as expected 

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off and shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Visit https://brianbondy.com/ and then turn on script blocking, nothing should load. Allow it from the script blocking UI in the URL bar and it should work.
- [x] Verify that default Bravery settings take effect on pages with no site settings
- [x] Verify that 3rd party storage results are blank at https://jsfiddle.net/7ke9r14a/7/ when 3rd party cookies are blocked
### Fingerprint Tests
  - [ ] Visit https://browserleaks.com/webrtc, ensure 2 blocked items are listed in shields
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content Tests

- [x] Go to https://brianbondy.com/ and click on the twitter icon on the top right. Verify that context menus work in the new twitter tab
- [x] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password is auto-populated when you visit the site again
- [x] Open a GitHub issue and type some misspellings, make sure they aren't autocorrected
- [x] Open an email on http://mail.google.com/ or inbox.google.com and click on a link. Make sure it works
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)

## Background

- [x] Start loading a page, background the app, wait > 5 sec, then bring to front, ensure splash screen is not shown

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by LaurenWags** [comment]
Verified using Asus Zenfone (x86) on Android 6 using BraveModernx86.apk
