### ISSUE TITLE
Binance tweaks for protocol handler

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9449]
This is a tracking issue for implementing some review feedback on the protocol handler for Binance oauth

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1809 (Build 17763.1158)

- Verified Oauth flows works on an account with 2FA enabled
- Verified Oauth flows works on an account with 2FA disabled
- Verified widget state is retained between browser restarts
---------
Verification passed on 

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified Oauth flows works on an account with 2FA enabled
- Verified Oauth flows works on an account with 2FA disabled
- Verified widget state is retained between browser restarts
---------
Verification passed on 

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Linux

- Verified Oauth flows works on an account with 2FA enabled
- Verified Oauth flows works on an account with 2FA disabled
- Verified widget state is retained between browser restarts
