### ISSUE TITLE
Browser crashes with multiple user profiles 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#945]
## Description 

While investigating browser crash issues found that if the browser profile has many user profile created, browser crash happens quite easily 

## Steps to Reproduce

   1. Launch new profile on 0.54.4
   2. Rename profile to Work (or anything else apart from Profile 1)
   3. Add a new profile called General (again change it to anything apart from Profile 2)
   4. Visit a couple of sites in work profile
   5. Click skip tour on general profile 
   6. Open webstore from Apps
   7. Click on any extension, reload the page and click the browser back button
   8. Click a second time on the back button and browser crashes

## Actual result:

Browser crashes with multiple user profiles 
Crash ID : ccefe2a44b115a0a
## Expected result:
Should not crash irrespective of how many user profile is created

## Reproduces how often: 

Easy 100% 

## Brave version (about:brave info) 

Brave | 0.54.4 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@brave/legacy_qa Should retest all these crash [issues ](https://github.com/brave/brave-browser/issues?q=label%3Acrash+is%3Aclosed)on multiple profiles

**Comment by srirambv** [comment]
Looks fixed on `0.55.3` on Windows too.

**Comment by bbondy** [comment]
w0000t

**Comment by GeetaSarvadnya** [comment]
Verification **PASS** on:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
