### ISSUE TITLE
[Desktop] Webcam not working on Snap

### ISSUE THREAD

**Issue by ligi** [brave/brave-browser#9451]
interestingly the webcam works with firefox and chromium

Description:	Ubuntu 18.04.4 LTS
Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

The device is a Lenovo Thinkpad P1

For me it would be nice to have it for jitsi - but to decouple the issue from jitsi I tried webcamtest.com

![Selection_427](https://user-images.githubusercontent.com/111600/80229657-099d5400-8651-11ea-997f-f8579841ff29.png)

here the output of v4l-info
```
### v4l2 device info [/dev/video0] ###
general info
    VIDIOC_QUERYCAP
	driver                  : "uvcvideo"
	card                    : "Integrated Camera: Integrated C"
	bus_info                : "usb-0000:00:14.0-8"
	version                 : 4.15.18
	capabilities            : 0x84200001 [VIDEO_CAPTURE,?,STREAMING,(null)]

standards

inputs
    VIDIOC_ENUMINPUT(0)
	index                   : 0
	name                    : "Camera 1"
	type                    : CAMERA
	audioset                : 0
	tuner                   : 0
	std                     : 0x0 []
	status                  : 0x0 []

video capture
    VIDIOC_ENUM_FMT(0,VIDEO_CAPTURE)
	index                   : 0
	type                    : VIDEO_CAPTURE
	flags                   : 1
	description             : "Motion-JPEG"
	pixelformat             : 0x47504a4d [MJPG]
    VIDIOC_ENUM_FMT(1,VIDEO_CAPTURE)
	index                   : 1
	type                    : VIDEO_CAPTURE
	flags                   : 0
	description             : "YUYV 4:2:2"
	pixelformat             : 0x56595559 [YUYV]
    VIDIOC_G_FMT(VIDEO_CAPTURE)
	type                    : VIDEO_CAPTURE
	fmt.pix.width           : 1280
	fmt.pix.height          : 720
	fmt.pix.pixelformat     : 0x47504a4d [MJPG]
	fmt.pix.field           : NONE
	fmt.pix.bytesperline    : 0
	fmt.pix.sizeimage       : 1843200
	fmt.pix.colorspace      : SRGB
	fmt.pix.priv            : 4276996862

controls
    VIDIOC_QUERYCTRL(BASE+0)
	id                      : 9963776
	type                    : INTEGER
	name                    : "Brightness"
	minimum                 : 0
	maximum                 : 255
	step                    : 1
	default_value           : 128
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+1)
	id                      : 9963777
	type                    : INTEGER
	name                    : "Contrast"
	minimum                 : 0
	maximum                 : 255
	step                    : 1
	default_value           : 32
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+2)
	id                      : 9963778
	type                    : INTEGER
	name                    : "Saturation"
	minimum                 : 0
	maximum                 : 100
	step                    : 1
	default_value           : 64
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+3)
	id                      : 9963779
	type                    : INTEGER
	name                    : "Hue"
	minimum                 : -180
	maximum                 : 180
	step                    : 1
	default_value           : 0
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+12)
	id                      : 9963788
	type                    : BOOLEAN
	name                    : "White Balance Temperature, Auto"
	minimum                 : 0
	maximum                 : 1
	step                    : 1
	default_value           : 1
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+16)
	id                      : 9963792
	type                    : INTEGER
	name                    : "Gamma"
	minimum                 : 90
	maximum                 : 150
	step                    : 1
	default_value           : 120
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+24)
	id                      : 9963800
	type                    : MENU
	name                    : "Power Line Frequency"
	minimum                 : 0
	maximum                 : 2
	step                    : 1
	default_value           : 1
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+26)
	id                      : 9963802
	type                    : INTEGER
	name                    : "White Balance Temperature"
	minimum                 : 2800
	maximum                 : 6500
	step                    : 10
	default_value           : 4600
	flags                   : INACTIVE
    VIDIOC_QUERYCTRL(BASE+27)
	id                      : 9963803
	type                    : INTEGER
	name                    : "Sharpness"
	minimum                 : 0
	maximum                 : 7
	step                    : 1
	default_value           : 0
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+28)
	id                      : 9963804
	type                    : INTEGER
	name                    : "Backlight Compensation"
	minimum                 : 0
	maximum                 : 2
	step                    : 1
	default_value           : 1
	flags                   : unknown

```

**Comment by ligi** [comment]
Digged a bit deeper - might be a problem with the snap and not brave directly. I see these in my dmesg:

`[206432.560664] audit: type=1400 audit(1587789524.957:9505): apparmor="DENIED" operation="open" profile="snap.brave.brave" name="/dev/video0" pid=18403 comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

**Comment by bsclifton** [comment]
@ligi definitely good debugging; there are already [some known issues with the snap](https://github.com/brave/brave-browser/issues/6782). You can always try uninstalling the snap and re-install using the standard instructions:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html

This may move the profile directory used by Brave (if snaps capture the profile in a place different than `~/.config/BraveSoftware/brave-browser/`; I can't remember)

**Comment by Frozen-byte** [comment]
I have installed chromium and brave via snap-package.
In Chromium the camera works fine.
Brave does not find my camera.

I've tried it with Google Meet.
```
#  brave --version                                                   
Brave Browser 81.1.7.98 

```
About screen tells me another version: Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
```
#  snap --version                                                                                                 ~ 
snap    2.44.3
snapd   2.44.3
series  16
ubuntu  19.10
kernel  5.3.0-51-generic
```

I'd like to contribute any further information you may ask.

**Comment by rebron** [comment]
cc: @mbacchi can you take a look?

**Comment by lucasfijen** [comment]
@Frozen-byte Works like a charm on Ubuntu 20.04! Thanks a lot!

**Comment by ligi** [comment]
@Frozen-byte cool - also works for me now. But I think we should leave this issue open so it gets this by default?!

**Comment by web-pat** [comment]
Can confirm. @Frozen-byte solution worked for me too.

```
Brave Browser 86.1.15.72  
$ snap --version
snap    2.47
snapd   2.47
series  16
ubuntu  20.04
kernel  5.4.0-48-generic
```

**Comment by fmarier** [comment]
We added a couple of dependencies to the Snap package in brave/brave-browser-snap#14 (copying everything from the [Chromium upstream snap](https://source.chromium.org/chromium/chromium/src/+/master:chrome/installer/linux/snap/snapcraft.yaml.in)). Does it work for you in version 1.18.75 or later of the Snap?

**Comment by web-pat** [comment]
Deinstalling and reinstalling the Brave snap package did not change anything for me. I still have to connect the camera according to @Frozen-byte 's solution.

**Comment by schweigert** [comment]
I needed to enable webcam access:

```
sudo snap connect brave:camera core:camera
```

Thanks @Frozen-byte

**Comment by helderjnpinto** [comment]
Same issue with ubuntu 20.04.1 & Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit) 
Solved with `sudo snap connect brave:camera core:camera`. 
Brave installed by snap store.
With google chrome all works fine.
thanks.

**Comment by fmarier** [comment]
@wknapik I wonder whether this might have the same root cause as the U2F issues you've been looking into recently.

**Comment by wknapik** [comment]
@fmarier it's the same class of issues. Some plugs are not autoconnected and require manual intervention (like the `sudo snap connect brave:camera core:camera` above).

We have two possible ways out - either we document it and say that to use the camera you'll need to run this command, or we request autoconnection from the Snap store.

While the first option is not especially user-friendly, I'd say there's a decent argument for it. As far as privacy goes, access to the camera is very sensitive. Most of the time your browser doesn't need it and for some people, it's never needed.

So it's a trade-off, as always ;] You can get a better user experience at the cost of some privacy risks, or you can get better privacy at the cost of user experience.

Both the Chromium and Firefox snaps have the autoconnection, Brave and Opera currently don't.

**Comment by wknapik** [comment]
@fmarier with u2f devices, the trade-off is easier. Having them accessible as soon, as the snap starts is not very controversial. That doesn't really apply to the camera.

**Comment by wknapik** [comment]
Our request for camera autoconnection has been granted. This will take effect for users with the next snap release.

**Comment by wknapik** [comment]
Confirmed that camera is autoconnected on fresh installations.
