### ISSUE TITLE
[Android] Upgrade from Chromium 81.0.4044.113 to Chromium 81.0.4044.122 (1.7.x)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9453]
Same as https://github.com/brave/brave-browser/issues/9361 - but for Android 😄 

Changelog: https://chromium.googlesource.com/chromium/src/+log/81.0.4044.113..81.0.4044.122?pretty=fuller&n=10000

**QA tests:**

Check branding items
Check for version bump

No specific areas to note for testing:
Only Chromium code has changed (no Brave code changes).

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.7.102 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/80340700-be688880-887e-11ea-95be-6009703366cd.png)
-------
Verification passed on Samsung Tab A with Android 9 running 1.7.102 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/80340802-f374db00-887e-11ea-941b-1cdaf7b5c20a.png)
