### ISSUE TITLE
[Android] Get rid of phone status and identity permission

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#9454]
## Description 
There is excessive permission that needs to be removed
![image](https://user-images.githubusercontent.com/30602739/80241596-db5c4c00-8631-11ea-8e33-9d0c8d83f071.png)

## Steps to reproduce 

   1. Go to app description on play store
   2. Click on permissions
   3. You will see that excessive permission

## Actual result 
Excessive permission is there

## Expected result
We don't need that permission

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): all
   - Device (Phone, Tablet, Phablet): all
   - Android version: 1.7.x
   
## Brave version
1.5.x and 1.7.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
@samartnik The permissions page on GPS still shows `Phone` section, but the build on `release` and `beta` is `1.7.102`. Could we get `v1.8.93` pushed to beta?

**Comment by samartnik** [comment]
Current beta is 1.8.92. It shows properly to me.

**Comment by btlechowski** [comment]
Thanks, I found it

Verification passed on Samsung Galaxy Tab S5e (Android 9.0). Phone permissions are not listed.
![Screenshot_20200510-234836_Google Play Store](https://user-images.githubusercontent.com/34715963/81348054-a6cea280-90bd-11ea-8e76-cd1d6a2fc839.jpg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 10` using the following build:

```
1.8.93 CR: 81.0.4044.129
```

 ![Screenshot_20200511-221923_Google Play Store](https://user-images.githubusercontent.com/2602313/81631420-da6b3e80-93d5-11ea-8326-21694cf620d5.jpg)

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 9` using the following build:

```
1.8.93 CR: 81.0.4044.129
```

![Screenshot_20200511-222438_Google Play Store](https://user-images.githubusercontent.com/2602313/81631674-5cf3fe00-93d6-11ea-8d04-f6a8dc5551b1.jpg)
