### ISSUE TITLE
redesign NTP settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9455]
## Description 
Update the design for New Tab page settings to allow for more customization of the page: to show/hide more widgets, to manage individual widget settings, for managing user uploaded wallpaper or choosing background colors.

## Test plan
Should match design

## Design

Clicking on customize now opens an expanded dashboard customization panel:

![user flows - customize](https://user-images.githubusercontent.com/2388823/81457209-230ec780-914a-11ea-803a-b9cbfed00d57.png)

![customize dashboard-full](https://user-images.githubusercontent.com/2388823/81457228-3457d400-914a-11ea-935c-e58416aa5afe.png)

The customization panel now has sections that contains toggles for each widget.

![customize dashboard-background image](https://user-images.githubusercontent.com/2388823/81457252-3cb00f00-914a-11ea-97d3-c332c5272510.png)

![customize dashboard-background image specs](https://user-images.githubusercontent.com/2388823/81457258-40dc2c80-914a-11ea-9d29-2dcc3a695864.png)

![customize dashboard-brave stats](https://user-images.githubusercontent.com/2388823/81457262-433e8680-914a-11ea-964f-847cf5a5b73f.png)

![customize dashboard-brave rewards](https://user-images.githubusercontent.com/2388823/81457267-46d20d80-914a-11ea-9e23-462b7590015c.png)

![customize dashboard-top sites](https://user-images.githubusercontent.com/2388823/81457274-4afe2b00-914a-11ea-8010-522c681f0bf1.png)

![customize dashboard-clock](https://user-images.githubusercontent.com/2388823/81457280-4e91b200-914a-11ea-925c-81d3d69d52be.png)

![customize dashboard-more cards](https://user-images.githubusercontent.com/2388823/81457289-54879300-914a-11ea-8d3c-6f7922a7be5e.png)

**Switching between sections**

Hover on another section:

![customize dashboard - hover](https://user-images.githubusercontent.com/2388823/81457297-594c4700-914a-11ea-9125-448f12078fe3.png)

When the user clicks on a different section in the panel, the highlight slides to the selected section:

![click section](https://user-images.githubusercontent.com/2388823/81457683-fbb8fa00-914b-11ea-8fe6-fe511cd1775b.gif)

**Dark theme**

Dark theme is supported:

![customize dashboard - dark theme](https://user-images.githubusercontent.com/2388823/81457300-5d786480-914a-11ea-94be-de17b7aeff14.png)

![customize dashboard - dark theme hover](https://user-images.githubusercontent.com/2388823/81457308-610beb80-914a-11ea-9b32-1d93f393e9cf.png)

## Assets
Figma link for CSS, sizing, etc.: https://www.figma.com/file/ZVez2eu0i1OFReiP2jEfgm/Customize-Dashboard-panel?node-id=0%3A1 <-- export the icons from here too

**Comment by karenkliu** [comment]
Designs and assets added!

**Comment by rebron** [comment]
cc: @cezaraugusto

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.85 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Generally confirmed design matches above, however followups are logged with https://github.com/brave/brave-browser/issues/10318 and https://github.com/brave/brave-browser/issues/10299
* Generally confirmed that the new design allows for items to be enabled/disabled from NTP and changes to on/off status are reflected on brave://settings/newTab
* Generally confirmed that adjusting on/off status for various NTP items using brave://settings/newTab was reflected on NTP and on the new Customize Dashboard popup
* Generally confirmed that if changes to NTP settings were made on 1.10.x, when upgrading to 1.11.x they are still reflected on NTP, on brave://settings/newTab and on the updated Customize Dashboard popup
* Encountered already logged issue https://github.com/brave/brave-browser/issues/10067#issuecomment-653018832 while testing

<details>
<summary>Dark Theme Images</summary>

<img width="698" alt="Screen Shot 2020-07-02 at 9 53 12 AM" src="https://user-images.githubusercontent.com/28145373/86368597-5c941880-bc4b-11ea-8731-637398497fff.png">
<img width="692" alt="Screen Shot 2020-07-02 at 9 53 25 AM" src="https://user-images.githubusercontent.com/28145373/86368602-5e5ddc00-bc4b-11ea-8450-addcacb9994e.png">
<img width="693" alt="Screen Shot 2020-07-02 at 9 53 32 AM" src="https://user-images.githubusercontent.com/28145373/86368614-5f8f0900-bc4b-11ea-9fcf-25f77f870d71.png">
<img width="692" alt="Screen Shot 2020-07-02 at 9 53 40 AM" src="https://user-images.githubusercontent.com/28145373/86368621-6158cc80-bc4b-11ea-8c9b-51c164bc9864.png">
<img width="692" alt="Screen Shot 2020-07-02 at 9 54 41 AM" src="https://user-images.githubusercontent.com/28145373/86368627-6289f980-bc4b-11ea-8b98-3095ada5261c.png">
<img width="698" alt="Screen Shot 2020-07-02 at 9 54 49 AM" src="https://user-images.githubusercontent.com/28145373/86368632-63bb2680-bc4b-11ea-9c36-8064f9f5cb8a.png">

</details>

<details>
<summary>Light Theme Images</summary>

<img width="694" alt="Screen Shot 2020-07-02 at 9 55 07 AM" src="https://user-images.githubusercontent.com/28145373/86368712-7d5c6e00-bc4b-11ea-9c6e-5cf081ed136a.png">
<img width="701" alt="Screen Shot 2020-07-02 at 9 55 13 AM" src="https://user-images.githubusercontent.com/28145373/86368715-7df50480-bc4b-11ea-9d53-ae3c861e729a.png">
<img width="699" alt="Screen Shot 2020-07-02 at 9 55 20 AM" src="https://user-images.githubusercontent.com/28145373/86368717-7f263180-bc4b-11ea-8048-16ce3722acfb.png">
<img width="696" alt="Screen Shot 2020-07-02 at 9 55 27 AM" src="https://user-images.githubusercontent.com/28145373/86368722-7fbec800-bc4b-11ea-95e6-3d968af023c4.png">
<img width="694" alt="Screen Shot 2020-07-02 at 9 55 34 AM" src="https://user-images.githubusercontent.com/28145373/86368728-81888b80-bc4b-11ea-92e9-f159a6471c58.png">
<img width="696" alt="Screen Shot 2020-07-02 at 9 55 41 AM" src="https://user-images.githubusercontent.com/28145373/86368736-82212200-bc4b-11ea-9af6-ebbe7de42cec.png">


</details>
