### ISSUE TITLE
[Desktop] "Undo" delete of a top site tile does not restore the tile to its previous position

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9457]
## Test plan
See https://github.com/brave/brave-core/pull/6584

## Description 

Found while testing https://github.com/brave/brave-browser/issues/2971

In 1.7.x version if you delete a tile (by clicking on the `x`) and then select `Undo` on the modal, the deleted top site tile is restored to its previous position.

If you do this on 1.8.x, the restored tile jumps to the first non-pinned position.

## Steps to Reproduce

   1. Have a profile with history and top site tiles (enough history so that if you remove a tile you have a site to take its place) - doesn't matter if it's clean or upgrade profile.
   2. Have a couple sites pinned (my 1st and 4th tiles are pinned).
   3. Delete a tile, such as the 5th one.
   4. On the modal, click `Undo`.

## Actual result:

Restored top site tile jumps to the first unpinned position (in this case, the 2nd place).
![18x-restoretile](https://user-images.githubusercontent.com/28145373/80251486-a8bb4f00-8643-11ea-9300-b9a3222189d9.gif)

## Expected result:
Tile is restored to its former position/place as it is in 1.7.x.
![17x-restoretile](https://user-images.githubusercontent.com/28145373/80251471-a527c800-8643-11ea-90ae-6315c8138dbc.gif)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

Brave | 1.10.9 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? not on 1.7.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron @cezaraugusto @bsclifton

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.17.39 Chromium: 86.0.4240.99 (Official Build) nightly (64-bit)
-- | --
Revision | 002668237e13d38aabd6d11c2d216dd22b736ff2-refs/branch-heads/4240@{#1229}
OS | Windows 10 OS Version 1903 (Build 18362.1082)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/6584
