### ISSUE TITLE
top site tile does not correctly reflect that site is bookmarked on upgrade

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9459]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/2971

If one of your top site tiles is bookmarked on 1.7.x and you upgrade to 1.8.x, the bookmark icon is not filled in on 1.8.x, although the site is actually bookmarked.

## Steps to Reproduce

   1. Using 1.7.x have a profile with history and at least one top site tile bookmarked.
   2. Update to 1.8.x.

## Actual result:

Tile does not indicate that the site is bookmarked but it is.
<img width="616" alt="Screen Shot 2020-04-24 at 4 39 24 PM" src="https://user-images.githubusercontent.com/28145373/80255069-3bf78300-864a-11ea-9862-228495172131.png">
<img width="1121" alt="Screen Shot 2020-04-24 at 4 39 34 PM" src="https://user-images.githubusercontent.com/28145373/80255072-3dc14680-864a-11ea-99b6-f486ea62c64d.png">

## Expected result:
Tile should indicate that the site is bookmarked as it does in 1.7.x.
<img width="687" alt="Screen Shot 2020-04-24 at 4 38 57 PM" src="https://user-images.githubusercontent.com/28145373/80255053-369a3880-864a-11ea-9542-6d678f623d1c.png">
<img width="1125" alt="Screen Shot 2020-04-24 at 4 39 09 PM" src="https://user-images.githubusercontent.com/28145373/80255059-38fc9280-864a-11ea-8ada-30804e170491.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.82 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron @cezaraugusto @bsclifton

**Comment by rebron** [comment]
Loosely related to #9481.

**Comment by bsclifton** [comment]
Closing as `wontfix` since bookmark icon is removed with https://github.com/brave/brave-browser/issues/9672
