### ISSUE TITLE
YT/Twitch not added to the table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#946]
Media publishers are not added to auto contribute table in rewards

**Comment by kjozwiak** [comment]
Doesn't seem to be working with the following build under `macOS 10.13.6 x64`

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

@LaurenWags mentioned that YT/Twitch is still not working as per conversations with the Rewards team. Will wait for a newer build to re-check.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

There seems to be some issues here and there where sometimes channels don't appear under the table despite watching them for 5min or more. However, generally, Twitch & YT channels are being added into the table. Will create new issues when I find STR for channels sometimes not being added.
