### ISSUE TITLE
Brave Rewards widget cut off when Binance is toggled off from brave://settings/newTab

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9460]
## Description 

Brave Rewards widget cut off when Binance is toggled off from brave://settings/newTab

## Steps to Reproduce

   1. Go to brave://settings/newTab
   2. Toggle off Binance
   3. Open a new tab
   4. See that Brave Rewards widget is still cut off

## Actual result:

![Screen Shot 2020-04-24 at 4 13 14 PM](https://user-images.githubusercontent.com/2388823/80263849-d0f87d00-8646-11ea-8fc0-79daf2d9063f.png)

## Expected result:
![Screen Shot 2020-04-24 at 4 15 55 PM](https://user-images.githubusercontent.com/2388823/80263873-e1a8f300-8646-11ea-8635-f0223641fd05.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.10.9 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by ryanml** [comment]
This is fixed by consequence of the fix for - https://github.com/brave/brave-browser/issues/9414

Commit is here: https://github.com/brave/brave-core/pull/5353/commits/988ebccb65ad59d15df2e239decf9d1ae6df9068 to be merged as a part of https://github.com/brave/brave-core/pull/5353

With the addition of `brave://settings/newTab` the logic to handle on NTP toggling had to be duplicated to handle outside pref updates from the settings page. cc: @rebron @karenkliu

**Comment by ryanml** [comment]
Closed via: https://github.com/brave/brave-core/pull/5353

**Comment by LaurenWags** [comment]
@ryanml @rebron @kjozwiak @bsclifton looks like brave://settings/newTab isn't in 1.8.x, should the milestone for this issue be 1.9.x instead?

**Comment by ryanml** [comment]
@LaurenWags good catch, however this is landing as part of a PR that’s going in to 1.8. It’s just a couple of checks inside the the new tab page component, it will work without the settings page because it’s just checking properties that already exist

**Comment by srirambv** [comment]
@LaurenWags I have verified the flow from dashboard settings. If you want I can add verification notes. I had not checked for the settings part of it so didn't add the notes

**Comment by LaurenWags** [comment]
probably good to add the verification notes @srirambv 👍 thanks!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1909 (Build 18363.778)

- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is enabled
- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is disabled
- Verified toggle Binance widget via dashboard settings doesn't cut off the rewards widget when ads grant notification is shown on the rewards widget
------
Verification passed on 

Brave | 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Linux

- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is enabled
- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is disabled
- Verified toggle Binance widget via dashboard settings doesn't cut off the rewards widget when ads grant notification is shown on the rewards widget
--------
Verification passed on 

Brave | 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is enabled
- Verified toggle Bianance widget via dashboard settings doesn't cut off the rewards widget when rewards is disabled
- Verified toggle Binance widget via dashboard settings doesn't cut off the rewards widget when ads grant notification is shown on the rewards widget
