### ISSUE TITLE
[Android] Play Video in background stopped working

### ISSUE THREAD

**Issue by tompro** [brave/brave-browser#9463]
## Description 
Playing YouTube videos in backgroud (Tab, in other App, and when display shut off) stopps working every few hours. Sometimes YouTube adds are shown as well. 
Going to settings, disable then reenable and restart Brave fixes the issue for a short time.
This has been working fine for several month. Dont know whether YouTube, Android or Brave related.

## Steps to reproduce 

   1. Add YouTube link to homescreen
   2. Open YouTube and watch any video, after a fresh start background video normally works
   3. Stop watching/listening, do other stuff or just wait
4. Go back to running Brave app instance and start some other video, open new tab or switch App stops Video playback.

## Actual result 
YouTube video playback stops playing when new Tab is opened, app is switched or sreen is shut off.

## Expected result
Video playback still plays.

## Issue reproduces how often 
For about 1 - 2 weeks, several times a day.

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): oneplus 6
   - Android version: 10
   
## Brave version
1.5.131

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Looks to be YT releated changes as I can reproduce is on Android tabs build as well. Maybe some script is being blocked 🤷‍♂️ 

cc: @SergeyZhukovsky @samartnik @ryanbr

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/android-browser-app-stops-playing-youtube-videos-in-the-background/121866?u=eljuno

**Comment by bonotheedge** [comment]
> Looks to be YT releated changes as I can reproduce is on Android tabs build as well. Maybe some script is being blocked 
> 
> cc: @SergeyZhukovsky @samartnik @ryanbr

I am experiencing this issue not only with YouTube.

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J5 version 5.1.1 running `BraveModernarm 1.8.93`
- Reproduced the issue in 1.5.131 and 1.7.102
- Verified the STR from the description, the issue is fixed and working fine in 1.8.93
