### ISSUE TITLE
Add Package to the Snap Store for Linux Users

### ISSUE THREAD

**Issue by ConvexPolygon** [brave/brave-browser#9464]
## Description 

Users who are using linux without much technical knowledge might have issues installing Brave on their computer. 

## Steps to Reproduce

N/a
## Actual result:

User has to install using command-line

## Expected result:
I guess they should be able to package to the snap store

## Reproduces how often: 

No Steps to reproduce

## Brave version (brave://version info)

N/A

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Yes
- Can you reproduce this issue with the dev channel?
Yes
- Can you reproduce this issue with the nightly channel?
Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No
## Miscellaneous Information:

This can easily be remedied by publishing a package to the [Snap Store](https://snapcraft.io/)

**Comment by bsclifton** [comment]
Hi @ConvexPolygon 

We do have a snap and it's live
https://snapcraft.io/install/brave/ubuntu

This was originally captured by https://github.com/brave/brave-browser/issues/1007
