### ISSUE TITLE
[Android] clicking clear browser data crashes Brave

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#9465]
Description 
When clicking on clear browser data on the privacy tab in the settings it crashes the app instead of opening the clear browser data menu.

Steps to reproduce
   1. Click on 3 dot hamburger menu
   2. Click on settings
   3. Click on privacy
   4. Click on clear browser data

Actual result
Crashes brave

Expected result
Open the clear browser data menu

## Issue reproduces how often
I tested it and it happens every time

## Issue happens on 
   - Current Play Store version? No
   - Beta build? No but pre-release tag

Device details
   - Install type (ARM, x86): arm64
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 10

Brave version
Android Release Channel v1.7.100

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/brave-core/pull/5340
