### ISSUE TITLE
Referer header stripped breaks OKTA SAML integration

### ISSUE THREAD

**Issue by mengesb** [brave/brave-browser#9470]
## Description 

When using Brave Browser with Shields Up, I cannot log into an OKTA SAML app Harness. It requires a `Referer` header that gets stripped when shields are up, versus when they're down the header is present and the application can perform normally

## Steps to Reproduce

   1. Invoke a POST saml login application with OKTA 
   2. Application on the other side receives post with SAML response, however no referer or header to validate SAML response with

## Actual result:

Application reports invalid SAML configuration or setup

## Expected result:

Application validates SAML response against SAML target, typically the `Referer` header

## Reproduces how often: 

While this is a SAML implementation detail, any application that integrates with an IDP that uses this method will fail with shields up. In this case, I'm using OKTA as the idp (free dev accounts are available), and Harness (https://harness.io/)

## Brave version (brave://version info)

```text

1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
--
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.1.307.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --disable-sync --disable-webrtc-apm-in-audio-service --enable-audio-service-sandbox --enable-dom-distiller --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=DnsOverHttps,MixedContentSiteSetting,SimplifyHttpsIndicator,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,PasswordImport --disable-features=VideoPlaybackQuality,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/bmenges/Library/Application Support/BraveSoftware/Brave-Browser/Default

```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? n/a, but I expect yes
- Can you reproduce this issue with the dev channel? n/a, but I expect yes
- Can you reproduce this issue with the nightly channel? n/a, but I expect yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? no - works as expected

## Miscellaneous Information:

Specifically, this app is broken by Brave's Shield by stripping the `Referer` header.

without shields up:

```text
POST /api/users/saml-login?accountId=[REDACTED] HTTP/1.1
Host: [REDACTED]
Connection: keep-alive
Content-Length: 9247
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: https://anaplan.okta.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Referer: https://[REDACTED]/app/[REDACTED]/[REDACTED]/sso/saml
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=[REDACTED]; _mkto_trk=id:[REDACTED]&token:[REDACTED]; _hjid=[REDACTED]; trwv.uid=[REDACTED]; ei_client_id=[REDACTED]; _gcl_au=[REDACTED]; _gid=[REDACTED]; pageviewCount=[REDACTED]; [REDACTED]; amplitude_id_[REDACTED]

SAMLResponse=[REDACTED]

HTTP/1.1 303 See Other
Server: nginx/1.15.6
Date: Sun, 26 Apr 2020 08:52:45 GMT
Content-Length: 0
Connection: keep-alive
Location: https://[REDACTED]/saml.html?apiurl=[REDACTED]%3D%3D&onprem=true&token=[REDACTED]

GET /saml.html?apiurl=[REDACTED]%3D%3D&onprem=true&token=[REDACTED] HTTP/1.1
```

with shields up:

```text
POST /api/users/saml-login?accountId=[REDACTED] HTTP/1.1
Host: [REDACTED]
Connection: keep-alive
Content-Length: 9241
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: https://anaplan.okta.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=[REDACTED]; _mkto_trk=id:[REDACTED]&token:[REDACTED]; _hjid=[REDACTED]; trwv.uid=[REDACTED]; ei_client_id=[REDACTED]; _gcl_au=[REDACTED]; _gid=[REDACTED]; pageviewCount=[REDACTED]; [REDACTED]; amplitude_id_[REDACTED]

SAMLResponse=[REDACTED]

HTTP/1.1 303 See Other
Server: nginx/1.15.6
Date: Sun, 26 Apr 2020 08:52:45 GMT
Content-Length: 0
Connection: keep-alive
Location: https://[REDACTED]/#/login?errorCode=invalidsso

GET / HTTP/1.1
```

**Comment by mengesb** [comment]
Possibly related issues:

- #8319

**Comment by fmarier** [comment]
So if I understand correctly, your site (your code?) is checking to see that the request came from `okta.com` but it's failing that check because the `Referer` header is empty. If that's the case, then the changes we are making to our referrer protections (https://github.com/brave/brave-browser/issues/8696) aren't going to help.

What would help however is the `Origin` header. This is the right header to use when doing security checks on form submissions since it's restricted to `POST` requests and not affected by referrer controls. Do you know whether or not that would be an option on your site? Do you know what exactly checks are being done on the `Referer` header?

**Comment by mengesb** [comment]
It's not my site, it's a vendor site. I'm relay this issue to them and see what can be facilitated

**Comment by fmarier** [comment]
@mengesb I also thought of a change we can make that might solve this problem:
```
2. Is this a cross-site navigation?
   - `GET` / `HEAD`?
     - If yes, change effective policy to `no-referrer`
   - Otherwise:
     - Requested policy of `origin`?
       - If yes, change effective policy to `strict-origin`
     - Requested policy of `no-referrer`, `same-origin`, or `strict-origin`?
       - If yes, change effective policy to the requested policy. 
```
In other words: have the `Referer` header match the contents of the `Origin` header for `POST` requests.
 
Once https://github.com/brave/brave-browser/issues/8696 is fixed on Nightly, it would be super helpful if you could re-test to see if your SSO problems are resolved.

**Comment by fmarier** [comment]
We've just landed the [change I aluded to](https://github.com/brave/brave-browser/issues/9470#issuecomment-639691957). Would you be able to test again using [Brave Nightly](https://brave.com/download-nightly/)?

**Comment by mengesb** [comment]
I just checked the nightly build 112.42 and was able to transition from OKTA to Harness cleanly without anything done to the shields (fresh, new, default install works)

**Comment by mengesb** [comment]
When I enabled script blocking; i was able to chop out google, and allow the required site scripts and everything still works well

**Comment by fmarier** [comment]
Thanks for confirming that our work-around worked!

**Comment by fmarier** [comment]
Fixed as part of the changes in https://github.com/brave/brave-browser/issues/8696.
