### ISSUE TITLE
When will there be a Desktop release on 1.7.x branch that has Chromium 81.0.4044.122?

### ISSUE THREAD

**Issue by arpitchauhan** [brave/brave-browser#9474]
The latest stable version of Brave on desktop is 1.7.98 which uses a vulnerable version of Chromium: 81.0.4044.113. The security issues were fixed in a new version of Chromium, [81.0.4044.122 ](https://chromereleases.googleblog.com/2020/04/stable-channel-update-for-desktop_21.html).

I have noticed that recently, there has been a significant delay in updating Chromium on the stable branch of Brave. E.g., it took many days to update from Chromium 80 to 81 on 1.7.x.

**Comment by joejoejo** [comment]
have the same issue with android releases which are delayed

**Comment by eljuno** [comment]
See https://github.com/brave/brave-browser/issues/9442#issuecomment-619509935

**Comment by bsclifton** [comment]
Hi folks - there will be an update with .122 coming this next week. Nightly is already on .122, we're bringing to release channel on Desktop with Brave version 1.8. Android will be having a 1.7 release soon with the updated Chromium
