### ISSUE TITLE
What happened to sync feature

### ISSUE THREAD

**Issue by ShardulAswale** [brave/brave-browser#9475]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Hi @ShardulAswale 

It's been disabled by default and we're working on a version 2 of sync right now

For more info, see https://support.brave.com/hc/en-us/articles/360042159452-How-do-I-re-enable-Brave-Sync-
