### ISSUE TITLE
Captcha report log

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#948]
Depends on GMP work.

Currently we have hardcoded grant amount, where we need to actually convert it to the value.

Fixed place: https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/rewards_service_impl.cc#L438

How we do it in js: https://github.com/brave/brave-core/blob/master/components/brave_rewards/ui/components/grant.tsx#L70

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* Verified steps from https://github.com/brave/brave-core/pull/409
