### ISSUE TITLE
[Desktop] wallet balance is showing as zero when ad grants are claimed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9482]
## Description 

wallet balance is showing as zero when ad grants are claimed

## Steps to Reproduce

   1. Clean profile 1.8.x or 19.x staging environment
   2. Restore an ad grants
   3. Clear the captcha test
   4. Wallet balance is showing as zero but the ad grants claimed is displayed as 20 BAT in the settings page

## Actual result:

wallet balance is showing as zero when ad grants are restored

## Expected result:
wallet balance should not be zero when ad grants are restored

## Reproduces how often: 

Intermittent
## Brave version (brave://version info)

Brave | 1.9.38 Chromium: 81.0.4044.113 (Official Build) dev (64-bit)
-- | --
Revision | cf9d66371ea608e227eed56ccba3abc2701bd23d-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc 

@maikelmclauflin and I ran into this issue while resetting uphold account when ad grants were not transferred to uphold account. Please note this issue is inconsistent sometimes it won't show wallet balance at all, sometimes the issue gets resolved by refreshing the brave://rewards page.

**Comment by LaurenWags** [comment]
Reported in the field internally here: https://bravesoftware.slack.com/archives/CB0KCRCQN/p1588006058245600?thread_ts=1588005271.243700&cid=CB0KCRCQN

**Comment by srirambv** [comment]
Issue on Android as well logged #9524

**Comment by NejcZdovc** [comment]
if you see this problem again please send me a profile of it

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc I can reproduce the issue again today. When I restore ad grants, wallet balance is showing as `0` 
![image](https://user-images.githubusercontent.com/38657976/83533095-c31efd00-a50c-11ea-87a0-36e4451825a2.png)
