### ISSUE TITLE
Remove extension based content script cosmetic filtering

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9487]
We should remove some of these content-script based (via brave-extension) rules since I believe they should be covered by cosmetic filters.

https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/manifest.json#L56

The full assets are here:
https://github.com/brave/brave-core/tree/master/components/brave_extension/extension/brave_extension/assets

The extension way isn't good because:
- It adds manual things we can't dynamically update
- It does not work on Android
- It should be covered already by cosmetic filters

# Test plan

Test to make sure with an older build vs this build, that the following sites block the same:
- https://www.washingtonpost.com/
- https://www.youtube.com/
- https://www.yahoo.com/
- https://coinmarketcap.com/
- https://www.glennbeck.com/

**Comment by rebron** [comment]
@bbondy can you assign a priority on this one? p4?

**Comment by antonok-edm** [comment]
@bbondy / @rebron Looks like this can be closed? https://github.com/brave/brave-core/pull/5386#issuecomment-620773969

**Comment by bbondy** [comment]
Yes but it was via https://github.com/brave/brave-core/pull/5878
Dupe of https://github.com/brave/brave-browser/issues/10319
