### ISSUE TITLE
[Android] Toggling 3p cookie settings breaks Twitter

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#9489]
## Description 
Toggling 3p settings from on-off-on breaks twitter. This is likely because of shield settings not applying the 3p cookie exceptions correctly.

## Steps to reproduce 

   1. Navigate to twitter.com/pjumde 
   2. Toggle 3p cookie settings
   3. Tweets cannot be loaded.

## Actual result 
Tweets are not visible

## Expected result
Tweets should be visible

## Issue reproduces how often 
Easily

**Comment by kjozwiak** [comment]
Some more context via https://github.com/brave/brave-core/pull/5318#issuecomment-619679544, https://github.com/brave/brave-core/pull/5318#issuecomment-619711110 and https://github.com/brave/brave-core/pull/5318#issuecomment-619899524 regarding the above not working on Android.

**Comment by GeetaSarvadnya** [comment]
- Verification passed on Samsung Galaxy J5 version 5.1.1 running `BraveModernarm.apk 1.8.93`
  Reproduced the issue in 1.5.131 and 1.7.102
  Verified the STR from the description, the issue is fixed and working fine in 1.8.93
