### ISSUE TITLE
[Desktop] `Hide Top Sites` on NTP Top sites is misaligned in Polish locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9497]
Follow up to https://github.com/brave/brave-browser/issues/9267

## Steps to Reproduce

   1. Open Brave in Polish locale
   2. Add pages to NTP Top Sites
   3. Hover over NTP Top Sites widget
   4. Show `Hide Top Sites`

## Actual result:

In polish locale `Hide Top Sites` is misaligned
![image](https://user-images.githubusercontent.com/34715963/80444394-f66cdb80-8911-11ea-9c66-222abb4ea31b.png)

## Expected result:
In polish locale `Hide Top Sites` is aligned properly

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @cezaraugusto @ryanml @rebron

**Comment by btlechowski** [comment]
Still reproducible

Brave | 1.11.35 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/83278413-de6bce80-a1d3-11ea-8a2b-a7206f0a4c6d.png)

**Comment by ryanml** [comment]
This was fixed by: https://github.com/brave/brave-core/pull/6327/files cc: @btlechowski @rebron

**Comment by bbondy** [comment]
If this is closed by the above PR pls specify the milestone where the code landed. If it's just a duplicate please just label as `closed/duplicate`.
