### ISSUE TITLE
Disable by default tab hover cards for Windows and Linux

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#9509]
edited by rebron for more details.

## Description 
![image](https://user-images.githubusercontent.com/19390797/80497564-f220dc80-896a-11ea-9a7e-0152ef9fd8c9.png)
Hover over any tab on Windows or Linux and notice Tab Hover card. This is default disabled on macOS and can be toggled with `brave://flags/#tab-hover-cards` enabled or disabled.

## Actual result:
When cursor is on the card, annoying useless windows are displayed.

## Expected result:
This option should be disabled by default.

1. brave://flags/#tab-hover-cards should be default disabled. Hover cards can get in the way of the URL bar.
2. Tooltip with page title should display on hover over tab by default.
<img width="373" alt="Screen Shot 2020-04-30 at 9 18 11 PM" src="https://user-images.githubusercontent.com/5951041/80781680-22fa4080-8b28-11ea-8621-894c543c1b08.png">

## Reproduces how often: 
100% on released & nightly

## Brave version (brave://version info)
Version 1.10.11 Chromium: 81.0.4044.122 (Official Build) nightly (64-bit)

## Version/Channel Information:
Relased / Nightly

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ✔
- Can you reproduce this issue with the dev channel? ✔
- Can you reproduce this issue with the nightly channel? ✔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ✔

**Comment by bsclifton** [comment]
What platform are you on? (Windows?)

I'm not able to reproduce - but I know this will happen if you manually enable brave://flags/#tab-hover-cards.  You can try toggling this to off

**Comment by TheAresjej** [comment]
on the main version (release) I use I have this flag switched but I don't remember if it was set like this from the start. but I just installed the latest Beta version available on your official website there this "problem" occurs. / _Version 1.9.45 Chromium: 81.0.4044.122 (Official Build) beta (64-bit)_

![image](https://user-images.githubusercontent.com/19390797/80543167-a728b880-89ae-11ea-8432-362564ba15c5.png)
I'm using Windows 1909 😋

**Comment by bsclifton** [comment]
Reproduced on Windows - doesn't seem to be happening on macOS

@rebron is this something we should disable?

**Comment by rebron** [comment]
We should disable on Windows.

**Comment by TheAresjej** [comment]
**OS**: Fedora 32 / **Brave** **Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)**
![image](https://user-images.githubusercontent.com/19390797/80713582-02b08e80-8af4-11ea-863e-6f89ce2a53b5.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5435

Verified for tabs in normal window, private window and private window with tor

![image](https://user-images.githubusercontent.com/34715963/82850148-682d4a80-9efb-11ea-9dda-eb13e6eb53a6.png)
![image](https://user-images.githubusercontent.com/34715963/82850210-bcd0c580-9efb-11ea-8ed0-40d9b2967c4b.png)

![image](https://user-images.githubusercontent.com/34715963/82850198-a9255f00-9efb-11ea-9ece-049b39c6a994.png)
