### ISSUE TITLE
use vetted list for reviewed extensions

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#951]
## Description 
When Brave users visit Chrome Web Store, use vetted list of Extensions to remove warning.

**Comment by mrzealot** [comment]
Attached a list of 3835 extensions from the top 5k that currently pass all filters.
Disclaimer: these are only usable for not displaying a warning popup upon install, and not for any endorsement. In other words, we're not sure these are "good", they just haven't been caught being "bad" yet.

[extension_whitelist_20181130.zip](https://github.com/brave/brave-browser/files/2634079/extension_whitelist_20181130.zip)

**Comment by rebron** [comment]
cc: @bbondy and @pilgrim-brave Sounded like we can move forward with using this extension list now. 
@mrzealot do you have an updated list?

**Comment by mrzealot** [comment]
@rebron No update since I shared the last version on Slack. I'll try to schedule a rerun sometime if this thread starts moving again, but the "old" one could/should be usable in the meantime as an initial version.

**Comment by mrzealot** [comment]
@rebron Resharing the last iteration of the whitelist publicly, as per our Slack discussions: [Refined_Ext_Shortlist_20181219.zip](https://github.com/brave/brave-browser/files/3037724/Refined_Ext_Shortlist_20181219.zip)
