### ISSUE TITLE
Screen sharing in Microsoft Teams web app doesn't work on Brave desktop app

### ISSUE THREAD

**Issue by pwittchen** [brave/brave-browser#9510]
Screen sharing in Microsoft Teams web app doesn't work on Brave desktop app on Linux. It works e.g. on Google Chrome. I cannot see what others are sharing or share my own screen via Brave browser.

My setup:

- Brave: Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) unknown (64-bit)
- OS: Arch Linux (5.6.7-arch1-1)

**Comment by bsclifton** [comment]
Hi @pwittchen are you able to try a more recent version of Brave?

1.3 is a few versions behind- we're up to 1.7 on stable

**Comment by pwittchen** [comment]
Thanks, I downloaded brave-dev-bin (1.9.46-4) from aur. I'll check this issue once when I'll have a chance to share screen with someone :).

**Comment by pwittchen** [comment]
It's half-working. I can share my screen, but I cannot see when someone else is sharing screen with me.

**Comment by pwittchen** [comment]
Ok, it seems to be fixed on the latest version `Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) unknown (64-bit)`.

**Comment by bsclifton** [comment]
Great! Thanks for the update, @pwittchen 😄

**Comment by ishnmu** [comment]
Hi , this one still not working in my brave. Unable to see the option for screen sharing itself when opened in brave. Working fine is other browsers like Safari, Chrome & Moz. 

OS: MACOS MONTEREY Version 12.1
Brave Version:  Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)

<img width="742" alt="image" src="https://user-images.githubusercontent.com/24570615/171587008-be3a9af0-f494-4f1b-a1e2-eb08b93ab59b.png">
