### ISSUE TITLE
Allow a user to troubleshoot why his displayed balance is not equal to his Uphold balance

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9512]
Per this thread: 
https://www.reddit.com/r/BATProject/comments/g9flj5/i_verified_my_uphold_wallet_about_a_month_ago_i/fotgdpx/

Users sometimes see that their displayed balance is not the same as their Uphold balance.

Besides Uphold balance, there is also UGP and user funds anon card.

The different types of funds should be displayed in brave://rewards-internals/
So that both support and users can see the difference. 
They should be able to add the numbers and get to the total.

Otherwise we are going blind and we don't know if there are bugs or not.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Case #1`**

* claimed a `ugp` grant on staging
* connected KYC wallet
* ensured that `brave://rewards-internals` is being updated correctly

<img width="602" alt="Screen Shot 2020-06-12 at 12 37 01 AM" src="https://user-images.githubusercontent.com/2602313/84465478-1a2b7d00-ac45-11ea-8f6e-4faa7a83dac2.png">

**`Case #2`**

* claimed a `ad` grant on staging
* connected KYC wallet
* ensured that `brave://rewards-internals` is being updated correctly

<img width="601" alt="Screen Shot 2020-06-12 at 1 20 59 AM" src="https://user-images.githubusercontent.com/2602313/84467766-1569c780-ac4b-11ea-98e3-e7b4e7250e59.png">

**`Case #3`**

* claimed a both a `ugp` & `ad` grant on staging
* connected KYC wallet
* ensured that `brave://rewards-internals` is being updated correctly

<img width="602" alt="Screen Shot 2020-06-12 at 1 24 55 AM" src="https://user-images.githubusercontent.com/2602313/84468761-99bd4a00-ac4d-11ea-81f3-80b1a2497039.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{# 657}
OS | Linux

<Details>
<summary>Scenario 1</summary>

- Claimed an UGP grant on staging
- Connected KYC wallet
- Verified that brave://rewards-internals is being updated correctly
![image](https://user-images.githubusercontent.com/17010094/84622485-b6ca7500-aefa-11ea-9760-c04e09b75420.png)

</details>


<Details>
<summary>Scenario 2</summary>

- Claimed an Ad grant on staging
- Connected KYC wallet
- Verified that brave://rewards-internals is being updated correctly
![image](https://user-images.githubusercontent.com/17010094/84622768-6e5f8700-aefb-11ea-9b78-08165e1810ef.png)

</details>


<Details>
<summary>Scenario 3</summary>

- Claimed both UGP and Ad grant on staging
- Connected KYC wallet
- Verified that brave://rewards-internals is being updated correctly
![image](https://user-images.githubusercontent.com/17010094/84622803-86cfa180-aefb-11ea-8a98-13a62dbc8494.png)

</details>
