### ISSUE TITLE
Promotions are fetch too often

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9513]
We should have some cacheing in this area, so that we don't pull every time that you open a panel for example. We should store last fetch in preferences (`last_fetch.promotion`) and then when we get request for promotion fetch we check that preference and if's not older then 10min just return what we have in db. We also need to allow for this check to be removed if you pass is_testing set

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5760
* Verified on staging env with the following flags `--args --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=6 --brave-ads-staging --rewards=staging=true --v=1`
* Confirmed after claiming the grant, there were no lines in the terminal like `[3346:13827:0720/153245.371484:VERBOSE1:network_delegate.cc(32)] NetworkDelegate::NotifyBeforeURLRequest: https://grant.rewards.bravesoftware.com/v1/promotions?migrate=true&paymentId=2e39e07b-74ea-4f54-bd62-2828bb09d142&platform=osx` until after >10 minutes had passed, then opening the panel triggered another fetch.

------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build
- Verified steps from https://github.com/brave/brave-core/pull/5760
- Verified log shows a request for promotion with the platform details
![image](https://user-images.githubusercontent.com/17010094/90092208-35d40200-dd20-11ea-8807-710180c60cb9.png)
- Verified no log after claiming the grant 
- Verified after ~10 mins opening the panel again and checking logs shows a second request sent to the server 
![image](https://user-images.githubusercontent.com/17010094/90092132-03c2a000-dd20-11ea-879d-d2fe6758f0cf.png)
