### ISSUE TITLE
brave://settings/themes does not work for SR/unable to turn off SR NTP images

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9515]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/8218

When installing using SR code, the brave://settings/themes page does not work. When you navigate there, nothing is selected (the SR radio button should be selected when installing from SR code). If you select an option and refresh the page, your selection is removed. If you select `Brave default images` and close the page, your selection is not respected so you can only view SR images on NTP.

Note - this seems to only be a problem in 1.8.x. Issue does not reproduce on 1.9.x or 1.10.x.

## Steps to Reproduce

1. Create empty profile dir
2. Create promoCode text file in root profile dir and that file has `TECHNIK` string
3. Load new tab and confirm you see Technikke image
4. Open brave://settings/themes page 
--> no radio button selected (expected Technikke one to be selected) 
5. Select `Brave default images` radio button.
6. Refresh page
--> your selection is removed
7. Select `Brave default images` again
8. Open NTP.
--> Technikke image displayed.

## Actual result:

<img width="680" alt="Screen Shot 2020-04-28 at 12 45 46 PM" src="https://user-images.githubusercontent.com/28145373/80518875-196caf00-8955-11ea-9385-8f209f4c5f0f.png">

## Expected result:
Should be like this as it is in 1.9.x and 1.10.x
<img width="695" alt="Screen Shot 2020-04-28 at 12 46 02 PM" src="https://user-images.githubusercontent.com/28145373/80518893-1ffb2680-8955-11ea-9eca-612b787b5173.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.8.85 Chromium: 81.0.4044.122 (Official Build) (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? reproduces in 1.8.x
- Can you reproduce this issue with the beta channel? no, does not reproduce in 1.9.x
- Can you reproduce this issue with the dev channel? no, does not reproduce in 1.9.x
- Can you reproduce this issue with the nightly channel? no, does not reproduce in 1.10.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @bsclifton @brave/legacy_qa

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/5413

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
- Verified the STR from the description
- ensured that the `TECHNIK` radio button is selected when Technikke image shown in NTP
![image](https://user-images.githubusercontent.com/38657976/80939953-df3f5980-8dfb-11ea-93bc-48e1e3773421.png)
- ensured that default brave images are shown in NTP when `Brave default images` radio button is selected
![image](https://user-images.githubusercontent.com/38657976/80940072-35140180-8dfc-11ea-82b4-ed7afe4004e2.png)
