### ISSUE TITLE
Needlessly difficult to select only the visible part of the URL in the address bar

### ISSUE THREAD

**Issue by GirkovArpa** [brave/brave-browser#9520]
## Description 
Can't select website name and suffix without the `https://www.` prefix, unless you first click twice in the address bar.

## Steps to Reproduce

   1. Select `github.com` in the address bar.
   2. Observe that the `https://www.` prefix is revealed and also part of your selection.
   3. Feel bad.

## Actual result:
[![Image from Gyazo](https://i.gyazo.com/d2048c29a3adc56462a2787aa2595d30.gif)](https://gyazo.com/d2048c29a3adc56462a2787aa2595d30)

## Expected result:
Select only `github.com`.

## Reproduces how often: 
Anytime there is more to the URL after `.com/`.  For instance, selecting works as intended if you're at `https://www.github.com` but not at `https://github.com/brave`.

## Brave version (brave://version info)
Brave: 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
Revision: e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS: Windows 10 OS Version 1803 (Build 17134.885)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Not sure.
- Can you reproduce this issue with the beta channel? Not sure.
- Can you reproduce this issue with the dev channel? Not sure.
- Can you reproduce this issue with the nightly channel? Not sure.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome?  I don't know.

**Comment by Johann999** [comment]
I wish that the full address is always displayed by default.
