### ISSUE TITLE
[Android] Claim grant doesn't update wallet balance

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9524]
## Description 
Claim grant doesn't update wallet balance

## Steps to reproduce 

   1. Upgrade/Install 1.7.102
   2. Claim Ads and UGP grants
   3. Wallet balance doesn't upgrade

## Actual result 
Claim grant doesn't update wallet balance but grant is removed 

## Expected result
Wallet should be updated with balance

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: 10
   
## Brave version
1.7.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?  NA

**Comment by srirambv** [comment]
Seems to be intermittent issue. On a clean install was able to claim UGP grants

**Comment by NejcZdovc** [comment]
@srirambv can you please run this with logs? to see if there is a server error or client side

**Comment by srirambv** [comment]
@NejcZdovc  this is the log for ad grant when I was able to claim grant successfully on one of the device 
[grant-claim-log.txt](https://github.com/brave/brave-browser/files/4550320/grant-claim-log.txt)

Unfortunately I don't have the install where the issue happened coz I had to uninstall and reinstall it to try again.

**Comment by NejcZdovc** [comment]
if it's successful, then it's fine. If you are able to reproduce it again please send logs over. Thank you

Based on the fact that is intermittent, do you think it's still release blocker?

**Comment by srirambv** [comment]
No not a release blocker. Not sure if it was a backend issue which was causing the problem. I will try it a few times and if I cant reproduce it will close the issue

**Comment by NejcZdovc** [comment]
thank you

**Comment by srirambv** [comment]
Tried this a bunch of times but can't reproduce the issue again. So closing the issue. Will reopen if it happens again

**Comment by srirambv** [comment]
Reopening the issue as this is an issue on Desktop as well. https://github.com/brave/brave-browser/issues/9482

**Comment by deeppandya** [comment]
@srirambv can you check if it's still relevant after BRE changes ?

**Comment by srirambv** [comment]
@deeppandya this can be closed. I tried on 1.21.20 and issue doesn't repro anymore.
