### ISSUE TITLE
DDG toggle button is not updated in guest window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#9525]
STR:
1. Open Guest window
2. Click DDG button
3. DDG button should be toggled but it's not changed. But search provider is properly set.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.30)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5414
- Verified that DDG button can be toggled in Guest window and DDG is used as search engine 
![image](https://user-images.githubusercontent.com/38657976/85122598-70e81680-b244-11ea-8071-0d48167eec10.png)
