### ISSUE TITLE
Start shared lib only if rewards is enabled

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9526]
We should check preferences (now that we have it) if rewards is enabled or not. If it's not we should not start shared lib.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5924

Clean profile, Rewards not enabled, confirmed `BAT Ledger Service` is not running:
<img width="1191" alt="9526 - clean profile" src="https://user-images.githubusercontent.com/28145373/89041203-fc0ffe00-d312-11ea-81af-a58266a37801.png">

Enabled Rewards, confirmed `BAT Ledger Service` is running:
<img width="1190" alt="9526 - Rewards enabled" src="https://user-images.githubusercontent.com/28145373/89041209-fe725800-d312-11ea-9bd2-33e9e2e685ec.png">

Confirmed able to claim UGP grant:
<img width="1022" alt="9526 - confirmed able to claim UGP grant" src="https://user-images.githubusercontent.com/28145373/89041220-00d4b200-d313-11ea-93b8-e54cd7270af8.png">

Disabled Rewards, confirmed `BAT Ledger Service` is not running:
<img width="1196" alt="9526 - Rewards disabled" src="https://user-images.githubusercontent.com/28145373/89041226-04683900-d313-11ea-8c7e-34bdb63830d9.png">

* Encountered and logged https://github.com/brave/brave-browser/issues/11038 - re-enabling Rewards from panel doesn't work but looks like it did
* Encountered and logged https://github.com/brave/brave-browser/issues/11039 - re-enabling Rewards from NTP widget doesn't look like it works but it did

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.109 x64 build
- Verified toggle rewards on page and enabling it via panel updates the state correctly on panel and page
--------
Verification passed on Samsung Tab A with Android 10 running 1.12.109 x64 build
- Verified toggle rewards on page and enabling it via panel updates the state correctly on panel and page
