### ISSUE TITLE
Add promotion info to rewards internals page

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9527]
We should add claimed promotions to internals page. We should also display how much BAT for each promotions is left.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified `Promotions` section is present in `brave://rewards-internals`. Verified promotions are properly displayed
![image](https://user-images.githubusercontent.com/34715963/83483850-e497ce80-a4a3-11ea-98b5-f8dafb92861e.png)
