### ISSUE TITLE
Rewards widget is shown in NTP when Binance settings is enabled in brave://settings/newTab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9529]
## Description 

When Brave Rewards and Binance settings are set to OFF, Rewards widget is shown in NTP when Binance settings is enabled in brave://settings/newTab

## Steps to Reproduce

   1. Set OS locale to Japan
   2. Install Brave nightly 1.8.55
   3. Make sure Binance and Rewards widget is shown
   4. Turn OFF both Binace and Rewards widgets in Dashboard settings
   5. Open an NTP and make sure Binance and Rewards widget isn't shown in NTP
   6. Upgrade to Brave nightly 1.10.15
   7. Navigate to NTP which is already opened in steps 5 and ensure Binance and Rewards widget isn't shown in NTP
   8. Open Dashboard settings and ensure there is no Binace settings and Rewards switch is in OFF state
   9. Navigate to brave://settings/newTab and ensure Binace option is in OFF state
   10. Enable the Binance option
   11. Open a NTP which shows Brave Rewards widget even though Rewards is OFF in both Dashboard and brave://settings/newTab settings
   

## Actual result:

https://drive.google.com/open?id=1LvuPr_KEv4ptRbsMDH0mvSbjmf_SM3JM
Rewards widget is shown in NTP when Binance settings is enabled in brave://settings/newTab
![image](https://user-images.githubusercontent.com/38657976/80576110-40dd7d80-8a22-11ea-8f1b-720433f48183.png)

## Expected result:
Rewards widget should not be shown in NTP when Binance settings is enabled in brave://settings/newTab

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.15 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @ryanml

**Comment by ryanml** [comment]
@GeetaSarvadnya I believe this is actually expected.

There exists this logic to show the widget in two cases, one where Rewards is enabled, or one where there is a sponsored image showing: https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/containers/newTab/index.tsx#L485 (Note in your picture the messaging reflecting that they can get paid for this)

So unless the widget shows when toggled off on non-sponsored image NTP's, I think we can close this. Maybe there should be an additional path though that users can take to have it off and still show sponsored images. cc: @rebron @karenkliu

**Comment by GeetaSarvadnya** [comment]
@ryanml The issue isn't reproducible as the Binance option is removed from from brave://settings/newTab settings for `Japan` locale (https://github.com/brave/brave-browser/issues/9416 - fixed) The issue was reproducible only when I turn on Binance option from settings. Good to close the issue as it's not reproducible now.

@ryanml Reg Rewards widget it was shown even in normal NTP including sponsored images NTP's anyways now the issue is not reproducible as Binance option is removed from `brave://settings/newTab settings` for `Japan` locale
