### ISSUE TITLE
have a way to view server errors in UI

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9533]
## Description 

On brave://rewards-internals page would be great to have a way to show any errors returned from the server that are currently only visible in terminal logs. 

## Steps to Reproduce

   1. Have Rewards enabled
   2. Encounter some error that is only visible in the terminal logs (perhaps server is returning some error)
   3. Be confused Rewards is not behaving as you expect, but you have no idea why

## Actual result:

No way to see any debugging info in the UI

## Expected result:
Be able to go to a page like brave://rewards-internals and see an "errors" section (or similar) that lists errors (maybe only going back X number of days), as well as date/time stamp. Perhaps including request/response might be useful as well.

cc @NejcZdovc for consideration

**Comment by NejcZdovc** [comment]
And not just network, but output from shared libs as well. This should be split between ads and rewards, so that user can load one or another in internals page. I think this needs to be recorded in a file and be per session for example.

**Comment by tmancey** [comment]
Discussed with privacy team and the log should be deleted when clearing browsing history and not log any diagnostic information when private browsing

**Comment by LaurenWags** [comment]
Verified passed using 1.11.91 and 

```
Brave	1.11.92 Chromium: 84.0.4147.68 (Official Build) dev (64-bit)
Revision	e7b7234037639b407e69c5428c891ce018cd6c0d-refs/branch-heads/4147@{#772}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5600
* Confirmed `Rewards.log` is written to the user profile Default folder
* Confirmed Rewards.log is curtailed to the last 20,000 lines when restarting the browser
* Confirmed able to auto-refresh log in brave://rewards-internals (refresh every 5s checkbox works)
* Confirmed able to refresh log in brave://rewards-internals
* Confirmed Rewards.log is curtailed to the last 20,000 lines when the log exceeds 10mb
* Confirmed able to download log from the download button on brave://rewards-internals
* Confirmed able to clear log in brave://rewards-internals
* Confirmed after clearing the logs, and then generating some log messages (tip, etc), I was able to view logs again. The cleared logs did not display on brave://rewards-internals or in `Rewards.log` file.
* Spot checked logs for various expected messaging (balance calls for restored wallet, tip information, etc)
* No obvious performance regressions noted (have been using Beta 1.11.x on personal profile for several weeks and didn't notice perf issues).

**Comment by LaurenWags** [comment]
Per discussion with @srirambv  removed `OS/Android` tag and logged android specific issue - https://github.com/brave/brave-browser/issues/10712
