### ISSUE TITLE
Memo should be shown for applicable assets in Binance summary

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9535]
## Description 
Currently, the deposit address is the only deposit data point taken in to account for assets. We should be using the deposit memo for assets like EOS

## Test Plan:

1. Connect via Oauth to the Binance widget
2. Click in to EOS in the Deposit view
3. See memo id displayed instead of a deposit address
4. Ensure the memo can be copied
5. Ensure the QR code scans to the memo id
6. Ensure other assets such as BTC, ETH, and LTC show the deposit address as expected.

<img width="303" alt="Screen Shot 2020-04-20 at 5 29 25 PM" src="https://user-images.githubusercontent.com/8732757/80636434-5480e800-8a12-11ea-91a9-eaa849d57949.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.4 x64 Catalina` using the following build:

```
Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
```

* ensured that the cases outlined under both https://github.com/brave/brave-browser/issues/9535#issue-609293051 & https://github.com/brave/brave-core/pull/5267#issuecomment-623149001 passed without any issues
* ensured that the `Rewards` widget is the default widget on a clean install
* ensured that the `EOS Deposit Memo` address is being displayed
* ensured that the QR code is being displayed for `EOS`
* ensured that clicking on `Copy` correctly copies the `EOS Deposit Memo`
* ensured that the `EOS Deposit Memo` address was being displayed after upgrading from
   * `1.8.86 CR: 81.0.4044.129` --> `1.8.89 CR: 81.0.4044.129`
   * `1.10.19 CR: 81.0.4044.129` --> `1.10.24 CR: 81.0.4044.129`

<img width="343" alt="Screen Shot 2020-05-04 at 12 16 34 AM" src="https://user-images.githubusercontent.com/2602313/80935874-9d32fb00-8d9c-11ea-8563-5b889ab0abd3.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{# 979}
OS | Linux

- Verified test plan from issue description
- Verified all coins listed in deposit has address shown even for 0 balance
- Verified QR code is shown for all coins even for 0 balance
- Verified copy button copies address to clipboard
- Verified upgrading from `1.8.86` to `1.8.89` populates address for all 
- Verified Memo ID is shown for available coins (BNB/XRP/EOS)
- Logged #9605 for missing address and only showing Memo id
- Logged #9606 for not showing all memo id's 
-------------
Verification passed on 

Brave | 1.8.89 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{# 979}
OS | Windows

- Verified test plan from issue description
- Verified all coins listed in deposit has address shown even for 0 balance
- Verified QR code is shown for all coins even for 0 balance
- Verified copy button copies address to clipboard
- Verified upgrading from `1.8.86` to `1.8.89` populates address for all 
- Verified Memo ID is shown for available coins (BNB/XRP/EOS)
- Encountered #9605 and #9606
