### ISSUE TITLE
[Android] Implement Social Media Blocking

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#9536]
## Test Plan

Specified here: https://github.com/brave/brave-core/pull/6899

## Description
Implement social media blocking settings on Android similar to Desktop: 

<img width="1015" alt="Screen Shot 2020-04-29 at 12 51 02 PM" src="https://user-images.githubusercontent.com/1903815/80640398-30280a00-8a18-11ea-8401-cf726e4861a7.png">

## Designs
Add social media blocking settings in the `Brave Shields & Privacy` section, under `Brave Stats`

![image](https://user-images.githubusercontent.com/2388823/91887134-3ab11500-ec3f-11ea-9b5f-d90422632c9e.png)

## Assets
Figma: https://www.figma.com/file/c5Sq98FXH6oz1z3FL8K3eN/Android-Brave-Shields?node-id=0%3A420

**Comment by anthonypkeane** [comment]
@karenkliu when you have a moment mock up an Android design for this one and add it here? Thank you.

**Comment by karenkliu** [comment]
Designs added!

**Comment by pes10k** [comment]
Just noting that this issue was also (indirectly) raised in a community thread, if that helps with prioritization:

https://community.brave.com/t/found-https-2a-firebase-app-com-in-allowed-cookies/154373 as discussed in https://github.com/brave/brave-browser/issues/11679

**Comment by jonathansampson** [comment]
Recently mentioned here as well: https://twitter.com/nairulislam/status/1309141451859726337

**Comment by btlechowski** [comment]
Verification passed on Brave v1.16.68 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from https://github.com/brave/brave-core/pull/6899

1. Verified social media blocking options is listed under privacy and Google/Facebook/Twitter is enabled by default and Linkedin is disabled
![Screenshot_20201026-233838_Brave](https://user-images.githubusercontent.com/34715963/97238535-e911aa80-17e9-11eb-9e3d-4a9ae92929d3.jpg)


2. Verified toggle settings and reloading the pages works correctly on `https://fmarier.github.io/brave-testing/social-widgets.html`

![Screenshot_20201026-234713_Brave](https://user-images.githubusercontent.com/34715963/97238585-fdee3e00-17e9-11eb-804e-1314dc69d0e3.jpg) | ![Screenshot_20201026-234921_Brave](https://user-images.githubusercontent.com/34715963/97238601-0a729680-17ea-11eb-82aa-b4cde8abb776.jpg)
-- | --

3. Verified test login works on the following sites
    - `https://quora.com` FB login works when FB setting is enabled 
    - `https://www.expensify.com/` Turned off: Went through login process, but was unable to login; Turned on: Was able to login
4. Verified the sites from the following issues only work when respective setting is enabled

`brave/browser-laptop#2014`
![Screenshot_20201027-001104_Brave](https://user-images.githubusercontent.com/34715963/97238790-7fde6700-17ea-11eb-8998-19e27028b70c.jpg) | ![Screenshot_20201027-001211_Brave](https://user-images.githubusercontent.com/34715963/97238797-879e0b80-17ea-11eb-8b23-77ab7835a49a.jpg)
-- | --


`brave/browser-laptop#1208`
![Screenshot_20201027-001334_Brave](https://user-images.githubusercontent.com/34715963/97238833-9ab0db80-17ea-11eb-80ca-2afcd2c1501e.jpg) | ![Screenshot_20201027-001356_Brave](https://user-images.githubusercontent.com/34715963/97238861-a7cdca80-17ea-11eb-9b69-33291e3b7d20.jpg)
-- | --

5. Verified Google login for `https://pinterest.com/login/` only works when the option is enabled
6. Verified disabling Google Login and navigating to Settings > Site Settings > Cookies doesn't show any exceptions in the list
![Screenshot_20201026-235900_Brave](https://user-images.githubusercontent.com/34715963/97238890-b87e4080-17ea-11eb-962d-d5c59c9688cc.jpg)


Logged https://github.com/brave/brave-browser/issues/12336 for missing translations
