### ISSUE TITLE
Cannot close the ad popup

### ISSUE THREAD

**Issue by osyed** [brave/brave-browser#9541]
I just installed the Brave browser on Linux Mint. Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

I turned on viewing ads. When a popup for an ad was shown there was no way to close the popup. The only thing I could do was click on the ad, which opened the advertiser page in another tab and closed the popup. That was the only way to close the popup. There used to be a small X button in the ad to close it (on Windows). Why is that not available on Linux Mint. I have turned off viewing ads since this is so annoying. No one would want to view the ads if they can't close it without having to visit the advertiser page. Also this is highly unfair to the advertisers who have to pay for the click and would think that I am interested in their product because I clicked on the ad. This needs to be fixed ASAP.

**Comment by Sardine12** [comment]
Same here, the popup fade by itself after some times

Kernel: 5.3.0-51-generic x86_64 bits: 64 Desktop: MATE 1.22.2 Distro: Linux Mint 19.3 Tricia
1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

![Capture du 2020-04-30 11-31-29](https://user-images.githubusercontent.com/64584365/80695987-0a156f00-8ad7-11ea-9d86-9231227e5ab2.png)

Fresh install on MATE, BUT, it used to work fine on mint Cinnamon

**Comment by rebron** [comment]
Closing per comment from @Sardine12 as it does like Mint theme notification issue.
