### ISSUE TITLE
BAT Confirmations should not be started if Rewards is disabled

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9544]
BAT Confirmations should not be started if Rewards is disabled

**Comment by btlechowski** [comment]
@tmancey I can see confirmations being initialized on clean profile(Started Brave on clean profile). Is this expected?
```
[15253:15253:0604/035425.021553:INFO:confirmations_impl.cc(57)] Initializing confirmations
```

Brave | 1.10.82 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

**Comment by btlechowski** [comment]
Talked to @tmancey. The above is not expected, but it does not reproduce in 1.11.x. I logged https://github.com/brave/brave-browser/issues/10085
