### ISSUE TITLE
website appearing under both "Allow" and "Block" under "brave://settings/content/javascript" breaking "Scripts blocked"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#9545]
## Description 

You can get into a case where the same website is listed under `brave://settings/content/javascript` as both `Block` and `Allow` as exampled in the screenshot below. When this occurs, the `Scripts blocked` basically breaks within Brave Shields.

## Steps to Reproduce

   1. launch brave and visit https://brianbondy.com
   2. enable `Scripts blocked` via shields which will add `brianbondy.com` into `Block` under `brave://settings/content/javascript` 
   3. go back to the https://brianbondy.com (should be blocked)
   4. click on the `Javascript icon` via the URL bar and select `Always allow JavaScript on https://brianbondy.com` and click on `Done` which will add `https://brianbondy.com:443` into the `Allow` category
    
You'll notice that the `Scripts blocked` toggle will break.

## Actual result:

The same website shouldn't be listed twice under `brave://settings/content/javascript` which breaks the `Scripts blocked` toggle. 

![Annotation 2020-04-29 232936](https://user-images.githubusercontent.com/2602313/80669927-942bec00-8a73-11ea-98cc-87d3a252c049.jpg)

## Expected result:

Shouldn't be adding the same website twice for both `Allow` and `Blocked` under `brave://settings/content/javascript`.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.815)
```

```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1909 (Build 18363.815)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @rebron @brave/legacy_qa

**Comment by bsclifton** [comment]
cc: @mkarolin @bridiver - we changed our behavior with C81. Basically, the hostname is recorded without the port number. Or it's supposed to be recorded without the port number

**Comment by bridiver** [comment]
@kjozwiak this is the correct behavior. If you use the chromium script icon it will specify the https version which takes precedence over the non-port version that is added by shields.

**Comment by mkarolin** [comment]
I think it's expected behavior. When blocking the site scripts using the Shields toggle the site is added to Blocked with all protocols (http, https, etc.) and all ports. When later enabling scripts via the icon on the URL bar you essentially creating an exception from the previous rule for https (port 443) specifically. If you were to go to an http site or https://... :8080 the scripts would be blocked.
