### ISSUE TITLE
URI/OminBar clips URI even when space is available

### ISSUE THREAD

**Issue by Golutazem** [brave/brave-browser#9546]
The URI or address or omni bar does not use available space. On my wide screen monitor, much space is unused.  When the URI is longer than the available space, the text is clipped. The bar does not expand.

This appears to be a problem which is specific to Brave -- Chromium does not have this problem.  Neither did earlier versions of Brave.

The image shows Brave with long text in the bar and much unused available space. The other side also has that much unused space.
![BraveBar](https://user-images.githubusercontent.com/1553700/80682883-99b12280-8ac3-11ea-8d15-7c6cdb1c5adc.png)

**Comment by rebron** [comment]
@Golutazem We have a setting for `Wide Address Bar` here. 
brave://settings/appearance

Does that work for you?

**Comment by Golutazem** [comment]
Yes, that setting can be considered to solve it. It would be better to have it automatically expand as needed.
Alternatively, it could remain wide and URIs or addresses entered could be centered in the field.
