### ISSUE TITLE
Wallet shows default ETH symbol instead of the defined in the Custom RPC

### ISSUE THREAD

**Issue by eMaringolo** [brave/brave-browser#9549]
## Description 
I'm connected to RSK Mainnet using Brave's wallet and all balances, fees, etc are shown using the ETH symbol instead of the one I defined in a custom RPC. It also ignores the custom block explorer setting.

## Steps to Reproduce
I'm experiencing this while using https://alpha.moneyonchain.com

   1. Go to `brave://wallet`
   2. Open the networks drop-down and select Custom RPC
   3. Enter a custom RPC network (details at the bottom).
   4. Add Network

## Actual result:
![image](https://user-images.githubusercontent.com/1625589/80705332-a0886700-8abc-11ea-820f-c56a0a30981f.png)

## Expected result:
Same as above but with the custom symbol instead.
(and ideally with a custom icon as well)

Screenshot from Chrome with Metamask.
![image](https://user-images.githubusercontent.com/1625589/80705796-75524780-8abd-11ea-9feb-7927e3ebf65b.png)

## Reproduces how often: 
Always. Also in other screens involving signing transactions.

## Brave version (brave://version info)
Brave | 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
-- | --
Revision | e3225dafb0475864a1812a374d73a92e391635ac-refs/branch-heads/4044@{#936}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
It does not happen with Metamask directly.

## Miscellaneous Information:

[RSK](https://rsk.co) Custom RPC Details
     * Network name: RSK Mainnet
     * RPC: https://public-node.rsk.co
     * Symbol: RBTC
     * Explorer: https://explorer.rsk.co

**Comment by bbondy** [comment]
@eMaringolo I think this is probably also an issue in MetaMask, can you confirm? If so I think it might be best to post this here https://github.com/MetaMask/metamask-extension/issues/new/choose

**Comment by eMaringolo** [comment]
@bbondy Do I still have to report it on MetaMask or did the Brave wallet forked from it?

**Comment by bbondy** [comment]
Sorry, I'll re-open this now since due to the MetaMask licensing changes we've hard forked.

**Comment by ryanml** [comment]
This is no longer an issue on the latest version of Crypto Wallets:

<img width="1112" alt="Screen Shot 2020-10-11 at 9 06 44 PM" src="https://user-images.githubusercontent.com/8732757/95704463-bff7f400-0c05-11eb-9b3a-d142e201f77d.png">

cc: @eMaringolo @bbondy
