### ISSUE TITLE
[Desktop] sometimes images are not being displayed for promo cards under "brave://rewards" - follow up to 8964

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9553]
## Description 

Issue originally reported with #8964 except now on Dev we also have P2P, and issue occurs for that as well.

Sometimes the image isn't shown on the TAP and P2P message boxes on brave://rewards. Page refresh fixes the issue.

## Steps to Reproduce

   1. Clean profile, US locale, staging env
   2. Enable Rewards
   3. On brave://rewards page, click on Verify Wallet
   4. Click on Verify Wallet on modal
   5. On Uphold page, login to an already KYC'd wallet
   6. You are directed back to brave://rewards page. 

## Actual result:

When you're directed back to brave://rewards page after connecting your wallet, look below the wallet panel at TAP and P2P boxes:
<img width="445" alt="Screen Shot 2020-04-30 at 10 39 01 AM" src="https://user-images.githubusercontent.com/28145373/80724007-50ff6680-8acf-11ea-94d5-5d1862474508.png">

## Expected result:
After page refresh:
<img width="422" alt="Screen Shot 2020-04-30 at 10 42 49 AM" src="https://user-images.githubusercontent.com/28145373/80724039-5bb9fb80-8acf-11ea-8d32-0a11ce7b96bf.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.9.49 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes for TAP, P2P is not in release
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa

**Comment by kjozwiak** [comment]
While QAing https://github.com/brave/brave-core/pull/6427#issuecomment-675626561, ran into the same thing on the following build:

```
Brave | 1.14.48 Chromium: 85.0.4183.69 (Official Build) nightly (64-bit)
-- | --
Revision | 4554ea1a1171bd8d06951a4b7d9336afe6c59967-refs/branch-heads/4183@{#1426}
OS | macOS Version 10.15.6 (Build 19G73)
```

Example:

<img width="389" alt="Screen Shot 2020-08-18 at 1 43 52 PM" src="https://user-images.githubusercontent.com/2602313/90548537-193e2c80-e15b-11ea-8918-22cb7c2e08e0.png">

@rebron @mandar-brave we might want to fix this sooner than later. It's been broken for several months and it looks pretty bad when we push new promo's and users need to refresh the page to see images when the above occurs.

**Comment by LaurenWags** [comment]
This reproduces with the new Gemini promo card (as well as continues to reproduce with existing cards) in 1.29.57.

cc @Miyayes @brave/legacy_qa

**Comment by LaurenWags** [comment]
Uplift verification notes: https://github.com/brave/brave-core/pull/9809#issuecomment-912528416

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.29.79 Chromium: 93.0.4577.63 (Official Build) (64-bit)
-- | --
Revision | ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135}
OS | Windows 10 OS Version 2009 (Build 19043.1165)

```
- Verified the STR from the description and https://github.com/brave/brave-core/pull/9809#issuecomment-912528416

<details>
<summary>Confirmed images display as expected with Uphold as custodian - PASSED</summary>

- Confirmed all the promo cards are shown on the brave://rewards page
- Click on `Verify wallet`, nav to wallet selection and logged in with Uphold account and navigated back to the brave://rewards page automatically, the promo cards were now showing their images without page refresh as expected
![image](https://user-images.githubusercontent.com/38657976/132494711-185bcb3a-eb67-4410-93bc-d1a07030b4f4.png)

</details>

<details>
<summary>Confirmed images display as expected with Gemini as custodian - PASSED</summary>


</details>
