### ISSUE TITLE
[Android] Onboarding V2

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#9555]
## Description 

Please search for the spec called "Mobile Onboarding (Retention Focused)" and implement per those details.

## Design

The new onboarding experience is broken up into smaller parts that are spread out over the course of a user lifecycle. 

### Day 1 - Limited feature tour

Users are introduced to privacy messaging and Brave Stats. 

![Android NTP forced privacy intro](https://user-images.githubusercontent.com/2388823/81882753-59808400-9548-11ea-829c-5b2d9e8e7e90.png)

Prototype: https://www.figma.com/proto/atoL4LN2kd8ILnPGwohUoV/Mobile-onboarding-v2?node-id=359%3A9605&viewport=366%2C329%2C0.3447243273258209&scaling=min-zoom

On the last screen, after the user taps "Turn on privacy stats", the dummy data in Brave Stats blurs into focus and increments down: **prototype TBA**

###  Day 1-30: Just-in-time Onboarding

Users are introduced to search engine alternatives (and setting a default) the first time they search.

![Search Engine discovery intro](https://user-images.githubusercontent.com/2388823/84309887-a2ab0000-ab15-11ea-8b11-c0c642684715.png)

Users are introduced to Brave Shields the first time it blocks something. Introductory popover only shows once.

![Shields discovery intro](https://user-images.githubusercontent.com/2388823/81741118-e47f5280-9452-11ea-9df8-9954c2b79c84.png)

The popover has a gradient background.
`background: linear-gradient(316.3deg, #BF14A2 0%, #F73A1C 98.59%);
`

The popover slides in as soon as the page is finished loading y-10, 0.3s with opacity:

![android shields intro](https://user-images.githubusercontent.com/2388823/81730795-e9d4a100-9442-11ea-97d4-9063915515e7.gif)

Prototype: https://www.figma.com/proto/atoL4LN2kd8ILnPGwohUoV/Mobile-onboarding-v2?node-id=403%3A300&viewport=545%2C466%2C0.7327766418457031&scaling=min-zoom

Users can discover the Brave Rewards feature by tapping on the BR icon or seeing a sponsored image on the new tab page.

![Brave Rewards discovery intro](https://user-images.githubusercontent.com/2388823/81741066-cdd8fb80-9452-11ea-8a80-265b4f0810d9.png)

### Day 4

Users are forcefully introduced to Brave Rewards on Day 4 - they see BR opt-in and Brave Ads onboarding on app open.

![Brave Rewards forced intro](https://user-images.githubusercontent.com/2388823/81731192-72ebd800-9443-11ea-8b70-6d2be38823f8.png)

### Push notifications
Deliver push notifications per spec.

## Assets
All motion graphics will be done using Lottie files.

- Each stat number and the stats icon is highlighted with a pulsing circle expanding outwards and fading. Play these animations only once; you can do this with:
`// Loop indefinitely
        app:lottie_loop="false"`
ads blocked preview: https://lottiefiles.com/share/GCzfOG
https://assets10.lottiefiles.com/packages/lf20_GCzfOG.json
data saved preview: https://lottiefiles.com/share/iUrj8U
https://assets10.lottiefiles.com/packages/lf20_iUrj8U.json
time saved preview: https://lottiefiles.com/share/7U0Nil
https://assets6.lottiefiles.com/packages/lf20_7U0Nil.json
- Privacy protection preview: https://lottiefiles.com/share/7tYphH
https://assets8.lottiefiles.com/packages/lf20_7tYphH.json
- Save data and battery preview: https://lottiefiles.com/share/QVdrmA
https://assets2.lottiefiles.com/packages/lf20_QVdrmA.json
- Websites load faster preview: https://lottiefiles.com/share/wclijk
https://assets5.lottiefiles.com/packages/lf20_wclijk.json

Figma for CSS, sizing, layout, spacing: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/Mobile-onboarding-v2?node-id=0%3A1

## Related Issues
https://github.com/brave/brave-browser/issues/8360
https://github.com/brave/brave-browser/issues/9693
https://github.com/brave/brave-browser/issues/9865

**Comment by karenkliu** [comment]
@deeppandya All the design specs except for the Day 1 privacy intro modals have been added.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.13.83 x64 nightly build

**Clean Install**
- Verified privacy stats onboarding is shown the moment browser is launched

First info card about `Privacy protection` highlights `Trackers & Ads blocked` | Second info card about `Save data and battery` highlights `Data Saved`  | Third info card about `Websites loads faster` highlights `Est. Time saved` | Fourth info card about `Get weekly updates`
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/91982745-9bfde480-ed22-11ea-871c-1448dd58fc1a.png) | ![image](https://user-images.githubusercontent.com/17010094/91982755-a02a0200-ed22-11ea-8022-816c3a6cf044.png) | ![image](https://user-images.githubusercontent.com/17010094/91982771-a61fe300-ed22-11ea-8a16-31ce75e82139.png) | ![image](https://user-images.githubusercontent.com/17010094/91987848-78d53400-ed26-11ea-82a7-26fb3fa5c051.png)


- Verified clicking `Turn on privacy reports` on the first screen and following through brings up the privacy reports modal once onboarding is completed

Light theme | Dark Theme
-- | --
![onboardlight](https://user-images.githubusercontent.com/17010094/91983632-de73f100-ed23-11ea-9e11-729e0f03b0b9.gif) | ![onboarddark](https://user-images.githubusercontent.com/17010094/91983725-eaf84980-ed23-11ea-9074-e203193f9bf2.gif)

- Verified swiping across the privacy onboarding brings up the fourth info card and clicking on `Learn more` starts the onboarding again

Light theme | Dark Theme
-- | --
![onboarding-skip-light](https://user-images.githubusercontent.com/17010094/91986574-c355b100-ed24-11ea-9133-a3e448fcf0e0.gif) | ![onboarding-skip-dark](https://user-images.githubusercontent.com/17010094/91986614-d23c6380-ed24-11ea-81f7-7a1c7b1170a7.gif)

- Clicking on individual stats on NTP brings up `Privacy report` modal when enabled
- Clicking on Individual stats on NTP brings up the fourth card when privacy stats is not enabled

**Search Engine discovery**
- Verified clicking on the URL bar brings up the SE onboarding 
- Verified changing default search engine via onboarding is retained
- Verified changing/retaining default search engine is set for both normal and private tabs

**Brave Shields**
- Verified visiting a page for the first time where nothing is blocked doesn't bring out the shields message
- Verified visiting a page for the first time shows shields onboarding message when the page load is done
- Verified clicking on the shields message opens the Shields panel 
- Onboarding message is dismissed when a tap is recorded anywhere on the app

**Rewards**
- Verified on clean install clicking on the rewards button brings up rewards onboarding as per spec
- Verified if not enabled, Rewards onboarding is shown upon launch after 4 days
- Clicking on sample ad notification sets focus to rewards panel

**Brave Desktop intro**
- Verified Brave Desktop intro card is shown after 12 days
- Verified intro card is shown on a private tab if the browser is launched via a private tab on the home screen

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/91987136-905fed00-ed25-11ea-8d36-7c7a78b40063.png) | ![image](https://user-images.githubusercontent.com/17010094/91987145-9524a100-ed25-11ea-9243-f9d3ea54b611.png)

**Upgrade Install**
- Verified stat button is shown on an upgrade on NTP
- Verified interaction hotspot is shown on the stats button on NTP
- Verified clicking it loads the privacy stats onboarding

-----------------------
Verification passed on Samsung Tab A with Android 10 running 1.13.83 x64 nightly build

**Clean Install**
- Verified privacy stats onboarding is shown the moment browser is launched

First info card about `Privacy protection` highlights `Trackers & Ads blocked` | Second info card about `Save data and battery` highlights `Data Saved`  | Third info card about `Websites loads faster` highlights `Est. Time saved` | Fourth info card about `Get weekly updates`
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/91987523-15e39d00-ed26-11ea-82b3-2af9da9d6d64.png) | ![image](https://user-images.githubusercontent.com/17010094/91987535-1a0fba80-ed26-11ea-94f2-d1621ad9c0ee.png) | ![image](https://user-images.githubusercontent.com/17010094/91987556-20059b80-ed26-11ea-8c1b-0711c6219176.png) | ![image](https://user-images.githubusercontent.com/17010094/91987565-2562e600-ed26-11ea-8666-ffa77fea2cf3.png)

- Verified clicking `Turn on privacy reports` on the first screen and following through brings up the privacy reports modal once onboarding is completed

Light theme | Dark Theme
-- | --
![tablight](https://user-images.githubusercontent.com/17010094/91989722-bfc42900-ed28-11ea-9ee9-7785859c0008.gif) | ![tabdark](https://user-images.githubusercontent.com/17010094/91989783-d36f8f80-ed28-11ea-82ac-789ef95ffe3a.gif)

- Verified swiping across the privacy onboarding brings up the fourth info card and clicking on `Learn more` starts the onboarding again

Light theme | Dark Theme
-- | --
![tablightskip](https://user-images.githubusercontent.com/17010094/91989902-f9952f80-ed28-11ea-9ab5-0fcc02dc6cdd.gif) | ![tabdarkskip](https://user-images.githubusercontent.com/17010094/91989963-0a45a580-ed29-11ea-8658-e145b20f9cd8.gif)

- Clicking on individual stats on NTP brings up `Privacy report` modal when enabled
- Clicking on Individual stats on NTP brings up the fourth card when privacy stats is not enabled

**Search Engine discovery**
- Verified clicking on the URL bar brings up the SE onboarding 
- Verified changing default search engine via onboarding is retained
- Verified changing/retaining default search engine is set for both normal and private tabs

**Brave Shields**
- Verified visiting a page for the first time where nothing is blocked doesn't bring out the shields message
- Verified visiting a page for the first time shows shields onboarding message when the page load is done
- Verified clicking on the shields message opens the Shields panel 
- Onboarding message is dismissed when a tap is recorded anywhere on the app

**Rewards**
- Verified on clean install clicking on the rewards button brings up rewards onboarding as per spec
- Verified if not enabled, Rewards onboarding is shown upon launch after 4 days
- Clicking on sample ad notification sets focus to rewards panel

**Brave Desktop intro**
- Verified Brave Desktop intro card is shown after 12 days
- Verified intro card is shown on a private tab if the browser is launched via a private tab on the home screen

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/91988146-d8334400-ed26-11ea-97fe-33055e3188e9.png) | ![image](https://user-images.githubusercontent.com/17010094/91988171-dc5f6180-ed26-11ea-9d80-efbe02bf9fe3.png)

**Upgrade Install**
- Verified stat button is shown on an upgrade on NTP
- Verified interaction hotspot is shown on the stats button on NTP
- Verified clicking it loads the privacy stats onboarding

-----------------------
