### ISSUE TITLE
Reddit tipping button is formatted wrong when mod

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9556]
<img width="672" alt="Screen Shot 2020-04-30 at 8 54 42 AM" src="https://user-images.githubusercontent.com/76526/80740604-2a403080-8acd-11ea-945c-66a06eb1bfea.png">

When logged into Brave as a moderator, the tipping button gets goofy. 

Relevant conversation on slack:

https://bravesoftware.slack.com/archives/CB0KCRCQN/p1583808638264900
https://bravesoftware.slack.com/archives/CB0KCRCQN/p1588262120290900

**Comment by MarkOSullivan94** [comment]
Find this really frustrating, any chance we could have an option to hide the tip option for certain subreddits or for subreddits which people are mods for?

**Comment by srirambv** [comment]
+1 on this on current nightly on Linux

**Comment by GeetaSarvadnya** [comment]
+1 Reproduced the issue in `Windows 10 x64 - 1.24.65` , Enable rewards and visit https://www.reddit.com/user/jsadler-brave
![image](https://user-images.githubusercontent.com/38657976/115362650-60475a80-a1df-11eb-89d6-997104a3c286.png)
