### ISSUE TITLE
Stablecoins are not reflected in total account value [Binance Widget]

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9559]
##  Description 
Stablecoins such as BUSD and USDT are not accounted for in the total account USD/BTC value.

## Steps to Reproduce
   1. Have a mixture of assets in your binance.com account plus BUSD/USDT
   2. Connect to the Binance Widget
   3. Unobscure the account values

## Actual result:
BUSD/USDT are not accounted for the in the total account value (First summary entry)

## Expected result:
The values of those assets should be factored in to the total, in both BTC and USD

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Linux

- Verified on `1.8.90` stablecoins are not part of the total balance
- Verified upgrading from `1.8.90` to `1.8.95`, automatically updates balance to include stablecoin
- Verified on a clean install, widget balance shows cumulative balance of all available assets 
- Verified on upgrade clicking on refresh button immediately updates the balance to include stablecoin
---------------
Verification passed on 

Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS |  macOS Version 10.15.4 (Build 19E287)

- Verified on `1.8.90` stablecoins are not part of the total balance
- Verified upgrading from `1.8.90` to `1.8.95`, automatically updates balance to include stablecoin
- Verified on a clean install, widget balance shows cumulative balance of all available assets 
- Verified on upgrade clicking on refresh button immediately updates the balance to include stablecoin
--------------
Verification passed on 


Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Windows 10 OS Version 1809 (Build 17763.1158)

- Verified on `1.8.90` stablecoins are not part of the total balance
- Verified upgrading from `1.8.90` to `1.8.95`, automatically updates balance to include stablecoin
- Verified on a clean install, widget balance shows cumulative balance of all available assets 
- Verified on upgrade clicking on refresh button immediately updates the balance to include stablecoin

**Comment by LaurenWags** [comment]
Adding `release-notes/include` per discussion with @srirambv
