### ISSUE TITLE
No Option to Preview PDF Files in Browser

### ISSUE THREAD

**Issue by moore-bryan** [brave/brave-browser#9571]
After searching open issues for anything pdf-related and not finding anything, I figured I might as well post this "bug;" although, it may just be a "feature request."

Steps to Reproduce:
     1. Launch Brave.
     2. Navigate to pdf file on the web.
     3. Click the link. 

Actual result:
     1. Download window is presented.

Expected result:
     1. Preview the pdf in-browser.

Reproduces how often: 
     1. Always.

Brave version (brave://version info)

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) unknown (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Linux
JavaScript | V8 8.1.307.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line | /usr/bin/brave-browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,DnsOverHttps --disable-features=AutofillServerCommunication,AllowPopupsDuringPageUnload,TextFragmentAnchor,NotificationTriggers,LookalikeUrlNavigationSuggestionsUI,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /usr/share/brave/brave
Profile Path | /home/bryan/.config/BraveSoftware/Brave-Browser/Default

Version/Channel Information:
I have no other version channels available.

**Comment by rebron** [comment]
@moore-bryan We have an option brave://settings/content/pdfDocuments 
We admit it's hard to find.

Brave defaults to viewing pdfs in the browser and the option is to downlad instead. What you're seeing is #1264 it looks like and is a bug. Will dupe this issue to #1264.

**Comment by moore-bryan** [comment]
Thanks, @rebron, I think it's that issue, too...

**Comment by kcaldwel** [comment]
I have this issue with my banking site.  I have the well hidden toggle set to "off" for downloading pdf files, but saving the file is still the only option I get.  Why can't I set it to open pdf in Document Viewer or something?

Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (64-bit)

System:    Kernel: 5.4.0-65-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal
