### ISSUE TITLE
Add a setting to disable top site and brave suggested site suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9572]
## Description 

Currently you can only completely disable autocomplete. 
It would be good for a user to be able to disable either or both of the alexa top site suggestions and the brave suggested sites. 

<img width="770" alt="Screen Shot 2020-05-01 at 11 12 42 AM" src="https://user-images.githubusercontent.com/831718/80815999-b1a8a500-8b9c-11ea-8ae6-5a13bd99c7a0.png">

# Test plan

- Type Bitcoin and see the Binance suggestion, disable the preference and doing the same should not suggest it anymore.
- Type slash and see the top site suggestion for slashdot.  Do it again with the setting off and it should not show that suggestion.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-browser/issues/9572#issue-610801948

`Show Brave suggested sites in autocomplete suggestions` on:
<img width="1451" alt="Screen Shot 2020-05-19 at 8 03 03 AM" src="https://user-images.githubusercontent.com/28145373/82324898-67029780-99a8-11ea-998c-047c533a7199.png">

`Show Brave suggested sites in autocomplete suggestions` off:
<img width="1458" alt="Screen Shot 2020-05-19 at 8 03 41 AM" src="https://user-images.githubusercontent.com/28145373/82324907-6964f180-99a8-11ea-8813-b793d75162c5.png">

`Show top sites in autocomplete suggestions` on:
<img width="1457" alt="Screen Shot 2020-05-19 at 8 04 00 AM" src="https://user-images.githubusercontent.com/28145373/82324915-6bc74b80-99a8-11ea-9884-db79fbbe9cd7.png">

`Show top sites in autocomplete suggestions` off:
<img width="1453" alt="Screen Shot 2020-05-19 at 8 04 19 AM" src="https://user-images.githubusercontent.com/28145373/82324926-6f5ad280-99a8-11ea-9f35-9c5d548ed2ab.png">
