### ISSUE TITLE
Sponsored images settings gets enabled when background images settings is disabled in brave://settings/newTab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9573]
## Description 

Found while testing the PR https://github.com/brave/brave-core/pull/5310
As per the spec the `Sponsored images` settings should be in disabled state when `Background images` settings is disabled

## Steps to Reproduce

   1. Clean profile 1.10.23
   2. Open a NTP `Dashboard settings` in 1st tab
   3. Open `brave://settings/newTab` in 2nd tab
   4. Turn off Background images settings in Dashboard settings
   5. Changes did not reflect in `brave://settings/newTab`  
   6. Don't refresh the `brave://settings/newTab` page
   7. Disable Background images settings in `brave://settings/newTab`
   8. Enable Background images in dashboard settings
   9. Changes did not reflect in `brave://settings/newTab`  ( don't refresh the page)
  10. Enable Background images in `brave://settings/newTab`
  11. Disable Background images in `brave://settings/newTab`

  **Issue1**: Verify that sponsored images settings gets enabled even though background image is disabled
**Issue2**: Changes which were done in step11 are not reflected in dashboard settings

  
**Note**: This issue is happening because `brave://settings/newTab` settings are not updated instantly after making changes in the dashboard settings. In order to see the changes,  refresh/reload is required in `brave://settings/newTab` tab page

## Actual result:

Sponsored images settings gets enabled when background images settings is disabled in brave://settings/newTab
![Sponsored images option gets enabled in settings page when background images is in disabled state](https://user-images.githubusercontent.com/38657976/80822401-4391cb80-8bf8-11ea-84fb-466675b94b25.gif)

## Expected result:
Sponsored images settings should not gets enabled when background images settings is disabled in brave://settings/newTab

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.10.23 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @karenkliu @simonhong @cezaraugusto @rebron 
please find the more info in the thread https://bravesoftware.slack.com/archives/CKNHM4RTK/p1588327431070000

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine in both `Dev 1.9.55` and `Nightly 1.10.27` builds. Changes made in NTP dashboard settings are reflected in `brave://settings/newTab` instantly and vice versa. Hence closing the issue.

```

Brave | 1.10.27 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
```

Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```

**Comment by GeetaSarvadnya** [comment]
@simonhong Please add the PR which fixed the issue, as I am not finding the PR associated.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified test plan from https://github.com/brave/brave-core/pull/5434
