### ISSUE TITLE
BAT loss in wallet issue

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9574]
## Description 
https://www.reddit.com/r/BATProject/comments/gavez3/uh_oh_the_brave_rewards_server_is_not_responding/

According to this user:

"Yeah WTF is going on, last night before I went to sleep I had 287.3 BAT in my wallet, that was at 9:30 PM last night. I JUST checked today at 11:00 AM and I have only 271.3 BAT - Where did 16 BAT go exactly??"

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by snok1010** [comment]
I have the same issues today

**Comment by snok1010** [comment]
It's the same for me, I have 1 BAT yesterday and today 0,5, and it says that I've seen 5 ads and when I roll out the history I'm in bcp more. 
What can we do to get our BATs back?

**Comment by jsecretan** [comment]
Hi @snok1010, which OS are you using?  Can you also check your version?  And you mean your "estimated earnings" right?  Have you turned ads on and off at all?
