### ISSUE TITLE
[Android] bottom banner on wallet panel on chrome://rewards should match desktop

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9575]
## Description 
Wallet panel of chrome://rewards on Android should be like that of desktop. See images below.

## Steps to reproduce 

   1. Install android version that is uphold wallet capable.
   2. Connect your KYC'd uphold wallet.
   3. Navigate to chrome://rewards and open wallet panel.

## Actual result 
![android-wallet](https://user-images.githubusercontent.com/28145373/80833422-7fa73b00-8bbc-11ea-8fde-ab65434570fa.png)

## Expected result
Same as desktop:
<img width="409" alt="Screen Shot 2020-05-01 at 2 55 26 PM" src="https://user-images.githubusercontent.com/28145373/80833371-68684d80-8bbc-11ea-8a62-008301854fd7.png">

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? Nightly

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): phone
   - Android version: 5.1
   
## Brave version

Brave | 1.10.22 Chromium: 81.0.4044.129 (Official Build) canary (32-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Android 5.1; Nexus 5 Build/LMY47D

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
1.35 solved.
