### ISSUE TITLE
Custom cosmetic filter rules should be applied irregardless of 1p or 3p status

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9577]
Currently cosmetic custom filter rules go through the same 1p vs 3p check that rules pulled from filter lists go through.

This should be changed so that custom filter list rules are always applied, independent of 1p vs 3p determination.

This would have the additional benefit of allowing us to move the rules from the "right click and hide" functionality to be custom filter rules, and unify the two systems (and avoid the duplicate MutationObservers)

**Comment by antonok-edm** [comment]
This is actually already supported!
