### ISSUE TITLE
[Android] Next payment date stuck in ads section

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9579]
## Description 

https://www.reddit.com/r/BATProject/comments/gae86f/rewards_stuck_in_february/

User describes the following: 

"Hi! I'm running the latest Brave on Android 9 and for quite a while now I cannot open the site information from the BAT logo on the address bar, and in the rewards section it says Next payment date 5 Feb. It's been stuck like this for quite a while there, also the number of ads is stuck to 16 (although I recently started getting more ads)."

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yachtcaptain23** [comment]
Root cause and fix discussed in https://github.com/brave/brave-browser/issues/10070.

I'll respond on Reddit.
