### ISSUE TITLE
Display sidebar navigation for Settings page

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#958]
## Test plan
1. Open brave://settings
2. Sidebar should always be shown (even when scrolling up and down), when the window is wide enough
3. Clicking items in sidebar should jump to the content
4. Sidebar should more or less match mockup below

## Description 
Use persistent sidebar navigation in Settings ~and Extensions page~.
chrome://settings
~chrome://extensions~ (edit by petemill: extensions can be a follow-up, several things to discuss - https://github.com/brave/brave-browser/issues/3771)

See mock for appearance, order, styling. 
Should be:
- Get Started
- Extensions 
- Sync
- Shields
- Search
- Appearance

Clicking on links above will take you to the corresponding section on the main screen.

Default collapse -> Additional Settings section.
In order should be:
- Privacy & Security
- Passwords & Autofill
- Languages
- Downloads
- Printing
- Accessibility
- System
- Reset

Show Brave logo and About Brave version.

## Design
![](https://user-images.githubusercontent.com/5951041/45063237-cba98180-b061-11e8-8f36-6a5f5fed200a.png)

**Comment by rebron** [comment]
![sidebar-nav](https://user-images.githubusercontent.com/5951041/45059315-7022c800-b050-11e8-84e8-e84c9ee5b15e.png)

**Comment by rebron** [comment]
![sidebar](https://user-images.githubusercontent.com/5951041/45063237-cba98180-b061-11e8-8f36-6a5f5fed200a.png)
updated file

**Comment by rebron** [comment]
For Reset item on the bottom, point onclick to launch into the Reset settings dialog :
![reset-mock](https://user-images.githubusercontent.com/5951041/45850290-6359d180-bcea-11e8-9cd9-235a9c7f9528.png)

Not here: chrome://settings/reset

**Comment by bsclifton** [comment]
Making good progress here; for those interested, here are the branches to check out:
https://github.com/brave/brave-core/tree/bsc-prefs-sidebar
https://github.com/brave/brave-browser/tree/bsc-prefs-sidebar

**Comment by petemill** [comment]
@rossmoody @bradleyrichter putting 'extensions' as an item in this sidebar makes me uncomfortable since it opens a new page that doesn't have the sidebar, as opposed to every other item, the behavior of which is to scroll the page to the item's section. Should Extensions actually be on the header nav?

**Comment by rebron** [comment]
@petemill the Extensions link in the sidebar should like to the Extensions section in settings where a user can then go to a new page. Same behavior as with Sync right below it.

There are very few access points for Extensions/Extensions manager. Possibly cleaner to have 'Extensions' in the upper nav but we're running out of real estate up there.

**Comment by petemill** [comment]
Reset linking directly to popup covered in another issue @rebron : https://github.com/brave/brave-browser/issues/3772

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

* Side bar navigation is always shown
* Advanced settings dropdown is hidden by default
* Clicking on each setting element loads the corresponding section of the settings page
