### ISSUE TITLE
Refactor Brave Ads OnMediaPlaying, Stopped and IsPlaying to use std::set

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9580]
Refactor Brave Ads OnMediaPlaying, Stopped and IsPlaying to use `std::set`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/5442

Opened youtube and played the video:
```
[5018:1:0603/063354.424877:INFO:ads_impl.cc(1080)] Notification not made: Media playing in browser
```
Paused the youtube video and ad was triggered.

Also verified vimeo and twitch
