### ISSUE TITLE
Update adblocking added via right-click context menu to be editable under the brave://adblock "Custom filters" section

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#9581]
Followup on #8914 and #9577

The right-click cosmetic filtering menu is a useful feature, but uses a different system than the one for custom adblock rules. It should be updated to append new cosmetic filter rules to the custom filters box on brave://adblock.

Any existing element hides added using the right-click method should be migrated to the custom filters box on the first startup of the browser after this change is implemented. Those can be turned into cosmetic filter rules fairly trivially - i.e. `<domain>##<CSS selector>`. The old cosmetic filtering logic (minus the right-click menu) can then be removed completely as in https://github.com/brave/brave-core/pull/5099.

**Comment by stephendonner** [comment]
Verified `PASSED` on `nightly` using the testplan from https://github.com/brave/brave-core/pull/8156

Brave | 1.23.36 Chromium: 89.0.4389.86 (Official Build) nightly (x86_64)
-- | --
Revision | 0c2dac31bc21e806a791641316e99920f84ea52c-refs/branch-heads/4389@{#1472}
OS | macOS Version 11.2.3 (Build 20D91)



### Migration

Using a *previous* browser version (I used `1.21.76`):

1. Visit `brave://adblock` in a new tab
2. Add some text of your choice to the "Custom filters" box

<img width="1312" alt="Screen Shot 2021-03-12 at 10 26 26 AM" src="https://user-images.githubusercontent.com/387249/110993884-c57c7600-832c-11eb-936c-e9a71d730c98.png">


I added:

```
SupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidociousSupercalifragilisticexpialidocious

1234567890
foo
facebook.com
https://www.cnn.com
!@#$%^&*()_+
```
3. Visit a website of your choice

`aol.com` and `twitch.tv`

4. Right-click on a page element of your choice
5. Select "Brave > Block element via selector"
6. Confirm the block
7. Repeat steps 3-6 a few times to block a variety of items through the legacy system. Block multiple items on the same page at least once.  Keep track of what is being blocked.

| aol.com (`1.21.76`) | twitch.tv (`1.21.76`) |
|---------|----------|
<img width="1312" alt="Screen Shot 2021-03-12 at 10 10 40 AM" src="https://user-images.githubusercontent.com/387249/110993965-e6dd6200-832c-11eb-95ef-b21f940715a1.png"> | <img width="1312" alt="Screen Shot 2021-03-12 at 10 25 13 AM" src="https://user-images.githubusercontent.com/387249/110993994-f3fa5100-832c-11eb-8ab9-1d96c0b48f4c.png">


Then, testing the same profile *after* the upgrade (`1.23.36`):

1. Visit `brave://adblock` in a new tab
2. Verify that any text previously added to the "Custom filters" box is still present
3. Verify that new lines have been added to the "Custom filters" box,  including one corresponding to each item previously blocked using the  right click menu

<img width="1224" alt="Screen Shot 2021-03-12 at 10 39 18 AM" src="https://user-images.githubusercontent.com/387249/110994929-66b7fc00-832e-11eb-8ed4-6a562c5b8f8c.png">


4. Revisit some of the websites and confirm that any previously blocked items are still hidden

| aol.com (`1.23.36`) | twitch.tv (`1.23.36`) |
|---------------------|---------------------|
<img width="1312" alt="Screen Shot 2021-03-12 at 12 19 10 PM" src="https://user-images.githubusercontent.com/387249/110994139-31f77500-832d-11eb-8bc0-46683f30aedf.png"> | <img width="1312" alt="Screen Shot 2021-03-12 at 10 40 02 AM" src="https://user-images.githubusercontent.com/387249/110994137-315ede80-832d-11eb-8209-6668735bee24.png">

### Adding new filters

Just on the new version (`1.23.36`):

1. Visit a website of your choice

`yahoo.com`

2. Right-click on a page element of your choice
3. Select "Brave > Block element via selector"
4. Confirm the block
5. Verify that the blocked item is hidden, and remains hidden after a page refresh
6. Reopen or refresh `brave://adblock` and verify that a new line has been added corresponding to the newly blocked item
7. Repeat steps 1-6 at least one more time

| `yahoo.com` (blocked elements) | `brave://adblock` rules |
|----------------------------------|-------------------------|
<img width="1312" alt="Screen Shot 2021-03-12 at 12 21 11 PM" src="https://user-images.githubusercontent.com/387249/110994546-c661d780-832d-11eb-88ad-972ee389d231.png"> | <img width="1286" alt="Screen Shot 2021-03-12 at 12 22 52 PM" src="https://user-images.githubusercontent.com/387249/110994542-c530aa80-832d-11eb-95b4-58d7ca5b06df.png">

**Reference Images** (no blocked items)

| `aol.com` | `twitch.tv` | `yahoo.com` |
|-----------|------------|--------------|
<img width="1500" alt="Screen Shot 2021-03-12 at 12 30 29 PM" src="https://user-images.githubusercontent.com/387249/110996153-602a8400-8330-11eb-8fcf-5d4fb5d7df6d.png"> | <img width="1500" alt="Screen Shot 2021-03-12 at 12 30 41 PM" src="https://user-images.githubusercontent.com/387249/110996150-5f91ed80-8330-11eb-97f5-8a251afa1820.png"> | <img width="1312" alt="Screen Shot 2021-03-12 at 12 23 21 PM" src="https://user-images.githubusercontent.com/387249/110994545-c5c94100-832d-11eb-8549-d3751d0ebbf9.png">
