### ISSUE TITLE
Brave browser card not showing up in Uphold

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9582]
## Description 
https://www.reddit.com/r/BATProject/comments/frowdv/brave_browser_card_in_uphold_not_showing_up/

User can successfully complete verification, but not card in Uphold wallet.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@jsecretan is Uphold allowing user to create bat card? They can easily try to create bat card in uphold UI and see if they are maybe in a region where BAT is not allowed

**Comment by Miyayes** [comment]
I think we have good handling for these cases in general, thanks to @szilardszaloki's improvements to the Uphold integration. We can file anew if needed.

**Comment by szilardszaloki** [comment]
Just adding here that cards with no balance don't show up in Uphold's new wallet implementation (`wallet.uphold.com`). Not sure if this is how it used to be with their old one.
