### ISSUE TITLE
Dashboard settings changes are not reflected in `brave://settings/newTab` until page is refreshed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9588]
## Description 

Dashboard settings changes are not reflected in `brave://settings/newTab` until page is refreshed

## Steps to Reproduce

   1. Clean profile 1.10.23
   2. Open a NTP `Dashboard settings` in tab1
   3. Open `brave://settings/newTab` in tab2
   4. Disabling few settings in `Dashboard settings`
   5. Changes are not reflected in `brave://settings/newTab` until the page is refreshed

## Actual result:

Dashboard settings changes are not reflected in `brave://settings/newTab` until page is refreshed

## Expected result:

Dashboard settings changes should be reflected in `brave://settings/newTab` instantly without page refresh

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.23 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @rebron @simonhong

**Comment by GeetaSarvadnya** [comment]
Verification passed on both `Nightly 1.10.27` and `Dev 1.9.55` channels. Changes in made in dashboard settings are reflected instantly in brave://settings/newTab and vice versa. Hence closing the issue.

```
Brave | 1.10.27 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
```
Brave | 1.9.55 Chromium: 81.0.4044.129 (Official Build) dev (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```

**Comment by GeetaSarvadnya** [comment]
@simonhong Please add the PR which fixed the issue, as I am not finding the PR associated.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description.
Verified test plan from https://github.com/brave/brave-core/pull/5434
