### ISSUE TITLE
`NTP Sponsored Images` component should refresh sooner

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9590]
## Description 
The `NTP Sponsored Images` component is registered with component updater and will refresh at browser launch and every 5 hours. For people that leave their computer open all the time, they may have to wait another 5 hours for the component to refresh OR quit/launch browser

## Steps to Reproduce
   1. Open Brave to sponsored new tab page
   2. Ask Brave employee to update image
   3. Refresh page; see how long it takes

## Actual result:
Takes up to 5 hours

## Expected result:
Should not take this long

## Reproduces how often: 
100%

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-browser/issues/9713 for `Android` as this might go out sooner via the `1.8.x HF1` that's planned.

**Comment by LaurenWags** [comment]
Per discussions between @kjozwiak and @bsclifton marking this as `QA/No`. @kjozwiak confirmed this is working as expected with https://github.com/brave/brave-core/pull/5449#issuecomment-626247318.
