### ISSUE TITLE
Implement Brave Ads "my first ad" flow

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9594]
Implement Brave Ads "my first ad" flow

**Comment by rebron** [comment]
@tmancey Is this for both desktop and android? 
cc: @karenkliu Dupe of another issue already in process.

**Comment by tmancey** [comment]
@rebron Desktop. I have added the labels. Thanks

**Comment by tmancey** [comment]
Closing issue as stale, however making @Miyayes aware for future consideration in new ongoing design changes
