### ISSUE TITLE
Shield settings are not saved after restart browser

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#96]
STR:
1. Open any page and set its shield setting
2. Restart the browser

expected result: the setting is the same as the setting before restarting the browser
actual result: its shield setting is the same as our default shield setting, not the saved one

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
