### ISSUE TITLE
create Get Started section in settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#960]
## Test plan
1. Open brave://settings
2. Very top section should be `Get Started`
3. Items should more or less match the description below (`New tab page shows` is not done yet- needs to be tracked in https://github.com/brave/brave-browser/issues/2999)
4. Verify `Get Started` is in the sidebar nav

## Description 
Create new Get Started section in Settings as the top item. 
Label section - 'Get Started'
Label in sidebar - 'Get Started'

This section will include access to Import, Default Browser, New tab page, and On Startup settings.
See design spec.

1) Selecting Import will take you to Import dialog window.
2) Move Default browser setting here. Default Browser will show 'Make Default' button if Brave is not default browser. Display ‘Brave is your default browser’ if Brave has been made the default browser.
3) Create new setting 'New tab page shows' with drop down menu: 
  a) Dashboard with images
  b) Homepage
  c) Default search engine
  d) Blank page
4) Move 'On startup' to this section w/ Brave styling.

## Design
![](https://user-images.githubusercontent.com/5951041/45063039-c0a22180-b060-11e8-9a61-ad7d70a5706d.png)

**Comment by rebron** [comment]
![get-started](https://user-images.githubusercontent.com/5951041/45063039-c0a22180-b060-11e8-9a61-ad7d70a5706d.png)

**Comment by srirambv** [comment]
+1 from @dfmabbas via #2967 for changing new tab

**Comment by rebron** [comment]
Created #2999. At minimum for this issue, need import, default browser, and on start up in this section.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from description
