### ISSUE TITLE
Incorrect ref code URL 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9601]
## Description 

Incorrect ref code URL 

## Steps to Reproduce

   1. Install nightly 
   2. Search for Biance
   3. Click on suggested link
   4. Gives 404 error 

## Actual result:

Navigates to a [URL](https://www.binance.com/buy-sell-crypto?fiat=USD&crypto=LTC&ref=39346846&utm_source=brave) which throws 404 error

## Expected result:
Should navigate to [this](https://www.binance.com/en/buy-sell-crypto?fiat=USD&crypto=LTC&ref=39346846&utm_source=brave)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.10.24 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by bbondy** [comment]
Fixed via https://github.com/brave/brave-core/pull/5438

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.72 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description, suggested links redirecting to correct ref code URL
![image](https://user-images.githubusercontent.com/38657976/82925243-13411100-9f9b-11ea-82bb-6855b6f4d901.png)
