### ISSUE TITLE
Both address and Memo ID should be shown for supported coins

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9605]
## Description 

Both address and Memo ID should be shown for supported coins

## Steps to Reproduce

   1. Install nightly 
   2. Connect widget and go to deposit 
   3. Certain coins only show Memo ID but require wallet address as well to make deposit

## Actual result:

Only memo id is shown

## Expected result:
Should show both memo id and wallet address to make a successful deposit 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.10.24 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the dev channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Linux

- Verified both Memo ID and Wallet address is shown where applicable
![image](https://user-images.githubusercontent.com/17010094/81282545-ef17a180-9078-11ea-8308-8a22b8f120f6.png)
![image](https://user-images.githubusercontent.com/17010094/81282815-53d2fc00-9079-11ea-9f70-6729549da187.png)
![image](https://user-images.githubusercontent.com/17010094/81282896-6d744380-9079-11ea-818b-9a27c6f499c2.png)
- Verified copy button copies Memo ID and Wallet address to clipboard
- Verified Memo ID and wallet address on widget matches whats on Binance portal
- Verified Copy button next to asset name copies the memo id and matches the listed memo id
-------------
Verification passed on 

Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Windows 10 OS Version 1809 (Build 17763.1158)

- Verified both Memo ID and Wallet address is shown where applicable
<img width="1038" alt="Screen Shot 2020-05-07 at 3 49 16 PM" src="https://user-images.githubusercontent.com/17010094/81284281-8978e480-907b-11ea-81a7-8090b7ca414c.png">
<img width="1038" alt="Screen Shot 2020-05-07 at 3 50 39 PM" src="https://user-images.githubusercontent.com/17010094/81284331-98f82d80-907b-11ea-9751-8b84b8e240ad.png">
<img width="1038" alt="Screen Shot 2020-05-07 at 3 50 57 PM" src="https://user-images.githubusercontent.com/17010094/81284398-add4c100-907b-11ea-9e4e-1f3a17801e98.png">

- Verified copy button copies Memo ID and Wallet address to clipboard
- Verified Memo ID and wallet address on widget matches whats on Binance portal
- Verified Copy button next to asset name copies the memo id and matches the listed memo id

**Comment by LaurenWags** [comment]
Changing to `release-notes/include` per discussion with @srirambv
