### ISSUE TITLE
Implement pagination for publisher list

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9607]
## Test plan
See https://github.com/brave/brave-core/pull/5458

## Description

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5458
* Confirmed for both staging and production
* Confirmed able to see various publisher types as verified (regular sites, YouTube, GitHub, Twitch, Reddit, Vimeo, Twitter)
* Confirmed able to see custom publisher banners (where applicable)
* Confirmed `Refresh Status` link in panel re-downloads the publisher list

**Comment by SephReed** [comment]
Still getting BAT ledger 100% issues.
<img width="692" alt="Screen Shot 2020-05-12 at 10 12 47 PM" src="https://user-images.githubusercontent.com/14002040/81767609-72345f80-949e-11ea-8e4c-271b451f2767.png">

**Comment by NejcZdovc** [comment]
@SephReed thank you for the update, my guess is that what will fix it for you is this one https://github.com/brave/brave-browser/issues/7595 which is in Nightly currently

**Comment by victorelec14** [comment]
it's still happening.

Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/543450/82759221-3a0d1500-9dec-11ea-9a11-3d5f22245f86.png)
