### ISSUE TITLE
Light theme color refinement

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#961]
https://github.com/brave/brave-core/pull/391 covers dark and private themes with regards to colors. Light theme still needs refinement according to spec.

**Comment by LaurenWags** [comment]
@petemill could you help with a Test Plan for this one?

**Comment by petemill** [comment]
Test plan added

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47126045-a7da7d80-d254-11e8-8e26-7b68253dbac2.png)
