### ISSUE TITLE
Rendering issue, blue lines across the whole screen

### ISSUE THREAD

**Issue by NicoG60** [brave/brave-browser#9610]
## Description
It's been a few month I'm using brave and in the last week or so I've been experiencing weird rendering issues. Some fat blue lines appear all over the rendering region of brave. It does not affect the GUI or the Settings part, just the web page rendering area

## Steps to Reproduce
Unfortunately I've not been able to recognise any pattern that to reproduce that bug. It seems to happen randomly from my point of view. I'm browsing as usual and at some point the page got the blue lines. Sometimes refreshing makes them disappear, sometimes not. Reloading the page in another tab does not seem to have any effect, it still happens randomly.

Edit:
It looks like disabling hardware acceleration solve the problem.

## Actual result:
Here are some screenshots:
![Screenshot 2020-05-04 at 13 48 36](https://user-images.githubusercontent.com/9570091/80968270-9396ab00-8e0f-11ea-94f7-0454232b872a.png)
![Screenshot 2020-05-04 at 13 51 48](https://user-images.githubusercontent.com/9570091/80968275-97c2c880-8e0f-11ea-9203-d30a41023a6c.png)
<img width="1109" alt="Screenshot 2020-05-04 at 13 48 12" src="https://user-images.githubusercontent.com/9570091/80968284-9b564f80-8e0f-11ea-9e8d-e2c827631f22.png">

It affects only certain part
![Screenshot 2020-05-04 at 15 47 58](https://user-images.githubusercontent.com/9570091/80979051-c5633e00-8e1e-11ea-8d1d-3bc88a08c22a.png)
s of the website:

## Expected result:
A normal looking web page :sweat_smile:

## Reproduces how often: 
Intermittent issue - No steps to reproduce

## Brave version (brave://version info)

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.1.307.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-features=NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,TextFragmentAnchor,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --disable-sync --disable-webrtc-apm-in-audio-service --enable-audio-service-sandbox --enable-dom-distiller --enable-features=DnsOverHttps,SimplifyHttpsIndicator,MixedContentSiteSetting,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,PasswordImport --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,PassiveMixedContentWarning,AutoupgradeMixedContent,WebUIDarkMode,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality,TextFragmentAnchor,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,NotificationTriggers --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/nicolas/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

I don't know about that.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

Same answer for the three: Does not seem to

**Comment by rebron** [comment]
Hi @NicoG60 When you get a chance, can you go to `brave://gpu/` and copy and paste your results in here.

**Comment by NicoG60** [comment]
Hi, it just happened again, on youtube, over the control bar as my previous screenshot shows. Here is the GPU report:

Data exported | 2020-05-08T11:21:39.693Z
-- | --
Chrome version | Chrome/81.0.4044.129
Operating system | Mac OS X 10.15.4
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/3d71af9f5704a40b85806f4d08925db24605ba25/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/3d71af9f5704a40b85806f4d08925db24605ba25/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 91c39dae9a51
2D graphics backend | Skia/81 5e3098d8fad5b3a6fa9c70d6438f416eec201db7
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,DnsOverHttps,SimplifyHttpsIndicator,MixedContentSiteSetting,WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync

**Comment by marksymoo** [comment]
Hi,

I have the same issue (just started to happen this morning).

I'm on Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit) with MacOS Catalina.

GPU Report:


Data exported | 2020-05-15T07:19:18.315Z
-- | --
Chrome version | Chrome/81.0.4044.129
Operating system | Mac OS X 10.15.4
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/3d71af9f5704a40b85806f4d08925db24605ba25/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/3d71af9f5704a40b85806f4d08925db24605ba25/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 91c39dae9a51
2D graphics backend | Skia/81 5e3098d8fad5b3a6fa9c70d6438f416eec201db7
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=DnsOverHttps,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=AutofillServerCommunication,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync

**Comment by marksymoo** [comment]
Rather than editing my post for the 100th time - turning off hardware acceleration seems to have resolved it?

**Comment by bsclifton** [comment]
@marksymoo thanks for sharing the work-around 😄 Artifacts being shown are almost always due to driver issues. Chrome and Chromium browsers (ex: Brave) use a driver list- if the bad driver or hardware is on that list, it's supposed to default to hardware acceleration off. It could be that your version of the driver hasn't been flagged yet? or maybe it's not a popular / widely reported piece of hardware

I'll close this issue out as that is the appropriate solution (turning off HW acceleration)
