### ISSUE TITLE
Binance tab is not shown

### ISSUE THREAD

**Issue by nsuvorov83** [brave/brave-browser#9612]
## Description 

Don't see Binance tab despite have latest version of Brave.

## Steps to Reproduce

   1. Open Brave (Version 1.8.86 Chromium: 81.0.4044.129), Language: Russian
   2. Create new tab

## Actual result:

There is no a Binance tab

## Expected result:
There is a Binance tab

## Reproduces how often: 

Permanently

## Brave version (brave://version info)

Brave	1.8.86 Chromium: 81.0.4044.129 (Официальная сборка) (64-bit)
Версия	3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
ОС	macOS Версия 10.13.6 (Выпуск 17G10021)
JavaScript	V8 8.1.307.31
Flash	32.0.0.363 /Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Командная строка	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_294984 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,NotificationTriggers,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,TextFragmentAnchor,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Путь к исполняемому файлу	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Путь к профилю	/Users/nikolaysuvorov/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

Version 1.8.86 Chromium: 81.0.4044.129

- Can you reproduce this issue with the current release?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

Russian is used.

**Comment by kjozwiak** [comment]
@nsuvorov83 thanks for the issue 👍 Unfortunately this is the expected behaviour for now. You can find more information via https://github.com/brave/brave-browser/issues/8849.
