### ISSUE TITLE
SERP ads delayed rendering

### ISSUE THREAD

**Issue by kaytwo** [brave/brave-browser#9617]
## Description 

Search ads pop in on Google SERPs about 500ms after the page renders. I've accidentally clicked on them a lot and it only drives me a little crazy. It only seems to happen when logged in. Here's an empty profile example: [serp ads pop in after rendering](https://gist.github.com/kaytwo/4c2975a2faefacfabf02b0900b0a8458/raw/f417de744de9ef18f27e9cb1cf517ea1fbcd1caf/serp.ads.mp4)

## Steps to Reproduce

   1. log in to google
   2. search for something that will cause ads to be displayed
   3. start reading the adblocked results
   4. watch the ads show up shortly thereafter

## Actual result:

The ads pop in

## Expected result:

The ads should either be rendered along with the page or not at all.

## Reproduces how often: 

Easily reproduced: I did it on two different accounts

## Brave version (brave://version info)

Brave | 1.9.45 Chromium: 81.0.4044.122 (Official Build) beta (64-bit)
-- | --
Revision | 44f4233f08910d83b146130c1938256a2e05b136-refs/branch-heads/4044@{#963}
OS | Windows 10 OS Version 1909 (Build 18363.815)

## Version/Channel Information:

- Can you reproduce this issue with the current release?

Stable: ad was successfully blocked completely

- Can you reproduce this issue with the beta channel?
Yes it's my daily driver

- Can you reproduce this issue with the nightly channel?
Nightly: it's a bit nondeterminstic, sometimes it's always hidden, sometimes there's a "fight" where the ad blinks on the screen then blinks off, but most of the time it pops up all the way

- Can you reproduce this issue with the dev channel?
I don't think this is a thing anymore?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes, ads show up right away and don't flash.

- Does the issue resolve itself when disabling Brave Rewards?
I have rewards disabled

- Is the issue reproducible on the latest version of Chrome? 
uBO doesn't exhibit this problem (ads always hidden), Vanilla Chrome doesn't either (ads always shown)

**Comment by ryanbr** [comment]
Cosmetic filter of first party is coming, this should take care of these google ads.

https://github.com/brave/brave-core/pull/5481

**Comment by kaytwo** [comment]
If someone pings me when this hits nightly I'll see whether it's been fixed on my end.

**Comment by rebron** [comment]
@kaytwo This has been in Nightly for a bit and actually in Beta too. Go to shields or in settings and set Trackers and Ads blocked (aggressive) and let us know if this is working for you.

**Comment by kaytwo** [comment]
LGTM - when there's no ads they never flash, and when there are ads they stick on the page without any annoying reflows.
