### ISSUE TITLE
Tab border refinement

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#962]
https://github.com/brave/brave-core/pull/391 covers changing the tab border radii, but does not deal with the bottom border radius, which needs to be removed according to the spec.

We also need to implement the changes to the tab separator - it gets thicker, taller, and aligned to the bottom.

![image](https://user-images.githubusercontent.com/741836/45243045-3e576e80-b2a7-11e8-9459-d9973d37a4a0.png)

**Comment by bbondy** [comment]
Removed pr/pending-review since PR seems to still be work in progress. I think that label makes it sound like it's waiting on a review.

**Comment by petemill** [comment]
Agreed @bbondy. I had submitted for review but then removed whilst I refactor.

**Comment by LaurenWags** [comment]
@petemill could you help with a test plan for this one?

**Comment by petemill** [comment]
Test plan added

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.17 Chromium: 70.0.3538.67 (Official Build) (64-bit)
-- | --
Revision | 9ab0cfab84ded083718d3a4ff830726efd38869f-refs/branch-heads/3538@{#1002}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/47126027-8bd6dc00-d254-11e8-9661-cf851c83380c.png)
