### ISSUE TITLE
Download folder path reverts to the default on its own

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#9620]
## Description 

- After changing the download folder path, it automatically reverts to the default path

## Steps to Reproduce

   1. Change the download path  (say, ~/Download2)
   2. Wait for 1,2 weeks (or perhaps on update)
   3. Download location reverts to default (~/Download)

## Expected result:
- Expect the setting remains 

## Reproduces how often: 

- No clear steps to reproduce but happened to me several times

## Brave version (brave://version info)

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.1.307.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,NotificationTriggers,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,TextFragmentAnchor,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --enable-features=AutoupgradeMixedContent,PassiveMixedContentWarning,PasswordImport,WebUIDarkMode,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps,ReaderMode --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/chikaki/Library/Application Support/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@chkk525 do you have the following setting disabled under brave://settings/downloads?
`Ask where to save each file before downloading`

If this is enabled, it's always going to ask where. The last saved location is shared across programs on the OS. It only uses the provided download location if the setting is disabled, as far as I know

**Comment by chkk525** [comment]
@bsclifton That was enabled. Thank you for confirming.

**Comment by bsclifton** [comment]
Perfect!

Maybe this issue should stay open though, as folks may be expecting that path to be set each time. We could hide that path unless person is disabling `Ask where to save each file before downloading`

WDYT @rebron?

**Comment by rebron** [comment]
We have `Ask where to save each file before downloading` enabled by default. 
Chrome (and Edge) have this setting disabled by default. So not sure if we want to make a change there.

But otherwise, looks like this is working as expected unless I'm missing something.

**Comment by bsclifton** [comment]
OK awesome - going to close this out 😄 Thanks, @rebron!
