### ISSUE TITLE
Anti-adblock showing up on `http://sh.st/iA5JK`

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9625]
## Description 
Anti-adblock showing up on `http://sh.st/iA5JK`

## Steps to Reproduce

   1. Visit `http://sh.st/iA5JK`
   2. Get Anti-Adblock message
   3. Regardless of shield settings, Anti-Adblock message will show.

## Actual result:
![sh-st](https://user-images.githubusercontent.com/1659004/81064629-1dd53100-8f2e-11ea-8df4-e9e9a6b430ca.png)

## Expected result:
Get no warning

## Reproduces how often: 
With default shields, will show. Even if you disable shield settings.

## Brave version (brave://version info)
Tested in **Release** `Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)` and tested in **Nightly** `Version 1.10.27 Chromium: 81.0.4044.129 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Was reported by a Brave user @Yuki2718 

https://github.com/uBlockOrigin/uAssets/pull/7304

The site seems to detect Brave if shields is enabled (with all other shield settings disabled).

Having uBO enabled doesn't get around this message.

**Comment by ryanbr** [comment]
Also applies to Desktop, not applicable to Android mobile. Android doesn't show the message.

**Comment by mapx-** [comment]
It works only clicking the orange button (disabling all other "invisible" protections for the site)

![image](https://user-images.githubusercontent.com/10303732/81069701-8991ac80-8ee2-11ea-9f40-66b3afd6d99c.png)

**Comment by ryanbr** [comment]
Okay, is fixed in Nightly, with roll out of $generichide.  https://github.com/brave/adblock-rust/pull/97 and Aggressive mode.

Closing ticket.
