### ISSUE TITLE
No cursor focus on new window in macOS (maximized / full screen mode only)

### ISSUE THREAD

**Issue by akshaybhalotia** [brave/brave-browser#9626]
## Description 
The cursor does not focus on address bar automatically, when opening a new window (normal, private and private with Tor) on macOS when Brave Browser is maximised (using the green button on window titlebar).

## Steps to Reproduce

   1. Open Brave Browser on macOS.
   2. Click on the green maximize / zoom button in the window titlebar or press keyboard shortcut ⌃⌘F.
   3. Open new window using menu options or shortcuts (⌘N, ⇧⌘N or ⌃⌘N).

## Actual result:
New window opens but cursor not present in address bar so user has to click with mouse or use a shortcut like ⌘L to focus the address bar

## Expected result:
New window opens with cursor in address bar and user can start typing immediately

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.14.6 (Build 18G4032)

## Version/Channel Information:
Haven't tried other channels

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
I was able to reproduce this in Chrome as well. Looks like no focus in the url bar is only for `New Window` (in Full screen mode) but works properly when opening a `New Tab`.

**Comment by akshaybhalotia** [comment]
Very interesting. This does not occur on Chromium. I'll post the version
details in a bit, I'm not at my computer right now.

**Comment by akshaybhalotia** [comment]
My Chromium version info, where this does not occur

Chromium | 84.0.4133.0 (Developer Build) (64-bit)
-- | --
Revision | d86a0d354ed5b5426011c1db1c66abf32dcaa9d6-refs/heads/master@{#764763}
OS | macOS Version 10.14.6 (Build 18G4032)

**Comment by rebron** [comment]
@akshaybhalotia Thanks for following up. Looks like the fix is on its way.

**Comment by bsclifton** [comment]
Closing as stale since there hasn't been an update in a while and there haven't been any additional reports- @akshaybhalotia please let us know if you're still experiencing this and we can re-open / investigate more. Thanks 😄

**Comment by akshaybhalotia** [comment]
Confirmed fixed. Current version details:


Brave | 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
-- | --
Revision | 1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6-refs/branch-heads/4389@{#1616}
OS | macOS Version 11.3 (Build 20E5224a)

**Comment by bsclifton** [comment]
Thanks for confirming, @akshaybhalotia! Hope you're having a great experience with Brave 😄
