### ISSUE TITLE
Expose publisher list download progress flag to public ledger interface

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#9629]
# Description 

At the moment when the user enables rewards they are able to tap "Refresh" on publisher panel even if the ledger is currently downloading/parsing the publisher list. 

Ledger should expose the current "is loading" status of the server publisher list so we may update the UI accordingly. 

This will be made easier by the changes made here: https://github.com/brave/brave-core/pull/5458

**Comment by Miyayes** [comment]
Closing as resolved since we don't use this old "publisher_list" style anymore.
