### ISSUE TITLE
Domains loaded over IPFS are not detected for brave rewards

### ISSUE THREAD

**Issue by RubenKelevra** [brave/brave-browser#9631]
## Description 
If a domain can be loaded over IPFS (DNSLink) the website is forwarded to the configured local gateway. In this case the domain looks like `<domain>.ipns.localhost[:<port>]`. While port might be any port or port 80 (not shown at all).

## Steps to Reproduce
   1. open brave
   2. enable ipfs
   3. install a local ipfs client
   4. navigate to https://ipfs.io

## Actual result:
![Screenshot_20200505_212025](https://user-images.githubusercontent.com/614929/81107236-21a98900-8f17-11ea-8c11-c4f0bdde79ee.png)

## Expected result:
ipfs.io is a verified creator and should be identified.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) unknown (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Linux
JavaScript | V8 8.1.307.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps,BraveSync,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,ImpulseScrollAnimations,LegacyTLSEnforced,PaintHolding,PercentBasedScrolling,SyncSetupFriendlySettings --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /usr/lib/brave-bin/brave
```

**Comment by spylogsster** [comment]
Show verified publishers for ipns:// domains only https://github.com/brave/brave-core/pull/8512.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.25.25 Chromium: 90.0.4430.72 (Official Build) nightly (x86_64)
-- | --
Revision | b6172ef8d07ef486489a4b11b66b2eaeed50d132-refs/branch-heads/4430@{#1233}
OS | macOS Version 11.2.3 (Build 20D91)



Steps:
1. new profile
2. loaded `ipns://ipfs.io`
3. clicked on `Use a local node`
4. after `ipns://ipfs.io` loaded, clicked on the BAT logo in the URL bar

Confirmed site was listed as a verified creator, had a creator's tip banner, and verified I could tip them.

example | example | example
--------|----------|----------
<img width="1530" alt="Screen Shot 2021-04-19 at 6 16 40 PM" src="https://user-images.githubusercontent.com/387249/115322787-af3bb400-a13b-11eb-9450-cb6f158ab28c.png"> | <img width="1530" alt="Screen Shot 2021-04-19 at 6 17 13 PM" src="https://user-images.githubusercontent.com/387249/115322803-b2cf3b00-a13b-11eb-8c7b-3f8ea2099b12.png"> | <img width="1530" alt="Screen Shot 2021-04-19 at 6 17 17 PM" src="https://user-images.githubusercontent.com/387249/115322807-b4006800-a13b-11eb-8e31-ea17ad9345c3.png">
