### ISSUE TITLE
[P3A] Amend bookmarks question for further refinements

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#9634]
Amend bucket 3 and add buckets 4 through 7 to Brave.Core.BookmarksCountOnProfileLoad:

0) 0 to 5	
1) 5 to 20	
2) 20 to 100	
3) 100 to 500
4) 500 to 1000
5) 1000 to 5000
6) 5000 to 10000
7) More than 10000

**Justification:** 
Improve granularity of upper bounds in order to quantify the cohort of users with large numbers of bookmarks

**Comment by GeetaSarvadnya** [comment]
@bsclifton Please update the ranges as below:

0) 0 to 5	
1) 5 to 20	
2) 21 to 100	
3) 101 to 500
4) 501 to 1000
5) 1001 to 5000
6) 5001 to 10000
7) More than 10000

**Comment by bsclifton** [comment]
@GeetaSarvadnya looks like https://github.com/brave/brave-browser/wiki/P3A has already been updated- I also updated top post above 😄

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}

#### Clean profile 
- Verified when bookmark count is between `0 - 5`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 0
<img width="718" alt="Screenshot 2020-05-19 at 3 33 30 p m" src="https://user-images.githubusercontent.com/17010094/82318366-588a9f00-99ed-11ea-8d46-ff68b9b5501a.png">


- Verified when bookmark count is between `6-20`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 1
<img width="718" alt="Screenshot 2020-05-19 at 3 34 06 p m" src="https://user-images.githubusercontent.com/17010094/82318209-17928a80-99ed-11ea-885c-0e2b5e457611.png">

- Verified when bookmark count is between `21-100`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 2
<img width="718" alt="Screenshot 2020-05-19 at 3 06 07 p m" src="https://user-images.githubusercontent.com/17010094/82318228-20835c00-99ed-11ea-8922-55f5746f77d6.png">

- Verified when bookmark count is between `101-500`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 3
<img width="718" alt="Screenshot 2020-05-19 at 3 28 53 p m" src="https://user-images.githubusercontent.com/17010094/82318247-25e0a680-99ed-11ea-8009-8e6e455f6ff3.png">

- Verified when bookmark count is between `501-1000`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 4
<img width="718" alt="Screenshot 2020-05-19 at 3 29 14 p m" src="https://user-images.githubusercontent.com/17010094/82318253-2aa55a80-99ed-11ea-8867-86f6a2b07582.png">

- Verified when bookmark count is between `1001-5000`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 5
<img width="718" alt="Screenshot 2020-05-19 at 3 29 57 p m" src="https://user-images.githubusercontent.com/17010094/82318272-309b3b80-99ed-11ea-85d0-2e56e749693b.png">

- Verified when bookmark count is between `5001-10000`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 6
<img width="718" alt="Screenshot 2020-05-19 at 3 31 18 p m" src="https://user-images.githubusercontent.com/17010094/82318276-342ec280-99ed-11ea-86eb-bb378af0e9de.png">

- Verified when bookmark count is between `More than 10000`, `Brave.Core.BookmarksCountOnProfileLoad.2` value is set to 7
<img width="718" alt="Screenshot 2020-05-19 at 3 31 37 p m" src="https://user-images.githubusercontent.com/17010094/82318288-38f37680-99ed-11ea-9ac3-1de81a9666a8.png">

#### Add/Delete bookmark

- With 5 bookmarks added verified `Brave.Core.BookmarksCountOnProfileLoad.2` is set to `0` and adding a new bookmark and relaunching the browser sets its value to `1`

- With 25 bookmarks added verified `Brave.Core.BookmarksCountOnProfileLoad.2` is set to `3` and deleting 15 bookmarks relaunching the browser sets its value to `1`

#### Upgrade scenario
- With 1010 bookmarks on `1.8.96`, `Brave.Core.BookmarksCountOnProfileLoad` value is set to `3`. Upgrading to `1.9.70` and relaunching browser, `Brave.Core.BookmarksCountOnProfileLoad` is changed to `Brave.Core.BookmarksCountOnProfileLoad.2` and the value is updated from `3` to `5`
- With 5000+ bookmarks on `1.8.96`, `Brave.Core.BookmarksCountOnProfileLoad` value is set to `3`. Upgrading to `1.9.70` and relaunching browser, `Brave.Core.BookmarksCountOnProfileLoad` is changed to `Brave.Core.BookmarksCountOnProfileLoad.2` and the value is updated from `3` to `6`
- With 10000+ bookmarks on `1.8.96`, `Brave.Core.BookmarksCountOnProfileLoad` value is set to `3`. Upgrading to `1.9.70` and relaunching browser, `Brave.Core.BookmarksCountOnProfileLoad` is changed to `Brave.Core.BookmarksCountOnProfileLoad.2` and the value is updated from `3` to `7`

- Verified adding bookmarks to root folder or under other bookmarks calculates the correct value for `Brave.Core.BookmarksCountOnProfileLoad.2`
- Verified adding/deleting a bookmark doesn't update the value for `Brave.Core.BookmarksCountOnProfileLoad.2` instantly. The correct value updates when the browser is restarted
