### ISSUE TITLE
[Android] User wallets not permitted up to a threshold of BAT earner

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#9636]
Issue: Currently a lot of users are being pushed in to the user wallet funnel w/o having a lot of earned BAT creating a load for the wallet partner.

Fix: Prevent any UI to trigger 'Verify Wallet' until XX BAT has been earned as a virtual grant before user is allowed to verify their user wallet.

Please block user wallet release on to Android until fix for this issue is made. We will lead with Android and make fix on Desktop after that.

cc @aekeus @LaurenWags @kjozwiak @jamesmudgett

**Comment by anthonypkeane** [comment]
@gdregalo This will need to be added to 1.9.x along with User Wallets

@bradleyrichter and co are working on a design, but it may be very simple. More TBD

**Comment by anthonypkeane** [comment]
Link: https://bravesoftware.slack.com/archives/C0816QH3R/p1589305511388300?thread_ts=1588347650.317300&cid=C0816QH3R

which details the BAT limit

**Comment by mandar-brave** [comment]
Here is what the plan is;

1) for users that have not yet accrued 25 BAT, we gray out the Verify Wallet button - they know the button is there but it does not take them to the verify link
2) for users that have reached the 25 BAT limit, follow the current design.
3) Add a tooltip for the gray out that says "25 BAT limit required to Verify Wallet"

@anthonypkeane if the tooltip is OK, we need to order translations. I am OK to live w/o it.

@kjozwiak @LaurenWags @jamesmudgett

**Comment by jenn-rhim** [comment]
1. We don't show the Verify button at all.
2. Verify screen will come up when relevant actions are requested by the user: i.e. Add Funds and Withdraw Funds.
3. I'd prefer not graying out the button based on the condition, so we can educate user when they click what condition needs to be met. 
@mandar-brave

**Comment by jenn-rhim** [comment]
The overlay info box that comes up when clicked these button while > 25BAT is in their balance, would say:

'To complete this action, you need to verify your wallet t. Minimum balance 25 BAT is required to verify.’

**Comment by mandar-brave** [comment]
@NejcZdovc @emerick we need to get this done for the 1.10 release.

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

Verified that `Verified Wallet` is grayed out. 
![Screenshot_20200617-051522_Brave](https://user-images.githubusercontent.com/34715963/84851251-13907180-b05a-11ea-992e-1eea5d234a43.jpg)

Verified clicking on `Verified Wallet` shows expected message
![Screenshot_20200617-051549_Brave](https://user-images.githubusercontent.com/34715963/84851272-2145f700-b05a-11ea-9d44-62a94d539a3f.jpg)

Verified that if condition of 25BAT is met, `Verified Wallet` stops being grayed out and is active
![Screenshot_20200617-051746_Brave](https://user-images.githubusercontent.com/34715963/84851214-f0fe5880-b059-11ea-81cc-ffac552e9c8d.jpg)


Verified that if condition of 25BAT is met, verification can be completed successfully
![Screenshot_20200617-050825_Brave](https://user-images.githubusercontent.com/34715963/84850940-4d14ad00-b059-11ea-80f5-3f11af38f3b7.jpg)
