### ISSUE TITLE
use Brave styling for (unchanged) Additional settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#964]
## Test plan
See https://github.com/brave/brave-browser/issues/955

## Description
For unchanged Additional Settings: Languages, Downloads, Printing, Accessibility, System, Reset Settings; add icons and use Brave styling for typography and buttons.

## Design
<img width="573" alt="updated-settings-screen" src="https://user-images.githubusercontent.com/5951041/45930107-5a4a4980-bf10-11e8-9bf4-f8e278f3ffea.png">

**Comment by rebron** [comment]
![additional-settings](https://user-images.githubusercontent.com/5951041/45063667-ef6dc700-b063-11e8-8fdc-82cf16a36fde.png)

**Comment by srirambv** [comment]
@rebron `Reset settings` in spec shows wrong icon. Need to be updated

**Comment by rebron** [comment]
@srirambv updated, got the right icon in there now.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta(64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/58434342-24ee9080-8089-11e9-8851-36593eb616a2.png)

* Verification based on the discussion in https://github.com/brave/brave-core/pull/1909
