### ISSUE TITLE
IPFS's IPNS support broken

### ISSUE THREAD

**Issue by RubenKelevra** [brave/brave-browser#9641]
## Description 
When an IPNS link is opened, it will be forwarded to `<IPNS-Hash>.ipns.localhost[:port]`.

It looks like the Brave Browser tries to resolve the .localhost domain instead of using it as a catch-all for `127.0.0.1` / `::1`.

## Steps to Reproduce

   1. open brave
   2. enable ipfs
   3. install a local ipfs daemon
   4. open a [link](https://ipfs.io/ipns/12D3KooWG55McTZWnWHP6Z6VMvcZNYodpmSBk6iLJ53XmhZTJfxW) like this

## Actual result:
The ipfs plugin forwards the link correctly to `http://<IPNS-Hash>.ipns.localhost[:port]`, but Brave seems to send the result to the DNS Server, instead of just using internal `127.0.0.1` / `::1` resolution.

![Screenshot_20200505_233938](https://user-images.githubusercontent.com/614929/81118853-ec5a6680-8f29-11ea-9497-b1b380962ea0.png)

## Expected result:
Open the page via the local webproxy on `127.0.0.1:80` / `[::1]:80`.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave | 1.8.86 Chromium: 81.0.4044.129 (Official Build) unknown (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Linux
JavaScript | V8 8.1.307.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver --flag-switches-begin --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps,BraveSync,DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,ImpulseScrollAnimations,LegacyTLSEnforced,PaintHolding,PercentBasedScrolling,SyncSetupFriendlySettings --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /usr/lib/brave-bin/brave
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

no

* Does the issue resolve itself when disabling Brave Rewards?

no

- Is the issue reproducible on the latest version of <strike>Chrome</strike> Firefox?

Nope, firefox opens the link just fine.

**Comment by bbondy** [comment]
I can't reproduce this problem, I think it was probably fixed at some point.  
Otherwise it could be maybe automatic redirection causing problems on the IPFS Companion extension.
