### ISSUE TITLE
Brave sometimes forgets all cookies!

### ISSUE THREAD

**Issue by andersmmg** [brave/brave-browser#9643]
## Description 
Sometimes, when I open Brave, it has forgotten ALL cookies from websites. This means I'm logged out of every site, and settings like YouTube dark mode are reset. this is really annoying and I'll have to switch back to another browser for a while until this is fixed.

## Steps to Reproduce
It's weird that I can't tell when it actually happens, it just does and then doesn't for a bit.

   1. Log in to websites
   2. Close Brave
   3. Open to see everything forgotten (sometimes)

## Actual result:
All cookies and local storage is cleared sometimes when opening the browser.
Extensions still retain their data, as does the bookmarks, rewards, and settings. It seems to be just other websites' data.

## Expected result:
Cookies and local storage should stay until they're supposed to expire.

## Reproduces how often: 
At least a few times a month this has happened. Enough times that I have to use another browser now because I don't want to have this happen and slow me down when I go to work on something.

## Brave version (brave://version info)

Brave | 1.7.92 Chromium: 80.0.3987.163 (Official Build) unknown (64-bit)
-- | --
Revision | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
OS | Linux
JavaScript | V8 8.0.426.30
Flash | 32.0.0.363 /usr/lib/PepperFlash/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=32.0.0.363 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/andersmmg/.config/BraveSoftware/Brave-Browser/Default

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:
I couldn't find any other instances of people reporting this or similar issues. No idea what the difference with my install could be.

**Comment by rebron** [comment]
<img width="537" alt="Screen Shot 2020-05-06 at 9 37 37 AM" src="https://user-images.githubusercontent.com/5951041/81203904-5819ef00-8f7d-11ea-8855-3dd78371e47e.png">
@andersmmg I'm going to guess you didn't set anything to clear here on exit? brave://settings/clearBrowserData

And this isn't happening during an upgrade e.g. going from like 1.7 to 1.8? Just normal use of the browser when opening and closing Brave with same version browser.

**Comment by andersmmg** [comment]
No, I didn't have anything clear on exit. And, I haven't upgraded recently and I'm pretty sure it's been the same version when it happens. It's not any specific sites, it's literally EVERY site I've logged into or saved settings that use cookies to store them across sessions. The ones that are the most annoying are YouTube and other Google products, and also things like Github and Discord which I use a lot.

**Comment by rebron** [comment]
@andersmmg Can you check one more setting for me: 
brave://settings/content/cookies

Want to make sure that setting is default one like below:
<img width="708" alt="Screen Shot 2020-05-06 at 9 50 22 PM" src="https://user-images.githubusercontent.com/5951041/81255897-c09bb700-8fe3-11ea-9df8-99e1d412abbf.png">

**Comment by andersmmg** [comment]
![image](https://user-images.githubusercontent.com/16022203/81309914-b0fe8b80-9040-11ea-86d6-d201beb583a5.png)
It's the same

**Comment by rebron** [comment]
@andersmmg Can you see if this is still an issue for you on 1.9.80? We're also releasing the next version soon 1.10.x.

**Comment by andersmmg** [comment]
It seems to be working right now, I'll keep using it and let you know if there's still an issue.

**Comment by allefeld** [comment]
This happens to me about once every 1 to 2 weeks. It affects all websites, i.e. I have to log in again everywhere. Including 2FA, which is quite annoying.

When it happens, Brave also often (always?) has forgotten passwords, but that can be fixed by closing and starting again. Is this maybe related to the wallet not being opened yet? Are cookies stored with libsecret?

Version 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)
Debian 12

**Comment by nonetrix** [comment]
Having this as well, I think it might(?) have something to do with KDE wallet for me. I never asked for this to be installed, idk how to remove it or set it up right Hyprland option in Arch installer seems to install it and it's not setup correctly
