### ISSUE TITLE
Follow up #5142 SpeedReader code review 

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#9652]
## Description 

Follow up for https://github.com/brave/brave-core/pull/5142

Documents comments left to address.

- [ ] We're using the component installer (`SpeedreaderWhitelist`) where we should be using the SpeedreaderService. `speedreader::Speedreader` should be a `base::Singleton` and can be accessed inside the `SpeedreaderService` using `Speedreader::GetInstance`
- [ ] `SpeedreaderWhitelist` should be SpeedreaderWhitelistInstaller`
- [ ] `kSpeedreaderEnabled` doesn't appear to actually disable speedreader, it just removes the button (wasting cpu cycles and memory when it's off). It sort of turns it off with `SpeedreaderTabHelper::UpdateActiveState`, but that should use a pref listener like the button
- [ ] explore ways to use chromium's css/html parsers instead of relying on third-party library that may be treating things differently

**Comment by iefremov** [comment]
stale
