### ISSUE TITLE
Disconnect uphold if we get 403 from uphold

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9653]
## Description 

Right now when there is uphold server problem 403 or 404 (when fetching a balance) we return error to the UI that sticks. What we should do is in this cases disconnect wallet and return ok to the UI.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with


Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5470

Before changing `address` in `Preferences`:
<img width="405" alt="Screen Shot 2020-05-18 at 5 35 44 PM" src="https://user-images.githubusercontent.com/28145373/82262211-7b09b300-992e-11ea-8ef4-22cce36456f5.png">

After changing `address` in `Preferences`:

```
[ RESPONSE - OnFetchBalance ]
> time: 1589837628
> result: Failure
> http code: 404
```

<img width="410" alt="Screen Shot 2020-05-18 at 5 34 22 PM" src="https://user-images.githubusercontent.com/28145373/82262205-793fef80-992e-11ea-9143-4fab6b3d13e2.png">

* Confirmed able to reconnect to Uphold after running thru test plan.
