### ISSUE TITLE
Mailchimp popup breaks page design only on Brave Browser

### ISSUE THREAD

**Issue by pateskinasy** [brave/brave-browser#9656]
## Description 
The mailchimp pop up is broken on Brave Browser desktop (MacOS) . The picture below is the bottom of my page. It renders the content that belongs to the popup in the page itself. Totally breaking the design of the page.

(this only happens on Brave browser when shields are up -> i.e. for most people using Brave)

All renders ok on Chrome, Safari and Opera. It is only broken on Brave.

## Steps to Reproduce
Just render any page with a mailchimp popup installed

`https://nocsok.com/about 1` <-- example (scroll to the bottom of the page, then wait a couple of seconds for the popup content to load)

## Actual result:
This is the bottom of the page, now a broken design (the messy content would have been in the popup from mailchimp)

<img width="1301" alt="Screenshot 2020-04-30 at 13 26 57" src="https://user-images.githubusercontent.com/18645509/81195888-4dc81700-8fb6-11ea-989e-29e629e86899.png">

To see it live. I just got any other website I knew had the Mailchimp popup installed and same, they are also broken:

`https://nocsok.com/about` 1 <-- example (scroll to the bottom of the page, then wait a couple of seconds for the popup content to load)

## Expected result:
Things in Brave should render like this (like in any other browser)
<img width="571" alt="Screenshot 2020-04-30 at 14 43 52" src="https://user-images.githubusercontent.com/18645509/81195991-6801f500-8fb6-11ea-8c3b-ee54af5c3f4e.png">

## Reproduces how often: 
Every page load (if shields are UP)

## Brave version (brave://version info)
Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? --> YES
- Is the issue reproducible on the latest version of Chrome? --> NO

**Comment by rebron** [comment]
cc: @ryanbr @pes10k Looks like we're breaking some functionality with mailchimp integration.

**Comment by pes10k** [comment]
@ryanbr do you know why the following are being blocked?

```https://downloads.mailchimp.com/css/signup-forms/popup/2.0/common.css
https://downloads.mailchimp.com/css/signup-forms/popup/2.0/banner.css
https://downloads.mailchimp.com/css/signup-forms/popup/2.0/layout-2.css
https://downloads.mailchimp.com/css/signup-forms/popup/2.0/modal.css
```

**Comment by pateskinasy** [comment]
I have a fourth file blocked on my site:

These are the ones blocked at [eskinasy.com](eskinasy.com)
```
https://downloads.mailchimp.com/css/signup-forms/popup/1.0/modal.css
https://downloads.mailchimp.com/css/signup-forms/popup/1.0/layout-2.css
https://downloads.mailchimp.com/css/signup-forms/popup/1.0/banner.css
https://downloads.mailchimp.com/css/signup-forms/popup/1.0/common.css
```

**Comment by pes10k** [comment]
assigning @ryanbr so that he gets the credit for the fix :)

**Comment by pateskinasy** [comment]
Thx for the fix!
