### ISSUE TITLE
[Android] Promotion notification is not cleared when error happens

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9657]
## Description 
User clicks on ad claim button in the panel. Error happens in claim flow (for this particular case in unblinding code) but user don't receive any feedback, just spinner. 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Expected result
If there is any error in claim flow we need to pass this back to the user and clear notification. So when we fetch promotions next time we get an actual result from the server and not something that is cached

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by gdregalo** [comment]
@NejcZdovc 
If multiple promotions are available, dismissing a promotion UI will open another promotion ready to be claimed. Is it safe to start the second claim while the first one is still being processed?

**Comment by NejcZdovc** [comment]
yes it's safe

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/the-claim-bat-button-is-gone-but-i-didnt-receive-last-months-reward/125922/2

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from https://github.com/brave/brave-core/pull/5520
Error message after tapping `Claim Grant`
![Screenshot_20200617-053418_Brave](https://user-images.githubusercontent.com/34715963/84852273-b944e000-b05c-11ea-894e-93ea6d1e0d66.jpg)

Error message after showing Rewards panel
![Screenshot_20200617-053329_Brave](https://user-images.githubusercontent.com/34715963/84852359-eb564200-b05c-11ea-9355-4da7991b7748.jpg)
