### ISSUE TITLE
Do not insert promotion if public key is empty

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9660]
Right now when we fetch promotions from the server we just insert them and only check if they are active. We should also check if public key is valid (meaning not an empty list) before inserting it.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Windows 10 OS Version 1809 (Build 17763.379)

- Verified test plan from https://github.com/brave/brave-core/pull/5485
- Verified promotion showed error when trying to claim 
<img width="1440" alt="Screenshot 2020-06-02 at 11 52 32 a m" src="https://user-images.githubusercontent.com/17010094/83512226-85f74280-a4ed-11ea-9b6a-152e47915397.png">
