### ISSUE TITLE
Guard claim promotion from the UI

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9662]
Right now if UI for some reason doesn't clear the claim button user could click on it twice which could override privacy pass data from the first click. To prevent this we should put guard in place in function `Promotion::Claim` (which is called from the UI, so that we check if promotion is already in progress we should exit so that we don't override any data. Retry logic will take over if something goes wrong

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc https://github.com/brave/brave-core/pull/5485 -  we cannot execute step 4 (solve captcha) and step 5 (make sure that you see an error and status stays at 1). After changing `promotion` status to 1, relaunch browser and click on BAT logo shows the `claim` button (so we don't have clear captcha modal). Click on `claim` just clears the promotion from UI. step 4 and 5 are expected? or it's bug.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya do not restart browser, change value in db while browser is still running

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc This time I didn't close the browser. After changing promotion status to `1`, I have solved captcha and I didn't see any error (I can see 20 BAT claimed grants) and also status in promotion table is NOT `1`
![image](https://user-images.githubusercontent.com/38657976/83441074-906cfa00-a463-11ea-904b-8cfae9d60d1e.png)
![image](https://user-images.githubusercontent.com/38657976/83441147-ad093200-a463-11ea-91c2-d92dcaec2841.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Windows 10 OS Version 1809 (Build 17763.379)

- Verified test plan from https://github.com/brave/brave-core/pull/5485
- Verified promotion showed error when trying to claim 
<img width="1440" alt="Screenshot 2020-06-02 at 11 52 32 a m" src="https://user-images.githubusercontent.com/17010094/83512226-85f74280-a4ed-11ea-9b6a-152e47915397.png">
