### ISSUE TITLE
Marketo error message when editing email with Shield up

### ISSUE THREAD

**Issue by frankfuu** [brave/brave-browser#9665]
## Description 

Error message "MKN: uninitialized() uninitialized()" shows up  when trying to edit an email in [Marketo](https://www.marketo.com/)

## Steps to Reproduce

   1. Login to a Marketo instance
   2. Look for any email and click "edit"
   3. Make an edit
   4. Wait for auto save to kick in

## Actual result:
![image](https://user-images.githubusercontent.com/7758528/81245050-64727a80-9057-11ea-9ee3-137e25a82853.png)

## Expected result: 
Message not to appear.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

Brave | 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit) | 
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | Linux

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

I think the offending trackers could be one of the following

- https://sn-mknodepub.marketo.com/mkto/static/mknode-client/mknode-client.js?app=mlm
- https://www.google-analytics.com/analytics.js
- https://app.pendo.io/data/ptm.gif/c9d7c253-a975-4161-4288-9f4726ad8446?v=2.19.1_prod&ct=15890340000470000&jzb=eJxVkM1somethingsomething14wZI4WMP

**Comment by ryanbr** [comment]
Which shield options is causing the issue @frankfuu ? (configure via the address bar)

**Comment by frankfuu** [comment]
Hi @ryanbr 

I think it is the "Cross-site option trackers blocked" option. When I disable this option but keep Brave Shields up for this site it still functions properly so I'm guessing this could be the culprit? 

![image](https://user-images.githubusercontent.com/7758528/81474003-0f488b80-9246-11ea-9b64-167ad3eac855.png)

**Comment by ryanbr** [comment]
Ah great. can you copy/paste the trackers into this Github report?

**Comment by frankfuu** [comment]
Yep it looks like this.

- https://sn-mknodepub.marketo.com/mkto/static/mknode-client/mknode-client.js?app=mlm
- https://www.google-analytics.com/analytics.js
- https://app.pendo.io/data/ptm.gif/c9d7c253-a975-4161-4288-9f4726ad8446?v=2.19.1_prod&ct=15890340000470000&jzb=eJxVkM1somethingsomething14wZI4WMP

**Comment by ryanbr** [comment]
Give it 24-48hrs, this commit should help. Thanks for the report @frankfuu 

https://github.com/easylist/easylist/commit/1158dc978b9c573d833da26e78175b2bd1ff1811

I'll leave this ticket open to confirm

**Comment by frankfuu** [comment]
Wow that was quick @ryanbr ! Thanks! 

Do I need to be in Non-Release channels (e.g. Nightly / Beta) to check?

**Comment by ryanbr** [comment]
Will be fixed in all channels :)

**Comment by ryanbr** [comment]
How is it looking @frankfuu ? everything okay?

**Comment by frankfuu** [comment]
Thanks @ryanbr ! That was lightning speed! 

Confirmed fixed on Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit) , Revision 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999} on Linux

**Comment by rebron** [comment]
@ryanbr ok to close this one?

**Comment by ryanbr** [comment]
Yup closed.
