### ISSUE TITLE
Remove binance.us from site suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9669]
## Description 

Remove LTC from suggestions for binance.us

Because it is not supported in the binance.us widget

## Steps to Reproduce

   1.  TYPE LTC or Litecoin in the URL bar

## Actual result:

Previous behavior is to have a .us and a .com suggestion.

## Expected result:

It should only have a .com suggestion

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified only `.com` suggestion is shown

![image](https://user-images.githubusercontent.com/34715963/82852812-379dde80-9f04-11ea-839b-40351dbe7aa6.png)
![image](https://user-images.githubusercontent.com/34715963/82852837-45536400-9f04-11ea-9052-ae52e2cf744c.png)
