### ISSUE TITLE
Remove sites from auto contribute list

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#967]
Add option to remove site from auto contribute list

**Comment by jasonrsadler** [comment]
Closed in https://github.com/brave/brave-core/pull/420

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Using test plan from https://github.com/brave/brave-core/pull/420
