### ISSUE TITLE
remove bookmark icon from top sites

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9672]
## Description 
In preparation for giving users the ability to edit top sites, remove the bookmark icon to remove the icon clutter on top sites. This will also improve perf on the new tab page as we're not needing to check for bookmarked sites.

## Steps to Reproduce

   1. Go to brave://newtab
   2. Ensure you have top sites.
   3. Hover over a tile and notice bookmark icon. 
   4. Expected result is that bookmark icon is no longer there.

## Actual result:

<img width="98" alt="screen_shot_2020-05-07_at_8 19 51_am" src="https://user-images.githubusercontent.com/5951041/81323738-ab0da800-904a-11ea-88eb-957fe5f8b871.png">

## Expected result:
![screen_shot_2020-05-07_at_12 37 02](https://user-images.githubusercontent.com/5951041/81323745-ae089880-904a-11ea-9288-f208c80025bc.png)

Future direction where we're only displaying one icon to edit or remove top sites.
<img width="536" alt="Screen Shot 2020-05-07 at 8 20 46 AM" src="https://user-images.githubusercontent.com/5951041/81323827-dbeddd00-904a-11ea-89f0-17693ddd752f.png">

## Reproduces how often: 
Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
Verified STR from the description
![image](https://user-images.githubusercontent.com/38657976/82880839-95f6ab80-9f5c-11ea-88eb-e035765b54d5.png)
- Installed 1.9.x added few top tiles and bookmarked them in NTP, upgraded to 1.10.x and verified that the bookmark icon is no longer displayed for top tiles

**Comment by LaurenWags** [comment]
Removing `QA Pass-Win64` as this will need to be rechecked on 1.9.x once uplift is approved and merged.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Veified STR from the description
Clean profile:
![image](https://user-images.githubusercontent.com/38657976/83142529-3dffa680-a10e-11ea-8f1f-d6d8764e2990.png)

Upgraded profile:

Install 1.9.72 add few top tiles in NTP and bookmark them and upgrade profile to 1.9.76 and verified that bookmarks icon is removed for top tiles

1.9.72
![image](https://user-images.githubusercontent.com/38657976/83143301-5a501300-a10f-11ea-9fcc-993d585d3d30.png)

1.9.76
![image](https://user-images.githubusercontent.com/38657976/83143413-89ff1b00-a10f-11ea-945c-8656881839b2.png)

**Comment by suryaceg** [comment]
It's still appearing. Please see.

![image](https://user-images.githubusercontent.com/840117/83394791-cb950c00-a416-11ea-9806-ab1765e5e811.png)

![Uploading image.png…]()

**Comment by bsclifton** [comment]
@suryaceg what version of Brave are you using? It should be 1.9.76 or newer
