### ISSUE TITLE
[Android] Icons in site settings menu are not properly tinted in dark mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#9674]
## Description 
Icons in `site settings` menu are not properly tinted in dark mode

## Steps to reproduce 

   1. Set dark mode
   2. Go to `Site settings`
   3. 2 last icons are not tinted there
![device-2020-05-07-151351](https://user-images.githubusercontent.com/30602739/81336168-d1493d00-9076-11ea-91ed-e9ee22b1dd0d.png)

## Actual result 
Icons are not tinted

## Expected result
Icons are tinted

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.7.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running BraveModernarm.apk 1.9.74
 - All the icons in the `Site settings` are tinted in dark mode
![Screenshot_2020-05-22-17-43-57](https://user-images.githubusercontent.com/38657976/82666726-1ca54300-9c54-11ea-99a2-1ea0774c9819.png)
