### ISSUE TITLE
[P3A] Amend Brave.Core.WindowCount question

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#9676]
## Test plan
1. Use build for a while (5-10 mins) with 1 window open (any platform)
2. Look in brave://local-state/ for `Brave.Core.WindowCount.2`
3. Value should be 1
4. On macOS, have no windows open (Brave will remain open)
5. Leave it open for 5-10 mins, so histogram records
6. In the profile directory, open the `local_state` file
7. Find the `Brave.Core.WindowCount.2` value and it should be 0

## Description
Need to understand number of users with 0 windows open separately from 1 window. New answers should be:
```
0) 0
1) 1
2) 2 to 5
3) 6 or more
```

**Comment by fmarier** [comment]
No difference from a data category point of view. :+1:

**Comment by bsclifton** [comment]
@mattmcalister is that correct? Answers being 0, 1, 1, and 2? (and not 0, 1, 2, 3)

**Comment by mattmcalister** [comment]
> @mattmcalister is that correct? Answers being 0, 1, 1, and 2? (and not 0, 1, 2, 3)

good catch. fixed

**Comment by GeetaSarvadnya** [comment]
@mattmcalister @bsclifton - Can we update the 3) 5 or more to `3) 6 or more`?

**Comment by bsclifton** [comment]
@GeetaSarvadnya updated! 😄 

About 4 minutes is OK - it does take a while to run. I was usually waiting 5-10 mins 😄

**Comment by bsclifton** [comment]
Closing as I believe this is closed

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5508
