### ISSUE TITLE
Fav icons for twitch

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#968]
When you are watching vod's on twitch favicon should be saved for that particular publisher.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/555
* Found that favicon does not display for the first VOD viewed by a publisher, however on second VOD played the favicon does display. Logged https://github.com/brave/brave-browser/issues/1566
![screen shot 2018-10-13 at 5 16 34 pm](https://user-images.githubusercontent.com/28145373/46910072-2610ea00-cf0c-11e8-98f7-23c6fef84fe9.png)
