### ISSUE TITLE
Please add a warning to Quit if installer has downloaded

### ISSUE THREAD

**Issue by yb66** [brave/brave-browser#9683]
## Description 

The Brave download isn't instantaneous by a long chalk (it's over 100MB). When prompted for the download I often start it going and then carry on browsing while I wait, and the download is in the background. I will then forget about it and quit meaning I have to go through the same cycle again.

## Steps to Reproduce

   1. Start download
   2. Start browsing while waiting for download
   3. Quit app and see the tiny download window closing
   4. Curse

## Actual result:

I reopen the app at some point and need to either:
a) wait when I'd rather be browsing.
b) browse and hope that what I'm browsing is uninteresting enough that I don't forget the download.

## Expected result:
More like hoped for result: I select Quit and it prompts me to complete the install.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Version 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Does the beta prompt for upgrades? How would I know?
- Can you reproduce this issue with the dev channel? I'm not going to do this.
- Can you reproduce this issue with the nightly channel? Or this.

## Other Additional Information:

It's not related to any of these.
- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Regards,
iain

**Comment by rebron** [comment]
Hi @yb66 You shouldn't have to re-install Brave via a download window when upgrading Brave. Upgrade prompts happen with the green arrow with the right hand corner menu and then upgrade downloads in the background. 

Can also manually check for updates here: brave://settings/help

If this happens to you again, can you attach a screenshot of what you're experiencing.

**Comment by yb66** [comment]
Hi @rebron,

Sorry if I wasn't clear, hopefully this will help.

1. I open Brave and it tells me a new version is available, I click "Install Update"

![Screenshot 2020-06-16 at 05 57 08](https://user-images.githubusercontent.com/326444/84985144-bd8bfe80-b12b-11ea-813e-418d19eb676b.png)

2. The download begins. 100MB+ is going to be a while on my connection.

![Screenshot 2020-06-16 at 05 57 27](https://user-images.githubusercontent.com/326444/84985221-ea401600-b12b-11ea-8727-0999872fd392.png)

3. While I'm waiting I start to browse.

![Screenshot 2020-06-16 at 05 57 48](https://user-images.githubusercontent.com/326444/84985274-00e66d00-b12c-11ea-9edd-e91ae419baee.png)

4. The install is ready… except it's not the front window, I'm browsing and because the internet is so engrossing I forget that Brave ever asked me to install anything.


5. As the app shuts down I briefly see the install-ready dialog and curse!

![Screenshot 2020-06-16 at 06 17 14](https://user-images.githubusercontent.com/326444/84985395-30957500-b12c-11ea-8f7d-aed2b5bc75ad.png)


What I'm hoping for is that if I press Quit and there's a download in progress or install ready that Brave warns me, else I have to go through the same cycle again next time.

Regards,
iain

**Comment by bsclifton** [comment]
Thanks for the clarification @yb66 😄 

This issue will be obsolete once we fix https://github.com/brave/brave-browser/issues/9562

**Comment by yb66** [comment]
@bsclifton I think it's fine to close this then. Thanks, and I appreciate the speedy responses.

Regards,
iain
