### ISSUE TITLE
May ads payout recovery

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9684]
We should preform one time check on user ad promotion and if it's in the bad state because of empty public key recover from it.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified the test plan from https://github.com/brave/brave-core/pull/5495.
* Confirmed putting the browser into a broken state with 1.8.95 in both cases.
* Launched broken profiles with 1.8.96 and confirmed balances displayed as expected.
* Confirmed able to tip in both cases after launching with 1.8.96.
* For test case 2, confirmed request to `/promotions/reportclobberedclaims` in terminal.

```
[ REQUEST ]
> url: https://grant.rewards.bravesoftware.com/v2/promotions/reportclobberedclaims
> method: UrlMethod::POST
> content: {"claimIds":["5fb28bd9-fb0d-45da-a1eb-47cdeea27913"]}
> contentType: application/json; charset=utf-8
[ END REQUEST ]
```
