### ISSUE TITLE
Unparsed HTML in Shields section of Settings Page

### ISSUE THREAD

**Issue by say4n** [brave/brave-browser#9690]
## Description 

brave://settings/ page shows `Look &amp; feel` instead of `Look & feel` for the heading.

## Steps to Reproduce

   1.  Go to brave://settings/
   2. Scroll down to the last item of Shields.
   3. That's it!

## Actual result:
<img width="1402" alt="Screenshot 2020-05-08 at 4 54 15 PM" src="https://user-images.githubusercontent.com/8839504/81401251-8ef22f80-914c-11ea-8267-72c33e78a041.png">

## Expected result:
The heading should read "Look & feel"

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)

Brave | 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes.
- Can you reproduce this issue with the beta channel?
Haven't tried.
- Can you reproduce this issue with the dev channel?
Haven't tried.
- Can you reproduce this issue with the nightly channel?
Haven't tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
No.

## Miscellaneous Information:

N/A.

**Comment by srirambv** [comment]
Can you update to `1.8.95` and check if its still happening? I don't see the issue on `1.8.95`

**Comment by say4n** [comment]
Ah, I did a `brew cask install`. Will update and get back to you ASAP.

**Comment by say4n** [comment]
Yes, @srirambv I updated to 1.8.95 (stable channel), and it is still there.


Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

<img width="1402" alt="Screenshot 2020-05-08 at 5 06 47 PM" src="https://user-images.githubusercontent.com/8839504/81402061-4e93b100-914e-11ea-8c2e-90266f9ea33d.png">

**Comment by srirambv** [comment]
Cant reproduce 
![image](https://user-images.githubusercontent.com/17010094/81402348-daa5d880-914e-11ea-95e7-02dac759d0e1.png)

cc: @kjozwiak @LaurenWags

**Comment by LaurenWags** [comment]
Reproducible with English (UK), possibly other variants as well. Does not reproduce with English (US).

```
Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

English (UK):
<img width="1837" alt="Screenshot 2020-05-08 at 7 47 06 AM" src="https://user-images.githubusercontent.com/28145373/81402843-2bdaab80-9100-11ea-98ee-bc5ebd694455.png">

English (US):
<img width="1835" alt="Screen Shot 2020-05-08 at 7 48 15 AM" src="https://user-images.githubusercontent.com/28145373/81402921-50368800-9100-11ea-8607-8e0582c5db16.png">

**Comment by rebron** [comment]
cc: @petemill While you're still in Settings can you take a look. Looks like a l10n issue with Look and Feel and displays with UK locale.

**Comment by say4n** [comment]
@rebron my issue is with en_IN though (not en_GB), I guess it may be an issue with locales other than en_US?

**Comment by LaurenWags** [comment]
@rebron I believe @say4n is correct, I didn't test every non-US English option for language on my laptop so my guess is that this affects multiple languages.

**Comment by srirambv** [comment]
+1 from @chaithanya-hr via https://github.com/brave/brave-ios/issues/2594

**Comment by say4n** [comment]
This issue seems to have been resolved. My current version string is as follows:

Brave | 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.15.6 (Build 19G73)

Should I close this issue?
