### ISSUE TITLE
Binance widget and autocomplete shouldn't use /en/ for all locales

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9691]
The Binance widget and autocomplete for site suggestions currently uses URLs with paths `/en/`
We should use one of these locales if they match first:

```
"en", "au", "cn", "tw", "ar", "nl", "ph", "fr", "de", "id",
 "it", "ja", "kr", "pl", "br", "pt", "ru", "es", "th", "tr",
 "ua", "vn", "ro", "cs", "he", "bg", "lv", "bn", "sv"
```

## Test Plan
**Autocomplete does not apply for Android**
1. Clean profile, with english set as device language
2. Navigate to the New Tab page, bring the Binance widget to the foreground, set TLD to `.com`
3. Ensure that the Buy Crypto button takes you to `https://www.binance.com/en/`
4. Repeat steps 1 - 3, but with a language from the list such as French. 
5. Clean profile, with english set as device language
6. In `brave://settings`, turn on suggested sites
7. In a new Tab, type in a keyword such as `bitcoin`
8. Confirm that `binance.com/en/` is shown as the suggested site
9. Repeat steps 5 - 8 with a language from the list such as French.
10. Repeat all steps using a locale that is unsupported, and ensure it defaults to English

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.21.65 Chromium: 88.0.4324.182 (Official Build) beta (64-bit)
-- | --
Revision | `73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202}`
OS | Linux

- Verified with supported EN locales (used IE), `Buy Crypto` button takes to `https://www.binance.com/en/`
- Verified enabling `Show Brave suggested sites` and typing `bitcoin` brings up `https://www.binance.com/en` in suggestion

https://user-images.githubusercontent.com/17010094/108828629-f899d800-75be-11eb-8f10-bdcbcbf90d39.mov

- Verified setting locale to French(FR), `Buy Crypto` button takes to `https://www.binance.com/fr/`
- Verified enabling `Show Brave suggested sites` and typing `bitcoin` brings up `https://www.binance.com/fr/` in suggestion

https://user-images.githubusercontent.com/17010094/108828771-2e3ec100-75bf-11eb-9b13-759950a3e63f.mov

- Verified setting locale to Greek(EL), `Buy Crypto` button takes to `https:/www.binance.com/en/`
- Verified enabling `Show Brave suggested sites` and typing `bitcoin` brings up `https://www.binance.com/en` in suggestion

https://user-images.githubusercontent.com/17010094/108828951-6e9e3f00-75bf-11eb-92dd-22735403e695.mov

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.21.70 x64 build
- Verified with supported EN locales (used IE), Buy Crypto button takes to `https://www.binance.com/en/`
- Verified enabling Show Brave suggested sites and typing bitcoin brings up `https://www.binance.com/en` in suggestion

https://user-images.githubusercontent.com/17010094/109496005-fb497100-7a87-11eb-8b58-c2854dc1c95c.mp4

- Verified setting locale to Netherlands(NL), Buy Crypto button takes to `https://www.binance.com/nl/`
- Verified enabling Show Brave suggested sites and typing bitcoin brings up `https://www.binance.com/es/` in suggestion

https://user-images.githubusercontent.com/17010094/109495881-ca693c00-7a87-11eb-8f46-d76c61adf950.mp4

- Verified setting locale to Hindi(HI), Buy Crypto button takes to `https:/www.binance.com/en/`
- Verified enabling Show Brave suggested sites and typing bitcoin brings up `https://www.binance.com/en/` in suggestion

https://user-images.githubusercontent.com/17010094/109495395-21224600-7a87-11eb-9104-b20405e6e9ed.mp4
