### ISSUE TITLE
Update NTP Brave Stats to 'Trackers & Ads Blocked' on desktop

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9692]
## Description 

Update NTP Brave Stat text from 'Ads and Trackers Blocked' to 'Trackers & ads blocked'

## Actual result:

![Screen Shot 2020-05-08 at 11 16 52 AM](https://user-images.githubusercontent.com/2388823/81435915-6dc61a80-911d-11ea-9829-b1d0ade392a7.png)

## Expected result:
![Screen Shot 2020-05-08 at 11 18 29 AM](https://user-images.githubusercontent.com/2388823/81436070-ad8d0200-911d-11ea-9055-5237f63d7ffa.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

All builds

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes 
 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

### Miscellaneous
This update is expected on all platforms.
iOS https://github.com/brave/brave-ios/issues/2528
Android https://github.com/brave/brave-browser/issues/9693

**Comment by rebron** [comment]
@0xedward Nice.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
- Verified both clean and upgraded profile
- Trackers & ads blocked count is retained after browser restart
![image](https://user-images.githubusercontent.com/38657976/84015773-fabcf780-a999-11ea-8c9e-a084b55ae668.png)
![image](https://user-images.githubusercontent.com/38657976/84015892-2213c480-a99a-11ea-9c10-26136b25358c.png)
