### ISSUE TITLE
[Android] Update NTP Brave Stats to 'Trackers & Ads Blocked'

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9693]
## Description 
Update NTP Brave Stat text from 'Ads and Trackers Blocked' to 'Trackers & ads blocked' . Can be done as part of https://github.com/brave/brave-browser/issues/9555

## Steps to reproduce 

   1. Open a new tab

## Actual result 
![Screen Shot 2020-05-08 at 11 20 57 AM](https://user-images.githubusercontent.com/2388823/81436264-0b214e80-911e-11ea-84b7-a2a1397f20c6.png)

## Expected result

![Screen Shot 2020-05-12 at 1 11 39 PM](https://user-images.githubusercontent.com/2388823/81740635-21971500-9452-11ea-9243-b67b1ab16534.png)

## Issue reproduces how often 
Easily

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): n/a
   - Device (Phone, Tablet, Phablet): n/a
   - Android version: n/a
   
## Brave version
All versions

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

### Miscellaneous
This update is expected on all platforms.
iOS https://github.com/brave/brave-ios/issues/2528
Desktop https://github.com/brave/brave-browser/issues/9692

**Comment by deeppandya** [comment]
@anthonypkeane @karenkliu i am updating this issue. it's just text change. i will finish it right away

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.106 x64 beta build
- Verified NTP stats text is updated to `Trackers & Ads Blocked`
![image](https://user-images.githubusercontent.com/17010094/89401937-fd279d80-d70d-11ea-93f4-e9339e4de31b.png)

--------
Verification passed on Samsung Tab A with Android 10 running 1.12.106 x64 beta build
- Verified NTP stats text is updated to `Trackers & Ads Blocked`
![image](https://user-images.githubusercontent.com/17010094/89401971-09abf600-d70e-11ea-8607-0821afa0b8ca.png)
