### ISSUE TITLE
[Android] Remove Sponsored images/Background images for devices running < Android 6

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9694]
## Description 
Remove Sponsored images/Background images for devices running < Android 6

## Steps to reproduce 

   1. Install Brave on a device running < Android 6
   2. Should not show any SI or Background images
   3. 

## Actual result 
Currently shows 

## Expected result
Should not show

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: Android 6
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Internal discussion here https://bravesoftware.slack.com/archives/C0816QH3R/p1588953717359200
cc: @kjozwiak @anthonypkeane @SergeyZhukovsky

**Comment by kjozwiak** [comment]
@SergeyZhukovsky I don't think this is going to get done for the `1.8.x HF1` release as we want to get both https://github.com/brave/brave-browser/issues/9733 and https://github.com/brave/brave-browser/issues/9724 out ASAP.

Lets move this into `1.9.x` for now 👍 Thoughts? CCing @bsclifton.

**Comment by bsclifton** [comment]
Definitely won't make it for the hotfix we're working on for all platforms. But it can be in a following one or the 1.9 release 👍

**Comment by LaurenWags** [comment]
Verification passed on LG Nexus 5 (ARM) with Android 5.1 running 1.11.98 using BraveModernx86.apk
* Confirmed for a clean install of 1.11.98 there are no background or SI on the NTP.
* Confirmed the previous NTP settings under Settings > Display are not shown
* Upgrade case 1 - Installed 1.10.99. Ensured background and SI were enabled on NTP. Upgrade to 1.11.98, confirmed there are no NTP images.
* Upgrade case 2 - Installed 1.10.99. Ensured background were enabled on NTP but SI were toggled off. Upgrade to 1.11.98, confirmed there are no NTP images.
* Upgrade case 3 - Installed 1.10.99. Ensured background were disabled on NTP. Upgrade to 1.11.98, confirmed there are no NTP images.
* Note, on clean install, this is what the screen looks like if the top site tiles are not ready: 
![Screenshot_2020-07-20-08-23-21](https://user-images.githubusercontent.com/28145373/87947634-9d749580-ca71-11ea-9ae4-926189f23685.png)

------
