### ISSUE TITLE
[Android] panel on Android uses 'publisher' but should probably say 'creator'

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9697]
## Description 
Android panel says `Brave Verified Publisher` but should probably use the same terminology as desktop which uses `Brave Verified Creator` instead.

## Steps to reproduce 

   1. Navigate to a verified publisher
   2. Open panel
 

## Actual result 
![android-GH](https://user-images.githubusercontent.com/28145373/81448115-df1cc200-914b-11ea-9127-19ead6ff45af.png)

## Expected result
<img width="977" alt="Screen Shot 2020-05-08 at 4 17 08 PM" src="https://user-images.githubusercontent.com/28145373/81448120-e2b04900-914b-11ea-8521-c14f392c437a.png">

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes 1.8.x (Beta channel)
   - Beta build? yes 1.10.x (Nightly channel)

## Device details
   - Install type (ARM, x86):  ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.8.93, 1.10.39

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Solved with new panel
