### ISSUE TITLE
[Android] Reddit publishers are not recognized on Android

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9698]
## Description 
If you navigate to a verified Reddit publisher on Android, the publisher info does not display in the panel, summary view is shown instead.

Note, on Nightly the BAT logo displays the verified check icon, but tapping on the logo still shows summary view, not publisher view.

I don't think Reddit was implemented on tabs version, I wasn't sure if we should get it automatically when switching to core.

## Steps to reproduce 

   1. Navigate to a verified reddit publisher (I was using staging) --> reddit.com/u/alex_the_brave
   2. Depending on which channel you are using, look at BAT logo. Release/Beta does not show verified check icon for this publisher, but Nightly will.
   3. Open panel.

## Actual result 
Release/Beta (1.8.x) no verified icon, summary view shown:
![reddit18x](https://user-images.githubusercontent.com/28145373/81449390-2906a780-914e-11ea-9404-35c01ad9653a.png)

Nightly (1.10.x) verified icon, summary view shown:
![reddit110x](https://user-images.githubusercontent.com/28145373/81449396-2c019800-914e-11ea-88cd-3920ec8f6da9.png)

## Expected result
Publisher info to be displayed similar to desktop
<img width="979" alt="Screen Shot 2020-05-08 at 4 17 51 PM" src="https://user-images.githubusercontent.com/28145373/81449341-12605080-914e-11ea-9ac7-e0603ccfdca6.png">

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? yes
   - Beta build? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.8.93, 1.10.39

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
I think Reddit is no longer supported on Android at the moment anyway, and will close this out due to new Rewards panel on Android in 1.35.

**Comment by LaurenWags** [comment]
@Miyayes This is still an issue in 1.36.x on Nightly, no publisher information is shown in panel. it just says reddit.com.



![Screenshot_20220124-154720](https://user-images.githubusercontent.com/28145373/150862278-22577e27-a2ba-4b69-9e3a-e5ab2681387e.png)
