### ISSUE TITLE
Apple app ID incorrect on release builds

### ISSUE THREAD

**Issue by RyanJarv** [brave/brave-browser#970]
## Description 
Brought up in https://github.com/brave/brave-core/pull/319#issuecomment-413366581

Release builds will have an extra dot at the end of the app id.

> com.brave.Browser.

This should be (edit: fixed spelling)

> com.brave.Browser

**Comment by bbondy** [comment]
`com.brave.Browser` right?

**Comment by bbondy** [comment]
any update on this? I mentioned the fix to @w0ts0n recently

**Comment by RyanJarv** [comment]
Not yet, not too hard of a fix just want to make sure it get's tested when it goes in. If anything is blocking this right now let me know.

**Comment by bbondy** [comment]
Test plan:
/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' Brave\ Browser\ Development.app/Contents/Info.plist


Should list:
com.brave.Browser.dev for dev channel
com.brave.Browser.beta for beta channel
com.brave.Browser.nightly for nightly channel

com.brave.Browser for release channel


Please check once for every channel.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

```
Kamils-MBP:~ kjozwiak$ /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Brave\ Browser\ Dev.app/Contents/Info.plist
com.brave.Browser.dev
```

Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

```
Kamils-MBP:~ kjozwiak$ /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Brave\ Browser\ Beta.app/Contents/Info.plist
com.brave.Browser.beta
```

**Comment by kjozwiak** [comment]
Once we get `Release` builds, will go through the same case and label as `QA Pass-macOS` when completed.

**Comment by LaurenWags** [comment]
Went through verification using the following build under `macOS 10.12.6 x64` - PASSED


Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

```
Laurens-MacBook-Pro:~ laurenwagner$ /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Brave\ Browser\ Beta.app/Contents/Info.plist
com.brave.Browser.beta
```


Brave | 0.56.2 Chromium: 70.0.3538.35 (Official Build) dev (64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Mac OS X

```
Laurens-MacBook-Pro:~ laurenwagner$ /usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Brave\ Browser\ Dev.app/Contents/Info.plist
com.brave.Browser.dev
```
