### ISSUE TITLE
Low BAT Adoption Rate - Browser/Website Edit Solution

### ISSUE THREAD

**Issue by thepostman97** [brave/brave-browser#9704]
## Description 

Current "Redeem BAT for Gift Cards" text appears below the web page fold and in the right hand column of the Rewards Settings page, and is not included on the Wallet window which shows how to buy BAT but not how spend BAT.

## Steps to Reproduce

   1. Click Brave Rewards triangle in the upper right corner of the desktop browser window. 
   2. Click Rewards Settings.
   3. Scroll down the page and look in the narrow right column to locate the following text "Redeem BAT for Gift Cards", "With TAP Network, you can redeem your BAT for popular name-brand gift cards", "Visit TAP", " * Requires Uphold Verification."

## Actual result:

Lower than expected BAT engagement from Brave Users

## Expected result:
Higher BAT engagement.

## Reproduces how often: 

Every time a user clicks on the Wallet triangle but doesn't click on the settings link, the message delivery of a key benefit of the Brave model fails. 

## Brave version (brave://version info)

Version 1.8.53 Chromium: 81.0.4044.83 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Unknown
- Can you reproduce this issue with the dev channel?
Unknown
- Can you reproduce this issue with the nightly channel?
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
Unknown
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

No

**Comment by NejcZdovc** [comment]
cc @mandar-brave @alexwykoff

**Comment by thepostman97** [comment]
Thank you. After more consideration, may I suggest replacing The words "Rewards Settings" to the right of "Add Funds" with "Spend Funds", which links to information on website donations spending or anything else they would like.
