### ISSUE TITLE
Fine tune time recording

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#971]
Play with youtube and twitch and make sure that time is recorded correctly

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

* Verified all scenarios from test plan and calculations looked correct
