### ISSUE TITLE
[Desktop] High CPU usage for Brave Browser on the Mac and ArcGIS web pages

### ISSUE THREAD

**Issue by kevinp2** [brave/brave-browser#9710]
## Description 
Slow performance and high CPU usage on certain ArcGIS web pages that host Covid dashboards

## Steps to Reproduce

   1. Open Brave Browser on the Mac: Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
   2. Navigate to this ArcGIS web page: `https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/ed483ecd702b4298ab01e8b9cafc8b83`
   3. Observer Activity Monitor % CPU for Brave Browser Helper processes.

## Actual result:
Web page is very slow and CPU usage goes high

## Expected result:
Normal CPU patterns

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@kevinp2 thanks for the report -I verified this is slow to load and takes up quite a bit of CPU.  I opened up hamburger menu (top right, 3 lines) and then picked `More Tools` => `Task Manager` and specifically the page was taking up the CPU

Is this page working OK for you in other browsers?

**Comment by kevinp2** [comment]
> @kevinp2 thanks for the report -I verified this is slow to load and takes up quite a bit of CPU. I opened up hamburger menu (top right, 3 lines) and then picked `More Tools` => `Task Manager` and specifically the page was taking up the CPU
> 
> Is this page working OK for you in other browsers?

@bsclifton, yes, the page loads quickly in Safari on MacOS and does not consume much CPU.  Brave struggles with it.

**Comment by rebron** [comment]
cc: @AndriusA When you get a chance can you help us out with this one? I see an initial spike on load in 1.10.x but doesn't seem high given the content of the page and I'd imagine we're matching Chrome perf. We should at least be matching Chrome perf on this page, WIndows and macOS.
