### ISSUE TITLE
Video player only shows black screen after switching tabs

### ISSUE THREAD

**Issue by sev-b** [brave/brave-browser#9711]
## Description 
Video players only show a black screen (with audio still playing) after switching to a new tab and back. I have encountered this issue both on Twitch and YouTube, on YouTube the black screen is only shown whilst the player hud/UI is visible (e.g. when you hover over the video).
I have disabled shield on both these sites.

## Steps to Reproduce

   1. Open a video (for example on YouTube or Twitch)
   2. Switch to a different new tab
   3. Go back to the video tab
   4. The video player is now a black screen (not always but often; in case of YouTube you have to hover over the video or pause it)

## Actual result:
![ezgif-5-e3a61123eb7a](https://user-images.githubusercontent.com/32382593/81509306-e25dac80-9309-11ea-916f-2687bb75a802.gif)
![ezgif-5-48ca7e158d05](https://user-images.githubusercontent.com/32382593/81509392-a37c2680-930a-11ea-8229-83f7220745b9.gif)

## Expected result:
![ezgif-5-08fc6f2d51f0](https://user-images.githubusercontent.com/32382593/81509303-dd006200-9309-11ea-94f4-06016eea6247.gif)
![ezgif-5-3ad1e57893b4](https://user-images.githubusercontent.com/32382593/81509338-2486ee00-930a-11ea-936c-3b17583f1b3a.gif)

## Reproduces how often: 
Intermittent issue

## Brave version (brave://version info)
Brave | 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by rebron** [comment]
@sev-b Is this still happening for you with the latest 1.10.97? Also, if you have Chrome still installed, are you seeing it happen there as well.

**Comment by sev-b** [comment]
@rebron nope, it seems to be fixes the latest, and at the time I tried to use different browsers (Chrome included) and I never had issues with them.

(Should I close the issue then?)

**Comment by bsclifton** [comment]
Thanks for following up @sev-b 😄 I'll go ahead and close
