### ISSUE TITLE
(Windows) Japan/Japanese locale not defaulting language setting to Japanese

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#9712]
## Description 
It's been reported that if your country / locale / language is set to Japan/Japanese on Windows, Brave is not setting the language by default. Users need to go to brave://settings/languages to manually change it

For an example of literature sharing how to manually set it (since it appears to be a bug), see https://freesoft-100.com/review/brave.html

## Steps to Reproduce
   1. Be on Windows; set locale to Japan/Japanese
   2. Remove any installs of Brave including profile data
   3. Install Brave

## Actual result:
When Brave launches (setup and after install), language is English

## Expected result:
Language shown should be Japanese

cc: @chkk525

**Comment by bsclifton** [comment]
Working back to find a root cause for this - it appears to have ALWAYS been an issue with Brave Core 🤔 

With my locale set to Japan/Japanese, here are the binaries I tested with (both the stub and standalone installers are tagged):
- [1.9.72](https://github.com/brave/brave-browser/releases/download/v1.9.72/BraveBrowserStandaloneSetup.exe) (Works! 🎉)
- [1.5.123](https://github.com/brave/brave-browser/releases/download/v1.5.123/BraveBrowserStandaloneSetup.exe) (does not work 😢)
- [1.1.20](https://github.com/brave/brave-browser/releases/download/v1.1.20/BraveBrowserStandaloneSetup.exe) (does not work 😢)
- [0.69.132](https://github.com/brave/brave-browser/releases/download/v0.69.132/BraveBrowserStandaloneSetup.exe) (does not work 😢)
- [0.62.50](https://github.com/brave/brave-browser/releases/download/v0.62.50/BraveBrowserStandaloneSetup.exe) (does not work 😢)
- [0.56.12](https://github.com/brave/brave-browser/releases/download/v0.56.12/BraveBrowserStandaloneSetup.exe) (does not work 😢)

You can tell immediately when it works because the "On your marks..." etc part of the installer is translated:
![image](https://user-images.githubusercontent.com/4733304/82497521-41a68400-9aa3-11ea-911a-3654a83fc8f3.png)

As well as the landing page:
![image](https://user-images.githubusercontent.com/4733304/82497540-49febf00-9aa3-11ea-8b65-3b189ab76a21.png)

**Comment by LaurenWags** [comment]
Verified passed with Win 10 x64 VM:

```
Brave	1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Windows 10 OS Version 1809 (Build 17763.914)
```

* Set VM to be Japan/Japanese. Downloaded BraveBrowserSetup.exe installer from https://github.com/brave/brave-browser/releases/tag/v1.9.72. Ran this stub installer. Confirmed installation screens were in locale/language selected for OS. 1.8.96 was installed as expected (this is stub installer and grabs latest release version), but also confirmed on launch that Brave was using correct locale/language:
<img width="1047" alt="japan - win10x64-stub1" src="https://user-images.githubusercontent.com/28145373/82502617-8b07cb00-9ac5-11ea-8abd-21969a39092e.png">
<img width="1055" alt="japan - win10x64-stub2" src="https://user-images.githubusercontent.com/28145373/82502622-8d6a2500-9ac5-11ea-81c7-e54cfcb515e9.png">

* Set VM to be Japan/Japanese. Downloaded BraveBrowserStandaloneSetup.exe installer from https://github.com/brave/brave-browser/releases/tag/v1.9.72. Installed using this standalone installer. Confirmed installation screens were in locale/language selected for OS. Confirmed on launch that Brave was using correct locale/language and that 1.9.72 was installed as expected:
<img width="1058" alt="japan - win10x64-standalone1" src="https://user-images.githubusercontent.com/28145373/82502631-91964280-9ac5-11ea-9c06-c3aee8ea44aa.png">
<img width="1051" alt="japan - win10x64-standalone2" src="https://user-images.githubusercontent.com/28145373/82502637-93f89c80-9ac5-11ea-8eca-583baf208e76.png">
