### ISSUE TITLE
[Android] Fix download link for top sites

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#9714]
## Description 
Download link for custom homepage top sites are missing the right permission.

## Steps to reproduce 

   1. Download the app with Ref code on the device with > android 6
   2. try to download link from the top sites
   3. 

## Actual result 
Download fails
## Expected result
it should ask for the permission for the new user and allow downloading

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Labelled as ARM since x86 devices do not have super referral.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.9.77 x64 stable build
- Verified downloading top tile asks for storage access 
-------
Verification passed on Samsung Tab A with Android 9 running 1.9.77 x64 stable build
- Verified downloading top tile asks for storage access
