### ISSUE TITLE
Remove preference for toggling RemoteDebugging

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#9715]
## Test plan
1. Load brave://settings/privacy
2. Verify that `Remote Debugging` no longer shows

## Description 
Follow-up from https://github.com/brave/brave-browser/issues/7645

Remove switch to toggle state of remote debugging.

**Comment by rebron** [comment]
@diracdeltas Sounds like this would be ok to remove. Not sure if there's a need to actually turn off remote debugging if we're already proxying.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.99 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description for both clean and upgraded profiles
* Confirmed `Remote debugging` option is not available in brave://settings/privacy

------

**Comment by rg-3** [comment]
>  Not sure if there's a need to actually turn off remote debugging if we're already proxying

The only need is to provide choice. As a user, I would prefer this to be always turned off and not use services relying on it. Proxy or no proxy I don't like the sound of this feature and would prefer it to be off. As a privacy-focused browser I found the issues relating to this odd, where convenience won over privacy. Personally I don't care if lighthouse is broken as long as it's not using questionable technology to do so.

**Comment by theronic** [comment]
Wait so how do I connect to Brave Browser from VSCode for remote debugging?

**Comment by xhorntail** [comment]
> Wait so how do I connect to Brave Browser from VSCode for remote debugging?

Exactly what brought me here.. I've been using Brave for years now, but had to uninstall today because this is just ridiculous. I'm not going to install an additional browser just to work on debugging JS. This option should be left to the user, or the bypass/solution should be well documented somewhere. This just feels deceptive.

**Comment by calebdw** [comment]
So...can I remote debug with Brave or do I need to install Chrome? The comments seem to indicate that the option as always on, but not sure how to check and / or configure the port.

**Comment by bsclifton** [comment]
@calebdw when fixing this GitHub issue, the setting was removed. You don't need to enable anything anymore, it should work just fine,

By default, it should be using port 9222. You can change this by passing in the port you'd like via the command line:
```
--remote-debugging-port=9222
```

If you're using an Android, make sure you're physically plugged in with USB.
cc: @deeppandya

**Comment by deeppandya** [comment]
> @calebdw when fixing this GitHub issue, the setting was removed. You don't need to enable anything anymore, it should work just fine,
> 
> By default, it should be using port 9222. You can change this by passing in the port you'd like via the command line:
> ```
> --remote-debugging-port=9222
> ```
> 
> If you're using an Android, make sure you're physically plugged in with USB.
> cc: @deeppandya 

And you should have USB debugging enabled in Developer options.

**Comment by calebdw** [comment]
Ah thanks!

Is this documented anywhere? Running `-h/--help` yields a no manual entry error
