### ISSUE TITLE
Litecoin only shows one Brave suggested sites  

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9718]
## Description 

Litecoin only shows one Brave suggested sites  

## Steps to Reproduce

   1. Install / Upgrade to Dev 1.9.61
   2. Open a new tab and type `Litecoin` or `Lite`
   3. Only shows one suggested site

## Actual result:

<img width="1055" alt="Screen Shot 2020-05-11 at 12 29 08 PM" src="https://user-images.githubusercontent.com/17010094/81533652-31e0be80-9384-11ea-9e4d-1169ac47eb20.png">
<img width="1055" alt="Screen Shot 2020-05-11 at 12 37 43 PM" src="https://user-images.githubusercontent.com/17010094/81533671-3b6a2680-9384-11ea-8dda-dc51498f4105.png">

## Expected result:
Should show both suggested links as per spec

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.9.61 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA 
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Found while testing #9302

**Comment by bbondy** [comment]
I updated the spec to only list one item. The reason was because binance.us doesn't have that asset in its widget.
