### ISSUE TITLE
Suggested site and history suggested link shows up as duplicate

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#9719]
## Description 

Suggested site and visited link shows up as duplicate

## Steps to Reproduce

   1. Install dev 1.9.61
   2. Type BTC in URL bar
   3. Select Brave suggested link and wait for the page to load
   4. Close tab and open new tab
    5. Type BTC the suggested site and visited site both show up making it a duplicate entry

## Actual result:

The only way to differentiate is the highlighted text in one of the entry 
<img width="1055" alt="Screen Shot 2020-05-11 at 12 29 57 PM" src="https://user-images.githubusercontent.com/17010094/81533933-b59aab00-9384-11ea-8620-27f8f00dd93b.png">

## Expected result:
Only show Brave suggested site if the user has visited the link and has it as a history suggestion 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.9.61 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{# 999}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Found while testing  #9302

**Comment by bbondy** [comment]
Putting P5 since this is now disabled by default with no plans to re-enable.

**Comment by bbondy** [comment]
This is no longer valid as of 1.48.x since the suggested sites feature (which is disabled by default) is no longer available.
