### ISSUE TITLE
Don't fetch publisher list on restart

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#972]
## Steps to Reproduce

   1. fresh profile
   2. enable rewards
   3. restart browser

## Actual result:

publisher list is fetched again

## Expected result:
publisher list should be fetched only after 48h

## Reproduces how often: 

Easily reproduced

**Comment by LaurenWags** [comment]
@NejcZdovc @ryanml looking at the test plan in https://github.com/brave/brave-core/pull/534 step 3 mentions HTTP debug messages. What parameters/flags do we need to launch with in order to see these?

**Comment by NejcZdovc** [comment]
@LaurenWags we don't have flag yet, so this needs to be tested with system network check

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with steps from test plan in https://github.com/brave/brave-core/pull/534
* Verified publishers.basicattentiontoken.org is called after Rewards is enabled:
![screen shot 2018-10-16 at 4 26 48 pm](https://user-images.githubusercontent.com/28145373/47045781-abd9a300-d161-11e8-8957-a6d8bc8f9c4c.png)
* Verified on relaunch that publishers.basicattentiontoken.org is not recalled:
![screen shot 2018-10-16 at 4 33 27 pm](https://user-images.githubusercontent.com/28145373/47045805-bac05580-d161-11e8-90f4-928d653539f2.png)
