### ISSUE TITLE
[Desktop] Desktop change for user wallets via KYC

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#9723]
Details captured in the Android issue here: https://github.com/brave/brave-browser/issues/9636

cc @bradleyrichter @jenn-rhim for opinion on any design specific changes.
This is a P2 that should hit BR on Desktop after prelim work.

**Comment by mandar-brave** [comment]
Upgraded to a P1.

Logic:
Remove access to Uphold flow for any user unless the have 25 BAT in earnings
And allow an existing user to relogin from the Brave flow.

Expected UI change is in the Verify Wallet flow; for users under 25 BAT we need to allow an existing user who does not see the Verify Wallet message to Login. needs discussion @jenn-rhim 

Details in spec for how to manage the flows.

cc @NejcZdovc @evq @jenn-rhim

**Comment by mandar-brave** [comment]
@NejcZdovc re-opening issue and restarting case flow from Android. In the discussion with Uphold, I missed updating the entire Android state flow here.

if user has <25 bat, they cannot verify a new wallet. Wallet needs to exist (this flow is working well) -- this seems like working as expected.
if user has <25 bat and not logged in with ID verified, all other flows (withdraw, add funds) need to be masked out. As in these flows need the user to re-login first to exist.

For a user is a pre-existing wallet user, and relogins back successfully, then enable Add-Funds and Withdraw. 

Alternative path for user with < 25 BAT (for desktop only); keep Add Funds and Withdraw; any clicks with a non ID checked wallet forces user to login. Do not take user to verify wallet modal (that will create a lot of confusion and breaks logic of the minimal 25 BAT value)

cc @LaurenWags

**Comment by LaurenWags** [comment]
fyi @srirambv on https://github.com/brave/brave-browser/issues/9723#issuecomment-662528125 to confirm Android matches this expected result

**Comment by NejcZdovc** [comment]
@mandar-brave closing this one as it was already merged, please open a new issue

**Comment by mandar-brave** [comment]
@LaurenWags @srirambv there was no requirement for Android for the "relogin" use case as yet. Will file a P3 for Android separately.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5986

Verified that click on `Verify Wallet` from the settings page opens up `Cancel` and `Login` pop up modal
![image](https://user-images.githubusercontent.com/38657976/89003298-0afbae00-d31d-11ea-92ac-efee6178ca93.png)
- Verified that click on `Login` redirects to `Sign in to uphold`
