### ISSUE TITLE
[Android] Implement pagination for publisher list

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#9724]
Created duplicate of https://github.com/brave/brave-browser/issues/9607 as this was placed in `1.9.x` for desktop. If there's another HF for desktop, https://github.com/brave/brave-browser/issues/9607 will be moved into that milestone. However, this will most likely go out first in the `1.18.x HF1` on Android that will include the CR bump.

## Test plan

See https://github.com/brave/brave-core/pull/5458

* Original PR --> https://github.com/brave/brave-core/pull/5458
* Uplift into `1.9.x` --> https://github.com/brave/brave-core/pull/5471
* Uplift into `1.8.x` --> https://github.com/brave/brave-core/pull/5472

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy j3 version 5.1.1 running `BraveModernarm.apk 1.8.112`
- Verified the test plan from https://github.com/brave/brave-core/pull/5458#issuecomment-626023782
- Verified that able to see the following verified publisher types on Android: regular sites, youtube channels, twitter, vimeo, and github. 
![Screenshot_2020-05-13-11-14-33](https://user-images.githubusercontent.com/38657976/81777275-228d7c80-950e-11ea-9fb4-529b65a66028.png)
![Screenshot_2020-05-13-11-15-30](https://user-images.githubusercontent.com/38657976/81777279-24574000-950e-11ea-97d1-ba2355fcef94.png)
![Screenshot_2020-05-13-11-16-29](https://user-images.githubusercontent.com/38657976/81777280-24efd680-950e-11ea-9de3-46ca342a6ca6.png)
![Screenshot_2020-05-13-11-34-34](https://user-images.githubusercontent.com/38657976/81777284-25886d00-950e-11ea-8af2-53f260245fdf.png)
![Screenshot_2020-05-13-10-46-52](https://user-images.githubusercontent.com/38657976/81777286-25886d00-950e-11ea-8e9c-1b47bb0a386a.png)
![Screenshot_2020-05-13-10-50-46](https://user-images.githubusercontent.com/38657976/81777290-26210380-950e-11ea-876e-09eed4a00868.png)
![Screenshot_2020-05-13-10-52-54](https://user-images.githubusercontent.com/38657976/81777295-26b99a00-950e-11ea-8af0-8632685ab143.png)
![Screenshot_2020-05-13-10-54-29](https://user-images.githubusercontent.com/38657976/81777297-27523080-950e-11ea-8edd-6f75606f8cdb.png)
![Screenshot_2020-05-13-10-58-44](https://user-images.githubusercontent.com/38657976/81777298-27eac700-950e-11ea-9b49-c99888fbfc91.png)
![Screenshot_2020-05-13-11-01-22](https://user-images.githubusercontent.com/38657976/81777300-28835d80-950e-11ea-9a0b-e01d3ec5bbbb.png)
- Encountered #7766, #7826, #9698, #9696 and #9697
