### ISSUE TITLE
[Desktop] DCHECK failure - view_counter_model.cc(30)] Check failed: -1 != total_image_count_ (-1 vs. -1)

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#9728]
Steps to reproduce:

1. Clear user dir
2. Put any promode code like ABCDEF(it should not organic and SR promo code)
3. Launch Browser
4. Open NTP and try reloading

Result from Debug build: DCHECK failure
```
[64319:775:0511/141533.833035:FATAL:view_counter_model.cc(30)] Check failed: -1 != total_image_count_ (-1 vs. -1)
```

Result from Release build
1. User only could see first wallpaper before relaunching (or ntp si component is updated)
2. After restarting, this issus will be fixed.

**Comment by simonhong** [comment]
I found the reproduce step.
1. Clear user dir
2. Put invalid SR code like `ABCDEF`(not default and SR)
3. Launch Browser
4. Open NTP and try reloading

**Comment by simonhong** [comment]
If browser has non-SR referral code, user will only see first SI bg(background-0.jpg) image among SI assets before NTP SI component is updated or browser relaunching after install.
If browser is relaunched or component is update, this issue is gone.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.18.69 Chromium: 87.0.4280.88 (Official Build) (64-bit)
-- | --
Revision | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
OS | Windows 10 OS Version 2004 (Build 19041.630)

```
- Verified the STR from the description
- When a profile is launched with a non-SR promo code, open NTP is showing normal NTP with bg image, reload NTP is showing SI in NTP. 
- Verified that the component NTP SI version is updated immediately in brave://components after the browser launch, hence the NTP SI images are shown correctly.
![image](https://user-images.githubusercontent.com/38657976/101185347-c63fa500-3677-11eb-8222-5e84a4bc0eb2.png)
