### ISSUE TITLE
[Android] Upgrade Chromium 81.0.4044.129 to Chromium 81.0.4044.138

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#9736]
**`Changelog:`**

* https://chromium.googlesource.com/chromium/src/+log/81.0.4044.122..81.0.4044.138?pretty=fuller&n=10000

**`QA tests:`**

List QA passes once they've been created.

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.8.112 on Samsung Galaxy Tab S5e (Android 9.0)

![Screenshot_20200515-204553_Brave](https://user-images.githubusercontent.com/34715963/81733208-eb798580-9491-11ea-921d-4c9251b7960b.jpg)

-----
