### ISSUE TITLE
LocationBar color doesn't update when changing theme

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#974]
## Steps to reproduce
- Go to Settings > Appearance
- Change theme between light and dark

### Expected
All toolbar colors, including location bar colors change immediately

### Actual
LocationBar colors do not change until something else updates the location bar (e.g. click)

## Notes
Needs to observe the prefs change, or the theme change (if we had such an observer), and update the colors. This is not built-in to chromium since an extension theme cannot change the location bar colors.

**Comment by simonhong** [comment]
As you expected, I think we should override `LocationBarView::OnThemeChanged()` and do similar thing in `OnNativeThemeChanged()`.

**Comment by srirambv** [comment]
@petemill just mouse over is enough to change the colour
![url](https://user-images.githubusercontent.com/17010094/45128098-24ece000-b14a-11e8-9420-5dd8a4db715d.gif)

**Comment by petemill** [comment]
Closing brave/brave-core#407 as duplicate which states "introduces switching NativeTheme between dark and light when our theme service mode is changed between dark and light. However, this does not change immediately when the user changes between light and dark via preferences. The user must switch tabs before these colors are re-calculated.

Similarly for GetOmniboxColor which is also sync'ed to light and dark choice, though that re-paints when the LocationBar is hovered.

Both should observe the theme mode preference and change immediately."

**Comment by LaurenWags** [comment]
Verification Pass with

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X
