### ISSUE TITLE
Brave connects to Rob Wu's website on startup

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#975]
EDIT: this appears to be for PDFJS telemetry

not sure what this is for, but i never saw it in browser-laptop. maybe PDFJS updates?

![screen shot 2018-09-05 at 10 59 47 am](https://user-images.githubusercontent.com/549654/45114339-98b6ca80-b101-11e8-8710-ce409ea7db6b.png)

Version: 0.54.4 Chromium: 70.0.3528.4 (Official Build) dev (64-bit) MacOS

**Comment by diracdeltas** [comment]
I think this for PDFJS's telemetry feature: https://github.com/Rob--W/pdfjs-telemetry

I disabled the telemetry module in our PDFJS fork which is probably why this didn't happen in browser-laptop

Maybe we should disable PDFJS telemetry by default since there's an option for it?

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified with test plan from https://github.com/brave/adblock-lists/pull/33
