### ISSUE TITLE
Some users reporting AC turning back on unexpectedly

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9750]
## Description 
Some users are reporting AC turning on despite having reported tuning it off in the past:

https://www.reddit.com/r/BATProject/comments/g6rtm4/autocontribute_turned_on_and_donated_20bat_to_no/
https://www.reddit.com/r/BATProject/comments/g0ri6g/browser_sent_2000_bat_to_brave_software_when_i/
https://www.reddit.com/r/BATProject/comments/g4v6f0/today_the_browser_sent_20_bat_itself/
https://www.reddit.com/r/BATProject/comments/gbcwcl/new_patch_new_ac_bug/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

## Steps to Reproduce

   1. 
   2. 
   3. 

## Reproduces how often: 
No steps to reproduce 

## Brave version (brave://version info)
Has been discussed in 1.7.98, 1.5.92 which would not be expected versions for this to happen based on #6716.  

## Version/Channel Information:
Release channels

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
This should be fixed with https://github.com/brave/brave-browser/issues/9869

**Comment by cryptojennie** [comment]
+ 1 from community: https://www.reddit.com/r/BATProject/comments/gse0n7/brave_auto_contribute_keeps_turning_on_and_im/ 

A-C turned back on specifically after browser update.

**Comment by cryptojennie** [comment]
+1 from community: 

> I've set a new system in the chain and even with the auto contribute disabled as soon as the new computer got registered it donated ~60 USD to Brave Foundation or whatever.

https://www.reddit.com/r/BATProject/comments/gwv11n/june_5_2020_brave_ads_payout_megathread/ft16aoi?utm_source=share&utm_medium=web2x

**Comment by cryptojennie** [comment]
+1: 
https://www.reddit.com/r/BATProject/comments/gwv11n/june_5_2020_brave_ads_payout_megathread/ftdj9ku?utm_source=share&utm_medium=web2x

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5844 / https://github.com/brave/brave-core/pull/5844#issuecomment-644565715

* Cleared `Local Storage` via DevTools for both panel and brave://rewards and confirmed AC remained off

<img width="1321" alt="Screen Shot 2020-06-17 at 11 18 32 AM" src="https://user-images.githubusercontent.com/28145373/84917067-d98c9300-b08c-11ea-8f2a-b638cf9090a8.png">

<img width="1727" alt="Screen Shot 2020-06-17 at 11 20 21 AM" src="https://user-images.githubusercontent.com/28145373/84917086-dee9dd80-b08c-11ea-903b-90228f2ad02a.png">
