### ISSUE TITLE
Welcome modal should no longer show if chrome.braveWallet.loadUI is available.

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9753]
As the disclosure statement is now a WebUI interface under `brave://wallet`, after clicking `I understand` users should not see the welcome modal again once the Crypto Wallets extension loads.

## Test Plan
1. Start Brave with a clean profile
2. Navigate to `brave://wallet`
3. Click `I understand`, prompting page reload.
4. Ensure that the welcome modal containing that original disclosure statement is not present.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)
```
- Verified the STR from the description
