### ISSUE TITLE
ETH Phishing Blacklist should be behind proxy cache

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9754]
Related: https://github.com/brave/devops/issues/3048

## Test Plan
1. Upgrade to latest Crypto Wallets extension.
2. Open Networking tab via background inspection for the Crypto Wallets extension
3. Ensure all infura calls, including blacklist go through `${network}-infura.brave.com`. For the blacklist, specifically `https://mainnet-infura-api.brave.com/`
4. Ensure `api.infura.io` does not appear in the contacted domains.

**Comment by GeetaSarvadnya** [comment]
https://bravesoftware.slack.com/archives/C7VLGSR55/p1590601314351800

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux

- Verified test plan from issue description
- Verified blacklist is proxied through `https://mainnet-infura-api.brave.com/`
 ![image](https://user-images.githubusercontent.com/17010094/83716556-dab1cf00-a64d-11ea-8d6d-eb21118cb365.png)
- Verified no calls to `api.infura.io` is captured when the extension is enabled and in-use
