### ISSUE TITLE
[P3A] Bookmarks count response value isn't showing correctly when bookmarks count is altered

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9755]
## Description 

[P3A] Bookmarks count response value isn't showing correctly when bookmarks count is altered

Q5: How many bookmarks do you have?
(Brave.Core.BookmarksCountOnProfileLoad.2)

0. 0-5
1. 6-20
2. 21-100
3. 101-500
4. 501-1000
5. 1001-5000
6. 5001-10000
7. More than 10000

## Steps to Reproduce

   1. Clen profile 1.8.x
   2. Open brave://local-state
   3. Make sure bookmarks count response value is `0`  
   6. Open 6 websites in new tabs and bookmark them
   7. Refresh brave://local-state
   8. Verify that bookmarks count response value is `1` as expected
   9. Out of 6 bookmarks delete one bookmark 
   10. Refresh brave://local-state
   11. Bookmarks count response value is not changed from `1` to `0` (waited for 10 mins)

Note: Page refresh and browser restart did not fix the issue.

## Actual result:

[P3A] Bookmarks count response value isn't showing correctly when bookmarks count is altered
## Expected result:
[P3A] Bookmarks count response value should show correct value when bookmarks count is altered

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @iefremov

**Comment by bsclifton** [comment]
Hi @GeetaSarvadnya - this was implemented recently with https://github.com/brave/brave-core/pull/5473 and is only in Nightly (1.10) actually. We have a PR to uplift to 1.9 with https://github.com/brave/brave-core/pull/5524
