### ISSUE TITLE
Install and lazy loading of Crypto Wallets

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9757]
# Overview

Due to the way we implicitly download the Crypto Wallets extension (MetaMask fork) on first use, we have several users that have extra network activity and resource usage that they don’t want or need. 

This spec will make it so explicit action is needed for the extension to be downloaded, and will also lazy load the extension if it’s already installed on first use.

# Not part of this spec

- Reducing network activity within the Crypto Wallets extension when it is loaded.

# Targeted Platforms

- Desktop

# Description

## Explicitly Installing Crypto Wallets

If the user does not have Crypto Wallets installed, but navigates to brave://wallet. They will get a first screen equivalent to the following popup which is built-in via web-ui and NOT part of the Crypto Wallets extension.  It will no longer be a popup and will take up the whole screen under the red / purple gradient settings bar.

<img width="384" alt="Screen Shot 2020-05-12 at 3 13 38 PM" src="https://user-images.githubusercontent.com/831718/81735538-2fa16180-9463-11ea-9e2e-9bb2a3b279bf.png">

## Re-opt in for Crypto Wallets if not setup
If a user has not setup Crypto Wallets yet, but the user does have the extension installed, then they will be considered as not installed, and it will show the above screen asking the user to Install.  We will check if the user has setup Crypto Wallets based on if the wallet seed is stored in preferences already.  These users will be considered as “not installed” in the sections below. I.e. they will need explicit opt-in for the extension to ever be loaded.

## Changes to Dapp detection infobar
When a user visits a Dapp page, they are already presented with this infobar:

<img width="414" alt="Screen Shot 2020-05-12 at 3 14 04 PM" src="https://user-images.githubusercontent.com/831718/81735578-3def7d80-9463-11ea-80a0-9f4abcffbaa4.png">

The behaviour of the Setup button will change.  If the user clicks Setup, a new tab will open with brave://wallet and the infobar will disappear. The page will not reload anymore.  This will not auto install the Crypto Wallets extension anymore.

For the equivalent infobar when MetaMask is installed, we’ll change “Use Crypto Wallets” to “Setup Crypto Wallets”.  If the user clicks it, it will navigate to brave://wallet and will not auto install the Crypto Wallets extension anymore.

<img width="619" alt="Screen Shot 2020-05-12 at 3 14 43 PM" src="https://user-images.githubusercontent.com/831718/81735634-552e6b00-9463-11ea-8435-b620236997b0.png">

## Startup behaviour

When the Crypto Wallets extension is installed, it will be by default lazily loaded henceforth. So on startup, Crypto Wallets will not be loaded.

The extension will be loaded in the following cases:

- If the user visits brave://wallet, the extension will be loaded if it is already installed.
- If the user visits a Dapp page and has Crypto Wallets set as the Dapp provider, but the extension is not loaded yet, the built-in web3 detection will show a new infobar message asking if the user would like to load Crypto Wallets. “Would you like to start Crypto Wallets for web3 support on this page? [ Yes ] [ Settings ].  If the user selects Yes, the extension will be loaded and the page will be reloaded.  If the user clicks Settings it will go to the Crypto Wallets settings section described below. The user can also use the [ x ] to get rid of the infobar.  If the user has any other Dapp provider setting, no infobar will be shown.  If the user would like to stop setting this infobar, they can turn off Crypto Wallets as the Dapp provider in settings.
- If the new setting described below is on, then on startup it will be loaded.

## Settings
A new setting will be added under the existing Web3 provider for using Dapps setting called “Load Crypto Wallets on startup”.  It will be defaulted to off. 

# QA Plan

### Test cases 1:
- Fresh profile, go to brave://wallet, make sure process doesn’t start (You can check via Brave’s Task Manager in the hamburger menu under More Tools).
- Click the button in Crypto Wallets to opt-in.  Task Manager should show that the extension is loaded.  Chrome:/settings/extensions should have Crypto Wallets set as the App provider.
- Close the browser and re-open, you should see Crypto Wallets not listed in Task Manager.
- Open the browser and the process shouldn’t be there, navigate to brave://wallet again and it should automatically start the process and load the Crypto Wallets interface.
- Go to Crypto Kitties while the process is still already started, it should not show an infowar and window.web3 should be available in the developer console.
- Close the browser and re-open it, the crypto kitties tab should prompt for loading the extension.
- Clicking on Start Crypto Wallets and reload should start the process in task manager and reload the page.  window.web3 should be available.
- Go to settings and click on Load Crypto Wallets on startup
- Close and open the browser, go to the crypto kitties page and it should not prompt you. It should just have window.web3 available. 

### Test cases 2:
- Fresh profile, go to crypto kitties.
- It should prompt you with an infowar to setup Crypto Wallets. Clicking on Setup should open a new tab and let you opt-in.
- Going back to the crypto kitties page and manually reloading should have web3 available.

### Test case 3:
- Fresh profile, install MetaMask
- Go to crypto kitties and in the infowar select to use MetaMask
- Going to settings should show that MetaMask is selected
- Going to crypto wallets and opting in, should not change the setting of MetaMask.
- Closing the browser and then going to Crypto kitties should have web3 available without an infobar. I.e. the lazy loading is only for Crypto Wallets, not MetaMask.

### Test case 4:
- Fresh profile, install MetaMask
- Go to crypto kitties and in the infowar select to use Crypto Wallets
- Settings should show Crypto Wallets as the Dapp provider
- Closing the browser and then going to Crypto kitties should have an infobar asking to start crypto wallets.

### Test case 5:
- Use a profile that existed from a previous version of Brave that had Crypto Wallets fully setup
- Check to make sure no process for crypto wallets exists in the task manager
- Navigate to brave://wallet, it should load the extension

### Test case 6:
- Use a profile that existed from a previous version of Brave that had Crypto Wallets installed but not setup
- Check to make sure no process for crypto wallets exists in the task manager
- Navigate to brave://wallet, it should NOT load the extension, but require an opt-in

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.11.25 Chromium: 81.0.4044.138 (Official Build) nightly (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux

Test for #9757

Scenario 1: 
- Verified on a fresh profile there is no process started until opted in. 
- Verified closing the browser and reopening doesn't list Crypto Wallet process
- Verified closing and reopening browser and visiting `brave://wallet` start the process 
- Verified with process running, visiting Crypto Kitties doesn't show info bar and `window.web3` is available in the tab
- Verified closing and relaunching browser and visiting Crypto Kitties shows info bar to start CW and reload the tab
- Verified setting process to always load works between relaunches

Scenario 2:
- Verified on a clean profile visiting CryptoKittes brings up info bar  to setup Crypto
- Verified clicking on setup in info bar loads `brave://wallet` in new tab and shows opt-in page
- Verified after opt-in reloading the page provides `window.web3` on the tab

Scenario 3: 
- Verified installing MM and setting it as default doesn't start the process. 
- Verified visiting CryptoKittes and setting MM as default also sets in setting 
- Close and relaunch browser doesn't start the process
- Verified opting to CW doesn't change settings for default web3 provider

Scenario 4: 
- Verified installing MM on a clean profile and visiting CryptoKitties shows info bar to choose default Dapp provider. Selecting CW sets its as default Web3 provider in settings
- Verified closing and relaunching the browser and visiting CryptoKitties shows info bar asking to restart the CW process

Scenario 5: 
- Verified from an existing profile where CW is fully setup, upgrading shows no process for CW in task manager
- Verified visiting `brave://wallet` loads the extension and works fine

Scenario 6:
- Verified from an existing profile where CW is loaded but not setup, upgrading shows no process for CW in task manager
- Verified visiting `brave://wallet` shows opt-in page

Ran into #9821 for scenarios 5/6 which is fixed in https://github.com/brave/brave-core/pull/5591


-------
Test for #8121

- Verified on a clean profile visiting CryptoKitties shows info bar and selecting CW loads `brave://wallet` in a new tab and goes into opt-in state
------

Test for #6595

- Verified having a window size of 400px by 400px and visiting `brave://wallet` loads the opt-in webUI which is responsive and scrollable

------

Test for #8925

Verified there is no constant polling in the background when the process is not running 

-------

Test for #8860

- Verified there is no Infura calls when the process is not running
-------

Test for #8120

- Verified visiting a Dapp automatically triggers info bar to setup CryptoWallet
- Verified if MM is installed and visiting a Dapp automatically triggers info bar to choose between CW and MM as default Dapp provider

**Comment by srirambv** [comment]
Moving to 1.10.x Beta as brave/brave-core#5624 is uplifted

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.81 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)
```

**`Test Case #1`**

* ensured `Extensions: Crypto Wallets` was being launched when launching Brave for the first time with a new profile
* ensured that visiting `brave://wallet` doesn't launch `Extensions: Crypto Wallets` (refreshed several times)
* ensured that `Extensions: Crypto Wallets` was launched once `I Understand` is clicked via the disclaimer
* ensured that `Crypto Wallets` for `Web3 provider for using Dapps` was selected as the default under `brave://settings/extensions`
* ensured that `Extensions: Crypto Wallets` wasn't being launched when restarting the browser and `Load Crypto Wallets on startup` is disabled under `brave://settings/extensions`
  * ensured that visiting `brave://wallet` launched `Extensions: Crypto Wallets`
* while `Extensions: Crypto Wallets` is running, visited https://www.cryptokitties.co and ensured that the infobar wasn't being displayed
  * ensured that `window.web3` is available via the browser console/dev tools

```
window.web3
  Proxy {_requestManager: a, currentProvider: Proxy, eth: w, db: e.exports, shh: s, …}
  [[Handler]]: Object
  [[Target]]: _
  [[IsRevoked]]: false
```

* restarted the browser and ensured that the infobar under https://www.cryptokitties.co was being displayed as `Extensions: Crypto Wallets` hasn't been launched

<img width="1406" alt="Screen Shot 2020-06-03 at 4 40 34 PM" src="https://user-images.githubusercontent.com/2602313/83686956-1b133d80-a5b9-11ea-9e4c-b6ab4a108a0a.png">

* ensured that clicking on `Start Crypto Wallets and reload` launched `Extensions: Crypto Wallets` and the page was refreshed and didn't redisplay the infobar the second time around
  * ensured that `window.web3` is available via the browser console/dev tools

```
window.web3
  Proxy {_requestManager: a, currentProvider: Proxy, eth: w, db: e.exports, shh: s, …}
  [[Handler]]: Object
  [[Target]]: _
  [[IsRevoked]]: false
```

* ensured that `Extensions: Crypto Wallets` loads when the browser is launched when `Load Crypto Wallets on startup enabled` has been enabled via `brave://settings/extensions`
  * ensured that loading https://www.cryptokitties.co didn't display the infobar as `Extensions: Crypto Wallets` was launched during startup


**`Test Case #2`**

* ensured that visiting https://www.cryptokitties.co dislpays the following infofar

<img width="1221" alt="Screen Shot 2020-06-03 at 4 58 32 PM" src="https://user-images.githubusercontent.com/2602313/83688474-7ba37a00-a5bb-11ea-914d-a2818c952afc.png">

* ensured that selecting `SETUP` opens `brave://wallet` in a new tab
  * ensured that clicking on `I understand` opted the user into Crypto Wallets and launched `Extensions: Crypto Wallets`
  * ensured that `window.web3` is available via the browser console/dev tools


```
window.web3
  Proxy {_requestManager: a, currentProvider: Proxy, eth: w, db: e.exports, shh: s, …}
  [[Handler]]: Object
  [[Target]]: _
  [[IsRevoked]]: false
```

**`Test Case #3`**

* ensured visiting https://www.cryptokitties.co and selecting `Use MetaMask` via the infobar changed `Web3 provider for using Dapps` to `MetaMask` via `brave://settings/extensions`

<img width="1210" alt="Screen Shot 2020-06-03 at 5 09 13 PM" src="https://user-images.githubusercontent.com/2602313/83689401-fa4ce700-a5bc-11ea-8dcf-1cbe131800e1.png">

* ensured that `MetaMask` was still selected for `Web3 provider for using Dapps` under `brave://settings/extensions` once Crypto Wallets was enabled via `brave://wallet` 
* ensured that restarting the browser and loading https://www.cryptokitties.co didn't display the infobar as lazy loading is only applicable for Crypto Wallets and not MetaMask.

**`Test Case #4`**

* installed MetaMask and ensured `Web3 provider for using Dapps` was still `Ask` under `brave://settings/extensions`
* ensured that selecting `SETUP` under https://www.cryptokitties.co changed `Web3 provider for using Dapps` to `Crypto Wallet` under `brave://settings/extensions`
* restarted the browser and ensured that the infobar displayed `Start Crypto Wallets and reload` after loading https://www.cryptokitties.co

**`Test Case #5`**

* Downloaded & launched `1.9.76 CR: 81.0.4044.138` (latest release) and setup a Crypto Wallet
* renamed `Brave-Browser` --> `Brave-Browser-Beta` and relaunched `1.10.81 CR: 81.0.4044.138` and ensured `Extensions: Crypto Wallets` wasn't launched on startup
* opened `brave://wallet` and ensured `Extensions: Crypto Wallets` was launched
* ensured that logging into the wallet worked without any issues

**`Test Case #6`**

* Downloaded & launched `1.9.76 CR: 81.0.4044.138` (latest release) to installed Crypto Wallets (didn't setup)
* renamed `Brave-Browser` --> `Brave-Browser-Beta` and relaunched `1.10.81 CR: 81.0.4044.138` and ensured `Extensions: Crypto Wallets` wasn't launched on startup
* opened `brave://wallet` and ensured that `Extensions: Crypto Wallets` wasn't launched and the user was asked to opt into Crypto Wallets
* ensured that selecting `I understand` loads `Extensions: Crypto Wallets`
