### ISSUE TITLE
Don't throw when accessing local,sessionStorage in 3p frame

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#9758]
Currently, Chromium throws an exception when JS just touches `window.{local,session}Storage`, which prevents sites from doing typical feature detection style checks.  We should just act as if these values aren't present (e.g. `window.localStorage === undefined|null`) so that defensive / well programmed sites still work correctly

**Comment by pes10k** [comment]
This is related to https://github.com/brave/brave-browser/issues/8514

**Comment by iefremov** [comment]
Should be resolved in https://github.com/brave/brave-core/pull/5533

**Comment by LaurenWags** [comment]
@pes10k @iefremov @bridiver could we get a test plan for this one please? If no manual QA is required, let's change the label to `QA/No`. Thanks! cc @rebron @kjozwiak

**Comment by pes10k** [comment]
Hi @LaurenWags , i just added tests for this at https://dev-pages.brave.software/storage/exceptions.html.  I think the text there explains the cases, but as long as the "received" column matches the "expected" column when shields are up, then it should be golden

**Comment by LaurenWags** [comment]
Thanks @pes10k! 

Verified passed with

```
Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-browser/issues/9758#issuecomment-666281980
* Confirmed with default shields the `received` column value matches the `expected` column value on https://dev-pages.brave.software/storage/exceptions.html

<img width="1160" alt="Screen Shot 2020-07-30 at 1 44 54 PM" src="https://user-images.githubusercontent.com/28145373/88956273-24442200-d26b-11ea-8356-6e465264f24c.png">

-------

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build
- Verified test plan https://github.com/brave/brave-browser/issues/9758#issuecomment-666281980
- Verified with default shields settings `expected and `received` values match 
   <img width=500 src=https://user-images.githubusercontent.com/17010094/89866490-8aa03d00-dba7-11ea-8f4b-4aea6c806fbb.png>

-------

Verification passed on OnePlus 6T  with Android 10 running 1.12.111 x64 build
- Verified test plan https://github.com/brave/brave-browser/issues/9758#issuecomment-666281980
- Verified with default shields settings `expected and `received` values match 
   <img width=400 src=https://user-images.githubusercontent.com/17010094/89866667-d8b54080-dba7-11ea-9c0c-170bf7dffead.png>
