### ISSUE TITLE
Be able to specify a specific version with Windows stub installer

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#976]
Current stub installer always tries to install latest version in update server.

**Comment by RyanJarv** [comment]
Fairly certain this is supported somehow, may be worth looking into what the chromium QA process is if it's documented anywhere.

**Comment by bsclifton** [comment]
For anyone wanting to check this out, `src/chrome/installer/mini_installer/mini_installer.cc` is a good place to start 😄

**Comment by simonhong** [comment]
I'll close this issue when we can build omaha standalone installer from brave-core (https://github.com/brave/brave-browser/issues/1784) because we can install specific brave version with standalone installer.

**Comment by bbondy** [comment]
Updated label to 0.56.x since the associated PR was merged there.
