### ISSUE TITLE
Add import/export db for QA

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9766]
We need to have a mechanism for QA to validate issues on android. A lot of times this includes modifying or checking data in database. To enable QA to do that we need option to import db file or export current db file. All of this should be available only in QA section for now.

Import
User needs to have an option to select db file from the phone and override it in the profile.

Export
User needs to have an option do download current db file in the profile to the phone

**Comment by samartnik** [comment]
In addition to QA options, export option was added to general Developer options section to be accessible for users.
![device-2020-05-21-073654](https://user-images.githubusercontent.com/30602739/82562146-aebd2680-9b42-11ea-8461-dc37f65c7bab.png)
![device-2020-05-21-073622](https://user-images.githubusercontent.com/30602739/82562159-b250ad80-9b42-11ea-8858-ad88cd741320.png)
![device-2020-05-21-073640](https://user-images.githubusercontent.com/30602739/82562164-b4b30780-9b42-11ea-8f9d-b1baebc3efc2.png)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.9.77 x64 stable RC build
- Verified able to export DB file successfully
-------
Verification passed on Smasung Tab A with Android 9 running 1.9.77 x64 stable RC build
- Verified able to export DB file successfully
-------

**Comment by abnvkdl** [comment]
@samartnik Hi there I am a brave nightly user...I was using nightly build of brave android...How do I unlock the QA preferences because it asks for QA code...

**Comment by samartnik** [comment]
`QA preferences` are intended for the internal QA team only
