### ISSUE TITLE
Better experience/clarity when an Uphold wallet needs to be re-connected

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9769]
## Description 
When users see the expected "Uh-oh your wallet has been disconnected" message asking them to reconnect Uphold, they seem to find this confusing and offputting.  This is an expected condition.  Perhaps we can redesign this to better explain what happened and why there is a need.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
This should be resolved with the new Rewards panel. We introduced new messaging from Cody.
