### ISSUE TITLE
add a way for QA to import wallets into rewards

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#9772]
## Description 

QA needs a way we can import reward wallets into android so we can easily test cases that needs either a UGP/Ad grant. QA has a list of staging ~500 wallets that have ad grants which QA uses on desktop to run through several Rewards/User Wallet cases.

Currently we need to request the server side rewards team to load particular `payment id` wallet with an ad grant which slows things down for both teams.

### `Quick note`

This will be internal only and shouldn't be available for end users. This will mostly be used by QA to verify claiming ad grants and other promotions.

## Steps to Reproduce

**`N/A`**

## Actual result:

**`Example on Desktop`**

<img width="711" alt="Screen Shot 2020-05-13 at 7 20 03 PM" src="https://user-images.githubusercontent.com/2602313/81875657-c5fe8180-954e-11ea-85b3-8cd58cef127f.png">

**`Example on iOS`**

<img width="298" alt="Screen Shot 2020-05-13 at 7 23 56 PM" src="https://user-images.githubusercontent.com/2602313/81875867-4de48b80-954f-11ea-924f-ff10eb36b216.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the dev channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @SergeyZhukovsky @LaurenWags @srirambv @mandar-brave @anthonypkeane

**Comment by samartnik** [comment]
Test plan:
1. Get some staging wallet with known recover pass phrase;
2. Claim grant;
3. Try to restore and make sure balance transferred;

**Comment by srirambv** [comment]
This is not fixed on 1.11.x. Added follow up issue #10932. Going to move this out of 1.11.x release and use #10932 to test the feature. The fix is only for QA purpose and won't affect end-user so not blocking the release for this.
