### ISSUE TITLE
CryptoWallet signing typed data UI is blocked

### ISSUE THREAD

**Issue by nicholasmueller** [brave/brave-browser#9775]
## Description 
The signing modal using the built in crypto wallet does not allow scrolling down when the typed data message is larger than the modal height.

## Steps to Reproduce

   1. try to sign a typeddata transaction

## Actual result:

![81643786-8a7d8d80-9450-11ea-8fcf-feb3963ca451](https://user-images.githubusercontent.com/29919550/81904219-2cd27800-95ed-11ea-9e7a-d314a7a9a05a.png)

See the orange arrow, you are unable to scroll down to confirm the signature. 

## Expected result:

Be able to scroll down and see all the typeddata and click confirm. Same like metamask.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no 
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/ethereum-remote-client/pull/147

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.12.86 Chromium: 84.0.4147.85 (Official Build) beta (64-bit)
-- | --
Revision | e20c13e958edc3707db3d26d513780a7f6331a4b-refs/branch-heads/4147@{# 837}
OS | Linux
Component | `0.1.56`

`Ethjs Personal Sign` | `Sign Typed Data` | `Sign Typed Data V3` | `Sign Typed Data V4`
--| -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/87666515-a65b2380-c760-11ea-92ae-97b17dd6143e.png) | ![image](https://user-images.githubusercontent.com/17010094/87666415-80ce1a00-c760-11ea-80fe-23261cbddc0f.png) | ![image](https://user-images.githubusercontent.com/17010094/87666447-8d527280-c760-11ea-8b56-99309f3d646b.png) | ![image](https://user-images.githubusercontent.com/17010094/87666478-98a59e00-c760-11ea-9fa9-81fb8471e023.png)
