### ISSUE TITLE
Various labels are dark text on dark background for dark theme

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#978]
Security Chip text and other LocationBar labels.

![image](https://user-images.githubusercontent.com/741836/45137804-01806000-b15f-11e8-8188-1557641c72fe.png)

![image](https://user-images.githubusercontent.com/741836/45137809-07764100-b15f-11e8-8ac7-bac1936fea4a.png)

This occurs because by default the `Label` view will make sure that the text color is readable by comparing the foreground and background colors.

Often the background color is inferred from the NativeTheme, even though it may actually not be set, or be on a different background color, set by a ThemeProperty.

Two ways to get around this:
1. Set the `SetAutoColorReadabilityEnabled(false);` property of the `Label` view for these items.
2. Use the Dark Aura theme in Dark mode, instead of just in Private mode.

We should certainly do (2) and eventually override more values in the `NativeTheme`, but (1) may be a quicker solution.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/45851597-11419c00-bd3c-11e8-82dc-89326b43c5b8.png)

![image](https://user-images.githubusercontent.com/34715963/45851621-2ae2e380-bd3c-11e8-8ed3-9110164b339e.png)

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

<img width="1103" alt="screen shot 2018-09-21 at 8 24 31 am" src="https://user-images.githubusercontent.com/2602313/45881166-64d1db00-bd78-11e8-9e02-79569952c15c.png">

<img width="311" alt="screen shot 2018-09-21 at 8 24 53 am" src="https://user-images.githubusercontent.com/2602313/45881170-68656200-bd78-11e8-906b-71582e5224ab.png">

<img width="211" alt="screen shot 2018-09-21 at 8 25 48 am" src="https://user-images.githubusercontent.com/2602313/45881178-6b605280-bd78-11e8-8df7-e5720da0dc4f.png">

<img width="1085" alt="screen shot 2018-09-21 at 8 27 31 am" src="https://user-images.githubusercontent.com/2602313/45881182-6ef3d980-bd78-11e8-8b9d-7dc9fba12a86.png">
