### ISSUE TITLE
[Android] Add top site and brave suggested site suggestion settings on Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9782]
Please add 2 new toggles in Android suggestions for controlling the prefs: `kTopSiteSuggestionsEnabled`
and `kBraveSuggestedSiteSuggestionsEnabled`.

It is to control the URL bar suggestions that come up.

The strings for them exist already for desktop in `IDS_SETTINGS_APPEARANCE_SETTINGS_USE_AUTOCOMPLETE_TOP_SITES` and
`IDS_SETTINGS_APPEARANCE_SETTINGS_USE_AUTOCOMPLETE_BRAVE_SUGGESTED_SITES` in `app/brave_generated_resources.grd`

It is needed for 1.9.x, Basically there are some new suggestions that we populate for brave suggested sites like "Bitcoin" to give a link to buy bitcoin on Binance with a referral code. 

The new suggestions FYI are these: https://github.com/brave/brave-core/blob/master/components/omnibox/browser/suggested_sites_provider_data.cc#L13

The default of the toggles is to be on.
The work for Suggested sites is all done here https://github.com/brave/brave-browser/issues/9302 
This is just a toggle to be able to turn it off from the Android side.

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.9.77 x64 RC build
- Verified 2 new entries for `Show top sites in autocomplete` and `Show suggested sites in autocomplete` under privacy
- Verified disabling `Show top sites in autocomplete` disables Alexa suggestions
- Verified disabling `Show suggested sites in autocomplete` disables Brave suggested sites 
- Verified settings work on both normal and private tabs
----------
Verification passed on Samsung Tab A with Android 9 running 1.9.77 x64 RC build
- Verified 2 new entries for `Show top sites in autocomplete` and `Show suggested sites in autocomplete` under privacy
- Verified disabling `Show top sites in autocomplete` disables Alexa suggestions
- Verified disabling `Show suggested sites in autocomplete` disables Brave suggested sites 
- Verified settings work on both normal and private tabs
