### ISSUE TITLE
Refcode is preceded with equal sign on Windows

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9783]
Follow up to https://github.com/brave/brave-browser/issues/7742

Ref codes are broken on Windows. 
This is a regression introduced in 1.9.x

## Steps to Reproduce

   1. Download a stub installer
   2. Add `-RED194` to the stub installer (for example `BraveBrowserDevSetup` -> `BraveBrowserDevSetup-RED194.exe`)
   3. Run the stub installer
   4. Open `brave://local-state` and check for `promo_code`

## Actual result:

promo_code is `=RED194`

![image](https://user-images.githubusercontent.com/34715963/81969388-2dcfcd80-961e-11ea-9f41-edf9479fd7d1.png)

## Expected result:
promo_code is `RED194`

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.9.66 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @rebron @bsclifton @corymcdonald @keur @emerick

**Comment by emerick** [comment]
@keur I think the problem is here, the extra equals sign needs to be removed on this line:

https://github.com/brave/brave-core/blob/cc8a6fe7e1b6807d374d65727e2eb5d5c36ae5f1/chromium_src/chrome/installer/mini_installer/mini_installer.cc#L20

**Comment by keur** [comment]
@emerick Yep. I came to the same conclusion. See the above PR.

**Comment by emerick** [comment]
Ohh, OK awesome - missed that!

**Comment by btlechowski** [comment]
I am not sure if we can fully test it. The changes were made in stub installer, but the installer downloads and installs version 1.8.x.

@keur Is testing on stub installer 1.9.70 which downloads 1.8.x good enough? Please note that upon release we always check ref codes so we will test fully on 1.9.x

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Windows 10 OS Version 1809 (Build 17763.914)
```

* Using Win 10.x64 VM ran thru the following scenarios:

1. Installed via `test` channel stub installer using normal promo code, `SGE733`. Confirmed correct version, 1.9.70, was installed. Confirmed `download_id` and `promo_code` on brave://local-state. @keur confirmed my `download_id` on the production server.

2. Installed via `test` channel stub installer using lower case promo code, `sge733`. Confirmed correct version, 1.9.70, was installed. Confirmed `download_id` and `promo_code` on brave://local-state. @keur confirmed my `download_id` on the production server.

3. Installed via `test` channel stub installer without using a promo code. Confirmed correct version, 1.9.70, was installed. Confirmed `download_id` and `promo_code` on brave://local-state (default promo code). @keur confirmed my `download_id` on the production server.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified on `test` server
Verified for uppercase ref code, lowercase ref code and default refcode

Verification passed on

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.592)

Verified on `test` server
Verified for uppercase ref code and lowercase code.

**Comment by bsclifton** [comment]
@btlechowski the stub installer will download the mini_installer from Omaha; using the `test` channel is a great way to verify it

Nice work, @LaurenWags 😄 👍
