### ISSUE TITLE
wrong folder created on macOS if refcode is lower case - follow up to 7742

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9785]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/7742 - found by @kjozwiak 

If the promocode in the pkg file name is lower case (ex. Brave-Browser-Dev-kam253.pkg instead of Brave-Browser-Dev-KAM253.pkg), then the pkg incorrectly creates a `Brave-Browser-Dev-kam253` profile folder when it should be creating `Brave-Browser-Dev` folder with a `promoCode` file inside.

Note, it does also create a promoCode file inside this profile folder, however, because the profile folder is named incorrectly, when you launch the browser it creates a new profile folder (correctly named), thus, the promo code never gets picked up.

Also important to note, you have to manually rename the pkg file to get it to be lower case, since when you download the pkg from referral page you are served the correctly named pkg with the refcode in caps.

## Steps to Reproduce

pre-req: don't have Dev installed or any dev profile folders
   1. Download pkg file for Dev from GH page
   2. Rename and add "-refcode" where refcode is something like `kam253` (be sure to use lower case
   3. Install from pkg.
   4. Look at the profile folder that was created

## Actual result:

<img width="767" alt="Screen Shot 2020-05-14 at 2 41 57 PM" src="https://user-images.githubusercontent.com/28145373/81973139-b126fa00-95f1-11ea-8555-0e85817763a8.png">

## Expected result:
"-refcode" should not be added to profile folder. Profile folder should be named appropriately for the channel ex:
<img width="769" alt="Screen Shot 2020-05-14 at 2 40 52 PM" src="https://user-images.githubusercontent.com/28145373/81973213-cdc33200-95f1-11ea-9f3e-2f1a2976a034.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.9.66 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unsure
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? unsure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @keur @bsclifton @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

- Verified correct profile folder is created when refcode is in lowercase. @keur confirmed the download id in backend.

**Comment by rebron** [comment]
Verified pass.

Same steps as https://github.com/brave/brave-browser/issues/9785#issuecomment-630961235 and verified download_id with @keur using macOS Version 10.15.5. 

1. .pkg using KAM253 (Brave-Browser-KAM253.pkg)
2. kam253 (Brave-Browser-kam253.pkg)
3. no promo code.

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F83c)
