### ISSUE TITLE
[Android] "Your wallet is verified" notification does not display on Android

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9787]
## Description 
On Desktop when your Uphold wallet becomes verified, you get a notification like the below:
![verified-desktop](https://user-images.githubusercontent.com/28145373/81984378-b476b180-9602-11ea-97eb-39049b9ba2d2.png)

On Android, you get the red notification bubble, but when you tap on the BAT logo, there's no notification (similar to what happens with https://github.com/brave/brave-browser/issues/9576).

Issues where this was implemented on desktop:
https://github.com/brave/brave-browser/issues/5004#issuecomment-527616712
https://github.com/brave/brave-browser/issues/5874#issuecomment-528391798

## Steps to reproduce 

   1. Using 1.10.x and staging, get an ad grant.
   2. Claim Ad grant.
   3. Tap on Verify Wallet.
   4. Start the wallet verification process (note, this is important, you cannot just connect an already verified/KYC'd Uphold account, you must start with one that is not KYC'd).
   5. Wait for verification (request from Uphold if necessary - lmk if you need instruction on this).
   6. Once you get confirmation verification has occurred, relaunch Brave.

## Actual result 
You will see a red notification bubble on BAT logo, but when you open panel, there's no notification.

## Expected result
Should be a notification w/ text like desktop.

## Issue reproduces how often 
easily

## Issue happens on 
   - Current Play Store version? n/a
   - Beta build? yes, Nightly

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.10.22

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
fyi @Miyayes this still occurs with 1.35.77 on Android. The expected design no longer matches what is in the issue but the notification still does not display even with the new panel work.

**Comment by Miyayes** [comment]
Closing in favor of: https://github.com/brave/brave-browser/issues/23519
