### ISSUE TITLE
Top/Pinned Sites Can't be Removed (Reappear after refresh)

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9788]
## Test plan
See https://github.com/brave/brave-core/pull/6584

## Description 
I spoke with a user last night who was finding it impossible to remove a pinned site from their New Tab Page. Removing it would appear to work, but refreshing the NTP would show the same site again. I took a look at the `grid-sites-data-v1` in localStorage, and found that the `removedSites` array had over 700 entries. Additionally, the entries in the array were extremely redundant, with identical objects repeated.

## Steps to Reproduce
N/A

## Actual result:
Users may not be able to remove pinned sites.

## Expected result:
Users can remove pinned sites.

## Reproduces how often: 
N/A

## Brave version (brave://version info)
1.8.96

## Other Additional Information:
Wiping out `grid-sites-data-v1` from localStorage appears to have resolved the issue.

## Miscellaneous Information:
![image](https://user-images.githubusercontent.com/815158/81984971-37940980-95fb-11ea-85d8-21d70600c607.png)

**Comment by adamwinn** [comment]
I see this same issue.  I'm on `Version 1.10.90 Chromium: 83.0.4103.97 (Official Build) (64-bit)` but it's been happening for a couple of months now


![Screenflick Movie 93](https://user-images.githubusercontent.com/3028964/84841203-e8c4ff80-affe-11ea-9227-9503aa870104.gif)

**Comment by norsehealer** [comment]
I'd be ok with a local file for them so that I can easily add/remove the ones I want.  

right now I have 2 icons for youtube. one for https://www.youtube.com and youtube.com.  unpinning one and clicking the X doesn't remove it.

**Comment by jonathansampson** [comment]
Would you (@adamwinn or @norsehealer) be available for a Zoom call? I'd love to take a more direct look at the issue you're experiencing. If so, please make sure your browser is fully up-to-date, and let me know when would be most convenient for you 🙂

**Comment by adamwinn** [comment]
@jonathansampson I've already deleted my `grid-sites-data-v1` file to fix it

**Comment by jonathansampson** [comment]
@adamwinn Thank you for the update; I'm sorry it came to that. We'll work on identifying the root issue, and fixing it in a future build.

**Comment by norsehealer** [comment]
Brave is up to date
Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)

I've literally removed the same 3-5 sites and just hit refresh and they're back. I've unpinned 1 and both youtube icons, removed the one and both, refresh and they're back.  Even the pinned sites aren't being shown until I remove a few sites.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.17.69 Chromium: 87.0.4280.60 (Official Build) (x86_64)
Revision	12697cfeb273d7de95cf9b18350d2c457f58224c-refs/branch-heads/4280@{#1352}
OS	macOS Version 10.14.6 (Build 18G6042)
```

Verified test plan from https://github.com/brave/brave-core/pull/6584
Testing notes can be found under https://github.com/brave/brave-browser/issues/9457#issuecomment-712306639
Additional notes that may be helpful: there is no more pinning top site tiles with 1.17.x. Additionally, modifications to top site tiles made with 1.16.x (and before) are not retained when upgrading to 1.17.x. Modified STR to check removing a tile was confirmed  as per the test notes in "Removing sites and Most Visited mode" case.

----------------
