### ISSUE TITLE
Folders in bookmarks toolbar are almost invisible 

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#979]
With current 0.55.1 version, folders in the bookmarks toolbar are easy to see because they are higher contrast.  However, when the popup is shown (the folder contents), the sub-folders are basically invisible
![image](https://user-images.githubusercontent.com/4733304/45136921-4aceb080-b15b-11e8-957b-da2b718c00eb.png)

**Comment by simonhong** [comment]
70.0.3538.6 has fix for this issue.
Need to check when brave-core is updated to 70.0.3538.6.

**Comment by bbondy** [comment]
added it to autoclose in my pr for when it lands.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

<img width="564" alt="screen shot 2018-09-21 at 8 17 39 am" src="https://user-images.githubusercontent.com/2602313/45880766-0a844a80-bd77-11e8-8734-c867c46e6845.png">
