### ISSUE TITLE
Option to disable autofill while in private browsing mode

### ISSUE THREAD

**Issue by Arbiter-Odie** [brave/brave-browser#9795]
## Description 
Private browsing mode does not disable autofill suggestions. This could be a privacy breach for users who are screen sharing, or live-streaming by revealing email accounts.

## Steps to Reproduce

   1. Have a Brave Profile that has information stored in the Autofill system
   2. Open a brave Private Browsing window from that profile
   3. Open a website that the profile has Autofill information stored for 
   4. Click on a field that Autofill has information stored for

## Expected result:
Private browsing windows are expected to have no crossover with the rest of the profile.

## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.778)
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,WebUIDarkMode,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AudioServiceOutOfProcess,SmsReceiver,NotificationTriggers,AllowPopupsDuringPageUnload,VideoPlaybackQuality,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Arbiter Odie\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | 5e3a236d-4113a79e

**Comment by bsclifton** [comment]
@diracdeltas @yrliou is this expected behavior? I thought off the record profiles inherit from the regular profile, but wasn't sure if that was supposed to include autofill

**Comment by diracdeltas** [comment]
@bsclifton this is the behavior in chrome but i think it makes sense to disable this in brave. just want to make sure we think of any use cases where people really want to have it autofill in private from data that is in regular.

**Comment by rebron** [comment]
Expected result of "Private browsing windows are expected to have no crossover with the rest of the profile" isn't true. The easy is example here is bookmarks. 

This could be a separate setting for autofill suggestions for private window.

**Comment by Arbiter-Odie** [comment]
Well, it's obvious that the bookmarks have crossover because the user sees them as soon as the private window opens. It's not obvious that Autofill is going to display your accounts to a website, because it doesn't happen until the user clicks on a field that Autofill has information stored for. This may not have happened in previous private sessions.

My behavior expectation for Autofill was probably informed by the way extensions work -- i.e. the user must manually enable an extension before it works in a private window.

**Comment by fmarier** [comment]
Here's a concrete idea: add a new UI setting (disabled by default) which enables auto-filling of saved info in private windows.
![Screenshot from 2023-07-27 15-50-55](https://github.com/brave/brave-browser/assets/167821/274a0f19-5b8b-41ab-ab5e-2b7964f3a1cb)

This would make the build-in password manager (and the address auto-fill) work the same as third-party password manager extensions like 1Password. Extensions do not run in private windows by default and users must opt in explicitly:
![Screenshot from 2023-07-28 12-46-33](https://github.com/brave/brave-browser/assets/167821/ae553fe9-42ad-4be1-b5b9-d0fcb24eda49)

**Comment by bbondy** [comment]
> add a new UI setting (disabled by default) which enables auto-filling of saved info in private windows.

Why would we disable by default? I think it's expected for most users and it also matches what Firefox does, Chrome does, Opera does, and Safari does.

**Comment by fmarier** [comment]
There are arguments on both sides (default ON, default OFF). The main argument for default ON is that other browsers are doing it this way, therefore it will presumably be more familiar to users who come from these browsers.

However, some other users (e.g. the one who reached out and initiated this investigation/discussion) are surprised to see their auto-fill show up when they open a private window. There are lots of different use cases for using private windows (and yes, some of these people should probably be using guest windows instead but they don't know about them), but this user was opening a private window to show something to someone else while keeping their regular browser profile hidden. They were not expecting to see their auto-fill data show up in that context.

**Comment by fmarier** [comment]
I think the most important part is to make it obvious that we auto-fill in private windows based on existing data from normal windows by having a setting controlling it.

Whether or not we change the default can be postponed to a later change (if we decide to do it).

**Comment by fmarier** [comment]
Current plan is to add the new setting from https://github.com/brave/brave-browser/issues/9795#issuecomment-1656235604, but leave it **enabled by default** for all users.

This means that there will be no change to the behavior until a user toggles this setting OFF.

**Comment by spylogsster** [comment]
Removed Android label here and created an issue for Android side https://github.com/brave/brave-browser/issues/32096 cc @deeppandya @rebron

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.92 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | cf6e2f14e9e5a022c570aaa24e8c7ff7e4a541e5
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Credit Cards (`Payment Methods`) - `PENDING`
<details>

### Steps:
1. installed `1.59.92`
2. launched Brave
3. opened `brave://settings`
4. clicked on `Autofill and passwords`
5. clicked on `Payment methods`
6. 

credit cards:

Fill and save info on regular profile https://fill.dev/form/credit-card-simple
Disable the option in the settings
Open it in Private profile and check.
Saved info should not be substituted if the option is off.

</details>

### Usernames (`Logins`) - `PENDING`
<details>

</details>

### Passwords (`Password Manager`) - `PENDING`
<details>

Passwords:

Login to Google and remember password in regular profile
Open Google in Private Window
It should not suggest saved password for login form in Private Window if the option disabled in the settings

</details>
