### ISSUE TITLE
Add to Brave whitelist: Just Read

### ISSUE THREAD

**Issue by ZachSaucier** [brave/brave-browser#9797]
Just Read is a web extension that helps users read web articles in a customize-able and distraction-free format. I maintain it and don't collect data from users. 

It has [a website](https://justread.link/) and the free version is [publicly viewable on GitHub](https://github.com/ZachSaucier/Just-Read). I'd like to submit it to the Brave extension whitelist because a user of it suggested that I do so.

Let me know if you need any additional information. 
Thanks for making a great browser!

**Comment by iefremov** [comment]
We don't maintain the whitelist anymore
