### ISSUE TITLE
Brave issues: AN UNEXPECTED ERROR HAS OCCURRED

### ISSUE THREAD

**Issue by adriatic** [brave/brave-browser#9798]
## Description 

Brave issues AN UNEXPECTED ERROR HAS OCCURRED opening the site `https://www.collusion.com/`

## Steps to Reproduce

Point the Brave browser to `https://www.collusion.com/`

## Actual result:

```
commons.02893d8dd383fa2fe9e9.js:47 ReferenceError: s is not defined
    at e.value (commons.02893d8dd383fa2fe9e9.js:1)
    at t.value (commons.02893d8dd383fa2fe9e9.js:1)
    at t.value (commons.02893d8dd383fa2fe9e9.js:1)
    at ha (commons.02893d8dd383fa2fe9e9.js:47)
    at pa (commons.02893d8dd383fa2fe9e9.js:47)
    at fa (commons.02893d8dd383fa2fe9e9.js:47)
    at Ii (commons.02893d8dd383fa2fe9e9.js:47)
    at ba (commons.02893d8dd383fa2fe9e9.js:47)
    at wa (commons.02893d8dd383fa2fe9e9.js:47)
    at Ea.render (commons.02893d8dd383fa2fe9e9.js:47)
ui @ commons.02893d8dd383fa2fe9e9.js:47
```

## Reproduces how often: 

Happens every time

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes, - Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? YES
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
@adriandgr  Thanks for the report, have rolled out a fix. give it 24-48hrs

https://github.com/easylist/easylist/commit/bab6bbbdde128c763c09c6bc012e59c6182c3ce4

**Comment by adriatic** [comment]
Thanks, I did not expect such quick response for a bug that goes away when disabling Brave Shields 😄

**Comment by ryanbr** [comment]
Everything should be working now @adriandgr . Safe to enable Brave Shields. Any issues let us know :)
