### ISSUE TITLE
Fix Brave Ads 30-day history segment does not fit

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9799]
## Description 
The 7-Day Ads History popup appears to have overflow issues, possibly caused in part by lengthy, non-wrapping category names.

## Steps to Reproduce
Open 7-Day Ads History on Windows

## Actual result:
It is likely you will see a horizontal scrollbar.

## Expected result:
Only a vertical scrollbar should be necessary.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.8.96

## Miscellaneous Information:
![image](https://user-images.githubusercontent.com/815158/82107955-08f85a80-96f1-11ea-8b93-6fcc69ae37b8.png)

**Comment by tmancey** [comment]
Closing as resolved by another issue
