### ISSUE TITLE
[Webcompat] Cookie issues with americanexpress.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9803]
## Description 
When using `americanexpress.com`, will complain about cookies being blocked.

## Steps to Reproduce

   1. Website complaints cookie issues american express website.
   2.  Related to chat and dashboard not showing.
   3. 

## Actual result:

<img width="402" alt="screen_shot_2020-05-10_at_6 48 44_pm" src="https://user-images.githubusercontent.com/1659004/82118066-c904a680-97c8-11ea-9cab-f9453d51ef60.png">

## Expected result:
Allow user to use american express without issue/complaints.

## Reproduces how often: 

Don't have a login, going by user feedback/troubleshooting.

## Brave version (brave://version info)
`Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
**Cookies being blocked:** 

<img width="434" alt="screen_shot_2020-05-10_at_7 00 56_pm" src="https://user-images.githubusercontent.com/1659004/82118128-3b758680-97c9-11ea-9303-0c793f74501e.png">

Going by the screenshot,`americanexpress.com` is using another domain `aexp-static.com` which should help fixing this.

**Comment by AndriusA** [comment]
Not seeing a complaint about cookies, but the dashboard does not fully load:

![image](https://user-images.githubusercontent.com/145422/82118742-210fbe80-9771-11ea-9170-f3e5851e73c4.png)

Requests blocked:
![image](https://user-images.githubusercontent.com/145422/82118706-e86fe500-9770-11ea-8ecc-d7077146c61d.png)

Switching fingerprinting setting to "All fingerprinting attempts allowed" works for that session, but closing tab and reopening same issue. Exactly the same with "All cookies allowed".

**Comment by ryanbr** [comment]
what domain shows in fingerprinting/shields?

**Comment by AndriusA** [comment]
<img width="365" alt="Screenshot 2020-05-16 at 13 39 15" src="https://user-images.githubusercontent.com/145422/82119974-a481dd80-977a-11ea-9d64-68dd30ac141d.png">

**Comment by yrliou** [comment]
@ryanbr I'm still seeing cookies blocked and the unsupported browser message when using Amex Chat on nightly (Version 1.11.7).
<img width="439" alt="Screen Shot 2020-05-18 at 5 40 02 PM" src="https://user-images.githubusercontent.com/4730197/82272234-d2a81e80-992e-11ea-95d6-638ac57e3f93.png">

**Comment by ryanbr** [comment]
@yrliou  can you screenshot the details from drop down triangles next to the 2 `aexp-static.com` domains?

**Comment by yrliou** [comment]
<img width="419" alt="Screen Shot 2020-05-18 at 7 04 15 PM" src="https://user-images.githubusercontent.com/4730197/82278067-3259f600-993e-11ea-9fd9-39d70fab2e1a.png">
<img width="413" alt="Screen Shot 2020-05-18 at 7 04 21 PM" src="https://user-images.githubusercontent.com/4730197/82278081-384fd700-993e-11ea-8a35-f3b24363e7de.png">
<img width="420" alt="Screen Shot 2020-05-18 at 7 04 26 PM" src="https://user-images.githubusercontent.com/4730197/82278089-3ab23100-993e-11ea-9b85-4e270d9a1f00.png">

**Comment by ryanbr** [comment]
@yrliou  also noted no local storage/session being blocked.  Seems safe to assume blocking `aexp-static.com` cookies on `americanexpress.com` is causing issues.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* With default shields, confirmed chat issue using `1.10.97` (however my dashboard still displayed fine):
<img width="452" alt="Screen Shot 2020-06-24 at 9 25 23 AM" src="https://user-images.githubusercontent.com/28145373/85566188-d00ba980-b5fd-11ea-8b22-49eb773690eb.png">

* Kept default shields and upgraded to 1.11.x and confirmed no longer seeing error message on chat window. Confirmed dashboard still displays as expected:
<img width="450" alt="Screen Shot 2020-06-24 at 9 27 18 AM" src="https://user-images.githubusercontent.com/28145373/85566549-25e05180-b5fe-11ea-9192-d0f265631c36.png">

* Clean install of 1.11.x with default shields, confirmed dashboard displays as expected and chat window does not display error.
