### ISSUE TITLE
[Android] [Feature Request] Splash Screen for PWA

### ISSUE THREAD

**Issue by aliglelo** [brave/brave-browser#9804]
# Please add a PWA splash Screen

## Description 
As a migrant from chrome i want to have a complete support for PWA.In chrome a beautiful splash screen is showed during loading of PWA.But i am missing that in Brave browser for Android.

## Steps to reproduce 

   1. Open brave and enter any PWA compatible website address.
   2. Add PWA to home screen.
   3. Launch PWA from home screen.

## Actual result 
There is a normal looking tab opened which then changes into a PWA.

## Expected result
There should be a chrome like splash screen.

## Issue reproduces how often 
Every time.

## Issue happens on 
   Yes - Current Play Store version?
   Don't Know - Beta build?

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 9.0
   
## Brave version
Latest verion on play store ``1.8.93``

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? 
NO

- Does the issue resolve itself when disabling Brave Rewards?
NO

- Is the issue reproducible on the latest version of Chrome? 
NO

**Comment by Poopooracoocoo** [comment]
aren't chrome's webapks proprietary?

**Comment by aliglelo** [comment]
Yes after researching by my ownself found it to be propriety as `WebAPK MINTING` requires system level access.
So going to close this request.
