### ISSUE TITLE
Brave Custom Theme Install results in visibility issues

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#9808]
## Description 
Installing a theme from the theme store does not work when switching from light to dark mode or from light to private or private with Tor. At this moment it seems not possible to use any other  theme than the default one.

## Steps to Reproduce
   1. Install theme from theme store
   2. Switch light to dark mode or light to private mode
   3. Observe weird color combinations or icons becoming invisible

## Actual result:
![Screen Shot 2020-05-16 at 8 25 59 PM](https://user-images.githubusercontent.com/56597375/82127487-3c4fed80-97b4-11ea-9469-236efc0fdaa5.png)
![Screen Shot 2020-05-16 at 8 26 24 PM](https://user-images.githubusercontent.com/56597375/82127488-3eb24780-97b4-11ea-9f2f-bff57d5afa42.png)
![Screen Shot 2020-05-16 at 8 26 58 PM](https://user-images.githubusercontent.com/56597375/82127491-407c0b00-97b4-11ea-8191-f4d8ef5e342d.png)

## Expected result:
User should be able to install a custom theme and indicate if it should replace the default light theme or the default dark theme - e.g. when set to automatic - the light to dark switch by macOS would switch the custom light to the custom dark theme and back again or custom light to default dark theme etc. Assuming the private browsing or private browsing with Tor is locked for theme changing, which would reduce theming complexity.

## Reproduces how often: 
No themes found that work without issues

## Brave version (brave://version info)
Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:
- Can you reproduce this issue with the current release?    Yes
- Can you reproduce this issue with the beta channel?        Yes
- Can you reproduce this issue with the dev channel?          Yes
- Can you reproduce this issue with the nightly channel?     Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Thanks for looking into, best regards.

**Comment by bsclifton** [comment]
cc: @petemill @simonhong 
I believe some of our colors are effectively hard-coded, so they would override what is used by a theme

**Comment by simonhong** [comment]
@bsclifton Yes, right. I think we should consider custom theme when we choose our colors.

**Comment by bsclifton** [comment]
@simonhong can you share steps for installing a custom theme that you had used?

**Comment by simonhong** [comment]
@bsclifton You can install any themes from chrome webstore - https://chrome.google.com/webstore/category/themes

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 Catalina x64` using the following build:

```
Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | macOS Version 10.15.5 (Build 19F101)
```

Used https://chrome.google.com/webstore/detail/pro-grey/enhpebdanojkmhbbneclbkmpleemilaj as the theme for verification as per https://github.com/brave/brave-browser/issues/9808#issue-619533524.

| `1.9.80 CR: 81.0.4044.138` | `1.10.86 Chromium: 83.0.4103.61` |
| --- | --- |
| <img width="1231" alt="Screen Shot 2020-06-09 at 3 54 58 PM" src="https://user-images.githubusercontent.com/2602313/84194489-16440300-aa6b-11ea-861b-5065a1e373e7.png"> | <img width="1234" alt="Screen Shot 2020-06-09 at 3 58 46 PM" src="https://user-images.githubusercontent.com/2602313/84194520-21972e80-aa6b-11ea-9af2-f80b9254adcf.png"> |
| <img width="1235" alt="Screen Shot 2020-06-09 at 3 55 24 PM" src="https://user-images.githubusercontent.com/2602313/84194610-455a7480-aa6b-11ea-82a5-d57ad45c1ac4.png"> | <img width="1224" alt="Screen Shot 2020-06-09 at 3 58 55 PM" src="https://user-images.githubusercontent.com/2602313/84194641-54d9bd80-aa6b-11ea-9f82-446f41c6baee.png"> |
| <img width="1230" alt="Screen Shot 2020-06-09 at 3 55 34 PM" src="https://user-images.githubusercontent.com/2602313/84194689-691dba80-aa6b-11ea-90d5-09d8b3a8aa6e.png"> | <img width="1228" alt="Screen Shot 2020-06-09 at 3 59 08 PM" src="https://user-images.githubusercontent.com/2602313/84194707-7044c880-aa6b-11ea-864d-48c66398e71a.png"> |
