### ISSUE TITLE
[Desktop] Brave Suggested sites don't display when Autocomplete of search is enabled

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#9811]
## Description 
Brave Suggested sites don't display when Autocomplete of search is enabled

## Steps to Reproduce

Turn on `Autocomplete searches and URLs` in brave://settings/privacy and notice that `Brave Suggested Sites` do not display, only the search autocomplete results.

## Actual result:
No Brave Suggested Sites.

## Expected result:
Brave Suggested sites per Test plan. https://github.com/brave/brave-browser/issues/9572#issue-610801948

## Reproduces how often: 
Easily.

## Brave version (brave://version info)

Brave | 1.10.60 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.836)

## Version/Channel Information:

- Can you reproduce this issue with the current release?n/a
- Can you reproduce this issue with the beta channel? Yes 1.10.x
- Can you reproduce this issue with the dev channel? 1.10.x
- Can you reproduce this issue with the nightly channel? Yes 1.11.x

**Comment by rebron** [comment]
cc: @bbondy We prioritized as p4. Please change if you feel differently.

**Comment by bbondy** [comment]
I think this is the correct behavior so closing
