### ISSUE TITLE
Brave Nightly - Make default browser should be locked

### ISSUE THREAD

**Issue by phoogm** [brave/brave-browser#9812]
Brave Nightly version offers to be made a default browser, however most other browsers lock Nightly or Canary versions to be set as default to protect the user from being impacted by known and especially unknown issues and impacts from usage.

## Description 
Brave Nightly has the setting for Make default browser enabled by default.

## Steps to Reproduce
   1. Start Brave Nightly.
   2. Navigate to Settings / Get Started.
   3. Observe the button Make default is enabled.

## Actual result:
![Screen Shot 2020-05-17 at 12 55 22 PM](https://user-images.githubusercontent.com/56597375/82142594-b5475780-983d-11ea-8aed-5ebfc822b284.png)

## Expected result:
The button Make default should be disabled for Brave Nightly.

## Reproduces how often: 
Seems to be the current default.

## Brave version (brave://version info)
Brave | 1.11.5 Chromium: 81.0.4044.138 (Official Build) nightly (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the dev channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
Thanks for considering. Best regards.

**Comment by bsclifton** [comment]
cc: @rebron 

Suggestion would be to just hide the `Default browser` area under `Get started`

**Comment by rebron** [comment]
@phoogm Thanks for the suggestion. We're going to mark this as wontfix. Nightly users are fairly savvy and will know to ignore this setting and some will want to use Brave Nightly as default. If we did attempt to fix this, we'd have an issue filed to revert the change pretty quickly.
