### ISSUE TITLE
Can't run godot apps when shield is up

### ISSUE THREAD

**Issue by tavurth** [brave/brave-browser#9813]
Hi! I'm enjoying Brave browser!

Currently when you do not allow access to microphone and video devices, you return null, which is apparently not the standard (should be an empty string?)

This breaks [Godot engine](http://godotengine.org/) web games.

**Godot version:**
<img width="614" alt="Screenshot 2020-05-16 at 23 40 02" src="https://user-images.githubusercontent.com/100964/82126785-93fb5280-97ce-11ea-944c-5ef71ec00d82.png">

**OS/device including version:**
<img width="330" alt="Screenshot 2020-05-16 at 23 40 18" src="https://user-images.githubusercontent.com/100964/82126788-9b226080-97ce-11ea-81f1-7df7a78bc92c.png">

**Issue description:**
HTML5 Web player fails in [Brave Browser](http://brave.com/) (Chromium), but works in latest chrome.

Brave is a Chromium based browser, I've been using it for a while. On every site with a Godot game I get the following error:
<img width="1066" alt="Screenshot 2020-05-16 at 23 39 19" src="https://user-images.githubusercontent.com/100964/82126808-c73de180-97ce-11ea-9eef-b10f265f865a.png">

<img width="1069" alt="Screenshot 2020-05-16 at 23 39 38" src="https://user-images.githubusercontent.com/100964/82126812-cc9b2c00-97ce-11ea-9540-a7e19480c18d.png">

Whereas on the latest Chrome the same game works correctly:

<img width="1071" alt="Screenshot 2020-05-16 at 23 41 52" src="https://user-images.githubusercontent.com/100964/82126815-d58bfd80-97ce-11ea-8239-6a1fae705e79.png">

**Steps to reproduce:**
1. Install Brave browser
2. Open [this game](https://tavurth.itch.io/godot-html5-test)

**Minimal reproduction Example:**
https://tavurth.itch.io/godot-html5-test

**Minimal reproduction project:**
https://github.com/tavurth/godot-html5-brave

**Additional notes**
This bug only occurs when Brave's tracker protection is enabled, and it cites two errors:
<img width="406" alt="Screenshot 2020-05-16 at 23 48 21" src="https://user-images.githubusercontent.com/100964/82126945-cf4a5100-97cf-11ea-9ca1-14d93e4da67c.png">

## Reproduces how often: 
Every time

## Brave version (brave://version info)
<details>
Brave	1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	macOS Version 10.15.3 (Build 19D76)
JavaScript	V8 8.1.307.32
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_57358 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,DnsOverHttps,SimplifyHttpsIndicator,MixedContentSiteSetting,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning --disable-features=AutofillServerCommunication,NotificationTriggers,TextFragmentAnchor,VideoPlaybackQuality,AllowPopupsDuringPageUnload,SmsReceiver,AudioServiceOutOfProcess,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/will/Library/Application Support/BraveSoftware/Brave-Browser/Default
</details>

**Comment by tavurth** [comment]
Here's a link to [the original issue](https://github.com/godotengine/godot/issues/38788)

**Comment by rebron** [comment]
cc: @pes10k Can you take a look and give a priority when you get a chance?

**Comment by pes10k** [comment]
This version of brave is 2 version behind current stable.  Can you try again on stable?  I can't reproduce on nightly

**Comment by tavurth** [comment]
@pes10k I went to brave.com and downloaded the latest release from there. The following image is the result of loading [my small test game](https://tavurth.itch.io/godot-html5-test).

<img width="1440" alt="Screenshot 2020-06-27 at 00 22 03" src="https://user-images.githubusercontent.com/100964/85889995-3bc36180-b80c-11ea-9265-ae73e0cba96b.png">

* Brave version information
<details>

Brave | 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.15.3 (Build 19D76)
JavaScript | V8 8.3.110.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser -psn_0_1892814 --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,VideoPlaybackQuality,TabHoverCards,SmsReceiver,LookalikeUrlNavigationSuggestionsUI --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox --disable-sync
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/will/Library/Application Support/BraveSoftware/Brave-Browser/Default

</details>

**Comment by pes10k** [comment]
Thank you for checking @tavurth.  In nightly i get the below in the page:
<img width="1763" alt="Screen Shot 2020-06-26 at 11 58 59 AM" src="https://user-images.githubusercontent.com/76526/85891704-6ed20a80-b7a4-11ea-9717-bd2f20c3fe63.png">

And this in the console:

<img width="1738" alt="Screen Shot 2020-06-26 at 11 59 29 AM" src="https://user-images.githubusercontent.com/76526/85891747-890be880-b7a4-11ea-9dc1-5bc102d02d3e.png">

If that looks good, then a fix is already on its way to stable, and looks like our ongoing redesign of the fingerprinting protections solved (hurray!).  If something beyond the above should happen, please let me know and I will make sure this is handled correctly but the work in the queue.

Thank you again for the bug report!

**Comment by tavurth** [comment]
@pes10k great news! Thank you :)

Should we leave this open until it's on stable?

**Comment by pes10k** [comment]
@tavurth terrific, glad it works for you.  I'm going to close now, since the fix will automatically make its way through the system.  If you're very curious, you might also check the beta channel, since it has more of the farbling / new fingerprinting protections implemented than stable does, but less than nightly.  And so will make its way to stable sooner.

Thanks again for the bug report!
