### ISSUE TITLE
Delay when downloading a file

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#9817]
## Description 
I started noticing a weird delay on downloaded files (no matter what size). The delay is present on some files (some dont seem to be affected?), estimated around 5-6 seconds. When downloading a file, there is a weird "stop" when nothing seems to be happening. The file seems to be already downloaded but cannot be opened. Attached is screenshot of a small zip file that was instantly downloaded but it took additional 5-6 seconds for it to save on the disk.

## Steps to Reproduce

   1.  download a file
   2.  notice the delay when writing the file to the disk (not download time)

## Actual result:
![Screenshot_1](https://user-images.githubusercontent.com/36133540/82159388-041cdd80-988e-11ea-82ec-2dc5a79c8f80.png)

the orange ring stays there for a long time, clicking the file does nothing.

## Reproduces how often: 
always on some files but never on others. [(example of affected file)](https://yts.mx/torrent/download/150F398A1531B4019DBC332190C5D2138C269219)

## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.836)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Sutka998** [comment]
I have got the same issue, since I'm using brave. I've tried disabling the ad-block, extensions, writing to the SSD or the HDD drives, neither of them solved the problem.

**Comment by rebron** [comment]
@pilsnerbeer If you have Chrome installed, is the behavior the same?

**Comment by pilsnerbeer** [comment]
I dont have Chrome installed and I must say I havent been able to reproduce the issue for a while now on Brave either (hopefully it wont come back!).

**Comment by srirambv** [comment]
Closing the issue based on last comment. Can reopen if issue repro's again

**Comment by Ajoalmejo** [comment]
I have the same problem. With Chrome, this doesn't happen.

**Comment by wcsxfrm** [comment]
Same here. All downloads implies 6 seconds annoy delay.

Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)
Xubuntu 20.04.2 LTS
