### ISSUE TITLE
[Android] [hackerone] #876192 - Cookie stealing

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#9818]
https://hackerone.com/reports/876192

## Test Plan

Specified here: https://github.com/brave/brave-core/pull/5841

**Comment by srirambv** [comment]
- Verification passed on OnePlus 6T with Android 10 running 1.12.111 x64 build
- Verification passed on Samsung Tab A with Android 10 running 1.12.111 x64 build

**Comment by jumde** [comment]
Re-opening since this was reverted: https://github.com/brave/brave-core/pull/6530 - This change breaks PDF reader on android. Details here: https://bravesoftware.slack.com/archives/C0816QH3R/p1598646322107500

**Comment by srirambv** [comment]
@jumde  logged https://github.com/brave/brave-browser/issues/11520 as this issue was already part of 1.12.x milestone.
