### ISSUE TITLE
Graphical Artifacts 

### ISSUE THREAD

**Issue by tehnools** [brave/brave-browser#9819]
## Description 
Whenever I am on a page probably a react webpage it will produce this visual artefact

## Steps to Reproduce

   1. Brave version 1.8.96
   2. Mac Book pro 2019 i7
   3. Open Brave Browser
   4. Type page url and enter

## Actual result:
![image](https://user-images.githubusercontent.com/20850573/82166318-3705b680-990c-11ea-8f54-d651f8993d78.png)

## Expected result:
The page loads normally without graphical Artifacts

## Reproduces how often: 
Very Random only happened with this release.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@tehnools can you please try going to brave://settings/system and disabling `Use hardware acceleration when available`? I believe this will resolve the problem for you

**Comment by tehnools** [comment]
@bsclifton 

Thanks for the reply. I restarted the whole machine and it worked.
