### ISSUE TITLE
LocationBar colors don't change immediately between dark and light themes

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#982]
https://github.com/brave/brave-core/pull/407 introduces switching NativeTheme between dark and light when our theme service mode is changed between dark and light. However, this does not change immediately when the user changes between light and dark via preferences. The user must switch tabs before these colors are re-calculated.

Similarly for GetOmniboxColor which is also sync'ed to light and dark choice, though that re-paints when the LocationBar is hovered.

Both should observe the theme mode preference and change immediately.

cc @simonhong who also worked on theme service

**Comment by simonhong** [comment]
duplicated with https://github.com/brave/brave-browser/issues/974?

**Comment by LaurenWags** [comment]
Verification Pass with

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X
