### ISSUE TITLE
Windows Shares Deleted Browsing History

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9820]
## Test plan
See https://github.com/brave/brave-core/pull/14086

## Description 
Even after deleting all history from Brave, Windows may still show browsing history. This issue was shared with us by [a user on Community](https://community.brave.com/t/start-menu-most-visited-sites-from-private-window/127785?u=sampson).

## Steps to Reproduce
1. Load up your browser with history
2. Clear all history from the browser
3. Type 'Brave' into Windows' start menu
4. Note _Most Visited_ section of URLs

## Actual result:
![image](https://user-images.githubusercontent.com/815158/82176538-a643c200-989c-11ea-9e85-979890ca7b88.png)

## Expected result:
Windows does not show any history.

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.8.96

**Comment by Krisztina2020** [comment]
Appears so because the information is loaded into Windows Jump List.
If you delete the files containing "Brave" here :\Users\<user>\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations and CustomDestinations and restart the computer it will disappear.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.43.53 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)
```
1. install `1.43.53`
2. launch Brave 
3. visit few sites (`cnn.com`, `bbc.com`,`wsj.com`) to establish a history
4. open `brave://history` to view the history
5. closed `CNN` tabs to view recently closed tabs history
6. pin Brave to the `task bar`
7. right click the icon in system taskbar to open Jump List and confirm entries for `Most visited and Recently closed are displayed
8. close Brave and right click the pinned icon to confirm entries for `Most visited and Recently closed are displayed
9. re-launch Brave and visit `brave://settings/clearBrowserData`
10.  select `All Time` for Time Range, select all the items, and then click Clear data
11. verified entries for `Most visited` and Recently closed` entries are cleared from Jump List
    - Right click Brave icon in the task bar and `Most visited` and `Recently closed` are cleared 
    - close Brave and right click the pinned icon in the taskbar


Step 3|Step 4|step5|Step7|Step7|Step 9&10|Step 11
------|------|------|------|------|------|-----
<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181830053-b33a1e0d-83a2-419d-a465-262a887bead1.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181830541-845d0f34-d82c-4bb1-8e48-715617ae17c5.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181830713-998ab07f-e767-47f1-bff8-6d97ad3c5560.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181831534-14119b08-6ca4-40f3-8b08-f874dcbab6ea.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181831683-0d749ced-b114-4db4-abec-c74c8f357b56.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181831803-4adf4384-c325-4549-a600-86234ffa0d5f.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181831893-ff19661d-1ee4-4edc-adfe-6286f9aaffe4.png">|<image width="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/181832068-624b17db-3234-41db-906a-d692081ea4f6.png">
