### ISSUE TITLE
[P3A] Follow up of #8854 - Search performed in PT is also considered for Brave.Omnibox.SearchCount

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9826]
## Description 

[P3A] Follow up of #8854 - Search performed in PT is also considered for Brave.Omnibox.SearchCount

more info: https://github.com/brave/brave-browser/issues/8854#issuecomment-630329209

## Steps to Reproduce

   1. Clean profile 1.9.70
   2. Perform a search in URL bar 5 times (In normal window tabs)
   3. `Brave.Omnibox.SearchCount` response value is displayed as 1 (expected)
   4. Open a Private window tab and perform search 1 time
   5. Refresh local-state and verify `Brave.Omnibox.SearchCount` response value changed from `1` to `2`
   6. Open a Guest window and perform search 5 times (till step 6 we have performed a search for 11 times in Normal, PT and Guest window tabs)
  7. Refresh local-state file and verify `Brave.Omnibox.SearchCount` response value changed from `2` to `1`. 

## Actual result:

Search performed in PT is also considered for Brave.Omnibox.SearchCount

## Expected result:

Search performed in PT is NOT considered for Brave.Omnibox.SearchCount
## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.9.70 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @iefremov @rebron

**Comment by rebron** [comment]
Closing as wontfix per @mattmcalister. Brave.Omnibox.SearchCount should increment even in a Private Window.
