### ISSUE TITLE
[Android] PWA Crashes When Opening

### ISSUE THREAD

**Issue by clayb91** [brave/brave-browser#9827]
## Description 
PWAs crash when attempting to open on latest Android Beta.

## Steps to reproduce 

   1. Add PWA to home screen via menu
   2. Tap icon on home screen
   3. Application crash

## Actual result 
Application crash message

## Expected result
Open webpage (Instagram, Google News, etc )

## Issue reproduces how often 
Easily reproduced

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
1.9.69

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by tschach** [comment]
I am currently experiencing this on Brave 1.8.112, Chromium 81.0.4044.138 after updating from the Play Store. Has this been fixed?

**Comment by bbondy** [comment]
Are you seeing this with 1.9?

**Comment by clayb91** [comment]
This was fixed in 1.9.75
