### ISSUE TITLE
Optimize SaveActivityInfoList insert

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9829]
https://brave.sp.backtrace.io/p/brave/triage?filters=(_deleted%3D0%2C(callstack%2Ccontains%2Cledger))&sort=(ver%2Chead%2Cdesc)&aggregations=((ver%2Chead)%2C(guid%2Cunique)%2C(classifiers%2Chead))&fingerprint=7f718b9c452857bd88fb749ecc21bfbad63a02ff12c03cac17aaecd21310b6e6

We should just create object with publisher_key, percent and weight and not whole publisher insert. We should also batch insert it with batch query

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G3020)

* Verified test plan from https://github.com/brave/brave-core/pull/5594
* Confirmed all AC publisher types added to auto contribute and DB (regular sites, YouTube, Vimeo, GitHub). Twitch publishers are not added, known issue logged with https://github.com/brave/brave-browser/issues/6142

<img width="728" alt="Screen Shot 2020-06-16 at 8 55 08 AM" src="https://user-images.githubusercontent.com/28145373/84777062-1bdfa280-afaf-11ea-98f8-47e6fb0cc783.png">
<img width="768" alt="Screen Shot 2020-06-16 at 8 54 58 AM" src="https://user-images.githubusercontent.com/28145373/84777068-1e41fc80-afaf-11ea-989a-dc2bfde239bb.png">
