### ISSUE TITLE
Installing a theme adds a blob on new tab button 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#983]
## Description 

Installing a theme adds a blob on new tab button 

## Steps to Reproduce

   1. Upgrade to 0.55.1
   2. Open Chrome store and add a theme 
   3. See new tab button get a beauty spot on top

## Actual result:

![theme](https://user-images.githubusercontent.com/17010094/45157306-cb6acc80-b1ae-11e8-9126-0d9a7e72d6da.gif)

## Expected result:
Should not get a beauty spot when a theme is installed

## Reproduces how often: 

100%

## Brave version (about:brave info) 

Brave | 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Windows / Linux

### Reproducible on current release:

No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @LaurenWags @kjozwiak to verify on mac for same behaviour

**Comment by kjozwiak** [comment]
Talked to @srirambv about this earlier today. It seems to be happening on my Win 7 & Win 8 VM's that are using the default themes. The VM's that I created are basically using the same theme that was enabled when the OS was installed. I didn't change any settings/themes etc.. The VM's are updated, but are using all the default settings and not themes were installed/selected. Examples:

- **Windows 7:**

<img width="1065" alt="screen shot 2018-09-10 at 1 47 09 am" src="https://user-images.githubusercontent.com/2602313/45278545-9c4ca780-b49b-11e8-85ca-cff6fc7944c8.png">

<img width="900" alt="screen shot 2018-09-10 at 1 48 10 am" src="https://user-images.githubusercontent.com/2602313/45278547-a1115b80-b49b-11e8-96fd-c837cd49d037.png">

- **Windows 8:**

<img width="1083" alt="screen shot 2018-09-10 at 1 50 09 am" src="https://user-images.githubusercontent.com/2602313/45278614-ee8dc880-b49b-11e8-93fd-75990f4391cc.png">

<img width="860" alt="screen shot 2018-09-10 at 1 50 33 am" src="https://user-images.githubusercontent.com/2602313/45278618-f188b900-b49b-11e8-9393-0794a3dcf133.png">

**Comment by GeetaSarvadnya** [comment]
Verified the issue on Windows 10. Issue is working fine on Default theme as well as on  added new theme, now we are not able to see dot on + tab on version1.55.5
@kjozwiak @srirambv  Issue needs to be verified on Win 7 and Win 8 with default theme and new theme.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/45851390-f1f63f00-bd3a-11e8-98c8-d98d8fc037ad.png)

**Comment by kjozwiak** [comment]
Looks like it's also resolved on my VM's where I used to see the beauty mark while using the default themes of each OS as mentioned in https://github.com/brave/brave-browser/issues/983#issuecomment-419794928. Used the following build for verification:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}

Windows 10 x64 VM using default theme - **PASSED**

<img width="1440" alt="screen shot 2018-09-24 at 5 07 23 pm" src="https://user-images.githubusercontent.com/2602313/45979257-8bb03b80-c01c-11e8-81b4-cc2f834bcb65.png">

Windows 8.1 x64 VM using default theme - **PASSED**

<img width="1291" alt="screen shot 2018-09-24 at 5 10 51 pm" src="https://user-images.githubusercontent.com/2602313/45979441-1c871700-c01d-11e8-9f63-4ed153dd8f0d.png">

Windows 7 x64 VM using default theme - **PASSED**

<img width="1222" alt="screen shot 2018-09-24 at 5 15 53 pm" src="https://user-images.githubusercontent.com/2602313/45979606-8f908d80-c01d-11e8-88cf-355d7f85689a.png">
