### ISSUE TITLE
[Android] Fingerprinting 2.0: UX / Shields Integration

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9830]
## Description
by default we have cosmetic filtering that attempts to differentiate 1p and 3p ads, and only block the latter.

Some users would like to do the simpler, "apply all cosmetic filters, always" approach.  Basically, just do what uBO does.

This issue would be to modify the current cosmetic filtering to have an option to automatically inject all cosmetic filters, and not do party checks.  '

## Design

![android farbling](https://user-images.githubusercontent.com/2388823/82265095-1133de00-991b-11ea-8f5e-0dfaf8a8d913.png)

Figma for CSS, layout, sizing: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=16%3A16326

### Subtasks
- [x] Fingerprinting controls https://github.com/brave/brave-browser/issues/9194
- [x] Aggressive cosmetic filtering controls https://github.com/brave/brave-browser/issues/9831

**Comment by antonok-edm** [comment]
This was tracked in https://github.com/brave/brave-browser/issues/7487 and is now completed.
