### ISSUE TITLE
[Android] Add "Aggressive" ads/trackers blocking config option in Shields Panel

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9831]
## Description
by default we have cosmetic filtering that attempts to differentiate 1p and 3p ads, and only block the latter.

Some users would like to do the simpler, "apply all cosmetic filters, always" approach.  Basically, just do what uBO does.

This issue would be to modify the current cosmetic filtering to have an option to automatically inject all cosmetic filters, and not do party checks.  '

## Design

![android cosmetic filtering](https://user-images.githubusercontent.com/2388823/82265265-712a8480-991b-11ea-861d-6cf6423217b9.png)

Figma for CSS, layout, sizing: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=16%3A16034

### Miscellaneous
Related to https://github.com/brave/brave-browser/issues/8475

**Comment by antonok-edm** [comment]
@karenkliu just a caution that cosmetic filtering is not currently supported on Android. That extra option won't enable anything new until https://github.com/brave/brave-browser/issues/9955 is done.

**Comment by karenkliu** [comment]
@antonok-edm Thanks for the note! cc @deeppandya

**Comment by antonok-edm** [comment]
Thanks to @SergeyZhukovsky's great work on https://github.com/brave/brave-core/pull/6735, we now have cosmetic filtering on Android, so this issue is no longer blocked.

**Comment by daphnei-mee** [comment]
Will this issue be worked on going forwards?

**Comment by bsclifton** [comment]
As noted above, issue is no longer blocked. We just need to create the UI for this! 😄

**Comment by ryanbr** [comment]
Another test `https://www.google.com/amp/s/www.ndtv.com/amp`   Plenty of empty of space. Reported via https://community.brave.com/t/brave-ad-blocker/241947

**Comment by karenkliu** [comment]
@bsclifton I think this issue https://github.com/brave/brave-browser/issues/7487 is the most current one for Android<>desktop parity. @alexsafe is working getting the "aggressive" trackers&ads blocking in as part of this (Please correct me if I'm wrong?)

**Comment by tjm00** [comment]
As far as I can tell, this isn't actually working.
#16789

**Comment by antonok-edm** [comment]
@tjm00 we've followed up with more info in https://github.com/brave/brave-browser/issues/16789#issuecomment-879446705, but that's actually a Reddit-specific issue. We'll get that fixed at some point!

**Comment by ryanbr** [comment]
Opening https://www.money.it/?page=amp&id_article=112187 (From https://github.com/brave/brave-browser/issues/17019)   with Aggressive mode enabled, should be hiding empty amp adboxs.

**Comment by Esokrates** [comment]
@ryanbr So whats the progress here? Without proper cosmetic filtering I do not see a point to use a browser with built in adblocking since I can mostly achieve the same result via dns filtering and the default chrome browser. I tested brave and within my first tries I could find a couple of sites that displayed big placeholders like 

https://www.google.com/amp/s/m.timesofindia.com/gadgets-news/google-chrome-will-soon-allow-android-users-to-remove-the-discover-feed-from-new-tab-page/amp_articleshow/91770258.cms

This led to immediate frustration on my side since no chromium based browser seems to get this right on android (and kiwi with ublock origin is no option since it is simply outdated).

**Comment by antonok-edm** [comment]
Aggressive mode has been available on Android since https://github.com/brave/brave-core/pull/8790, so I'll close this issue. If there are any outstanding issues with the implementation on Android please feel free to open a new issue!
