### ISSUE TITLE
[Android] Claim notification is not closed even when claim itself is already received

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#9833]
## Description 
Claim notification is not closed even when claim itself is already received. Issues started after this change https://github.com/brave/brave-core/pull/5520

## Steps to reproduce 

   1. Click claim from panel
   2. Infinite spinner is running and notification is not closed
   3. 

## Actual result 
Infinite spinner is running and notification is not closed

## Expected result
Claim notification is closed, once claim is received

## Issue happens on 
   - Current Play Store version? no
   - Beta build? no

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version: 
   
## Brave version
1.10.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.10.92 on Samsung Galaxy Tab S5e (Android 9.0)

Verified test plan from the description. 
Verified Grant notification is no longer shown after claim was successful
Verified there is no infinite spinner after claiming a grant
