### ISSUE TITLE
Include BAT ad values as part of the catalog

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9835]
## Description 
Currently, the ad protocol will return the ad value upon being seen.  We could more reliably manage the display of estimated earnings with this.

**Comment by tmancey** [comment]
@jsecretan as we no longer reset ads state this should no be a problem, your thoughts please?

**Comment by tmancey** [comment]
Blocked until catalog endpoint is updated to support ad values

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.31.71 Chromium: 94.0.4606.71 (Official Build) beta (64-bit)
-- | --
Revision | 1d32b169326531e600d836bd395efc1b53d0f6ef-refs/branch-heads/4606@{#1256}
OS | Ubuntu 18.04 LTS


Verified values are part of catalog v8 on production
![image](https://user-images.githubusercontent.com/34715963/137029856-8972ba59-4c72-489f-a822-ddaab2cd7d85.png)

Verified values are parsed into database 
![image](https://user-images.githubusercontent.com/34715963/137030330-ce4f0fc0-f0ed-4d1a-a072-40cb708f2c5d.png)
