### ISSUE TITLE
Brave Together Widget

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#9836]
## Description 
Brave Together is a fast and secure way to connect with friends or colleagues through video conferencing built into the browser. See https://github.com/brave/brave-core/pull/5515

## Test Plan:

- [ ] Show/Hide Brave Together extension from the NTP customize panel. Ensure that widget is hiding/showing correctly.
- [ ] Hide Brave Together from the widget menu on widget upper right hand corner "..."
- [ ] Add multiple widgets on NTP, select between widgets to change active widget. Ensure that widget is properly displayed and others are activated when clicked.
- [ ] Click "Start video call" on Brave Together widget and ensure that the url https://together.brave.com/<name> launches a new call.
- [ ] Names are 43 unguessable characters which are generated for the user when clicking call button.

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as Brave Together is only going to be available on `master` (Nightly) for now and isn't being released in `1.11.x` so there's nothing QA can do here.

Once Brave Together starts moving through the trains and a release milestone is set, QA will go through the feature.

CCing @rebron @bsclifton.
