### ISSUE TITLE
Remove "Estimated" from bandwidth saved and time saved

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9838]
## Description 

Remove "Estimated" from Brave Stats on NTP.

## Steps to Reproduce

   1. Open a new tab page

## Actual result:

<img width="474" alt="Screen Shot 2020-05-19 at 11 33 58 AM" src="https://user-images.githubusercontent.com/2388823/82364810-a343f100-99c4-11ea-8272-fd50e818ac30.png">

## Expected result:
<img width="452" alt="Screen Shot 2020-05-19 at 11 34 21 AM" src="https://user-images.githubusercontent.com/2388823/82364842-b060e000-99c4-11ea-92df-032dfa570aa8.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the dev channel? no 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome?  n/a

**Comment by rebron** [comment]
@0xedward Can you grab this one too. Maybe as part of this pr https://github.com/brave/brave-core/pull/5630

**Comment by 0xedward** [comment]
@rebron Sure, looking into it now

**Comment by 0xedward** [comment]
While updating the text from "Estimated bandwidth saved" to "Bandwidth saved", I noticed the attribute name for that message is `IDS_BRAVE_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED`. Is that something we want to replace with `IDS_BRAVE_NEW_TAB_BANDWIDTH_SAVED` and update all current instances of `IDS_BRAVE_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED` to reflect that change?

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
![image](https://user-images.githubusercontent.com/38657976/84012775-b29bd600-a995-11ea-9ce5-83928f063480.png)
- Encountered https://github.com/brave/brave-browser/issues/9993

**Comment by rebron** [comment]
> While updating the text from "Estimated bandwidth saved" to "Bandwidth saved", I noticed the attribute name for that message is `IDS_BRAVE_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED`. Is that something we want to replace with `IDS_BRAVE_NEW_TAB_BANDWIDTH_SAVED` and update all current instances of `IDS_BRAVE_NEW_TAB_ESTIMATED_BANDWIDTH_SAVED` to reflect that change?

@0xedward No need to change above. That can stay as is. 

Thanks again for the fix.
