### ISSUE TITLE
[Android] Bottom toolbar setting reverted (possibly on update)

### ISSUE THREAD

**Issue by mbacchi** [brave/brave-browser#9843]
## Description 
I have "Enable bottom toolbar" checked, and when updating the last time it was reverted. I also noticed it has reverted today whether there was an update or not I'm not sure.

## Steps to reproduce 

   1. Turn "Enable bottom toolbar" on
   2. Wait for update (or maybe just wait a number of days not sure my version was updated during this latest reversion)
   3. Setting is reverted, toolbar is on top again

## Expected result
Toolbar should remain on bottom

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86): ?
   - Device (Phone, Tablet, Phablet): Pixel 2
   - Android version: 10 (QQ2A.200501.001.B3)
   
## Brave version
1.8.112 (81.0.4044.138)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
I also had the same issue with stable release.

**Comment by anthonypkeane** [comment]
<img width="980" alt="Screen Shot 2020-06-12 at 08 49 30" src="https://user-images.githubusercontent.com/7606853/84521321-abbcde00-ac89-11ea-8486-6268b3818862.png">

**Comment by LaurenWags** [comment]
I haven't reproduced this in testing. I do have Beta and Stable installed on my personal device from the GPS. When Beta updates this never happens, but when Stable updates this occurs for me also.

**Comment by srirambv** [comment]
I haven't seen the issue on Pixel 3XL on release. Bottom bar is always retained.

**Comment by SergeyZhukovsky** [comment]
I'm going to remove upgrade logic from tabs to brave-core based. For QA team to check that you will need to get a latest tabs apk install it, change settings that we migrate, background video playback for example or view sites on desktop mode always and make sure that on upgrade to brave-core based they are not retained.

**Comment by nickidw** [comment]
I'm glad some other people are having the same issue, I thought I was going mad!

**Comment by GeetaSarvadnya** [comment]
Verification passed on Samsung Galaxy J3 version 5.1.1 running `BraveModernarm.apk.1.10.95`
- Verified upgrading from 1.10.94 to 1.10.95 doesn't reset bottom toolbar state
- Verified upgrading from 1.9.80 to 1.10.95 doesn't reset bottom toolbar state

-------
Verification passed on Gionee version 5.1 running `BraveModernarm.apk.1.10.95`
- Verified upgrading from 1.10.94 to 1.10.95 doesn't reset bottom toolbar state
- Verified upgrading from 1.9.80 to 1.10.95 doesn't reset bottom toolbar state
