### ISSUE TITLE
Ad count and BAT mismatch

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#9846]
## Description 
`7-day ads history` show more ads than `Ad notifications received this month`
The rewards pending use `Ad notifications received this month` figure rather than `7-day ads history` count.

## Expected result:
In both cases, the count should be same.

## Reproduces how often: 
No steps to reproduce

## Brave version
1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
## Miscellaneous Information:
I was using adguard vpn intermittently. I don't know whether that is related.

**Comment by tmancey** [comment]
@specter78 Ads History shows 7 days of history, however as expected, the ad notifications received this month will only show ads received since the 5th of the month.
