### ISSUE TITLE
Add UN M49 area code for the Channel Islands to Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9849]
Add UN M49 area code for the Channel Islands to Brave Ads. The area code is 830. See `supported_regions.h`

**Comment by LaurenWags** [comment]
@tmancey is there a test plan QA can follow for this one?

**Comment by tmancey** [comment]
@LaurenWags Unfortunately this is not going to be easy for QA to test. I will mark as QA/No. Thanks

**Comment by LaurenWags** [comment]
sounds good, thanks @tmancey 😄

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` after discussion with @kjozwiak and @rebron
