### ISSUE TITLE
Brave not opening after closing a Brave Ad while closed

### ISSUE THREAD

**Issue by Sobudd** [brave/brave-browser#9851]
## Description 
If you click 'close' on a brave rewards windows 10 notification ad while the browser is closed, you can't open a new instance of the browser until you stop the process in task manager.

## Steps to Reproduce

   1. Wait for an ad to appear in a windows 10 notification
   2. Close the browser
   3. Close the ad notification
   4. Try to start the browser

## Actual result:
Browser does not start until you end the 'Brave browser' process in task manager

## Expected result:
Browser opens normally.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.8.96 (Has persisted for a while now)

## Version/Channel Information:
I only use the current version, but the bug has been present for a while.

**Comment by bsclifton** [comment]
cc: @tmancey

**Comment by tmancey** [comment]
@Sobudd Can you please let me know if you can reproduce on latest release build as I have tried the above steps and all is working as expected for me. Thanks in advance for your help

**Comment by Sobudd** [comment]
> @Sobudd Can you please let me know if you can reproduce on latest release build as I have tried the above steps and all is working as expected for me. Thanks in advance for your help

Hi @tmancey, I've just had a chance to check, and the bug seems to no longer be present. Sorry for the slow reply!

**Comment by tmancey** [comment]
@Sobudd Thank you, much appreciated
