### ISSUE TITLE
Firebase authentication doesn't work with Brave

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#9852]
## Description 
From: https://github.com/brave/brave-browser/issues/5869#issuecomment-631596024

## Steps to Reproduce

   1. Navigate to https://haynet.horse - Click Register

## Actual result:
This browser is not supported or 3rd party cookies and data may be disabled.

## Expected result:
Should register

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
Its a Storage issue. Also seen here: https://www.rep2recall.net/

 https://community.brave.com/t/firebase-auth-not-working-due-to-localstorage/134551

**Comment by pes10k** [comment]
closed with https://github.com/brave/brave-core/pull/5952

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.12.105 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Windows 10 OS Version 1903 (Build 18362.959)


```
- Verified the STR from the description
- Able to register https://haynet.horse/ with default shield settings
![image](https://user-images.githubusercontent.com/38657976/89029541-51b4cc80-d34c-11ea-8cd6-52545a7b5a43.png)

**Comment by chrisjenx** [comment]
Awesome, thank you ❤️
