### ISSUE TITLE
Universal Bypass

### ISSUE THREAD

**Issue by Alasayrux** [brave/brave-browser#9855]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
@Alasayrux do you have more information? As-is, there's not enough information here for us to answer a question, look into anything, etc

I'll close issue- but please re-open with more information if possible. Thanks!
