### ISSUE TITLE
Fav icon for youtube

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#986]
Youtube icons are currently not saving. More info here https://github.com/brave-intl/bat-native-ledger/issues/83

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta (64-bit)  
-- | -- 
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux
 
* Verified YT icon is shown for YT entries for both publishers and YT site

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.13 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Mac OS X

* Verified passed using test plan from https://github.com/brave/brave-core/pull/574
* Logged issue for double 'on Youtube' text
![screen shot 2018-10-13 at 4 12 14 pm](https://user-images.githubusercontent.com/28145373/46909572-e0035880-cf02-11e8-9475-0c16d790b6c2.png)
