### ISSUE TITLE
Disable ability for sites to portscan localhost

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#9860]
Some sites are [portscanning the local machine using websockets](https://nullsweep.com/why-is-this-website-port-scanning-me/) (also see this [detailed analysis](https://blog.nem.ec/2020/05/24/ebay-port-scanning/)).

While we shouldn't disable websockets entirely since it's used for legitimate use cases (see #2524 for an example), it may be possible to disable them on localhost.

This could be used to mount an attack on a user's insecure local services, or to fingerprint users based on the local daemons they have.

**Comment by fmarier** [comment]
List of affected domains: https://docs.google.com/spreadsheets/u/1/d/1Nu4lpyZ5PQUIpiLJBddXnr67t5-1y0u40dzyzSYj1gc/preview

(From https://github.com/disconnectme/disconnect-tracking-protection/issues/182#issue-627807817)

**Comment by fmarier** [comment]
@pes10k pointing out that Folding@home might actually uses this to connect the website with the local application.

If we wanted to allow legitimate use cases like these, we could add a user-visible permission.

**Comment by fmarier** [comment]
There is a new extension called [Behave](https://github.com/mindedsecurity/behave) which blocks these: https://www.ghacks.net/2020/07/05/behave-for-chrome-and-firefox-warns-you-of-port-scans-and-local-attacks/

**Comment by fmarier** [comment]
Ungoogled-chromium also has an [issue open](https://github.com/Eloston/ungoogled-chromium/issues/1058) and there is some [related upstream work](https://bugs.chromium.org/p/chromium/issues/detail?id=378566).

Bromite also has this patch: https://github.com/bromite/bromite/blob/master/build/patches/Block-gateway-attacks-via-websockets.patch

**Comment by fmarier** [comment]
@ryanbr Did we already stop all of these via rules in our adblock lists?

**Comment by pes10k** [comment]
Yep! https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt#L2

**Comment by fmarier** [comment]
A user has recently pointed out that our solution is incomplete: https://community.brave.com/t/restrict-interaction-with-local-network/319313/6?u=fmarier

In addition to various IP address tricks, which we could manually add to the list, anybody could create a CNAME on their own domain that points to `127.0.0.1`.  If we want to block all of these, we probably need a specific feature in the browser that looks at what a name eventually resolves to.

Also, having this as a separate feature may make it easier to enable people to toggle ON/OFF (https://github.com/brave/brave-browser/issues/15004).

**Comment by pes10k** [comment]
Just repeating conversation from slack here, but most of this will be solved when we introduce the ability to make exceptions to our eTLD+1 blocking exception policy, which we hope to land Q1 of 2022.

cc: @ShivanKaul @antonok-edm

**Comment by fmarier** [comment]
What's left to do with respect to finishing the work in aggressive mode is to add the missing aliases to the local machine to `brave-specific.txt`. I made a [test page](http://fmarier.com/unprotected/localhost-resources.html) and found the following missing entries:

- `0.0.0.0`
- `[::]`
- `[::ffff:0.0.0.0]`
- `[::ffff:7f00:1]`

**Comment by fmarier** [comment]
[@pes10k 's PR](https://github.com/brave/adblock-lists/pull/744) has taken care of all of the remaining non-DNS-based test cases on http://fmarier.com/unprotected/localhost-resources.html.

**Comment by pes10k** [comment]
Terrific, thanks @fmarier ! I'm going to reclose this issue, since the new localhost aliases have been addresses above, and the CNAME issues will be addressed by https://github.com/brave/brave-browser/issues/20426
