### ISSUE TITLE
about:blank "your connection to this site is not secure"

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-browser#9861]
## Description 
security warning on about:blank

## Steps to Reproduce

   1. go to about:blank
   2. click on a warning

## Actual result:
![image](https://user-images.githubusercontent.com/19390797/82500070-0e8be100-9af3-11ea-887d-281c0691205d.png)

## Expected result:
![image](https://user-images.githubusercontent.com/19390797/82500096-18addf80-9af3-11ea-9412-7daff1a3ef28.png)
![image](https://user-images.githubusercontent.com/19390797/82500125-24010b00-9af3-11ea-8764-93c48a3825fd.png)

## Reproduces how often: 
100%

## Brave version (brave://version info)
Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? ✔
- Can you reproduce this issue with the beta channel? ❔
- Can you reproduce this issue with the dev channel? ❔
- Can you reproduce this issue with the nightly channel? ❔

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? ❌
- Does the issue resolve itself when disabling Brave Rewards? ❌
- Is the issue reproducible on the latest version of Chrome? ❔

**Comment by edwardqiu** [comment]
I was able to reproduce this issue on Chrome 83.0.4103.61 (latest version of Chrome for Ubuntu) and found the [same issue posted on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=882501).

![image](https://user-images.githubusercontent.com/14011954/82642803-5712cf80-9bc3-11ea-8afe-30a05b151036.png)

Is this something the Brave team wants to work on or would it be better to wait for the Chromium team to fix the issue then pull those changes downstream?

**Comment by bsclifton** [comment]
@edwardqiu good find! I think we'd wait for Upstream Chromium to have a fix. Will mark appropriately

**Comment by Madis0** [comment]
This is probably why it's done this way upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1065418
