### ISSUE TITLE
Pull P2P referral signup from Brave Rewards

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#9862]
Please comment out code for P2P referrals from Brave Rewards settings.
No support on Release and eventually remove support from Developer and Release.

cc @NejcZdovc @zenparsing 

cc @LaurenWags @davidtemkin

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.10.79 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5609
* Encountered https://github.com/brave/brave-browser/issues/9553 for TAP promo card only, page refresh fixes that.
<img width="1182" alt="Screen Shot 2020-06-01 at 1 49 26 PM" src="https://user-images.githubusercontent.com/28145373/83438282-27f42d80-a40f-11ea-996f-8982c5f7a01e.png">
