### ISSUE TITLE
[Android] Update existing onboarding

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#9865]
## Description 
Update onboarding based on below spec.
https://user-images.githubusercontent.com/2388823/81731192-72ebd800-9443-11ea-8b70-6d2be38823f8.png

https://user-images.githubusercontent.com/2388823/81741032-bef24900-9452-11ea-892c-4f0131f69342.png

https://user-images.githubusercontent.com/2388823/81741066-cdd8fb80-9452-11ea-8a80-265b4f0810d9.png

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.12.112 x64 build

### Clean Install

<ul>
<li> Verified clean install launch doesn't show any onboarding flow</li>
<li> Verified clicking on URL bar brings up SE onboarding flow</li>
<li> Verified BR panel shows "?" and clicking on it brings up reards onboarding flow<br/>
   <img width=300 src=https://user-images.githubusercontent.com/17010094/90005488-31abd400-dc8f-11ea-8cdf-80cd2db03af6.png></li>
<li> Verified visiting a site and blocking ads/trackers shows Shields onboarding flow</li>
</ul>

**Rewards on - Ads On**

Verified on a clean install and reward enabled opening an NTP with SI brings up bottom banner | Verified clicking anywhere on the banner brings up rewards info modal
-- | --
   <img width=300 src=https://user-images.githubusercontent.com/17010094/90005337-f7423700-dc8e-11ea-9c6b-819e4e940045.png> | <img width=300 src= https://user-images.githubusercontent.com/17010094/90005409-12ad4200-dc8f-11ea-818e-503b0b0adc41.png>
</ul>

**Rewards on - Ads Off**

Verified on a clean install and reward enabled but ads turned off, opening an NTP with SI brings up bottom banner | Verified clicking anywhere on the banner brings up rewards info modal
-- | --
   <img width=300 src=https://user-images.githubusercontent.com/17010094/90009210-8eaa8880-dc95-11ea-96bc-1a2ed2004a3b.png> |   <img width=300 src=https://user-images.githubusercontent.com/17010094/90009243-a255ef00-dc95-11ea-8c97-1f77af07d05e.png>


**Rewards Off**
- Verified no banners are shown when rewards is off. This was done as part of #8360 

### Upgrade Install
**Upgrade Install with Rewards off**
- Verified upgrading from 1.11.105 to 1.12.112 shows `?` on Rewards panel in URL
- Verified clicking BR button shows onboarding


**Upgrade Install with Rewards On but Ads off**
- Logged  #11199

-----------------
Verification passed on Samsung Tab A with Android 10 running 1.12.112 x64 build

### Clean Install

<ul>
<li> Verified clean install launch doesn't show any onboarding flow</li>
<li> Verified clicking on URL bar brings up SE onboarding flow</li>
<li> Verified BR panel shows "?" and clicking on it brings up reards onboarding flow<br/>
   <img width=500 src=https://user-images.githubusercontent.com/17010094/90010383-a97dfc80-dc97-11ea-82b3-4b4a580211a2.png></li>
<li> Verified visiting a site and blocking ads/trackers shows Shields onboarding flow</li>
</ul>

**Rewards on - Ads On**

Verified on a clean install and reward enabled opening an NTP with SI brings up bottom banner | Verified clicking anywhere on the banner brings up rewards info modal
-- | --
![image](https://user-images.githubusercontent.com/17010094/90010411-b4389180-dc97-11ea-9cd6-1788312f37f7.png) |![image](https://user-images.githubusercontent.com/17010094/90010418-b864af00-dc97-11ea-8946-f2322f2d39bc.png)
 

**Rewards on - Ads Off**

Verified on a clean install and reward enabled but ads turned off, opening an NTP with SI brings up bottom banner | Verified clicking anywhere on the banner brings up rewards info modal
-- | --
![image](https://user-images.githubusercontent.com/17010094/90010442-c286ad80-dc97-11ea-9327-531af7b3975e.png) | ![image](https://user-images.githubusercontent.com/17010094/90010454-c74b6180-dc97-11ea-945c-6c6d24ac1b4c.png)

**Rewards Off**
- Verified no banners are shown when rewards is off. This was done as part of #8360 

### Upgrade Install
**Upgrade Install with Rewards off**
- Verified upgrading from 1.11.105 to 1.12.112 shows `?` on Rewards panel in URL
- Verified clicking BR button shows onboarding


**Upgrade Install with Rewards On but Ads off**
- Logged  #11199

**Tablet specific issues**
- SE onboarding isn't smooth - #11201
- Rewards panel retains the red dot after onboarding - #11202
