### ISSUE TITLE
[Android] Chrome logo appears when flipping open tabs

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#9867]
## Description 
When having a couple of open tabs and you swipe vertically repeatedly the open tabs flip and the Google Chrome logo is displayed. This started to happen after Android version was rebased on brave-core. Previous to this update it used to display the Brave logo.

## Steps to reproduce 

   1. Have at least 2 tabs open.
   2. Tap on the tabs button on the bottom right of the screen (the one that displays the number of open tabs)
   3. Swipe vertically from bottom to top with your finger repeatedly for 5 or 6 times.

## Actual result 
Tabs flip vertically and Chrome logo is shown while flipping.
![May-21-2020 10-49-02](https://user-images.githubusercontent.com/6596039/82538126-ea142100-9b53-11ea-9344-38d3d4b50068.gif)

## Expected result
While tabs flip the Brave logo should be displayed instead of Chrome's as used to be the case before the rebase with the brave-core.

## Issue reproduces how often 
Always

## Issue happens on 
   - Current Play Store version

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone Motorola One (XT1941-4)
   - Android version: 10
   
## Brave version
Brave 1.8.112

**Comment by lOscarl** [comment]
Hello, I'm new in the Open Source world, can I take this issue?

**Comment by srirambv** [comment]
@lOscarl that would be great. You can please follow the guidelines mentioned [here](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md#pull-requests)

**Comment by kjozwiak** [comment]
Getting several +1 from the community via the following thread:

* https://www.reddit.com/r/brave_browser/comments/hylrh3/just_discovered_an_easter_egg

CCing @SergeyZhukovsky @aekeus

**Comment by srirambv** [comment]
+1 from @pragyanone via #11507

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.24.76, Chromium 90.0.4430.85` on Android 9, Pixel XL, arm64.

Steps:
1. opened a few tabs
2. opened `Settings` > `Appearance` > deselected `Enable Tab Groups`
3. tapped on the tab switcher icon
4. swiped up a few times on one of the displayed tabs, until the tab card rotated

Confirmed there was no Google Chrome logo on the card


https://user-images.githubusercontent.com/387249/116632940-1cee9980-a90d-11eb-8fe5-c5b4e24a43c0.mp4
