### ISSUE TITLE
Move data from ledger_state into preferences

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9869]
We should move data from ledger_state file into preferences. We should move following data:
- [x] `walletInfo->paymentId` (`wallet.payment_id`)
- [x] `walletInfo->keyInfoSeed` (`wallet.seed`)
- [x] `walletInfo->addressCARD_ID` (`wallet.anonymous_card_id`)
- [x] `bootStamp` (`creation_stamp`)
- [x] `reconcileStamp` (`ac.next_reconcile_stamp`)
- [x] `fee_amount` (`ac.amount`)
- [x] `user_changed_fee` (do not persist, just use if for migrating `ac.amount`)
- [x] `rewards_enabled` (`enabled`)
- [x] `auto_contribute` (`ac.enabled`)
- [x] `inline_tips` (`tips.inline_tips.*`, we would have each entry per media type)

All business logic for setting this values should be done in shared lib. Example that needs to be fixed is `RewardsServiceImpl::OnWalletInitialized`

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.11.73 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | Windows 10 OS Version 1903 (Build 18362.900)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5647

**Test plan 1:**
- Verified that the values which are set in AC advanced settings are retained after the browser restart
- Verified that the `brave://rewards-internals/` page displays the correct wallet info
- Verified that the AC, one-time tip, recurring tip, and other parameters displayed correctly in DB
- Logged https://github.com/brave/brave-browser/issues/10438 for upgraded profile scenarios

**Test plan 2:**
- Verified that USD conversion values are displayed correctly in an upgraded profile (**Note**: Need to reload the page)
added comments in the issue https://github.com/brave/brave-browser/issues/10438#issuecomment-648738253

**Test plan 3:** - Working as expected
- Verified that default values 1, 10, 100 are displayed correctly for unverified pubs  in Tipping banner
![image](https://user-images.githubusercontent.com/38657976/85542218-7a9fbe80-b636-11ea-8ace-d3f84fd5d55b.png)
