### ISSUE TITLE
[Android] Claim continuously spins on claim

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9872]
## Description 

Community report here: https://community.brave.com/t/unable-to-claim-rewards-continuously-spins/112354

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closing as this was fixed here https://github.com/brave/brave-browser/issues/9657
