### ISSUE TITLE
Brave Ads crashes on iOS for ads with an invalid target URL

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9873]
## Description 

Brave Ads crashes on iOS for ads with an invalid target URL

## Steps to Reproduce

   1. Add an ad with an invalid target url to the catalog
   2. Click an ad

## Actual result:

Application crashes

## Expected result:
Application should not crash

## Reproduces how often: 

No steps to reproduce

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.84 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* Used Charles Proxy to rewrite staging catalog so that an ad had an invalid `targetURL`. When I clicked on the ad, confirmed that Brave did not crash.
