### ISSUE TITLE
For users not receiving ads, "jiggling the handle" seems to fix it

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#9874]
## Description 
These users report that if they turn rewards on and off they can receive ads again:

https://www.reddit.com/r/BATProject/comments/fieobk/havent_been_receiving_ads_this_month/
https://www.reddit.com/r/brave_browser/comments/fiiknt/not_getting_ads_anymore/

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Disabling rewards clears ads state, which removes frequency caps etc.
