### ISSUE TITLE
Fingerprinting setting getting reverted

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#9875]
## Description 
I have set fingerprinting to `block all`. Still every time I restart browser, it goes back to `block cross-site`. 

## Steps to Reproduce

Change setting and restart browser

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.9.72

**Comment by pes10k** [comment]
Thank you for the report!  This issue is being tracked here, and we should have a solution soon. 

https://github.com/brave/brave-browser/issues/10303
