### ISSUE TITLE
Top Sites Rendered Over Customize Menu on NTP

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9876]
## Description 
At certain widths, the Top Sites module partially occludes the Customize menu.

![image](https://user-images.githubusercontent.com/815158/82587308-88a57f80-9b5e-11ea-93f1-031982680e27.png)

## Expected result:
The customize menu should always be on top.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.11.17

**Comment by rebron** [comment]
Fixed in newer versions of 1.11.x. We have a different Customize settings dialog in later builds.
