### ISSUE TITLE
Uh oh! The Brave Rewards server is not responding.

### ISSUE THREAD

**Issue by ravenclaw900** [brave/brave-browser#9877]
Possibly (but probably not) related to #9874.

## Description 

I keep getting the "**Uh oh!** The Brave Rewards server is not responding. We will fix this as soon as possible." error.  Because of that, I haven't been getting ads.

## Steps to Reproduce

   1. Go to brave://rewards?

## Actual result:

<img width="374" alt="Screen Shot 2020-05-21 at 1 16 55 PM" src="https://user-images.githubusercontent.com/50060110/82591792-7f6be100-9b65-11ea-9b00-d0aa07f55840.png">

## Expected result:
<img width="374" alt="Screen Shot 2020-05-21 at 1 16 55 PM" src="https://user-images.githubusercontent.com/50060110/82592191-26507d00-9b66-11ea-8fa1-0312c8b1285c.png">

## Reproduces how often: 

No steps to reproduce

## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.13.6 (Build 17G12034)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No, seems to be installation specific
- Can you reproduce this issue with the dev channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by NejcZdovc** [comment]
@ravenclaw900 do you maybe have uphold wallet connected?

**Comment by ravenclaw900** [comment]
No, I do not have an Uphold Wallet connected.

**Comment by NejcZdovc** [comment]
Could you please go to brave://rewards-internals/ and see if see `Key Info Seed: Valid`

**Comment by ravenclaw900** [comment]
It is not.

**Comment by ravenclaw900** [comment]
I do have a copy of my recovery key, if that's useful.

**Comment by NejcZdovc** [comment]
what do you see on this page?

**Comment by ravenclaw900** [comment]
Okay, oddly enough, I clicked "Join Rewards" using the icon in the URL bar, pasted my recovery key in, and it's working (and valid) now.

**Comment by ravenclaw900** [comment]
Would it be possible to recover my pages visited for the auto-contribute?  I have a copy of Brave Browser Beta with all of it (and working).
