### ISSUE TITLE
Filter out Doubleclick's tracking parameter from the query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#9879]
Google Display Ads uses a [`dclid`](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dclid) query string parameter to tie ad clicks to individual users and GTM will [use it in the same way as `gclid`](https://support.google.com/dcm/answer/9182069?hl=en).

This [enhanced attribution](https://wojtek.ch/advertising/google-campaign-manager/google-enhanced-attribution-how-does-it-work/) was designed to work around earlier versions of ITP.

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.68 Chromium: 83.0.4103.106 (Official Build) dev (64-bit)
-- | --
Revision | ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5633

* Reproduced the issue using `1.10.93`:
<img width="1197" alt="Screen Shot 2020-06-18 at 12 10 37 PM" src="https://user-images.githubusercontent.com/28145373/85045507-0b6d2a80-b15d-11ea-85f6-f9ea3b4f0ae8.png">

* Confirmed parameter is filtered out on `1.11.x`:
<img width="1196" alt="Screen Shot 2020-06-18 at 12 11 16 PM" src="https://user-images.githubusercontent.com/28145373/85045518-0f994800-b15d-11ea-98c3-ebf099733fe4.png">
