### ISSUE TITLE
Sort auto contribute table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#988]
We need to sort table in DESC order based on %.

**Comment by ryanml** [comment]
This has been fixed with: https://github.com/brave/brave-core/pull/441

**Comment by NejcZdovc** [comment]
This should be done on DB level and not in JS level. So when you fetch publishers for auto contribute table you should specify order in SQL query using this logic here https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/publisher_info_database.cc#L366

**Comment by NejcZdovc** [comment]
@ryanml we will probably have some sorting, but I don't see this in a near future. When we will have this I suggest that we do generic sorting in table component and pass in default sort as part of header prop for table. This way we just do in once and use it everywhere. 

example of header prop
```
[
 { content: 'Col 1', defaultSort: 'desc', customStyle: {} },
 { content: 'Col 2', customStyle: {} }
]
```

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X

Using test plan from https://github.com/brave/brave-core/pull/487
