### ISSUE TITLE
Appcast points to wrong release notes

### ISSUE THREAD

**Issue by vitorgalvao** [brave/brave-browser#9881]
On macOS, [the Sparkle appcast feed for the stable version](https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml) mentions under `<description>` that the changelog is located at https://github.com/brave/brave-browser/blob/master/CHANGELOG.md.

That link is a 404. The correct address is https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md.

https://github.com/brave/brave-browser/pull/9880 is tangentially related.

**Comment by bsclifton** [comment]
cc: @mbacchi

**Comment by mbacchi** [comment]
This is fixed in nightly, dev and beta channels already(1.10.x milestone), and will reach release channel on June 9. The PR that fixes it is https://github.com/brave/brave-core/pull/5519.

Closing as dup.
