### ISSUE TITLE
[Android] Implement simpler Shield Panel

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#9888]
## Description 
Implement the simpler shield panel design
It is the sub issue of https://github.com/brave/brave-browser/issues/6831

**Comment by anthonypkeane** [comment]
## Designs
![shields 1](https://user-images.githubusercontent.com/2388823/74183838-990e9b80-4bfa-11ea-9f7f-2c00f3a0ef1e.jpg)

Tapping the help icon will show more information about Brave Shields:

![shields 2](https://user-images.githubusercontent.com/2388823/74183865-a2980380-4bfa-11ea-8962-f9d58991e65d.jpg)


Advanced site-specific controls are available in an expand/collapse section, which persists across sites. So if the user expanded Advanced controls on one site, it will still be expanded when they open Shields on a different site.

![shields 3](https://user-images.githubusercontent.com/2388823/74185757-21db0680-4bfe-11ea-99f9-7c1650751c87.jpg)

Label changes:

- "Block Ads & Tracking" becomes "Block cross-site trackers"
- "HTTPS Everywhere" becomes "Upgrade connections to HTTPS"
- Same options to block cookies and fingerprinting as on desktop

Tapping on "Block cross-site cookies" opens options in a subpanel:
![shields 4](https://user-images.githubusercontent.com/2388823/78923597-5546df80-7a4d-11ea-9193-85a1bd23dfeb.jpg)

Tapping on "Block cross-site fingerprinting" opens options in a subpanel: 
![shields 5](https://user-images.githubusercontent.com/2388823/78923669-73acdb00-7a4d-11ea-8697-463cf870005e.jpg)


Tapping "Change global Shields defaults" under Advanced Controls deeplinks the user to the app settings page:

![Settings 2](https://user-images.githubusercontent.com/2388823/74183977-c8250d00-4bfa-11ea-9a40-f412458cb3a9.jpg)

Tap on the cookies line item to see more options in a sub-page:

![Settings 3](https://user-images.githubusercontent.com/2388823/74183990-cf4c1b00-4bfa-11ea-9047-880332a1e403.jpg)

Tap on the fingerprinting line item to see more options in a sub-page:

![Settings 4](https://user-images.githubusercontent.com/2388823/74183995-cfe4b180-4bfa-11ea-9b78-b63b6f763d1d.jpg)


When Brave Shields is down (whether Advanced controls is expanded or not), users can report a broken site by tapping "Report a broken site"

![shields webcompat 1](https://user-images.githubusercontent.com/2388823/74184048-edb21680-4bfa-11ea-8fcc-1b3046f34483.jpg)
![shields webcompat 2](https://user-images.githubusercontent.com/2388823/74184054-ef7bda00-4bfa-11ea-8f2b-aa29128a3231.jpg)


The confirmation message should dismiss on its own after 1s if the user doesn't tap out first:

![shields webcompat 3](https://user-images.githubusercontent.com/2388823/74184066-f4408e00-4bfa-11ea-8fa1-ea5890a64296.jpg)

### Dark theme
Dark theme is supported. Text, toggles, buttons, links, and icons have lighter colors:

![dark theme shields 1](https://user-images.githubusercontent.com/2388823/74184778-3e763f00-4bfc-11ea-8606-bb115a7eb5df.jpg)
![dark theme shields 2](https://user-images.githubusercontent.com/2388823/74184780-3fa76c00-4bfc-11ea-9a92-64d6ad6cb181.jpg)
![dark theme shields 3](https://user-images.githubusercontent.com/2388823/74184783-40400280-4bfc-11ea-82e9-9d077c96555c.jpg)
![dark theme shields 4](https://user-images.githubusercontent.com/2388823/74184786-40d89900-4bfc-11ea-9cb7-6ace4b8bfd35.jpg)
![dark theme shields 5](https://user-images.githubusercontent.com/2388823/74184789-41712f80-4bfc-11ea-9ce7-60c5d374771c.jpg)
![dark theme shields 6](https://user-images.githubusercontent.com/2388823/74184790-41712f80-4bfc-11ea-92eb-21597586578d.jpg)

### Landscape mode
This works the same as currently.

![shields landscape](https://user-images.githubusercontent.com/2388823/74184805-47ffa700-4bfc-11ea-9b7b-7e30b8b1d43e.jpg)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.11.102 x64 build

<details>
<summary>Verified shields design is as per spec</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Dark Theme</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88798876-859dbf80-d19d-11ea-885a-67c69801cd41.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799129-e9c08380-d19d-11ea-8931-df1267d82189.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799353-42901c00-d19e-11ea-80da-c0679aa329c2.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799360-458b0c80-d19e-11ea-8898-94062169163f.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799369-4885fd00-d19e-11ea-95a8-90e94ff194f5.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799374-4b80ed80-d19e-11ea-988c-ab50a012cae9.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799377-4e7bde00-d19e-11ea-98de-cb0c95243754.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799387-5176ce80-d19e-11ea-89ee-8690a652130d.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Light Theme</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799622-aadefd80-d19e-11ea-8908-c54b50122d3d.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799647-b16d7500-d19e-11ea-9fa3-e226e1c3aacd.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799659-b500fc00-d19e-11ea-8a8e-0d3ef4e8acb0.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799665-b8948300-d19e-11ea-9e11-539121e51abe.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799677-bc280a00-d19e-11ea-928d-0eb3b7a6454f.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799687-bfbb9100-d19e-11ea-84d6-03fba8495309.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799692-c2b68180-d19e-11ea-96d5-bf78be5178ac.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88799704-c77b3580-d19e-11ea-9897-4df3c9870ca7.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Landscape Orientation</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800205-aebf4f80-d19f-11ea-9a2b-e8cdec09893e.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800239-baab1180-d19f-11ea-960f-e3c4a5007f8a.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800244-be3e9880-d19f-11ea-9a5d-303f88d37bde.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800249-c1d21f80-d19f-11ea-93b1-0767a890888b.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800258-c565a680-d19f-11ea-9d47-f6c892989691.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800266-c8609700-d19f-11ea-8316-fb676960c4ed.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800273-cb5b8780-d19f-11ea-809d-c480f54005ed.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88800281-cdbde180-d19f-11ea-86d0-6f6e49e695a5.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
</table>
</details>

---------

Verification passed on Samsung Tab A with Android 10 running 1.11.102 x64 build

<details>
<summary>Verified shields design is as per spec</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Dark Theme</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801338-73258500-d1a1-11ea-93e3-051756f7eef2.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801393-8b959f80-d1a1-11ea-9fe8-8d4080780dd4.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801403-905a5380-d1a1-11ea-9989-d5e841046ea5.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801413-951f0780-d1a1-11ea-8098-f97ef206f5b2.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801421-98b28e80-d1a1-11ea-99a6-a0d8af3326f7.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801434-9d774280-d1a1-11ea-89f0-92b8a386c4f7.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801444-a10ac980-d1a1-11ea-8944-02ee69d2a162.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801493-b7188a00-d1a1-11ea-842f-2ac6ac3a57ac.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Light Theme</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801507-bed82e80-d1a1-11ea-9b60-64e9f5bdaa1e.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801519-c3044c00-d1a1-11ea-8088-0d93dece7bd9.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801532-c697d300-d1a1-11ea-8c03-3535d3be9832.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801557-cbf51d80-d1a1-11ea-8ae6-f9948a3a8ff0.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801582-d0213b00-d1a1-11ea-8bf8-cd7fb29873f3.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801604-d4e5ef00-d1a1-11ea-9fd1-21726a47260d.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801616-d9120c80-d1a1-11ea-9a94-cc64b869fd94.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801628-de6f5700-d1a1-11ea-8feb-f6ac217f1506.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Landscape Orientation</summary>
				<table>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801706-f8a93500-d1a1-11ea-8974-17f56dbdfb52.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801718-fcd55280-d1a1-11ea-953f-da56cc60708a.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801729-ffd04300-d1a1-11ea-8fe7-e9efbef2cb7d.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801741-065eba80-d1a2-11ea-90b4-b39d916eb1b2.png></td>
					</tr>
					<tr>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801750-0bbc0500-d1a2-11ea-9482-913ef1208e86.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801763-0fe82280-d1a2-11ea-84a6-b815b32be503.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801775-15456d00-d1a2-11ea-8459-501ac7aecfaa.png></td>
						<td><img src=https://user-images.githubusercontent.com/17010094/88801797-1bd3e480-d1a2-11ea-96a7-2b6b31af84aa.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
</table>
</details> 

-------
Logged follow up issues #10992 & #10993
