### ISSUE TITLE
Add unique to token_value in unblinded_tokens table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9889]
There could be cases where we retry unblinding tokens where we already have same tokens in the table. Token value is unique and always the same, so if we run unblinding we will always get the same token_value. Because of that we should add UNIQUE constrain on token_value. 

We also need to handle upgrade case as some users could have duplicated tokens already in the table. We need to make sure that we have browser tests for this upgrade case

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified test plan from https://github.com/brave/brave-core/pull/5683 on staging env
* Used 1.10.97 and upgraded to 1.11.x to confirm balance was restored to what it should be

-----
