### ISSUE TITLE
Dismissed Ads in Notifications Section

### ISSUE THREAD

**Issue by attacker34** [brave/brave-browser#9892]
## Description 

I downloaded and installed Brave Browser and as I was checking different videos related to this and even FAQ of brave website shows a different UI of ads where there is option for "Close" & " View" 

I've received different ads via push notifications but as they didn't have the "View" Option on them.. I thought its not worth looking for or its not the brave browser's ads.

```
https://support.brave.com/hc/en-us/articles/360026361072-Brave-Ads-FAQ

```
![Screen Shot 2020-05-22 at 1 11 29 PM](https://user-images.githubusercontent.com/10330087/82646306-cfae7600-9c2d-11ea-9b52-a5d8939535b2.png)

My Question is Whether I can see the dismissed ads by going into:

```
brave://rewards/

```

Software Version on Mac:

```
Version 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)

```

**Comment by bsclifton** [comment]
@attacker34 this is expected - Chromium removed this in Chromium 80 I believe? You can click the notification itself to view it 😄 

cc: @tmancey

**Comment by attacker007** [comment]
Hi @bsclifton  Please update FAQs with both type of UI's

Thanks !!

**Comment by bsclifton** [comment]
cc: @Miyayes @Brave-Matt
