### ISSUE TITLE
Click no longer works at www.tvinfo.de.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#9897]
## Description 
This page has not worked since upgrading to version 1.9.72 correct.
This page still works correctly under Brave version 1.7.98 and Brave 1.8.96 and all other browsers (Chromium, Chrome, etc.).

## Reproduces how often: 
always

## Brave version (brave://version info)
Brave	1.9.72 Chromium: 81.0.4044.138 (Official Build) (32-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Windows 10 OS Version 1909 (Build 18363.592)

**Comment by bsclifton** [comment]
@Johann999 do you have more information?

I'm visiting www.tvinfo.de and am able to navigate around just fine. Is there a specific set of steps you are trying?

**Comment by Johann999** [comment]
Under Brave version 1.9.72 i can't click anything  on website www.tvinfo.de.
If tracking is deactivated for this website, it will work normal.

**Comment by ryanbr** [comment]
Investigating. Caused by a filter in uBO. `##+js(set, String.prototype.slice, noopFunc)`

**Comment by ryanbr** [comment]
Will re-check this in the next few days to confirm this is fixed.

**Comment by Johann999** [comment]
The website www.tvinfo.de works again correctly.
Thanks a lot.

**Comment by ryanbr** [comment]
Confirmed, everything now working.
