### ISSUE TITLE
[Android] Switch to this tab (from omnibox)

### ISSUE THREAD

**Issue by Poopooracoocoo** [brave/brave-browser#9899]
## Updated issue description (by @bsclifton)
Desktop has a feature where (when typing in omnibox) if match is found a `Switch to this tab` button is shown and you can open that existing tab instead of searching/visiting the URL again.
![image](https://user-images.githubusercontent.com/4733304/101064602-06543a00-3549-11eb-8deb-cb3130ebf7da.png)

It would be great to have this feature on Android also. 

Chromium has an issue tracking this here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1043372

**Comment by Poopooracoocoo** [comment]
@Madis0 don't know if you've seen this already, thought you might like this: 
https://chromium-review.googlesource.com/c/chromium/src/+/2200252/14
https://bugs.chromium.org/p/chromium/issues/detail?id=1085220
:)

**Comment by Poopooracoocoo** [comment]
Before Brave even put it on their roadmap/project board, Google implemented switch to tab. I don't have much hope for searching tabs, bookmark all tabs and bookmark import/export (the latter which I especially want in Chromium AND there is a patch from Bromite already available! they're already available for desktop) :(

@bsclifton I get that you guys have very limited resources but I hope you guys understand how I feel as a user. I totally understand that you're a business and that your ads are very important to it. It feels like the Android version doesn't get much love. 

Cheers.

**Comment by Poopooracoocoo** [comment]
also see #9900 for a *similar* issue @srirambv if you're there, could you close it? (i could but im testing to see if you guys still care about the android browser)

**Comment by bsclifton** [comment]
@Poopooracoocoo updated issue description to be clear and include a screenshot 👍

**Comment by Poopooracoocoo** [comment]
@bsclifton um. could you please close this? it's been implemented upstream as i said in my comments above.

**Comment by bsclifton** [comment]
@Poopooracoocoo this is implemented? the Chromium issue linked shows it as assigned but not closed?

**Comment by Poopooracoocoo** [comment]
The feature could require the flag to be enabled, but since I've enabled it, I'm not sure. 

But there's no point keeping this issue open since all they'll do is just enable the feature by default (if it isn't already) and then remove the flag. You could take a look at the comments and other issues in that crbug, like https://bugs.chromium.org/p/chromium/issues/detail?id=1085220 

ughhhh seeing the comment in that makes me want import/export bookmarks and bookmark all tabs.
