### ISSUE TITLE
Bump bat-native-usermodel deps

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9903]
Fixes https://github.com/brave-intl/bat-native-usermodel/pull/30

**Comment by LaurenWags** [comment]
@tmancey from the test plan the second step is 
> Verify wallet (Uphold)

Is connecting an already verified wallet sufficient or do we need to start the KYC process on a new wallet? Or perhaps something else that I'm missing?

Marking as `QA/Blocked` until test plan is confirmed.

cc @rebron @kjozwiak

**Comment by tmancey** [comment]
@LaurenWags Connecting and already verified wallet would be suffice, hanks

**Comment by LaurenWags** [comment]
Thanks @tmancey - so after we connect the wallet if we see the Uphold balance reflected in the browser we're good? Any other steps we need to take - maybe tip a site or perform an auto contribute - to confirm that all is as expected?

**Comment by tmancey** [comment]
@LaurenWags No other steps required, this was enough to trip the crash. Thanks

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.11.78 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Per https://github.com/brave/brave-browser/issues/9903#issuecomment-649545625, connected a KYC'd wallet (staging env) in 1.11.x and confirmed no crash as mentioned in https://github.com/brave/brave-browser/issues/9903#issuecomment-650037357

<img width="401" alt="Screen Shot 2020-06-26 at 1 21 29 PM" src="https://user-images.githubusercontent.com/28145373/85884175-33d5d400-b7b0-11ea-8481-3a3bf7e34535.png">

------
