### ISSUE TITLE
Add setting to enable/disable "tab hover cards" 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#9906]
## Description 

According to https://github.com/brave/brave-browser/issues/9509, the default "tab hover cards' will revert to the "tooltip" display on-hover. However, the option to display the preview on-hover is still desired by many users (especially those who miss the old [tab preview feature from days of old](https://github.com/brave/brave-browser/issues/275)).

We should surface this option from flags to Settings so that users have the choice to display one or the other:
![image](https://user-images.githubusercontent.com/3299098/82704762-1ea6dc00-9c2b-11ea-9807-c00aecb5453c.png)

## Designs
Add toggle for search tabs button to "Appearance" section, above 'Hide search tabs button'

![image](https://user-images.githubusercontent.com/2388823/123491453-92a07a00-d5cb-11eb-8292-813ad050183d.png)

## Assets
Figma: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/?node-id=808%3A9464

**Comment by qubetzl** [comment]
I've taken a look at the chatter in Chromium's tracker about the recently removed flag for "tab hover cards" - https://bugs.chromium.org/p/chromium/issues/detail?id=1213741

While looking around I stumbled upon the commit that removed the flag and the feature checks about it - https://chromium.googlesource.com/chromium/src/+/e2124a1d261f70ffe0048553b0f4642e0444d6a1

Hope this information is useful for getting the ticket solved.

**Comment by alrasch** [comment]
There used to be a setting to "disable hover cards", but I can no longer find that setting and I'm permanently stuck with the abomination now.

Can it be overridden in Brave despite Chromium's persistence?

**Comment by opal1974** [comment]
Yes, this is absolutely distracting and annoying. You used to be able to turn it off in experimental but while the option is still there it does nothing.

**Comment by r01k** [comment]
These large tooltips are distracting and cover sections of the URL that often give you the same information to help you differentiate tabs when their title is hidden due to being are pinned. The net effect is that they feel annoying.

Please implement a setting to disable them and instead have the previous practical, unobtrusive tooltip.

**Comment by adamwinn** [comment]
We need a way to disable these.  They are so annoying

**Comment by vphantom** [comment]
Is there a way we could perhaps have a bounty to fast track this? I'd gladly contribute $100 towards having an option to disable those horrible things entirely in Brave, since the flag is gone.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.82 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

### Steps:

1. installed `1.44.82`
2. launched Brave
3. visited `nytimes.com`
4. visited `cnbc.com`
5. visited`bloomberg.com`
6. opened `brave://settings/appearance`
7. confirmed 3 options for configuring `Tab Hover Mode`
      `Card`
      `Card with preview`
       `Tooltip`
8. confirmed the setting for `Tab hover mode` was set to `Card` as a default
9. hovered over the `nytimes.com` tab's title
10. confirmed a card displaying the the title & origin of the tab popped up after a ~ 1-2 second delay
11. opened `brave://settings/appearance`
12. changed the setting to `Card with preview`
13. hovered over a tab (not the currently active tab)
14. confirmed a thumbnail and preview of the tab was shown after a ~1-2 second delay
15. changed the setting to `Tooltip`
16. hovered over a tab
17. confirmed tooltip displaying the site title was displayed

steps 6-8 | step9-10 | step 11-12 | step 13-14|step15|step 16-17
----------|--------|--------|--------|--------|---------
<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189753401-28c75d2f-65a7-4f02-8202-e951fe31e778.png">|<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189750483-4d1a7388-0c60-47c6-9d4d-68b9056b67ef.png">|<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189751005-19dddd14-0161-4d67-bd41-e0054c5e5474.png">|<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189751482-432d64f1-7b6e-481e-82c5-d923e93160cb.png">|<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189751602-ac87bef6-962c-4237-8b0a-6eea3369ea4a.png">|<image width="950" alt="step6-7" src="https://user-images.githubusercontent.com/98358127/189754039-86d14fb6-097f-4174-aa06-51bec6ce0dc1.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.88 Chromium: 105.0.5195.136 (Official Build) beta (64-bit) 
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Linux

### Steps:
1. installed `1.44.73`
2. launched Brave
3. opened `abcnews.com`
4. opened `bbcnews.com`
5. opened `cbsnews.com`
6. hovered over the cbsnews.com tab's title
7. confirmed a card displaying the the title & origin of the tab popped up after a ~ 1-2 second delay
8. opened `chrome://settings/appearance`
9. confirmed the setting for `Tab hover mode` was set to `Card`
10. changed the setting to `Card with preview`
11. hovered over a tab (not the currently active tab)
12. confirmed a thumbnail and preview of the tab was shown after a ~1-2 second delay
13. changed the setting to `Tooltip`
14. hovered over a tab
15. confirmed tooltip displaying the site title was displayed

steps 6-7 | step 9 | step 12 | step 15
----------|--------|--------|--------
<img width="1203" alt="Screen Shot 2022-09-16 at 1 21 02 PM" src="https://user-images.githubusercontent.com/387249/190727173-0918369e-c483-4508-beee-4fbc58cb2e82.png"> | <img width="1318" alt="Screen Shot 2022-09-16 at 1 15 08 PM" src="https://user-images.githubusercontent.com/387249/190727506-d4e3361f-75fe-4a5b-98b3-713bc59f01ed.png"> | <img width="1209" alt="Screen Shot 2022-09-16 at 1 25 22 PM" src="https://user-images.githubusercontent.com/387249/190727689-6a1ecf5a-af19-4af7-9829-51b801dd8925.png"> | <img width="1212" alt="Screen Shot 2022-09-16 at 1 25 02 PM" src="https://user-images.githubusercontent.com/387249/190727106-c973fa63-d61b-405d-b10c-985b72122bf9.png">
