### ISSUE TITLE
Install Widevine prompt should include more DRM background information

### ISSUE THREAD

**Issue by Madis0** [brave/brave-browser#9907]
## Description 

Running EME on a site for the first time makes Brave ask the user, whether they'd like to install it. While that's a good thing, it also has a big piece of text, explaining:

- Widevine is from Google
- it's bad but you choose
- we take no responsibility

However, it lacks information on:

- what DRM itself is
- why it's bad
- where can user manage it (#2791)

## Steps to Reproduce

   1. Open https://permission.site/
   2. Click "Encrypted Media (EME)"
   3. Note the popup

## Actual result:

![Popup](https://user-images.githubusercontent.com/8611110/82705195-dfef4100-9c7f-11ea-847a-a407ccdfc6db.png)

## Expected result:
Expected a short popup with one-sentence description and a link to read more. Something [more like Firefox](https://techdows.com/wp-content/uploads/2016/09/Firefox-prompts-to-Enable-DRM.png), but with an actual explanation.

Example text:
> Widewine is a Digital Rights Management plugin by Google, used to give users access to protected content by displaying it in a controlled environment. _Read more_

The "read more" should link to a Brave article explaining what a DRM is, how it works, why it's bad, how Widevine works and how to install/enable/disable/remove it.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.10.60

## Version/Channel Information:

- Can you reproduce this issue with the current release? Probably
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Probably
- Can you reproduce this issue with the nightly channel? Probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Related: #2791

**Comment by rebron** [comment]
cc: @rmcfadden3 If you think we should revisit update our widevine screen.

**Comment by rmcfadden3** [comment]
Ah, didn't realize how frequently this message might appear.

Will investigate new / better copy, and a corresponding help doc with more info that people could click through to.

**Comment by rebron** [comment]
cc: @Brave-Matt We'll be updating the text here and will need to Support documentation to match.

**Comment by rmcfadden3** [comment]
@rebron — here's new copy for the Widevine message. Note the "Learn more" will point to a support page that explains more. Also note the "X" beside the header is meant to allow user to close the message without making a decision.

Header:

- [sitename] is asking you to install Google Widevine		**X**

Body:

- Widevine is sometimes needed to play media on a webpage. It’s a Google extension loaded from Google servers, which Brave cannot inspect. By installing, you’ll agree to Google’s terms of use. Learn more.

CTAs:

- Block
- Allow
- Change later at brave://settings/extensions

**Comment by rebron** [comment]
@rmcfadden3 What did you want to do with the Change later at brave://settings/extensions CTA? Do we want to just include it as text and link in the body or how did you want to incorporate that one.

**Comment by simonhong** [comment]
Below is our latest widevine permission bubble.
This one has additional footer area about change later or learn more and and it mentions general `site permission`
and `Learn more` link. Instead of this, how about customizing this footer area for widevine specific settings and
learn more link?

 
<img width="386" alt="Screen Shot 2022-01-12 at 3 00 39 PM" src="https://user-images.githubusercontent.com/6786187/149072474-d68ec159-eff9-4e7d-a952-e41116020192.png">

**Comment by simonhong** [comment]
@rmcfadden3 @rebron How about this?
<img width="343" alt="Screen Shot 2022-01-12 at 4 15 53 PM" src="https://user-images.githubusercontent.com/6786187/149081300-f265a71b-5f50-448a-b6d0-d551a421564e.png">

**Comment by rmcfadden3** [comment]
@simonhong — that looks really good. The only thing I'd suggest is changing the order in the message footer, so it's clear that "Learn more" will tell you about Widevine, rather than settings in general. So the footer could read:

"[Learn more about Widevine](URL goes here). Change later at brave://settings/extensions."

**Comment by rmcfadden3** [comment]
BTW, I just checked in w/ Mattches to see about publishing a support doc so you have an endpoint URL for that "Learn more about Widevine" text.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.36.45 Chromium: 97.0.4692.71 (Official Build) nightly (x86_64)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | macOS Version 11.6.1 (Build 20G224)

Steps:
1. new profile
2. launched Brave
3. loaded `https://permission.site`
4. clicked on `Encrypted Media (EME)`
5. looked at the resulting Widevine dialog

Confirmed the text change.

before | after
-------|------
<img width="1312" alt="Screen Shot 2022-01-18 at 11 15 25 AM" src="https://user-images.githubusercontent.com/387249/150003805-251369bc-b4ee-4c02-9387-e09dd24e894a.png"> | <img width="1312" alt="Screen Shot 2022-01-18 at 10 57 46 AM" src="https://user-images.githubusercontent.com/387249/150003832-a71f497d-123c-4ac7-9e69-5694cb137792.png">
