### ISSUE TITLE
High CPU/disk usage when Brave Rewards is downloading/processing the new publishers list

### ISSUE THREAD

**Issue by MinisterFister** [brave/brave-browser#9908]
I noticed that Brave CPU spikes around the same time I see /api/v3/public/channels?page=[page_number] calls (used a proxy for this). I also notice there are a lot of write operations in the publishers_info_db file (when looking at disk usage in Resource Monitor in Windows). My hypothesis is that this is the root cause of the CPU usage issues for a lot of people (or fan spinning noises or high disk usage, etc). I notice the issues on Brave launch most of the times, and I assume it's because it has to download/save the publishers list in publishers_info_db file. Maybe the saving of data in the sqlite db can be optimized, which is my hypothesis of the root cause of the issue. 

I have the latest Brave version (Release channel 1.9.72). Using Windows 10.
I know for a fact this CPU usage issue didn't happen, or wasn't as bad, when we had the previous publishers_list in a .json file.

Hope it helps and is enough info. If you guys need any more info please let me know!
Thanks,

**Comment by bsclifton** [comment]
Should be addressed when https://github.com/brave/brave-core/pull/5568 is finished/merged

**Comment by MinisterFister** [comment]
Ohhh gotcha @bsclifton tyvm! Can't wait for the update :)

Also I went into the db and noticed in the "server_publisher_banner" there are a lot of rows that have no title, description, background and logo (currently count is 100k). Not sure if these are downloaded from the server or not, but that's a big portion of the total row count which are basically useless (which is around 550k in my db). If these are downloaded from the servers maybe removing these can help also :)

Query would be : 
SELECT "_rowid_",* FROM "main"."server_publisher_banner" WHERE title = "" AND description = "" AND background = "" AND logo = "";
Result: 100083 rows returned in 270ms

**Comment by NejcZdovc** [comment]
closing this one as this will be resolved with https://github.com/brave/brave-browser/issues/9502
