### ISSUE TITLE
Use First Name Instead of Full Name in Rewards

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9909]
## Description 
Brave Rewards presently displays the users full name so they are able to distinguish between connected accounts. The full name is not likely necessary, as the first name alone should suffice.

![image](https://user-images.githubusercontent.com/815158/82706856-6dab3c00-9c40-11ea-9757-d81a5f1666cc.png)

## Brave version (brave://version info)
1.9.72

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.64 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

| 1.10.90 CR: 83.0.4103.97 (Old)  | 1.11.64 CR: 83.0.4103.97 (New) |
| ------------- | ------------- |
| <img width="432" alt="Screen Shot 2020-06-15 at 11 38 05 PM" src="https://user-images.githubusercontent.com/2602313/84729283-50c50880-af61-11ea-9bce-ec54aaad67b0.png">  | <img width="430" alt="Screen Shot 2020-06-15 at 11 35 03 PM" src="https://user-images.githubusercontent.com/2602313/84729194-18bdc580-af61-11ea-9145-abbc134e592e.png"> |
