### ISSUE TITLE
Send api key with usage pings

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#9911]
## Description 

Sending browser API_KEY with usage pings

## Steps to Reproduce

   1. Watch network requests
   2. Notice that api_key not sent to stats https://laptop-updates.braev.com/1/usage/braveCore

## Actual result:
N/A

## Expected result:
N/A

## Test Plan

1. Get a release of the browser that has not sent it's daily activity ping to laptop-updates
2. Use charles/wireshark/etc and watch network requests
3. See that api_key as a query parameter to https://laptop-updates.brave.com/1/usage

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` after speaking with @keur. This will basically be checked via https://github.com/brave/brave-browser/issues/10230.
