### ISSUE TITLE
Show 'estimated ad earnings this month' on the top-level Brave Rewards settings screen and do not hide under 'View Details' (additional press)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#9914]
## Description 

The "Estimated ad earnings" counter should appear in the top-level Brave Rewards settings page. Based on support queries, users often mistakenly believe their Brave Ads is broken because they do not see BAT immediately increasing upon seeing an ad. However, this is further exacerbated by "estimated ad earnings" being hidden under an additional press on mobile ("View Details"), which many users miss or do not notice.

![image](https://user-images.githubusercontent.com/11497541/82717628-68171b80-9c6b-11ea-9e75-365dc20a7fe6.png) 
_This screenshot is from iOS, but it is the same on Android._

Initial response to this suggested change (August 2019 internally), including among @brave/design, was mostly well-received! :)

## Steps to reproduce 

1. On mobile, go into Brave Rewards settings. (Applies to both iOS and Android)
2. Estimated ad earnings is always hidden under "View Details" rather than surfaced immediately in the top-level Settings page.

**Comment by Miyayes** [comment]
UI is still very confusing to a large number of users. 

+1 among many: https://www.reddit.com/r/brave_browser/comments/hiklaz/is_this_not_the_ads_that_you_earn_bat_from_im_new/

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/hkv6if/brave_rewards_not_working_on_android/

**Comment by Miyayes** [comment]
@jsecretan Related to proposed "processing" UI.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/hzy6j8/started_using_brave_mobile_ios_watched_5_ads_no/ (iOS)

**Comment by Miyayes** [comment]
Can we resurrect this? It is bad UI/UX that hurts retention and needs to be improved. I was speaking to a first-time user of Brave yesterday, and they turned off Brave Ads because they couldn't find where their ads were being counted/estimated pending rewards, and thought they were simply not being counted.

**Comment by jsecretan** [comment]
Yes, I would love to resurrect this, if you can help get us some new designs from the design team @Miyayes we can push this through.

**Comment by tmancey** [comment]
@Miyayes are you happy to close this issue based on new UI for Android:
![image](https://user-images.githubusercontent.com/1188719/154301686-2f6f6460-da68-46bf-b552-ea8a46089d26.png)

**Comment by Miyayes** [comment]
@tmancey Yes, happy to close. Also adding screenshot of the new Rewards settings page on Android.

![image](https://user-images.githubusercontent.com/11497541/154301962-207ddd1f-bb40-4a9f-af99-80c015edeef1.png)

**Comment by tmancey** [comment]
Love the new UI :-)

**Comment by tmancey** [comment]
Closed (see above screenshots)
