### ISSUE TITLE
[Android] Estimated bandwidth savings in NTP suggest bits rather than bytes

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9915]
Follow up from: https://github.com/brave/brave-browser/issues/8845

The notation is:
Upper case `B` is bytes
Lower case `b` is bits

The original design suggests bytes and upper case `B`: https://github.com/brave/brave-browser/issues/7783 https://github.com/brave/brave-browser/issues/8969

## Steps to reproduce 

   1. Browse few websites
   2. Open NTP
   3. Check `Data Saved`

## Actual result 
Lower case `b` is used, suggesting bits
![Screenshot_20200523-041125_Brave](https://user-images.githubusercontent.com/34715963/82719697-332bb880-9cad-11ea-8dc9-2930eff34aad.jpg)

## Expected result
The original suggests bytes and upper case `B`.
https://github.com/brave/brave-browser/issues/7783
![image](https://user-images.githubusercontent.com/145422/72570283-694acd00-38b4-11ea-928f-5c74e0d3cc76.png)
https://github.com/brave/brave-browser/issues/8969
![replace https with estimated data saved](https://user-images.githubusercontent.com/2388823/78176165-ed6f1400-7410-11ea-9bfd-cf827d66cba1.png)

## Issue reproduces how often 
100% repro rate

## Device details
   - Install type (ARM, x86): Arm
   - Device (Phone, Tablet, Phablet): Tablet
   - Android version: 9
   
## Brave version
BraveModernarm v1.9.74 on Samsung Galaxy Tab S5e (Android 9.0)

cc @brave/legacy_qa @karenkliu @SergeyZhukovsky @anthonypkeane @samartnik

**Comment by LaurenWags** [comment]
Verification passed on Asus Zenfone (x86) with Android 6.0 running 1.9.77 BraveModernx86.apk

![Screenshot_20200529-164046_1](https://user-images.githubusercontent.com/28145373/83303740-9ba5f880-a1cb-11ea-9859-c30d10ff1695.jpg)

![Screenshot_20200529-164126_1](https://user-images.githubusercontent.com/28145373/83303752-a1034300-a1cb-11ea-8e6b-6a5603adfe0a.jpg)

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.9.77 on Samsung Galaxy Tab S5e (Android 9.0)
Verified on clean install
![Screenshot_20200529-210009_Brave](https://user-images.githubusercontent.com/34715963/83311857-cf574180-a210-11ea-9bfa-8ff3935dc216.jpg)
Verified on upgrade
![Screenshot_20200529-204744_Brave](https://user-images.githubusercontent.com/34715963/83311864-d67e4f80-a210-11ea-97b0-392b5720e3ed.jpg)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.9.77 x64 stable build
![image](https://user-images.githubusercontent.com/17010094/83381303-f45cd780-a3fd-11ea-9590-f27a2005ec23.png)
![image](https://user-images.githubusercontent.com/17010094/83381353-122a3c80-a3fe-11ea-9ca9-118747dd57ce.png)
