### ISSUE TITLE
BraveBrowserSetup.exe install  failed ,Please add  release version of offline installer file 

### ISSUE THREAD

**Issue by keepgoodfeeling** [brave/brave-browser#9916]
## Description 

In some country , people can not install brave by download BraveBrowserSetup.exe file ,beause of country firewall，but they can use the offline installer ; when using github, they can download files ,so please add release version of offline installer on github or "brave.com" .We truely love the brave browser .

## Steps to Reproduce

   1. download  "BraveBrowserSetup.exe" from "brave.com".
   2. downloging will take a long time and fail finally . wasting time.
   3. 

## Expected result:
 release version of offline installer on github or "brave.com" 

## Reproduces how often: 

every time

**Comment by bsclifton** [comment]
@rebron I wonder if we can add an optional link on the landing pages (Windows only) that grabs the full installer? (even if you need to scroll down - like a "Full download here" link)

**Comment by keepgoodfeeling** [comment]
> @rebron I wonder if we can add an optional link on the landing pages (Windows only) that grabs the full installer? (even if you need to scroll down - like a "Full download here" link)
Thanks a lot .
And in  some country, people can not connect to "brave.com" ,but can connect to "github.com", if  the full installer can be downloaded from github ,that can help  a lot .
