### ISSUE TITLE
Error code: RESULT_CODE_HUNG - Medium.com

### ISSUE THREAD

**Issue by Icesofty** [brave/brave-browser#9918]
## Description 
Tab crash when browsing into a Medium.com articles.

## Steps to Reproduce

   1.  Got to https://medium.com/recoding/rendering-html-css-in-deno-using-view-engine-e07469613598 , for example
   2. The webpage stop loading
   3. If you wait 1/2 minutes the Tab will crash with Error code: RESULT_CODE_HUNG

## Actual result:
https://imgur.com/a/qrGkZrq

## Expected result:
https://imgur.com/a/YoHrfdw

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by ryanbr** [comment]
I tested this in Brave release/nightly. both instances loaded. But the site was slow to render the images/embedded elements.  Can you re-test in private mode? Of if an option, a Brave beta? A VPN may also affect how quickly the embedded items load also.

**Comment by Icesofty** [comment]
> I tested this in Brave release/nightly. both instances loaded. But the site was slow to render the images/embedded elements. **Can you re-test in private mode?** Of if an option, a Brave beta? A VPN may also affect how quickly the embedded items load also.

So I tried by disabling the extensions one by one, and one of them makes the website crash : 

It's an extension called [Dashlane - Password Manager](https://github.com/Dashlane) which makes the website crash only on Brave. On Chrome and Firefox it works great. 
I'll open an Issue on their Website. 
Thanks for the hint!

**Comment by SeedyROM** [comment]
@Icesofty Currently experiencing this with Brave 86.1.16.67, thanks for the tip.

**Comment by Icesofty** [comment]
> @Icesofty Currently experiencing this with Brave 86.1.16.67, thanks for the tip.

I didn't find any public repo or @ address, so I just contacted them via Twitter. Will update this issue when I've more info

**Comment by Icesofty** [comment]
> @Icesofty Currently experiencing this with Brave 86.1.16.67, thanks for the tip.

The official answer from Dahslane support via Twitter: "Brave is not officially supported by Dashlane"
