### ISSUE TITLE
Expose the switch for prediction service in the address bar in settings page

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#992]
Ref: https://github.com/brave/brave-core/pull/244/files#diff-0f4a33a4998a356ad68d5e8a2a5c78c1R44

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
