### ISSUE TITLE
Feature/Suggestion: Tabs below Navigation Bar or someway to edit the UI with css?

### ISSUE THREAD

**Issue by stefankeys** [brave/brave-browser#9920]
## Description 
Is there a way to edit the UI with a GUI or with CSS? I would like to place the tabs below the navigation bar and the bookmarks bar and maybe even have multi-row tabs. 

## Here is a screenshot of what I would like it to be able to make it look like with css or a gui:

<img src="https://i0.wp.com/www.howtogeek.com/wp-content/uploads/2007/07/image14.png"/>

## Miscellaneous Information:

Firefox has a feature called userchrome.css which easily allows users to edit the UI with CSS for those who want to. A firefox fork from ancient times called Pale Moon also allows users to edit the browser UI with a GUI through extensions though I understand that would be a nightmare to implement and maintain. The reason I don't use these other browsers is that there is no way to use BAT on them.

**Comment by rebron** [comment]
Hi @stefankeys I know that userChrome.css feature. There isn't anything like that in chromium based browsers, there are extensions for other customizations though. I don't believe there's one for moving tabs to the bottom of the url bar.
