### ISSUE TITLE
Usage pings not being sent for users migrating to 1.9.72

### ISSUE THREAD

**Issue by keur** [brave/brave-browser#9921]
## Description 

Usage pings being dropped on 1.9.72

## Steps to Reproduce

   1. Have a release version of Brave < 1.9.72
   2. Upgrade to 1.9.72
   3. See that usage pings are not sent when the browser starts

## Actual result:

Changing of referral initialization local preference means that, for migrated users, usage pings are not being sent to referral server.

## Expected result:

All users send usage pings

## Reproduces how often: 

Always

## Miscellaneous Information:

Hotfix in nightly https://github.com/brave/brave-core/pull/5635

**Comment by keur** [comment]
## Test Plan

1. Have a release version of Brave < 1.9.72 and hotfixed version > 1.9.72
2. Start browser version < 1.9.72. 
3. Ensure that browser has initialized with the referral server (promo code file deleted, should have download id in brave://local-state)
4. Simulate an upgrade by launching hotfixed version > 1.9.72
5. View network traffic with Wireshark, Charles, etc
6. See that usage ping is sent out to laptop-updates
7. Test this with a referral code and without a referral code

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/brave-core/pull/5635

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Scenario 1 (Upgrade case w/ non-default promo code):
1. Launch Fiddler.
2. Installed 1.8.96 
3. Launch 1.8.96 using promoCode `KAM253`
4. Confirmed I saw ping in Fiddler:
<img width="1625" alt="1 8 96 KAM253" src="https://user-images.githubusercontent.com/28145373/83189487-21a83d80-a0ff-11ea-97b8-68afc5125222.png">

5. Close Brave. Update to 1.9.72. 
6. Move computer clock ahead one day. 
7. Launch Brave using 1.9.72. 
8. Confirmed I could reproduce the issue of not seeing a ping like above image.
9. Close Brave. Update to 1.9.76
10. Move computer clock ahead one day.
11. Launch Brave using 1.9.76.
12. Confirmed I saw ping in Fiddler:
<img width="1740" alt="1 9 76 KAM253" src="https://user-images.githubusercontent.com/28145373/83189547-2836b500-a0ff-11ea-9161-9d2db14e17c6.png">


Scenario 2 (Upgrade case with default promo code):
1. Launch Fiddler.
2. Installed 1.8.96 
3. Launch 1.8.96 without a promoCode (uses default `BRV001`)
4. Confirmed I saw ping in Fiddler.
<img width="1751" alt="1 8 96 BRV001" src="https://user-images.githubusercontent.com/28145373/83189574-2cfb6900-a0ff-11ea-9ea0-b6c451bee7bd.png">

5. Close Brave. Update to 1.9.72.
6. Move computer clock ahead one day.
7. Launch Brave using 1.9.72
8. Confirmed I could reproduce the issue of not seeing a ping like above image.
9. Close Brave. Update to 1.9.76.
10. Move computer clock ahead one day.
11. Launch brave using 1.9.76.
12. Confirmed I saw ping in Fiddler.
<img width="1666" alt="1 9 76 BRV001" src="https://user-images.githubusercontent.com/28145373/83189579-2f5dc300-a0ff-11ea-9d5e-7826d88e2432.png">


Scenario 3 (Clean install of 1.9.76):
1. Launch Fiddler.
2. Installed 1.9.76.
3. Launch 1.9.76 without a promoCode (uses default `BRV001`).
4. Confirmed I saw ping in Fiddler.
<img width="1670" alt="1 9 76 clean" src="https://user-images.githubusercontent.com/28145373/83189588-32f14a00-a0ff-11ea-805d-50d4fd4fb8f8.png">

5. Close Brave.
6. Move computer clock ahead one day.
7. Launch again.
8. Confirmed I saw ping in Fiddler.
<img width="1685" alt="1 9 76 clean day 2" src="https://user-images.githubusercontent.com/28145373/83189592-3553a400-a0ff-11ea-9d75-348711e5b856.png">
