### ISSUE TITLE
macOS crash on page load if KeyBoard viewer is open

### ISSUE THREAD

**Issue by rhuanjl** [brave/brave-browser#9922]
## Description 

If the macOS KeyboardViewer is open attempting to load any website in Brave results in Brave exiting unexpectedly.

## Steps to Reproduce

   1. Open the macOS KeyBoard Viewer
   2. Open Brave
   3. Attempt to navigate to any website

## Actual result:

Brave exits unexpectedly. No error message is given. No crash log is created.

## Expected result:
Website should load.

## Reproduces how often: 

Reproduces 100% of the time.

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.2 (Build 19C57)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **yes**
- Can you reproduce this issue with the beta channel? **not tested**
- Can you reproduce this issue with the dev channel? **not tested**
- Can you reproduce this issue with the nightly channel? **not tested**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **NO**
- Does the issue resolve itself when disabling Brave Rewards? **NO**
- Is the issue reproducible on the latest version of Chrome? **NO**

**Comment by simonhong** [comment]
I can reproduce this crash after enabling `Enable Accessibility Keyboard` from System Preferences > Accessibility > Keyboard > Accessibility Keyboard.
Is this same with you? @rhuanjl

**Comment by rhuanjl** [comment]
> I can reproduce this crash after enabling `Enable Accessibility Keyboard` from System Preferences > Accessibility > Keyboard > Accessibility Keyboard.
> Is this same step with you? @rhuanjl

It's not the way I was opening it but it looks like it's the same thing. I used it via: System Preferences > Keyboard > Input Sources > Show Input menu in menu bar

Then from the Input menu that that adds to the menu bar there's Show Keyboard Viewer.

**Comment by bsclifton** [comment]
I think this is the same problem as https://github.com/brave/brave-browser/issues/7546

It also should be happening in Chromium 81 (which isn't around anymore) and fixed with Chromium 83 (which we're finishing merge for now). This should be fixed in Brave soon 😄

**Comment by rhuanjl** [comment]
Looks like it - sorry for the duplicated I'd searched for existing issues but didn't find that.
