### ISSUE TITLE
Can't sign in on Medium.com

### ISSUE THREAD

**Issue by dextorer** [brave/brave-browser#9923]
## Description
I am trying to sign in using my account on medium.com, but either I receive an error (see below) or the page refreshes itself and I'm still logged out.

I have first tried to allow for all cookies, then to disable Shields entirely. Both didn't help.

## Steps to Reproduce
   1. Navigate to medium.com
   2. Press "Sign in"
   3. Use either email or Twitter
   4. Observe either an error message or the page refreshing
   5. You'll still be logged out 

## Actual result:
<img src="https://user-images.githubusercontent.com/765319/82735420-edf59e00-9d21-11ea-9ac2-acf3938ad84e.png" width=300 />

## Expected result:
I would expect to be logged in

## Reproduces how often: 
Reproducible every time.

## Brave version (brave://version info)
Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.3 (Build 19D76)

## Version/Channel Information:
I have only tried on the stable channel.

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
  _Nope._
- Does the issue resolve itself when disabling Brave Rewards?
  _Already disabled._
- Is the issue reproducible on the latest version of Chrome? 
  _Nope_

**Comment by Icesofty** [comment]
Hey, 

Can you try to disable your extensions one by one? 
I had an issue on Medium with an extension called Dashlane 

https://github.com/brave/brave-browser/issues/9918

**Comment by dextorer** [comment]
🤦 You're absolutely right, even though in my case it was caused by another extension. I thought I removed them all and tried, but apparently that wasn't the case.

I'm closing this, thanks @Icesofty for the support!

**Comment by luthfianto** [comment]
had this issue with "Bypass Paywalls Clean" extension. disabling it allow me to login to medium.com

**Comment by prashantghimire** [comment]
> had this issue with "Bypass Paywalls Clean" extension. disabling it allow me to login to medium.com

This was my problem. Definitely check your extensions if you're having this problem.

**Comment by praveenzid** [comment]
> had this issue with "Bypass Paywalls Clean" extension. disabling it allow me to login to medium.com

Bang on, extensions were the problem.
