### ISSUE TITLE
[Desktop] Password reminder still ask me for save the password

### ISSUE THREAD

**Issue by daveflr** [brave/brave-browser#9924]
## Description 

Password reminder is still asking me if I want to save passwords although I clicked in 'Never' button.

Ive check if the site is saved in the never saved list, and yes, its there, but still asking me if I want to save it every time I login in.

And its the same I all the sites that I use.

## Steps to Reproduce

   1. Login with any of your account in any site
   2. Click in the 'Never' save button
   3. Check if the site is in the 'Never saved' list
   4. Log out from your site
   5. Log in again
   6. It ask me if I want to save it again

## Actual result:

Don't ask me if I want to save it again

## Expected result:
Should not ask me again for save the password. It ask me again anyway 

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --disable-domain-reliability --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --disable-webrtc-apm-in-audio-service --enable-dom-distiller --enable-features=DnsOverHttps,SimplifyHttpsIndicator,MixedContentSiteSetting,PasswordImport,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode --extension-content-verification=enforce_strict --extensions-install-verification=enforce --no-pings --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps --disable-features=VideoPlaybackQuality,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,AllowPopupsDuringPageUnload,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,AutofillServerCommunication --flag-switches-begin --enable-features=WebUIDarkMode,PassiveMixedContentWarning,AutoupgradeMixedContent,PasswordImport,SimplifyHttpsIndicator,MixedContentSiteSetting,DnsOverHttps,BraveSync --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/daveflr/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Don't know 
- Can you reproduce this issue with the dev channel?
Don't know
- Can you reproduce this issue with the nightly channel?
Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
Don't know

## Miscellaneous Information:

![Peek 2020-05-23 23-02](https://user-images.githubusercontent.com/31354970/82746188-3d4fc480-9d4a-11ea-93d8-36a803ae65bd.gif)

**Comment by rebron** [comment]
cc: @srirambv Can you check to see if this reproduces for you?

**Comment by rebron** [comment]
Possible this is site specific, let's test on this site and another site that prompts for password.
cc: @bsclifton

**Comment by daveflr** [comment]
Well it happens in all sites, that one was just an example

**Comment by srirambv** [comment]
Can't reproduce it. Tried on a bunch of sites on nightly. First time the save password modal is shown. Closing the tab and revisiting the same site and logging in doesn't prompt but still shows the key icon in the URL bar. Only when i click on it the password modal pops up. 

@daveflr can you record the behaviour of this and share ?

**Comment by daveflr** [comment]
Sure, I recorded a [video](https://vimeo.com/440545359) with 3 sites, it doesn't happen with Deezer, but seems to be the only site that not, all the others its the same.

**Comment by srirambv** [comment]
@daveflr Sorry for the late reply but the issue seems to be that the browser is unable to set Bitwarden as the default password manager. For example if you have 1Password installed it shows the message like this 
![image](https://user-images.githubusercontent.com/17010094/103725254-12ab3700-4fce-11eb-8e05-e636ca88beed.png)

but with Bitwarden installed and signed in the browser isn't setting it as default password manager. Is the behaviour same on Chrome as well for you?
