### ISSUE TITLE
Brave reward ads keep popping up after turning on "Do Not Disturb"

### ISSUE THREAD

**Issue by MikeScotty** [brave/brave-browser#9927]
## Description 
When I turn on Do Not Disturb mode on ubuntu 20.04 the brave rewards ads keep popping up

## Steps to Reproduce

   1. Turn on "Do Not Disturb"
   2. browse
  

## Actual result:

Brave rewards ads pop up

## Expected result:
brave reward ads do not pop up

## Reproduces how often: 

all the time

## Brave version (brave://version info)

Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? IDK
- Can you reproduce this issue with the dev channel? IDK
- Can you reproduce this issue with the nightly channel? IDK

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I don't mind the reward ads myself but the device I use is a shared device and the other users don't like them, so I would like the Do Not Disturb mode stop reward ads from popping up so I won't have to turn brave ads on and off

**Comment by Icesofty** [comment]
Hi, 

Did you remove Brave from your priority list? 
For reference:
https://www.howtogeek.com/349829/how-to-use-focus-assist-do-not-disturb-mode-on-windows-10/

**Comment by MikeScotty** [comment]
@Icesofty I'm using Ubuntu, not windows

**Comment by MikeScotty** [comment]
BTW how do I add labels to my issues and requests?

**Comment by tmancey** [comment]
This issue will be resolved as part of https://github.com/brave/brave-browser/issues/5542
