### ISSUE TITLE
New Tab override via extension not working

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#993]
## Description 
Extensions are able to override a bult-in page such as New Tab page https://developer.chrome.com/extensions/override
This works in Chrome but not in Brave 0.55

## Steps to Reproduce

   1. Install momentum extension from https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca/related?hl=en
   2. Open New Tab

## Actual result:

Brave's default New Tab page is shown

## Expected result:
Momentum's New Tab page is shown

## Reproduces how often: 

Always

## Brave version (about:brave info) 

0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

## Additional
Brave policy is to allow these overrides, so this is a bug

**Comment by eljuno** [comment]
+1 from community (likely with other extension) https://community.brave.com/t/home-page-new-tab-page/32776?u=eljuno

**Comment by ngurney** [comment]
+1 for me as well. Looking to use the Tabliss extention which I assume is caused by the same issue.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/custom-new-tab-page-settings/34468

**Comment by srirambv** [comment]
+1 from @krono via #1771

**Comment by andrewcking** [comment]
I think #960 will accomplish this ("New Tab Page Shows")

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/momentum-custom-new-tab-doesnt-work/35847?u=eljuno

**Comment by srirambv** [comment]
+1 from @krmbzds via #1872

**Comment by KyleConstantin** [comment]
+1 this is a major issue for me converting fully over to brave. please fix!

**Comment by krmbzds** [comment]
Why not move this to a `Brave New Tab` extension?

**Comment by bbondy** [comment]
I put it to P2 because there's a lot of community asks for it. We can do this soon.

**Comment by Brave-Matt** [comment]
FWIW: This is easily one of the most frequently requested/mentioned features users ask for. Both the ability to override NTP with extensions and for Brave NTP redesign. 
While I clearly understand the potential workload involved in redesigning our own new tab page/dashboard, I think its priority merits reconsideration. Users should obviously be able to use any of the available extensions if they want but I don't think installing 3p extensions is ideal.

**Comment by bbondy** [comment]
@Brave-Matt this is a different issue than new tab redesign and this is already marked with top priority. It'll be done soon. Reconsidering priority wouldn't help since it's already marked with top priority. P1 is reserved for something we need to do a chemspill release for.

**Comment by manitaggarwal** [comment]
Still not working for me..

**Comment by bbondy** [comment]
@manitaggarwal are you using 0.57.x? It'll be released tomorrow but you can get an early RC on github already.

**Comment by bbondy** [comment]
Oops sorry this is only on 0.58.x so better to grab a Dev channel build from the releases page on this repo.

**Comment by manitaggarwal** [comment]
@bbondy I am on 0.56, I'll wait for this fix to be merged into stable channel... Thanks for the info.. 😄

**Comment by xverz** [comment]
Can't wait for this to be implemented to my favorite browser.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- ![screenshot from 2018-12-11 15-16-24](https://user-images.githubusercontent.com/17010094/49792035-beceb500-fd57-11e8-87da-4bcf61823d0d.png)

**Comment by KelvinMDunn** [comment]
Need to be able to customize new tab page! You already know!

**Comment by dogancelik** [comment]
Brave's default New Tab extension overrides my Chrome theme's wallpaper!
