### ISSUE TITLE
Follow up to #9408 - `speedreader-rust-ffi` has no entry in `brave://credits`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9939]
Follow up to #9408 

## Steps to Reproduce

   1. Open `brave://flags`
   2. Enable `SpeedReader`
   3. Open ``brave://credits``
   4. Search for `speedreader-rust-ffi`

## Actual result:

`speedreader-rust-ffi` has no entry in `brave://credits`

## Expected result:
`speedreader-rust-ffi` has an entry in `brave://credits`
It should have a license and a working link.

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.11.25 Chromium: 81.0.4044.138 (Official Build) nightly (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.10.71 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @rebron @fmarier @bridiver

**Comment by fmarier** [comment]
I can confirm that it should no longer appear in `brave://credits` because the old repo got removed in https://github.com/brave/brave-core/pull/5142.

I will clean this up in brave/brave-core#5722.
