### ISSUE TITLE
Release new stable version with Chromium 83.0.4103.61?

### ISSUE THREAD

**Issue by arpitchauhan** [brave/brave-browser#9941]
## Description 
Chrome/Chromium 83.0.4103.61 was released on May 19, and includes 38 security fixes with 5 having high severity.

I expected a Brave stable release with the new Chromium in a day or two, given the severity of security issues, but there hasn't been one as of the filing of this issue (May 26 ET).

## Brave version (brave://version info)
Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Comment by DragoCubed** [comment]
#9760

**Comment by jiripospisil** [comment]
What is going on? You're *2* security releases behind at this point.

**Comment by wooque** [comment]
@jiripospisil Chrome/Chromium 82 was never released because of coronavirus, 83 is first release after 81, still Chromium 83 is out for 2 weeks, it should take that long to release stable version after Chromium release

**Comment by bsclifton** [comment]
@jiripospisil we're behind unfortunately. This is and has been live on Nightly, but we've pushed the release of Chromium 83 until the 1.10 release which is scheduled for June 9th

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/9760

The release schedule has been updated accordingly. Thanks for your patience
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

**Comment by jiripospisil** [comment]
@wooque There's an [update](https://chromereleases.googleblog.com/2020/06/stable-channel-update-for-desktop.html) for Chromium 83 that fixed 5 additional security issues.

@bsclifton Thanks for the update. I understand that applying and making sure that all of your patches and custom features work correctly against code base such as Chromium must be a gigantic pain but still feel like several weeks is too many for a security focused browser.
