### ISSUE TITLE
[Android] Verified pubs state is not retained when app is removed from memory and relaunched

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9942]
## Description 
[Android] Verified pubs state is not retained when app is removed from memory and relaunched

## Steps to reproduce 

   1. Clean profile 1.9.x
   2. Enable rewards
   3. Open DDG and make sure the pub is displayed as verified 
   4. Add DDG to AC table and send a one time tip and monthly tips to it
   5. Verify that the checkmark is shown in AC table, Monthly tips and One-time tips panel for DDG
   6. Trigger AC 
   7. Remove the app from memory and relaunch
   8. Verified checkmark is shown for DDG in AC table, but no checkmark is shown for DDG in monthly tips panel
  9. Monthly tips are not processed as DDG is non verified only AC is happening

**Note**: After AC, the verified checkmark is shown for DDG in monthly tips panel. I am suspecting this issue is happening only with low-end devices.
  
## Actual result 
Verified pubs state is not retained when app is removed from memory and relaunched

## Expected result
Verified pub state should be retained when app is relaunched

## Issue reproduces how often 

Intermittent
## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.9.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/legacy_qa @NejcZdovc

**Comment by srirambv** [comment]
Verified on OnePlus 6T with Android 10. The issue happens right after the app is launched after triggering AC. Giving it a few seconds loads the verified checkmark on BR Panel/AC list/Monthly tips

**Comment by GeetaSarvadnya** [comment]
@Miyayes Verified the issue against the build `1.42.86` , the issue is not reproducible anymore. Verified checkmark is shown on the publisher in monthly tips panel before and after AC, mhence closig the issue
