### ISSUE TITLE
Showing warning on Brave Ads UI if notifications are disabled

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9943]

**Comment by jenn-rhim** [comment]
@tmancey Given that we can't detect the notification settings across the platforms, the message has to be generic unfortunately.  Here is what I can provide. If we have a help section about this, we can link to it as well.

![Screen Shot 2020-05-26 at 4 06 37 PM](https://user-images.githubusercontent.com/4369856/82958792-1ae8c180-9f6b-11ea-9a4c-88828796d4eb.png)

**Comment by tmancey** [comment]
Blocked as issue will be closed once https://github.com/brave/brave-browser/issues/9592 has been implemented

**Comment by tmancey** [comment]
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/9592
