### ISSUE TITLE
Address bar background color dos not change in private mode when dark theme enabled.

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#9945]
## Description 

When dark theme  is enabled, if I open a Private window, the address bar background color remains the same as in normal window. If light theme is enabled, the address bar background color changes to adjust to the purple theme of the Private window. 

## Steps to Reproduce

   1. Enable dark theme from Settings > Appearance > Brave colors
   2. Open a new Private window (File > New Private Window)

## Actual result:

The address bar background color is the same with the one of the dark theme, not adjusting to the purple theme of the private window.
![private_window_dark_theme](https://user-images.githubusercontent.com/6596039/82894228-e8cf6380-9f5a-11ea-98d6-16d050094c16.png)

## Expected result:

The address bar background color should change to adjust to the purple theme of the private window.
![private_window_light_theme](https://user-images.githubusercontent.com/6596039/82894249-f2f16200-9f5a-11ea-8723-326c1bd9b0db.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave: 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision: 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS: macOS Version 10.15.1

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
   Yes
- Can you reproduce this issue with the beta channel? 
  Yes
- Can you reproduce this issue with the dev channel?
   Yes
- Can you reproduce this issue with the nightly channel?
   Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
   Not related to Brave Shields
- Does the issue resolve itself when disabling Brave Rewards?
   Not related to Brave Rewqrds
- Is the issue reproducible on the latest version of Chrome?
   No

**Comment by bsclifton** [comment]
I'm not able to reproduce this on Windows - @georapbox do you have the mouse in the URL bar? If the URL bar is hovered, it will change to that color

**Comment by simonhong** [comment]
I think the issue is address bar background is not refreshed if address bar doesn't have focus while changing theme.

**Comment by georapbox** [comment]
Unfortunately I don't have a Windows machine available at the moment to test. The issue appears to be on MacOS though. The address bar background color does not adjust to the purple theme of the private window. Below I attach a screenshot comparing light and dark theme along with how the address bar reacts on mouse away, mouse over and focus states. Hope this proves helpful..

![brave_address_bar](https://user-images.githubusercontent.com/6596039/83618362-08860d80-a593-11ea-9b04-27f325acc2b9.png)

**Comment by bsclifton** [comment]
@georapbox this is perfect, thanks! So without mouse above, it's black rather than purple. Can see problem clearly now

**Comment by 360fun** [comment]
I've a similar problem: when the dark theme/mode is active I barely see some text in the address bar.
![image](https://user-images.githubusercontent.com/844090/84839562-9eaf3e80-b03d-11ea-8222-88e1e6e89bc4.png)
![image](https://user-images.githubusercontent.com/844090/84839593-b25aa500-b03d-11ea-97d2-2aabc7a27534.png)

The color contrast is very very low (dark blue on almost black backgrounf), even for a "normal" person: for people with problems it probably looks all background with no urls.

**Comment by karenkliu** [comment]
☝️ Changing Chromium colored address bar links to Brave-styled in light/dark should probably be logged as a  separate issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
```
Reproduced issue in 1.11.x
Dark theme - address bar
![image](https://user-images.githubusercontent.com/38657976/89014913-d9daa800-d333-11ea-90cb-ab513dd6de1c.png)

Custom theme - address bar
![image](https://user-images.githubusercontent.com/38657976/89014644-72245d00-d333-11ea-89ba-b42f8374915a.png)
