### ISSUE TITLE
The color of "Background images" toggle text in brave://settings/newTab is wrong.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#9949]
## Description 

The color of "Background images" toggle text appears to be different from other toggles.
In the design (see https://github.com/brave/brave-browser/issues/8760) all toggles are the same color.

![image](https://user-images.githubusercontent.com/41635752/82931710-56789100-9f55-11ea-8f42-299b86e3a519.png)

## Steps to Reproduce

   1. Open Brave
   2. Navigate to brave://settings/newTab
   3. See the colors of the toggles text

## Actual result:

"Background images" text color is different from other toggles text

## Expected result:
"Background images" text color is the same as the other toggles text

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.9.72, 1.11.28

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.11.65 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.14.6 (Build 18G3020)

* Reproduced issue on 1.10.90

<img width="733" alt="Screen Shot 2020-06-16 at 9 47 05 AM" src="https://user-images.githubusercontent.com/28145373/84782811-7b8d7c00-afb6-11ea-96a6-84eedcd4d358.png">

* Confirmed STR from description

<img width="733" alt="Screen Shot 2020-06-16 at 9 47 13 AM" src="https://user-images.githubusercontent.com/28145373/84782816-80eac680-afb6-11ea-8b9d-1dd992f9a881.png">

-----
