### ISSUE TITLE
twitter i18n problem

### ISSUE THREAD

**Issue by ligi** [brave/brave-browser#9950]
I am seeing this:

![Selection_548](https://user-images.githubusercontent.com/111600/82932044-20083980-9f88-11ea-861b-7177686814a2.png)

happens with brave Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

**Comment by rebron** [comment]
hi @ligi Can you update to the latest version of the browser, 1.10.97? I believe this was already fixed.
cc: @emerick
