### ISSUE TITLE
The Brave Together widget should be available for Canadian users in nightly

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#9953]
Currently, in nightly, the US is the only supported country to display the Brave Together widget on the NTP Canada should be supported as well.

## Test Plan
1. Install nightly, clean profile with region set to US
2. Confirm that the Brave Together widget is available on the NTP
3. Repeat steps 1 & 2 with the system's region set to Canada
4. Confirm that regions besides the US and Canada do not see the Together widget.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/9836#issuecomment-644501606, going to label this as `QA/No` as this isn't being released in `1.11.x` and is only currently available on `master` (Nightly).
