### ISSUE TITLE
Active tab background color regression with C83

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#9957]
Active tab bg color should be same with toolbar color

![image](https://user-images.githubusercontent.com/6786187/82990972-f0b10580-a037-11ea-8ae5-d8c00924a785.png)

Inactive tab bg color with custom theme
![image](https://user-images.githubusercontent.com/6786187/82999795-80f54780-a044-11ea-923e-f5c9e0857831.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on
```

Brave | 1.10.86 Chromium: 83.0.4103.61 (Official Build) (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

``` 
- Verified the STR from the description
**Default**– Active tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038323-6b294000-a9bd-11ea-80cc-1a21064282f8.png)


**Default**- New tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038361-79775c00-a9bd-11ea-9918-64526de3888e.png)

**Dark** – Active tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038412-8b58ff00-a9bd-11ea-8c6f-1bbf9e19e4bc.png)

**Dark**- New tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038449-96ac2a80-a9bd-11ea-8ed2-a032b1f3e9ae.png)

**Light**- Active tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038487-a3308300-a9bd-11ea-99e9-cf586bdfca35.png)

**Light**- New tab color
 
![image](https://user-images.githubusercontent.com/38657976/84038523-afb4db80-a9bd-11ea-8572-2dd0f37763ec.png)

**Custom theme**- Active tab
 
![image](https://user-images.githubusercontent.com/38657976/84038575-bcd1ca80-a9bd-11ea-8a71-a71e1a34db37.png)

**Custom theme**- New tab
 
![image](https://user-images.githubusercontent.com/38657976/84038608-c5c29c00-a9bd-11ea-80aa-7abef05f47f0.png)

**Custom theme**-PT New tab
 
![image](https://user-images.githubusercontent.com/38657976/84038655-d1ae5e00-a9bd-11ea-9630-f85b88954351.png)

**Custom theme**- TOR New tab
 
![image](https://user-images.githubusercontent.com/38657976/84038681-da069900-a9bd-11ea-81f8-e83254186602.png)
