### ISSUE TITLE
Remove unneeded saves in ledger_state

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#9959]
Properties in `ledger_state`:
- `persona_id`
- `user_id`
- `registrar_vk`
- `pre_flight`

are not needed there as they can be just passed in the next function

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

```

Brave | 1.11.75 Chromium: 83.0.4103.116 (Official Build) dev (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Windows 10 OS Version 1903 (Build 18362.900)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/5666
- Verified that the wallet can be created and AC, recurring tips and one-time tips are processed successfully
- Verified that the wallet can be restored (user funded wallet) and AC, recurring tips and one-time tips are processed successfully
- Verified that the wallet can be connected to KYC'd uphold account and AC, recurring tips and one-time tips are processed successfully
- Verified that the processor data is displayed as expected in DB in the table
