### ISSUE TITLE
AC isn't going through for the connected publisher from KYC'd uphold account

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9962]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/8938

AC isn't going through for the connected publisher from KYC'd uphold account. One time tip and recurring tips are getting added to the Pending contribution list as expected.
AC for the connected pub is tested from both self-funded and ads grants claimed wallets, in both types of funds AC is not going through for connected pubs. 

## Steps to Reproduce

   1. Clean profile 1.10.x staging environment
   2. Enable rewards 
   3. Connect KYC'd uphold staging account ( should have some balance (self funded or ad grants))
   4. Send a one time tip and recurring tip to connected pub DDG
   5. Add connected pub DDG to AC table
   6. Wait for AC to trigger
   7. AC didn't happen, wallet balance didn't go down. 
   8. Click on BAT logo displays the error message as `There was a problem processing your contribution`

Note: AC is going through in Release channel (1.9.x) even though we get `There was a problem processing your contribution` message on BAT logo

## Actual result:

AC isn't going through for the connected publisher from KYC'd uphold account
![image](https://user-images.githubusercontent.com/38657976/83010481-f1489c80-a035-11ea-8a10-4f97dba483cb.png)

## Expected result:
AC should go through for the connected publisher from KYC'd uphold account

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? No sure
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @NejcZdovc @rebron

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya is recurring tip to connected publisher going through?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Nope, recurring tips are getting added in a `Pending contribution list`

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya and what is the source of funds for AC and recurring tips?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc I have self-funded the brave uphold wallet via uphold staging wallet

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```
Brave | 1.10.80 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

```
- Verified STR from the description
AC is happening successfully, AC notification is shown on BAT logo and amount got deducted from self-funded uphold wallet
![image](https://user-images.githubusercontent.com/38657976/83528296-923bc980-a506-11ea-83e1-6f5718bcd03e.png)
