### ISSUE TITLE
Show `Downloading Component` message instead of spinner when opting into CW

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#9964]
## Description 

Show `Downloading Component` message instead of the spinner when opting into CW

## Steps to Reproduce

   1. Clean profile 1.10.74
   2. Enable Crypto wallet via hamburger menu
   3. Click on `I Understand`
   4. Click on `I Understand` button is showing a spinner

## Actual result:

Show `Downloading Component` message instead of spinner when opting into CW
![image](https://user-images.githubusercontent.com/38657976/83019904-5b1c7280-a045-11ea-92ba-73afcdd06fab.png)

## Expected result:

Show `Downloading Component` message instead of the spinner when opting into CW

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No 
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @ryanml @rebron

**Comment by kjozwiak** [comment]
@bbondy @srirambv not 100% sure why this is in the `1.10.x` milestone. Is this something we're planning on fixing in `1.10.x`? Double checking before I move this out. This can be triaged and moved into the appropriate milestone once fixed.

**Comment by srirambv** [comment]
Would be good to get into 1.10.x as we have lazy loading component(#9757) as part of 1.10.x. I am ok with leaving it out as well but preferably get it fixed as part of this release itself.

**Comment by kjozwiak** [comment]
Moving this out of `1.10.x` as it won't be uplifted into the `1.10.x` release at this point. We can probably let this ride the trains as it will be released in `1.11.x` 👍

**Comment by srirambv** [comment]
Merged PR doesn't seem to be on 1.11.x branch https://github.com/brave/brave-core/pull/5717#issuecomment-650914514

**Comment by bbondy** [comment]
> Moving this out of 1.10.x as it won't be uplifted into the 1.10.x release at this point. We can probably let this ride the trains as it will be released in 1.11.x 👍

Even if it was uplifted btw, we should always mark the milestone that it is landed in and update later if uplifted. I updated to 1.12.x where the code is 👍

**Comment by srirambv** [comment]
Verification passed on 

rave | 1.12.98 Chromium: 84.0.4147.89 (Official Build) beta (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{# 852}
OS | Linux

- Verified clicking on `I understand` start to download the component and shows `Downloading Component` instead of spinner icon
![image](https://user-images.githubusercontent.com/17010094/88658550-87974e00-d0cb-11ea-9188-fa189ae5398e.png)
