### ISSUE TITLE
consider updating link or link text on brave://flags in Beta channel - follow up to 1422

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9968]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/1422

On brave://flags page when using Beta channel, there is a line that says:

> Interested in cool new Brave features? Try our dev channel.

`dev channel` is a link that points to https://brave.com/download-beta/, however I'm already using Beta. We should consider having this point to either download Dev (like the link says) or Nightly and change the link text.

Note - this link is only available in release/beta, it does not display in dev/nightly.

## Steps to Reproduce

   1. Using Beta channel, navigate to brave://flags
   2. Click on `dev channel` link.

## Actual result:

You are directed to https://brave.com/download-beta/

<img width="687" alt="Screen Shot 2020-05-27 at 10 31 12 AM" src="https://user-images.githubusercontent.com/28145373/83033527-386a6980-a005-11ea-9768-b71a63ac1369.png">

## Expected result:
Either:
1. be directed to download dev channel like the link says
OR
2. change link text to nightly and point to download nightly channel (probably makes more sense given that dev/beta are the same now)

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.10.73 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a for 1.9.x
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? no, this link does not display on dev channel
- Can you reproduce this issue with the nightly channel? no, this link does not display on nightly channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @rebron

**Comment by jneplokh** [comment]
>Either:
>1. be directed to download dev channel like the link says
>OR
>2. change link text to nightly and point to download nightly channel (probably makes more sense given that dev/beta are the same now)

I'm probably going to open a PR for this (just changing what is here: https://github.com/brave/brave-core/blob/master/components/flags_ui/resources/brave_flags_overrides.js#L13)

Should I go with option 2, then? Promote Nightly instead?

**Comment by simonhong** [comment]
Oops, there was a mistake. will fix soon!

**Comment by jneplokh** [comment]
Ah ok, no worries!

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.13.66 Chromium: 84.0.4147.125 (Official Build) beta (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description
* Confirmed clicking on the link navigates you to https://brave.com/download-nightly/
<img width="1058" alt="Screen Shot 2020-08-13 at 3 12 46 PM" src="https://user-images.githubusercontent.com/28145373/90176806-92aed700-dd77-11ea-86f4-2ff6e028ec1a.png">
