### ISSUE TITLE
HttpsEverywhere doesn't work on texdoc.net

### ISSUE THREAD

**Issue by ravenclaw900** [brave/brave-browser#9972]
## Description 

Any page on texdoc.net is HTTP only.  It's not just the PDFs (which is what the page is made for), the homepage is too.  Brave is sometimes reporting upgrading code.jQuery.com to HTTPS, but not always.  HTTPS can be manually achieved by adding it to the beginning of the URL.

## Steps to Reproduce

   1. Go to texdoc.net

## Actual result:

<img width="1084" alt="Screen Shot 2020-05-27 at 11 18 15 AM" src="https://user-images.githubusercontent.com/50060110/83045928-e4af4e80-a00b-11ea-963f-19411ba7cfac.png">

## Expected result:
<img width="1085" alt="Screen Shot 2020-05-27 at 11 19 51 AM" src="https://user-images.githubusercontent.com/50060110/83046089-1aecce00-a00c-11ea-9a32-1ef629cdc946.png">

## Reproduces how often: 

Easily reproduced, seems to work every time.

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.13.6 (Build 17G13033)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the dev channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by dentistformyeye** [comment]
When I accessed texdoc.com with the HTTPS Everywhere extension with EASE disabled, I didn't get redirected to the HTTPS version, which means Brave is doing exactly what HTTPS Everywhere would do.

HTTPS Everywhere uses a list of domains (retrieved from https://atlas.eff.org/index.html) that are known to use HTTPS, but not every site that uses HTTPS is on the list. If you want to automatically redirect to HTTPS, you must install the HTTPS Everywhere extension and turn on Encrypt All Sites Eligible (EASE) or write your own [rulesets](https://www.eff.org/https-everywhere/rulesets), unless Brave has incorporated EASE and I haven't found it yet.

**Comment by ravenclaw900** [comment]
Okay.  You could also (I think) install the DuckDuckGo Privacy Essentials.  I'm going to see if I can get EASE added to Brave.
