### ISSUE TITLE
Use a delegate for BraveComponentLoader usage in Crypto Wallets

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#9973]
Otherwise CI can intermittently fail with:

```
declarations -c ../../brave/components/brave_wallet/browser/brave_wallet_service.cc -o obj/brave/components/brave_wallet/browser/browser/brave_wallet_service.o
20:58:09  In file included from ../../brave/components/brave_wallet/browser/brave_wallet_service.cc:16:
20:58:09  In file included from ../../brave/browser/extensions/brave_component_loader.h:14:
20:58:09  ../../chrome/browser/extensions/component_loader.h:23:10: fatal error: 'chrome/common/buildflags.h' file not found
20:58:09  #include "chrome/common/buildflags.h"
20:58:09           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
20:58:09  1 error generated.
```

## Test plan

Rerun tests from https://github.com/brave/brave-browser/issues/9757

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.11.91 Chromium: 83.0.4103.116 (Official Build) beta (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS | Windows 10 OS Version 1809 (Build 17763.1282)

- Verified test plan from https://github.com/brave/brave-browser/issues/9757
------------
Verification passed on 

Brave | 1.11.91 Chromium: 83.0.4103.116 (Official Build) beta (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS | Linux

- Verified test plan from https://github.com/brave/brave-browser/issues/9757
------------
Verification passed on 

Brave | 1.11.91 Chromium: 83.0.4103.116 (Official Build) beta (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{# 716}
OS | macOS Version 10.15.5 (Build 19F101)

- Verified test plan from https://github.com/brave/brave-browser/issues/9757
