### ISSUE TITLE
Make grammar consistent for titles and dropdowns on brave://settings/shields

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#9975]
## Description 

The grammar for titles and dropdown text on brave://settings/shields is inconsistent. Make them consistent with the following:

- [x] Change `Block trackers & ads` to `Trackers & ads blocking`
- [x] Make `Trackers & ads blocking` dropdown options: `Aggressive` `Standard` and `Disabled`
- [x] Change `Cookies` to `Cookie blocking`
- [x] Make `Cookie blocking` dropdown options: `All` `Only cross-site` and `Disabled`
- [x] Change `Fingerprinting` to `Fingerprinting blocking`
- [x] Make `Fingerprinting blocking` dropdown options: `Strict, may break sites` `Standard` and `Disabled`

## Steps to Reproduce

   1. Go to brave://settings/shields

## Designs
![shields settings2](https://user-images.githubusercontent.com/2388823/83062189-1841a700-a013-11ea-8044-b5271419b7d8.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Nightly

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.5 x64` using the following build:

```
Brave | 1.11.64 Chromium: 83.0.4103.97 (Official Build) dev (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | macOS Version 10.15.5 (Build 19F101)
```

* ensured that `Block trackers & ads` was changed to `Trackers & ads blocking`
* ensured that the `Trackers & ads blocking` dropdown had the following entries
  * `Aggressive`, `Standard` & `Disabled`
* ensured that `Cookies` was changed to `Cookie blocking`
* ensured that the `Cookie blocking` dropdown had the following entries
  * `All`, `Only cross-site` & `Disabled`
* ensured that `Fingerprinting` was changed to `Fingerprinting blocking`
* ensured that the `Fingerprinting blocking` dropdown had the following entries
  * `Strict, may break sites` `Standard` & `Disabled`

<img width="728" alt="Screen Shot 2020-06-15 at 11 16 38 PM" src="https://user-images.githubusercontent.com/2602313/84728477-515c9f80-af5f-11ea-8d7b-aa5bc6bc000f.png">

<img width="719" alt="Screen Shot 2020-06-15 at 11 16 46 PM" src="https://user-images.githubusercontent.com/2602313/84728482-56215380-af5f-11ea-94d4-c7f06b2c1745.png">

<img width="731" alt="Screen Shot 2020-06-15 at 11 16 55 PM" src="https://user-images.githubusercontent.com/2602313/84728486-5883ad80-af5f-11ea-86cf-73192faab282.png">
