### ISSUE TITLE
[Desktop] Unable to login to developer.huawei.com with Brave

### ISSUE THREAD

**Issue by eldk** [brave/brave-browser#9979]
## Description 
`https://developer.huawei.com/ `
Brave is crashed (Shield is activated/deactivated/activated ...), no way to login.

## Steps to Reproduce

   1. Go to `https://developer.huawei.com/ `
   2. Try to login : sign in (my account is created)
   3. Brave shield is "flickering" and an infinite loop begin

## Expected result:

Dashboard page is opened after login (It is in last Chrome/ium stable releases)

## Reproduces how often: 

at every login attempt

## Brave version (brave://version info)

Brave	1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision	8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS	Linux
JavaScript	V8 8.1.307.32
Flash	(désactivée)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=WebUIDarkMode,PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,LookalikeUrlNavigationSuggestionsUI,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path	/opt/brave.com/brave/brave

## Version/Channel Information:

Was the same with previous Brave Desktop stable releases.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?

No

- Does the issue resolve itself when disabling Brave Rewards?

No

- Is the issue reproducible on the latest version of Chrome? 

No

## Miscellaneous Information:

Maybe something is trying to disable Brave shield

**Comment by rebron** [comment]
@eldk Still an issue for you with 1.10.97? 
cc: @ryanbr

**Comment by eldk** [comment]
@rebron

Tested with 1.10.97, it's ok : able to login.

Thanks,

Eric
