### ISSUE TITLE
[Desktop] Search Settings not Working

### ISSUE THREAD

**Issue by claytoncarney** [brave/brave-browser#9980]
## Description 
The 'Search settings' often fails to find entries by name.

## Steps to Reproduce
   1. Go to Settings
   2. Click search icon, enter 'handlers'

## Actual result:
No search results found

## Expected result:
Settings -> Site and Shields Settings -> Handlers

## Reproduces how often: 
Always

## Brave version (brave://version info)
Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

## Other Additional Information:
Works as expected in Chrome

**Comment by rebron** [comment]
@claytoncarney I'm testing in our next release candidate that will be out next week. What I have below are the results:
![Screen Shot 2020-07-10 at 10 17 04 AM](https://user-images.githubusercontent.com/5951041/87181134-a5288300-c296-11ea-9962-9f8573691c30.png)
![Screen Shot 2020-07-10 at 10 17 12 AM](https://user-images.githubusercontent.com/5951041/87181166-b1144500-c296-11ea-803d-727f338aa5c9.png)

Were you expecting to go to Settings -> Site and Shields Settings -> Handlers directly?

**Comment by 1John419** [comment]
No, I was just expecting a non-empty set. Actually, Brave's approach is better than the current Chrome result, which folds results by category, often hiding the desired search results. In testing Brave 1.10.97, I find the results are now as expected.

**Comment by rebron** [comment]
Closing per last comment.
