### ISSUE TITLE
Twitter alerts not working since upgrade to 1.9.72

### ISSUE THREAD

**Issue by nexxai** [brave/brave-browser#9981]
## Description 

Twitter notifications have stopped working since upgrading to v1.9.72

## Steps to Reproduce

   1. Receive an action that would prompt an alert (e.g. a like on a tweet or a direct message)

## Actual result:

No notification is displayed

## Expected result:
Notification is displayed

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.4 (Build 19E287)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the dev channel? unsure
- Can you reproduce this issue with the nightly channel? unsure
 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

I have also tried disabling and re-enabling the alerts on the Twitter side, as in the past this has solved similar problems.  I am not sure if this is affecting other sites (I don't use other social media sites) but I can confirm it's not a Notification Center issue as the Brave Rewards Ads show up as expected.

**Comment by nexxai** [comment]
I realize this is not helpful, but notifications just started working (without my making any changes).  I'm not sure if Twitter was having issues or Brave or the Google Notification Service but they're appearing now, so I'm going to close this issue.

**Comment by bsclifton** [comment]
@nexxai thanks for following up - glad you're resolved 😄

**Comment by nexxai** [comment]
Ok, so it looks like this issue came back at random.  Is it possible that some kind of API limit with Google's notification service backend is being reached since I know you guys integrate with it somehow?

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.15.5 (Build 19F101)

**Comment by nexxai** [comment]
If it helps, according to the Mac Notification Center, the last Brave notification I received was at 8:44AM MDT this morning

**Comment by rebron** [comment]
@nexxai Looks intermittent.Still an issue for you with 1.10.97?
