### ISSUE TITLE
Distinguish Between Support Types in Twitter Message

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#9984]
## Description 
Presently, when you give a tip or commit to monthly support of a creator, Brave presents the same message to share on Twitter:

> I just tipped _username_ using the Brave Browser. Check it out at https://brave.com/tips.

## Steps to Reproduce
1. Issue a one-time tip
2. Commit to monthly support of a property

## Actual result:
The Twitter button for both actions has the same message

## Expected result:
The Twitter button yields an appropriate message given the action taken

> **Proposal for monthly-giving:** I just committed to monthly support of _username_ using the Brave Browser. Check it out at https://brave.com/tips.

## Brave version (brave://version info)
1.9.72

**Comment by rmcfadden3** [comment]
@jonathansampson — your proposed copy for the monthly-recurring thing LGTM. I'd say ship it, but tell me if there's any other nuance you wanted me to look at.

**Comment by jonathansampson** [comment]
@rmcfadden3 No additional nuance AFAIK :)

**Comment by rmcfadden3** [comment]
> @rmcfadden3 No additional nuance AFAIK :)

OK, then I'd say ship it!

**Comment by Miyayes** [comment]
This may change soon since we are going to remove "Set monthly tip" as its own thing, and make it a special case of a one-time tip.
