### ISSUE TITLE
Can't play videos on Google Drive if Brave Shields are enabled

### ISSUE THREAD

**Issue by ibLeDy** [brave/brave-browser#9986]
## Description 

Can't play videos inside Google Drive with Brave Shields enabled

## Steps to Reproduce

   1. Open a video on Google Drive
   2. Click play
   3. Seems like it's loading but never starts playing

## Actual result:

Not being able to play a video with Brave Shields enabled

## Expected result:
Being able to play a video with Brave Shields enabled

## Reproduces how often: 

Always with Brave Shields are enabled, tested on Linux and Windows

## Brave version (brave://version info)

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 10 OS Version 1909 (Build 18363.720)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? YES
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by ryanbr** [comment]
Hey @ibLeDy   I just tested this, I have a few sample mp4's they seemed to play fine.  We had a previous issue https://github.com/brave/brave-browser/issues/1122 which was resolved.  Can you update to the latest build Version 1.10.97 and re-test?

**Comment by ibLeDy** [comment]
Just re-tested and they seem to play fine now. (Version 1.10.97 with Brave Shields enabled)

**Comment by bsclifton** [comment]
Thanks for the update, @ibLeDy 😄
