### ISSUE TITLE
[Webcompat] Playstation Logins not working - follow up to 8629

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#9987]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/8629

Unable to login on store.playstation.com. See https://github.com/brave/brave-browser/issues/8629#issuecomment-635384133.

## Steps to Reproduce

   1.  Visit ` https://store.playstation.com/` 
   2.  Click on Login. 
   3.  Doesn't work with default Shields

## Actual result:
Login will fail.

<img width="452" alt="Screen Shot 2020-05-28 at 10 02 27 AM" src="https://user-images.githubusercontent.com/28145373/83160511-4be50580-a0d5-11ea-80ae-aa74f7fe6038.png">

## Expected result:
Expect menus and login to work.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | macOS Version 10.14.6 (Build 18G3020)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
In order to see `Login` button on store.playstation.com, you must `Allow all cookies` - not sure if this should be resolved as part of this issue as well.

cc @rebron @pes10k @ryanbr @brave/legacy_qa

**Comment by ryanbr** [comment]
Kept an eye on this, also affecting other browsers (Firefox)

https://old.reddit.com/r/firefox/comments/fbhl9y/cant_login_to_playstation_store_sign_in_button/
https://old.reddit.com/r/firefox/comments/glagsb/cannot_log_into_playstation_store/

**Comment by seanarnold** [comment]
Any updates to this?

**Comment by pes10k** [comment]
@seanarnold looks like we had to rev the solution, but that the PR is here, and is on track to be in nightly very shortly: https://github.com/brave/brave-core/pull/5857

**Comment by LaurenWags** [comment]
Issue is still not resolved with 

```
Brave | 1.12.104 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

Logged follow up issue https://github.com/brave/brave-browser/issues/11000

Removing `QA/Yes` and `release-notes/include` labels and adding `QA/No` and `release-notes/exclude` since issue is still not resolved.
