### ISSUE TITLE
Sync V2

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#9989]
sync v1 will be completely removed and sync v2 will fully run on chromium sync engine with
1. Sync Chain concept inherited from v1
    - UI spec specified in https://github.com/brave/brave-browser/issues/9241
2. Brave specific auth flow
    1. Derive public/private key pair from seed
    2. Fetch timestamp from server
    3. Compose access token by timestamp, signed timestamp and public key
3. Client encryption
    - Use bip39 keywords of seed as custom passphrase
    - Clients will derive encryption/decryption key based on the passphrase    
4. Migration from v1
    - Reset sync engine to clean state
    - Strip off meta info store in bookmarks used by v1

**Comment by artella-coding** [comment]
@darkdh While the team is working on sync any chance someone could implement import/export from/to file for the Android Browser (https://github.com/brave/brave-browser/issues/6378) ? With Sync v1 (which i performed just now) I was finding 130-170 bookmarks were being synced every 80 seconds. This means if you have a lot of bookmarks it will take a long time for sync to complete.

**Comment by TitanKing** [comment]
This is probably the most important missing feature in Brave, good luck, can't wait to get rid of Soros sponsored Firefox.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.107 Chromium: 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/qa-resources/issues/172
Verified test plan from https://github.com/brave/brave-core/pull/5294

**Upgrade scenario**
`profile/Default/Bookmarks` for `Sync 1` on `1.11.101`
![image](https://user-images.githubusercontent.com/34715963/89479773-f479aa80-d793-11ea-8792-4ae38dd70231.png)
Bookmarks file: [Bookmarks_before.txt](https://github.com/brave/brave-browser/files/5032016/Bookmarks_before.txt)

After Upgrade - all the sync meta data is gone
![image](https://user-images.githubusercontent.com/34715963/89480260-2ccdb880-d795-11ea-8eda-58398ae0982a.png)
Bookmarks file: [Bookmarks_after.txt](https://github.com/brave/brave-browser/files/5032018/Bookmarks_after.txt)
Note: `sync_metadata` at the bottom of `Bookmarks` file is expected.

Verified that bookmarks are retained after upgrade
![image](https://user-images.githubusercontent.com/34715963/89480552-f17fb980-d795-11ea-9d18-b7fb02f89c4f.png)

Verified that message is shown after upgrade
![image](https://user-images.githubusercontent.com/34715963/89480112-cf396c00-d794-11ea-9de6-0c547de856ba.png)

Verified able to create sync 2 chain.

**Comment by LaurenWags** [comment]
A list of all `sync` and/or `fixed-with-sync-v2` issues in the 1.12.x milestone can be found here: https://github.com/brave/brave-browser/issues?q=is%3Aissue+milestone%3A%221.12.x+-+Release%22+label%3Afeature%2Fsync+is%3Aclosed
