### ISSUE TITLE
NTP stats strings are not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9990]
Important: This is regression in 1.10.x. 

## Steps to Reproduce

   1. Open Brave in PL / JP locale
   2. Open NTP

## Actual result:

`Ads and trackers blocked`, `Estimated bandwidth saved` and `Estimated time saved` are not translated

JP - Japanese
![image](https://user-images.githubusercontent.com/34715963/83200325-5f2eba00-a143-11ea-8f8d-b499641abac2.png)
PL - Polish
![image](https://user-images.githubusercontent.com/34715963/83200228-2bec2b00-a143-11ea-8a29-ba1d15ec6c27.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/83171674-c2562780-a116-11ea-80ef-7beaa22bce79.png)
![image](https://user-images.githubusercontent.com/34715963/83171000-b158e680-a115-11ea-828f-404666c0ff8f.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

**Reproducible on**
Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Brave | 1.11.31 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

**Not reproducible on**

Brave | 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @brave/legacy_qa @rebron @mkarolin @bsclifton

**Comment by btlechowski** [comment]
Not reproducible anymore.

![image](https://user-images.githubusercontent.com/34715963/87967104-a2136b00-cabe-11ea-93bd-357ca2199594.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.94 Chromium: 84.0.4147.89 (Oficjalna wersja) dev (64-bitowa)
-- | --
Wersja | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
System operacyjny | macOS Wersja 10.14.6 (kompilacja 18G3020)
```

Verified Polish and Japanese as per the issue description
<img width="765" alt="Zrzut ekranu 2020-07-20 o 4 34 08 PM" src="https://user-images.githubusercontent.com/28145373/87983776-ec88ed80-caa6-11ea-890d-f8b02d67331d.png">

<img width="883" alt="スクリーンショット 2020-07-20 午後4 33 43" src="https://user-images.githubusercontent.com/28145373/87983770-e98dfd00-caa6-11ea-82ae-0741e59b7f0c.png">
