### ISSUE TITLE
[Android] Fix rewards db import on Android 10

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#9991]
## Description 
There is additional security layer on Android 10, that prevents from copying db file directly from Downloads folder. Needs to be fixed.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
1. Try to import database on Android 10;
2. No errors should be shown on that;

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.11.100 x64 build
- Verified able to import db without any errors or failure
------
Verification passed on OnePlus 6T with Android 10 running 1.11.100 x64 build
- Verified able to import db without any errors or failure
