### ISSUE TITLE
[Android] Balances on Android suddenly displaying 0.0 BAT (after May 2020 ad payout)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#9992]
## Description 

Around the Brave Ads payout (May 5th, 2020), many users report seeing their Brave Rewards balance suddenly going to `0.0 BAT`.

Awaiting https://github.com/brave/brave-browser/issues/9766 in order to allow further investigation.

## Steps to reproduce 

1. Open Brave Rewards panel

## Actual result 

![image](https://user-images.githubusercontent.com/11497541/83197964-638bb080-a10c-11ea-86bc-3cbecb7578d3.png)

BAT balance is reset to `0.0 BAT` in the interface.

## Expected result

BAT balance should **not** be `0.0 BAT`. 

## Issue reproduces how often 

For users affected, it occurs 100% of the time. However, not all users are affected. A large number of users are affected.

## Issue happens on 

Occurs on current release build. 

## Additional info

1. Original payout megathread: https://www.reddit.com/r/BATProject/comments/ge3w7w/support_megathread_may_5th_2020_brave_ads_payout/
2. Follow up hotfix megathread: https://www.reddit.com/r/BATProject/comments/gkgg3d/hotfix_support_megathread_brave_ads_may_5th_2020/

**Comment by SergeyZhukovsky** [comment]
It actually happened before 1.8.112. The HF isn't involved in that. It could be because of the May payout, but the reports started to come before 1.8.112.

**Comment by Miyayes** [comment]
**Update:** #9766 is now live in v1.9.79 on Android, and affected users have begun submitting their db files for analysis and debugging.

**Comment by sebutek** [comment]
As being affected by the problem, it would be very helpful if there was a step by step guide on how to export the database and especially **how to get the database from the device**.

**Comment by Miyayes** [comment]
> As being affected by the problem, it would be very helpful if there was a step by step guide on how to export the database and especially **how to get the database from the device** and where to send it. @sebutek 

`Settings->Developer options->Rewards Debug->Export Rewards Database`

The database should appear in `Downloads` folder under the `Rewards` folder. 

You can send it to the Brave staff who is working with you. You can send it to cnguyen at brave dot com (me). Thanks!

**Comment by Miyayes** [comment]
1. **Please do not delete or reset your device in attempts to solve this issue.** This will reset your browser data, BAT balance, and will likely result in BAT loss. 

2. As of v1.10 of Android, users can verify their Brave Rewards wallet with Uphold. If you are affected by this issue/bug, you can still go ahead and verify your Brave Rewards wallet if you so choose. However, if you would rather play it safe and not undertake any major operations to your wallet while affected by this bug, that is OK too. Verifying is not necessary!

**Comment by samartnik** [comment]
Verification passed on Lenovo Tablet with Android 8.1 running 1.10.99 arm build
- Verified test plan from issue description

**Comment by SergeyZhukovsky** [comment]
Verification passed on Pixel XL with Android 10 running 1.10.99 arm build

- Verified test plan from issue description

**Comment by NejcZdovc** [comment]
this was merged in https://github.com/brave/brave-core/pull/5940. Waiting for 1.11 and 1.12 merges as we need to define if we want to do it for desktop as well or not.
