### ISSUE TITLE
NTP `Estimated bandwidth saved` stat is not shown on clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#9993]
Follow up to https://github.com/brave/brave-browser/issues/8969

## Steps to Reproduce

   1. Clean install
   2. Open new tab

Important: after loading 1 page, the stat is shown

## Actual result:

NTP `Estimated bandwidth saved` stat is not shown on clean install
![image](https://user-images.githubusercontent.com/34715963/83207963-bb4e0a00-a154-11ea-95a7-731e94758771.png)

## Expected result:
NTP `Estimated bandwidth saved` stat is shown on clean install
![image](https://user-images.githubusercontent.com/34715963/83208029-e9334e80-a154-11ea-914c-b7cd58b2945d.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

Brave | 1.10.74 Chromium: 81.0.4044.138 (Official Build) dev (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Ubuntu 18.04 LTS

Brave | 1.11.31 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)
-- | --
Revision | 94f915a8d7c408b09cc7352161ad592299f384d2-refs/branch-heads/4103@{#561}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

cc @brave/legacy_qa @rebron @AndriusA @karenkliu

**Comment by rebron** [comment]
cc: @AndriusA Can you take a look?

**Comment by AndriusA** [comment]
will do, there's a simple explicit condition that hides the metric if it is zero, will remove it

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.12.92 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | macOS Version 10.14.6 (Build 18G3020)
```

* Verified STR from description

<img width="1197" alt="Screen Shot 2020-07-17 at 8 39 43 AM" src="https://user-images.githubusercontent.com/28145373/87787136-25a43200-c809-11ea-822c-75ef5c63cf5a.png">

--------
