### ISSUE TITLE
[Webcompat] Audio playback issues on https://audiomass.co/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#9995]
## Description 
Playback on https://audiomass.co/ will slowly mute. From author @pkalogiros

## Steps to Reproduce

   1. Open https://audiomass.co/
   2. Click on `Here use a Sample` button.
   3. Click on the play button at the top of the page

## Actual result:
Volume will slowly lower as it plays after 15-20secs

## Expected result:
Expects volume to stay the same.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
`Version 1.11.35 Chromium: 83.0.4103.61 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, but  volume is much reduced  over a longer period
- Can you reproduce this issue with the beta channel? Yes, but  volume is much reduced over a longer period
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Checked Chrome Canary/Firefox, no volume playback issues.
No console error messages showing up.

**Comment by ryanbr** [comment]
Related report also: https://github.com/pkalogiros/AudioMass/issues/10

**Comment by pkalogiros** [comment]
https://github.com/pkalogiros/AudioMass/issues/10#issuecomment-647085091

**Comment by ryanbr** [comment]
This is resolved in the latest Brave build, closing.
