### ISSUE TITLE
Transition Brave Ads prefs from the service layer to bat-native-ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#9999]
Transition Brave Ads prefs from the service layer to bat-native-ads using `Get<Type>Pref`, i.e. `GetBooleanPref`, `GetStringPref` etc.

**Comment by kjozwiak** [comment]
Labeling this one as `QA/No` as https://github.com/brave/brave-core/pull/6872 will basically cover most of these cases. The remaining cases mentioned in https://github.com/brave/brave-core/pull/6872 will also be covered via our manual passes.
